export type ModuleStatus = "active" | "coming-soon";

export interface ModuleDefinition {
  slug: string;
  faculty: string;
  title: string;
  subtitle: string;
  status: ModuleStatus;
  priceCent: number;
  compareAtCent: number; // Vergleichspreis (klassischer Vorbereitungskurs)
  chapters: string[];
  questionCount: number;
  // Für die dreistufige Auswahl auf dem Dashboard (Studiengang → Fach → Nummer):
  studiengang: string; // z. B. "Wirtschaftsingenieurwesen"
  subject: string; // Fach-Gruppe, z. B. "Statistik", "VWL"
  number: string; // Nummer/Variante innerhalb des Fachs, z. B. "I", "2" — leer, wenn es (noch) nur eine Variante gibt
  popular?: boolean; // Wird auf dem Dashboard standardmäßig (ohne Filter) angezeigt
  exampleQuestion?: string; // Beispielfrage, die im Chatbot als Vorschlag angezeigt wird
}

// Studiengänge, die auf dem Dashboard zur Auswahl stehen. Aktuell ist nur
// Wirtschaftsingenieurwesen mit echten Modulen hinterlegt — die anderen
// werden ausgegraut mit "bald verfügbar" angezeigt, damit sichtbar ist,
// dass Lumo wächst, ohne schon Inhalte dafür zu versprechen.
export const STUDIENGAENGE: { name: string; active: boolean }[] = [
  { name: "Wirtschaftsingenieurwesen", active: true },
  { name: "Maschinenbau", active: false },
  { name: "Elektrotechnik und Informationstechnik", active: false },
  { name: "Informatik", active: false },
];

export const modules: ModuleDefinition[] = [
  {
    slug: "statistik-1",
    faculty: "WiWi-Fakultät",
    title: "Statistik I",
    subtitle: "Deskriptive Statistik, Wahrscheinlichkeitsrechnung, Zufallsvariablen & Verteilungsmodelle",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Deskriptive Statistik",
      "Wahrscheinlichkeitsrechnung",
      "Zufallsvariablen",
      "Verteilungsmodelle",
    ],
    questionCount: 45,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Statistik",
    number: "I",
    popular: true,
    exampleQuestion: "Erklär mir den Satz von Bayes an einem Beispiel.",
  },
  {
    slug: "vwl-2",
    faculty: "WiWi-Fakultät",
    title: "VWL 2: Makroökonomie",
    subtitle: "BIP, Wachstum, Arbeitslosigkeit, Geld & Inflation, Konjunktur (IS-LM), offene Volkswirtschaften & Gesamtangebot",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Methodik & BIP",
      "Geld, Inflation & Bankensystem",
      "Arbeitslosigkeit",
      "Wachstum I & II (inkl. KI & Klima)",
      "Konjunktur I & II",
      "Gesamtwirtschaftliches Angebot",
      "Offene Volkswirtschaften I & II (inkl. Zölle)",
    ],
    questionCount: 53,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "VWL",
    number: "2",
    popular: true,
    exampleQuestion: "Erklär mir das IS-LM-Modell an einem Beispiel.",
  },
  {
    slug: "statistik-2",
    faculty: "WiWi-Fakultät",
    title: "Statistik II",
    subtitle: "Schätzen, Testen, Regression",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Statistik",
    number: "II",
  },
  {
    slug: "vwl-1",
    faculty: "WiWi-Fakultät",
    title: "VWL 1: Mikroökonomie",
    subtitle: "Haushalte, Unternehmen, Märkte & Wettbewerb",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Markt und Budgetmenge",
      "Technologie und Gewinnmaximierung der Unternehmung",
      "Präferenzen und Nutzen",
      "Monopol",
      "Kostenminimierung und Kostenkurven",
      "Optimale Entscheidung und Nachfrage",
      "Konsumentenrente, Marktnachfrage und Marktgleichgewicht",
      "Bekundete Präferenzen und Slutsky-Zerlegung",
      "Tausch und Wohlfahrtstheorie",
      "Angebot der Unternehmung und Marktangebot der Branche",
      "Oligopoltheorie",
      "Kaufen, Verkaufen und intertemporale Entscheidung",
      "Spieltheorie",
    ],
    questionCount: 62,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "VWL",
    number: "1",
    exampleQuestion: "Erklär mir das Gewinnmaximierungsproblem des Monopolisten an einem Beispiel.",
  },
  {
    slug: "mathematik-1-semester",
    faculty: "WiWi-Fakultät",
    title: "Mathematik 1: Semesterklausur",
    subtitle: "Aussagenlogik, Mengenlehre, Relationen, Abbildungen, Folgen, Reihen & Potenzreihen — Stoff der Semesterklausur (1. Prüfungsteil)",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Aussagenlogik",
      "Mengenlehre",
      "Exkurs: Gruppen, Ringe und Körper",
      "Relationen",
      "Vollständige Induktion und die natürlichen Zahlen",
      "Abbildungen",
      "Kombinatorik und das Laplace-Modell",
      "Die reellen Zahlen",
      "Folgen",
      "Teilfolgen, Häufungspunkte und die Dichtheit von Q in R",
      "Reihen",
      "Potenzreihen",
      "Spezielle Funktionen",
    ],
    questionCount: 77,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Mathematik",
    number: "1 – Semesterklausur",
    popular: true,
    exampleQuestion: "Erklär mir die vollständige Induktion an einem Beispiel.",
  },
  {
    slug: "mathematik-1-abschluss",
    faculty: "WiWi-Fakultät",
    title: "Mathematik 1: Abschlussklausur",
    subtitle: "Grundlagen der Analysis und linearen Algebra — Stoff der Abschlussklausur (2. Prüfungsteil)",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Mathematik",
    number: "1 – Abschlussklausur",
  },
  {
    slug: "mathematik-2-semester",
    faculty: "WiWi-Fakultät",
    title: "Mathematik 2: Semesterklausur",
    subtitle: "Fortführung Analysis & lineare Algebra — Stoff der Semesterklausur (1. Prüfungsteil)",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Mathematik",
    number: "2 – Semesterklausur",
  },
  {
    slug: "mathematik-2-abschluss",
    faculty: "WiWi-Fakultät",
    title: "Mathematik 2: Abschlussklausur",
    subtitle: "Mehrdimensionale Funktionen & Fortführung — Stoff der Abschlussklausur (2. Prüfungsteil)",
    status: "active",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [
      "Jordan-Inhalt und messbare Mengen im Rⁿ",
      "Partielle Differenzierbarkeit und der Gradient",
      "Ober- und Untersummen: das Riemann-Integral im Rⁿ",
      "Richtungsableitungen",
      "Eigenschaften des Jordan-Inhalts und der Satz von Fubini",
      "Totale Differenzierbarkeit und die Tangentialebene",
      "Normalbereiche und das Prinzip von Cavalieri",
      "Kettenregel, Jacobi-Matrix und vektorwertige Funktionen",
      "Treppenfunktionen, gleichmäßige Stetigkeit und Integrierbarkeit stetiger Funktionen",
      "Höhere Ableitungen und der Satz von Schwarz",
      "Der Gradient als Richtung des steilsten Anstiegs",
      "Der Transformationssatz und Koordinatenwechsel",
      "Taylorpolynome und der Mittelwertsatz im Rⁿ",
      "Lokale Extrema, die Hessematrix und Sattelpunkte",
    ],
    questionCount: 70,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Mathematik",
    number: "2 – Abschlussklausur",
    exampleQuestion: "Erklär mir die Hessematrix und Sattelpunkte an einem Beispiel.",
  },
  {
    slug: "mathematik-3",
    faculty: "WiWi-Fakultät",
    title: "Mathematik 3",
    subtitle: "Vertiefende Mathematik für Wirtschaftsingenieure",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Mathematik",
    number: "3",
  },
  {
    slug: "bwl-1",
    faculty: "WiWi-Fakultät",
    title: "Management und Marketing",
    subtitle: "Grundlagen des Managements und Marketings",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "BWL",
    number: "1",
  },
  {
    slug: "bwl-2",
    faculty: "WiWi-Fakultät",
    title: "Finanzierung und Rechnungswesen",
    subtitle: "Grundlagen der Finanzbuchhaltung und Unternehmensfinanzierung",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "BWL",
    number: "2",
  },
  {
    slug: "bwl-3",
    faculty: "WiWi-Fakultät",
    title: "Produktion, Logistik und Wirtschaftsinformatik",
    subtitle: "Produktionswirtschaft, Logistik und Wirtschaftsinformatik",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "BWL",
    number: "3",
  },
  {
    slug: "informatik-1",
    faculty: "WiWi-Fakultät",
    title: "Einführung in die Programmierung",
    subtitle: "Grundlagen der Programmierung",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Informatik",
    number: "1",
  },
  {
    slug: "informatik-2",
    faculty: "WiWi-Fakultät",
    title: "Grundlagen der Informatik",
    subtitle: "Logik, Algorithmen, Datenstrukturen, Sortieren, Komplexität & UML",
    status: "active",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [
      "Algorithmen: Grundbegriffe und Eigenschaften",
      "Aussagenlogik",
      "Datenstrukturen I: Abstrakte Datentypen, Listen, Keller und Schlangen",
      "Prädikatenlogik",
      "Entwurfsprinzipien und Testen von Algorithmen",
      "Datenstrukturen II: Graphen, Bäume und binäre Suchbäume",
      "Boolesche Algebra",
      "Sortierverfahren",
      "Datenstrukturen III: Kürzeste Wege und minimale Spannbäume",
      "Komplexität von Algorithmen",
      "Einführung in UML und Anwendungsfalldiagramme",
      "Klassen- und Objektdiagramme",
      "Verhaltensdiagramme: Sequenz, Zustand und Aktivität",
    ],
    questionCount: 86,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Informatik",
    number: "2",
    exampleQuestion: "Erklär mir binäre Suchbäume an einem Beispiel.",
  },
  {
    slug: "or-1",
    faculty: "WiWi-Fakultät",
    title: "Einführung in das Operations Research",
    subtitle: "Lineare Optimierung, Netzplantechnik & Entscheidungsmodelle",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Operations Research",
    number: "",
  },
  {
    slug: "ing-1",
    faculty: "WiWi-Fakultät",
    title: "Werkstoffkunde",
    subtitle: "Werkstoffe und ihre Eigenschaften für Ingenieuranwendungen",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Ingenieurwissenschaften",
    number: "1",
  },
  {
    slug: "ing-2",
    faculty: "WiWi-Fakultät",
    title: "Technische Mechanik",
    subtitle: "Statik, Festigkeitslehre und Kinematik",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Ingenieurwissenschaften",
    number: "2",
  },
  {
    slug: "ing-3",
    faculty: "WiWi-Fakultät",
    title: "Elektrotechnik",
    subtitle: "Grundlagen der Elektrotechnik",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Ingenieurwissenschaften",
    number: "3",
  },
  {
    slug: "ing-4",
    faculty: "WiWi-Fakultät",
    title: "Weiterführende ingenieurwissenschaftliche Grundlagen",
    subtitle: "Vertiefende ingenieurwissenschaftliche Inhalte",
    status: "coming-soon",
    priceCent: 799,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Ingenieurwissenschaften",
    number: "4",
  },
];

export function getModule(slug: string): ModuleDefinition | undefined {
  return modules.find((m) => m.slug === slug);
}

export function formatEuro(cent: number): string {
  return (cent / 100).toLocaleString("de-DE", {
    style: "currency",
    currency: "EUR",
  });
}
