export type ModuleStatus = "active" | "coming-soon";

export interface ModuleDefinition {
  slug: string;
  faculty: string;
  title: string;
  subtitle: string;
  status: ModuleStatus;
  priceCent: number;
  compareAtCent: number; // Vergleichspreis (klassischer Vorbereitungskurs)
  chapters: string[];
  questionCount: number;
  // Für die dreistufige Auswahl auf dem Dashboard (Studiengang → Fach → Nummer):
  studiengang: string; // z. B. "Wirtschaftsingenieurwesen"
  subject: string; // Fach-Gruppe, z. B. "Statistik", "VWL"
  number: string; // Nummer/Variante innerhalb des Fachs, z. B. "I", "2" — leer, wenn es (noch) nur eine Variante gibt
  popular?: boolean; // Wird auf dem Dashboard standardmäßig (ohne Filter) angezeigt
  exampleQuestion?: string; // Beispielfrage, die im Chatbot als Vorschlag angezeigt wird
}

// Studiengänge, die auf dem Dashboard zur Auswahl stehen. Aktuell ist nur
// Wirtschaftsingenieurwesen mit echten Modulen hinterlegt — die anderen
// werden ausgegraut mit "bald verfügbar" angezeigt, damit sichtbar ist,
// dass Lumo wächst, ohne schon Inhalte dafür zu versprechen.
export const STUDIENGAENGE: { name: string; active: boolean }[] = [
  { name: "Wirtschaftsingenieurwesen", active: true },
  { name: "Maschinenbau", active: false },
  { name: "Elektrotechnik und Informationstechnik", active: false },
  { name: "Informatik", active: false },
];

export const modules: ModuleDefinition[] = [
  {
    slug: "statistik-1",
    faculty: "WiWi-Fakultät",
    title: "Statistik I",
    subtitle: "Deskriptive Statistik, Wahrscheinlichkeitsrechnung, Zufallsvariablen & Verteilungsmodelle",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Deskriptive Statistik",
      "Wahrscheinlichkeitsrechnung",
      "Zufallsvariablen",
      "Verteilungsmodelle",
    ],
    questionCount: 45,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Statistik",
    number: "I",
    popular: true,
    exampleQuestion: "Erklär mir den Satz von Bayes an einem Beispiel.",
  },
  {
    slug: "vwl-2",
    faculty: "WiWi-Fakultät",
    title: "VWL 2: Makroökonomie",
    subtitle: "BIP, Wachstum, Arbeitslosigkeit, Geld & Inflation, Konjunktur (IS-LM), offene Volkswirtschaften & Gesamtangebot",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Methodik & BIP",
      "Geld, Inflation & Bankensystem",
      "Arbeitslosigkeit",
      "Wachstum I & II (inkl. KI & Klima)",
      "Konjunktur I & II",
      "Gesamtwirtschaftliches Angebot",
      "Offene Volkswirtschaften I & II (inkl. Zölle)",
    ],
    questionCount: 53,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "VWL",
    number: "2",
    popular: true,
    exampleQuestion: "Erklär mir das IS-LM-Modell an einem Beispiel.",
  },
  {
    slug: "statistik-2",
    faculty: "WiWi-Fakultät",
    title: "Statistik II",
    subtitle: "Schätzen, Testen, Regression",
    status: "coming-soon",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Statistik",
    number: "II",
  },
  {
    slug: "vwl-1",
    faculty: "WiWi-Fakultät",
    title: "VWL 1: Mikroökonomie",
    subtitle: "Haushalte, Unternehmen, Märkte & Wettbewerb",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Markt und Budgetmenge",
      "Präferenzen und Nutzen",
      "Optimale Entscheidung und Nachfrage",
      "Konsumentenrente, Marktnachfrage und Marktgleichgewicht",
      "Bekundete Präferenzen und Slutsky-Zerlegung",
      "Technologie und Gewinnmaximierung der Unternehmung",
      "Kostenminimierung und Kostenkurven",
      "Angebot der Unternehmung und Marktangebot der Branche",
      "Monopol",
      "Oligopoltheorie",
      "Spieltheorie",
      "Tausch, Wohlfahrtstheorie und intertemporale Entscheidung",
    ],
    questionCount: 62,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "VWL",
    number: "1",
    exampleQuestion: "Erklär mir das Gewinnmaximierungsproblem des Monopolisten an einem Beispiel.",
  },
  {
    slug: "mathematik-1-semester",
    faculty: "WiWi-Fakultät",
    title: "Mathematik 1: Semesterklausur",
    subtitle: "Aussagenlogik, Mengenlehre, Relationen, Abbildungen, Folgen, Reihen & Potenzreihen — Stoff der Semesterklausur (1. Prüfungsteil)",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Aussagenlogik",
      "Mengenlehre",
      "Exkurs: Algebraische Strukturen",
      "Relationen",
      "Vollständige Induktion und die natürlichen Zahlen",
      "Abbildungen",
      "Kombinatorik und das Laplace-Modell",
      "Die reellen Zahlen",
      "Folgen",
      "Teilfolgen, Häufungspunkte und die Dichtheit von Q in R",
      "Reihen",
      "Potenzreihen und spezielle Funktionen",
    ],
    questionCount: 77,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Mathematik",
    number: "1 – Semesterklausur",
    popular: true,
    exampleQuestion: "Erklär mir die vollständige Induktion an einem Beispiel.",
  },
  {
    slug: "mathematik-1-abschluss",
    faculty: "WiWi-Fakultät",
    title: "Mathematik 1: Abschlussklausur",
    subtitle: "Grundlagen der Analysis und linearen Algebra — Stoff der Abschlussklausur (2. Prüfungsteil)",
    status: "coming-soon",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Mathematik",
    number: "1 – Abschlussklausur",
  },
  {
    slug: "mathematik-2-semester",
    faculty: "WiWi-Fakultät",
    title: "Mathematik 2: Semesterklausur",
    subtitle: "Fortführung Analysis & lineare Algebra — Stoff der Semesterklausur (1. Prüfungsteil)",
    status: "coming-soon",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Mathematik",
    number: "2 – Semesterklausur",
  },
  {
    slug: "mathematik-2-abschluss",
    faculty: "WiWi-Fakultät",
    title: "Mathematik 2: Abschlussklausur",
    subtitle: "Mehrdimensionale Funktionen & Fortführung — Stoff der Abschlussklausur (2. Prüfungsteil)",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Partielle Ableitungen und der Gradient",
      "Richtungsableitungen und der Gradient als steilster Anstieg",
      "Totale Differenzierbarkeit und die Tangentialebene",
      "Kettenregel, Jacobi-Matrix und vektorwertige Funktionen",
      "Höhere Ableitungen, der Satz von Schwarz und Taylorpolynome",
      "Lokale Extrema, die Hessematrix und Sattelpunkte",
      "Jordan-Inhalt und das Riemann-Integral im Rⁿ",
      "Normalbereiche, das Prinzip von Cavalieri und der Transformationssatz",
    ],
    questionCount: 70,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Mathematik",
    number: "2 – Abschlussklausur",
    exampleQuestion: "Erklär mir die Hessematrix und Sattelpunkte an einem Beispiel.",
  },
  {
    slug: "mathematik-3",
    faculty: "WiWi-Fakultät",
    title: "Mathematik 3",
    subtitle: "Vertiefende Mathematik für Wirtschaftsingenieure",
    status: "coming-soon",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Mathematik",
    number: "3",
  },
  {
    slug: "bwl-1",
    faculty: "WiWi-Fakultät",
    title: "Management und Marketing",
    subtitle: "Grundlagen des Managements und Marketings",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Grundlagen: Was Unternehmer und Unternehmen leisten",
      "Gründerpersonen, Motive und unternehmerische Gelegenheiten",
      "Entscheiden unter Risiko und Unsicherheit",
      "Geschäftsmodelle systematisch entwickeln und planen",
      "Vom Prototyp zum Pivot: Lean Startup und Design Thinking",
      "Organisation des Unternehmens",
      "Strategische Analyse und strategische Optionen",
      "Corporate Governance und Personalführung",
      "Kundenverhalten verstehen: von Daten zu Erkenntnissen",
      "Produktgestaltung, Preispolitik und Kommunikationspolitik",
      "Erfolg beim Kunden messen: CLV und Customer Equity",
    ],
    questionCount: 91,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "BWL",
    number: "1",
    exampleQuestion: "Wie berechne ich den Customer Lifetime Value bei bekannter Wiederkaufrate?",
  },
  {
    slug: "bwl-2",
    faculty: "WiWi-Fakultät",
    title: "Finanzierung und Rechnungswesen",
    subtitle: "Grundlagen der Finanzbuchhaltung und Unternehmensfinanzierung",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Zeitwert des Geldes: Barwert und Endwert",
      "Rentenformeln: Ewige und endliche Renten",
      "Investitionsrechnung I: Kapitalwert und Amortisationsdauer",
      "Investitionsrechnung II: Interner Zinssatz und Kapitalwertrate",
      "Bewertung von Anleihen",
      "Eigenkapitalfinanzierung: Aktien und Ausschüttungspolitik",
      "Portfoliotheorie und CAPM",
      "Grundsätze ordnungsmäßiger Buchführung und das Buchungssystem",
      "Bewertungswahlrechte im externen Rechnungswesen",
      "Grundlagen der Kosten- und Leistungsrechnung",
      "Der Betriebsabrechnungsbogen und Kalkulationsverfahren",
      "Deckungsbeitragsrechnung",
    ],
    questionCount: 69,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "BWL",
    number: "2",
    exampleQuestion: "Wie berechne ich den Kapitalwert einer Investition bei bekanntem Zahlungsstrom und Zinssatz?",
  },
  {
    slug: "bwl-3",
    faculty: "WiWi-Fakultät",
    title: "Produktion, Logistik und Wirtschaftsinformatik",
    subtitle: "Produktionswirtschaft, Logistik und Wirtschaftsinformatik",
    status: "coming-soon",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "BWL",
    number: "3",
  },
  {
    slug: "informatik-1",
    faculty: "WiWi-Fakultät",
    title: "Einführung in die Programmierung",
    subtitle: "Grundlagen der Programmierung",
    status: "coming-soon",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Informatik",
    number: "1",
  },
  {
    slug: "informatik-2",
    faculty: "WiWi-Fakultät",
    title: "Grundlagen der Informatik",
    subtitle: "Logik, Algorithmen, Datenstrukturen, Sortieren, Komplexität & UML",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Aussagenlogik",
      "Prädikatenlogik",
      "Boolesche Algebra",
      "Algorithmen: Grundbegriffe und Eigenschaften",
      "Entwurfsprinzipien und Testen von Algorithmen",
      "Datenstrukturen I: Abstrakte Datentypen, Listen, Keller und Schlangen",
      "Datenstrukturen II: Graphen, Bäume und binäre Suchbäume",
      "Sortierverfahren",
      "Datenstrukturen III: Kürzeste Wege und minimale Spannbäume",
      "Komplexität von Algorithmen",
      "UML: Anwendungsfall-, Klassen- und Objektdiagramme",
      "UML: Verhaltensdiagramme",
    ],
    questionCount: 86,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Informatik",
    number: "2",
    exampleQuestion: "Erklär mir binäre Suchbäume an einem Beispiel.",
  },
  {
    slug: "or-1",
    faculty: "WiWi-Fakultät",
    title: "Einführung in das Operations Research",
    subtitle: "Lineare Optimierung, Netzplantechnik & Entscheidungsmodelle",
    status: "coming-soon",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Operations Research",
    number: "",
  },
  {
    slug: "ing-1",
    faculty: "WiWi-Fakultät",
    title: "Werkstoffkunde",
    subtitle: "Werkstoffe und ihre Eigenschaften für Ingenieuranwendungen",
    status: "coming-soon",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Ingenieurwissenschaften",
    number: "1",
  },
  {
    slug: "ing-2",
    faculty: "WiWi-Fakultät",
    title: "Technische Mechanik",
    subtitle: "Statik und Festigkeitslehre",
    status: "active",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [
      "Kräfte, Axiome und der starre Körper",
      "Kraftgruppen, Hebelgesetz und das Moment einer Kraft",
      "Gleichgewicht, Lagerarten und statische Bestimmtheit",
      "Haftreibung, Seilreibung und der Kraftkegel",
      "Fachwerke: Knotenschnitt- und Rittersches Verfahren",
      "Schnittgrößen am geraden Balken",
      "Spannungen, Dehnungen und das Hookesche Gesetz",
      "Flächenträgheitsmoment und der Satz von Steiner",
      "Gerade Biegung und die Biegelinie",
      "Mehrteilige Tragwerke und der Gelenkbalken",
      "Exkurs: Mehrachsiger Spannungszustand und der Mohrsche Spannungskreis",
      "Exkurs: Knicken von Stäben nach Euler",
    ],
    questionCount: 61,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Ingenieurwissenschaften",
    number: "2",
    exampleQuestion: "Erklär mir den Satz von Steiner an einem Beispiel.",
  },
  {
    slug: "ing-3",
    faculty: "WiWi-Fakultät",
    title: "Elektrotechnik",
    subtitle: "Grundlagen der Elektrotechnik",
    status: "coming-soon",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Ingenieurwissenschaften",
    number: "3",
  },
  {
    slug: "ing-4",
    faculty: "WiWi-Fakultät",
    title: "Weiterführende ingenieurwissenschaftliche Grundlagen",
    subtitle: "Vertiefende ingenieurwissenschaftliche Inhalte",
    status: "coming-soon",
    priceCent: 499,
    compareAtCent: 1500,
    chapters: [],
    questionCount: 0,
    studiengang: "Wirtschaftsingenieurwesen",
    subject: "Ingenieurwissenschaften",
    number: "4",
  },
];

export function getModule(slug: string): ModuleDefinition | undefined {
  return modules.find((m) => m.slug === slug);
}

export function formatEuro(cent: number): string {
  return (cent / 100).toLocaleString("de-DE", {
    style: "currency",
    currency: "EUR",
  });
}
