import type { Question } from "@/lib/questions";

// Themen entsprechen (in Kurzform) den Kapiteltiteln aus lib/content/ing-2.ts.
// Alle Übungsaufgaben, die inhaltlich auf reale Übungsblätter/Mitschriebe
// zurückgehen, wurden gemäß den Projektregeln (CLAUDE.md) sowohl in den
// Zahlen als auch im Szenario verändert — es taucht nie derselbe Zahlensatz
// UND dasselbe Szenario wie im Original gleichzeitig auf. Rein abstrakte/
// symbolische bzw. bereits allgemeingültige Aufgaben (z. B. reine
// Formelanwendung ohne erfundenen Kontext) wurden nur bei den Zahlen
// verändert.
export const TOPICS = [
  "Spannungen und Hookesches Gesetz",
  "Kräfte und Axiome der Statik",
  "Flächenträgheitsmoment und Satz von Steiner",
  "Kraftgruppen und Moment",
  "Knicken von Stäben",
  "Gleichgewicht und Lagerarten",
  "Biegung und Biegelinie",
  "Mehrteilige Tragwerke",
  "Mohrscher Spannungskreis",
  "Fachwerke",
  "Schnittgrößen am Balken",
  "Haftreibung und Seilreibung",
] as const;

export const questions: Question[] = [
  // ---------- Spannungen und Hookesches Gesetz (frei zugänglich) ----------
  {
    id: "sp-01",
    topic: "Spannungen und Hookesches Gesetz",
    type: "mc",
    prompt: "Wie ist die Normalspannung σ in einem Querschnitt mit Fläche A unter Normalkraft N definiert?",
    options: ["σ = N · A", "σ = N / A", "σ = A / N", "σ = N + A"],
    correctIndex: 1,
    explanation: "Die Normalspannung ist die auf die Querschnittsfläche bezogene Normalkraft: σ = N/A.",
    source: "Kapitel 1.1, Von der Schnittgröße zur Spannung",
    free: true,
  },
  {
    id: "sp-02",
    topic: "Spannungen und Hookesches Gesetz",
    type: "numeric",
    prompt: "Ein Aufzugsseil mit Querschnittsfläche A = 150 mm² wird mit einer Kraft F = 45 kN belastet. Wie groß ist die Normalspannung σ?",
    correctValue: 300,
    tolerance: 2,
    unit: "N/mm²",
    explanation: "σ = N/A = 45 000 N / 150 mm² = 300 N/mm².",
    source: "Kapitel 1.1, Von der Schnittgröße zur Spannung",
    free: true,
  },
  {
    id: "sp-03",
    topic: "Spannungen und Hookesches Gesetz",
    type: "numeric",
    prompt: "Ein Aluminiumstab (E = 70 000 N/mm²) der Länge ℓ = 3000 mm wird auf σ = 90 N/mm² belastet. Um wie viel mm verlängert er sich (Δℓ)?",
    correctValue: 3.86,
    tolerance: 0.05,
    unit: "mm",
    explanation: "ε = σ/E = 90/70 000 ≈ 1,2857·10⁻³. Δℓ = ε·ℓ ≈ 1,2857·10⁻³ · 3000 mm ≈ 3,86 mm.",
    source: "Kapitel 1.2, Dehnung und das Hookesche Gesetz",
    free: true,
  },
  {
    id: "sp-04",
    topic: "Spannungen und Hookesches Gesetz",
    type: "numeric",
    prompt: "Für einen Werkstoff gilt E = 200 000 N/mm² und ν = 0,3. Wie groß ist der Schubmodul G?",
    correctValue: 76923,
    tolerance: 50,
    unit: "N/mm²",
    explanation: "G = E/(2(1+ν)) = 200 000/(2·1,3) = 200 000/2,6 ≈ 76 923 N/mm².",
    source: "Kapitel 1.3, Der dreiachsige Spannungszustand",
    free: true,
  },
  {
    id: "sp-05",
    topic: "Spannungen und Hookesches Gesetz",
    type: "mc",
    prompt: "Wie groß ist die Normalspannung in der neutralen Faser eines auf reine Biegung beanspruchten Balkens (ohne zusätzliche Normalkraft)?",
    options: ["Maximal (Zug)", "Maximal (Druck)", "Null", "Gleich der mittleren Schubspannung"],
    correctIndex: 2,
    explanation: "In der neutralen Faser (z = 0) verschwindet die Biegespannung σ(x,z) = M(x)/Iy(x)·z, da z = 0 ist.",
    source: "Kapitel 7.2, Biegespannungen und das Widerstandsmoment",
    free: true,
  },

  // ---------- Kräfte und Axiome der Statik ----------
  {
    id: "ax-01",
    topic: "Kräfte und Axiome der Statik",
    type: "mc",
    prompt: "Welche der folgenden Aussagen ist KEIN Grundaxiom der Statik starrer Körper?",
    options: [
      "Gleichgewichtsaxiom (zwei Kräfte im Gleichgewicht liegen auf einer Wirkungslinie, sind gleich groß und entgegengesetzt)",
      "Kräfteparallelogramm-Axiom",
      "Wechselwirkungsgesetz (actio = reactio)",
      "Energieerhaltungssatz",
    ],
    correctIndex: 3,
    explanation: "Der Energieerhaltungssatz ist ein Prinzip der Mechanik allgemein, aber kein Grundaxiom der Statik starrer Körper im engeren Sinn.",
    source: "Kapitel 2.2, Die Grundaxiome der Statik",
    free: false,
  },
  {
    id: "ax-02",
    topic: "Kräfte und Axiome der Statik",
    type: "mc",
    prompt: "Was besagt das Wechselwirkungsgesetz (actio = reactio)?",
    options: [
      "Jede Kraft erzeugt ein Moment gleicher Größe",
      "Die Kraft von Körper A auf B ist betragsgleich und entgegengesetzt gerichtet zur Kraft von B auf A",
      "Kräfte an starren Körpern dürfen beliebig verschoben werden",
      "Zwei Kräfte an einem Punkt addieren sich immer zu null",
    ],
    correctIndex: 1,
    explanation: "Das Wechselwirkungsgesetz ist die Grundlage jedes Freischnitts: An einer Schnittstelle sind die Kräfte an beiden Schnittufern betragsgleich und entgegengesetzt gerichtet.",
    source: "Kapitel 2.2, Die Grundaxiome der Statik",
    free: false,
  },
  {
    id: "ax-03",
    topic: "Kräfte und Axiome der Statik",
    type: "numeric",
    prompt: "Eine Kraft mit Betrag F = 250 N wirkt entlang eines Richtungsvektors (5, 12). Wie groß ist die Komponente Fx?",
    correctValue: 96.15,
    tolerance: 0.5,
    unit: "N",
    explanation: "Der Betrag des Richtungsvektors ist √(5²+12²) = 13. Fx = F · 5/13 = 250·5/13 ≈ 96,15 N.",
    source: "Kapitel 2.3, Richtungscosinus im 2D- und 3D-Raum",
    free: false,
  },
  {
    id: "ax-04",
    topic: "Kräfte und Axiome der Statik",
    type: "mc",
    prompt: "Was besagt das Prinzip der Linienflüchtigkeit einer Kraft?",
    options: [
      "Eine Kraft darf entlang ihrer Wirkungslinie verschoben werden, ohne die Wirkung auf den starren Körper zu ändern",
      "Eine Kraft darf beliebig quer zu ihrer Wirkungslinie verschoben werden",
      "Kräfte verschwinden nach kurzer Zeit (sind 'flüchtig')",
      "Nur Kräfte entlang der x-Achse dürfen verschoben werden",
    ],
    correctIndex: 0,
    explanation: "Die Linienflüchtigkeit erlaubt nur eine Verschiebung entlang der eigenen Wirkungslinie; quer dazu ändert sich die Wirkung auf den starren Körper.",
    source: "Kapitel 2.2, Die Grundaxiome der Statik",
    free: false,
  },
  {
    id: "ax-05",
    topic: "Kräfte und Axiome der Statik",
    type: "mc",
    prompt: "Warum idealisiert man Bauteile in der Statik häufig als 'starren Körper'?",
    options: [
      "Weil reale Bauteile sich gar nicht verformen",
      "Um Gleichgewichtsbedingungen formulieren zu können, ohne die (i. A. sehr kleine) elastische Verformung berücksichtigen zu müssen",
      "Weil starre Körper leichter sind",
      "Weil nur starre Körper Kräfte übertragen können",
    ],
    correctIndex: 1,
    explanation: "Die Idealisierung als starrer Körper erlaubt es, Gleichgewicht zu betrachten, ohne die tatsächliche elastische Verformung (Gegenstand der Festigkeitslehre) einbeziehen zu müssen.",
    source: "Kapitel 2.1, Der starre Körper und die Einzelkraft als gebundener Vektor",
    free: false,
  },

  // ---------- Flächenträgheitsmoment und Satz von Steiner ----------
  {
    id: "fl-01",
    topic: "Flächenträgheitsmoment und Satz von Steiner",
    type: "numeric",
    prompt: "Ein Rechteckquerschnitt hat Breite b = 60 mm und Höhe h = 90 mm. Wie groß ist das axiale Flächenträgheitsmoment Iy bezüglich der Schwerachse?",
    correctValue: 3645000,
    tolerance: 5000,
    unit: "mm⁴",
    explanation: "Iy = b·h³/12 = 60·90³/12 = 60·729 000/12 = 3 645 000 mm⁴.",
    source: "Kapitel 3.1, Axiale Flächenmomente 2. Grades",
    free: false,
  },
  {
    id: "fl-02",
    topic: "Flächenträgheitsmoment und Satz von Steiner",
    type: "numeric",
    prompt: "Ein Querschnitt hat bezüglich seiner Schwerachse Iy,S = 400 000 mm⁴ und Fläche A = 1000 mm². Wie groß ist Iy bezüglich einer dazu parallelen Achse im Abstand zS = 30 mm?",
    correctValue: 1300000,
    tolerance: 5000,
    unit: "mm⁴",
    explanation: "Nach Steiner: Iy,A = Iy,S + zS²·A = 400 000 + 30²·1000 = 400 000 + 900 000 = 1 300 000 mm⁴.",
    source: "Kapitel 3.2, Der Satz von Steiner",
    free: false,
  },
  {
    id: "fl-03",
    topic: "Flächenträgheitsmoment und Satz von Steiner",
    type: "mc",
    prompt: "Unter allen zueinander parallelen Achsen — bezüglich welcher Achse ist das Flächenträgheitsmoment eines Querschnitts am kleinsten?",
    options: ["Bezüglich einer beliebigen Randachse", "Bezüglich der Schwerachse", "Bezüglich der am weitesten entfernten Achse", "Das Flächenträgheitsmoment ist für alle Achsen gleich groß"],
    correctIndex: 1,
    explanation: "Der Steiner-Anteil zS²·A ist stets ≥ 0, daher ist Iy bezüglich der Schwerachse (zS = 0) das kleinstmögliche unter allen parallelen Achsen.",
    source: "Kapitel 3.2, Der Satz von Steiner",
    free: false,
  },
  {
    id: "fl-04",
    topic: "Flächenträgheitsmoment und Satz von Steiner",
    type: "mc",
    prompt: "Wie geht man beim Flächenträgheitsmoment eines Querschnitts mit einer Aussparung (z. B. Bohrung) vor?",
    options: [
      "Das Flächenträgheitsmoment der Aussparung wird addiert",
      "Das Flächenträgheitsmoment der Aussparung wird von dem der Vollfläche subtrahiert",
      "Aussparungen werden bei Flächenträgheitsmomenten ignoriert",
      "Es muss ein völlig neues Integral ohne Zerlegung aufgestellt werden",
    ],
    correctIndex: 1,
    explanation: "Man zerlegt den Querschnitt in Teilflächen und behandelt die Aussparung als Teilfläche mit negativem Vorzeichen (Subtraktion).",
    source: "Kapitel 3.3, Zusammengesetzte Querschnitte",
    free: false,
  },
  {
    id: "fl-05",
    topic: "Flächenträgheitsmoment und Satz von Steiner",
    type: "numeric",
    prompt: "Ein Querschnitt besteht aus zwei Teilflächen: A1 = 800 mm² bei r1 = 10 mm und A2 = 400 mm² bei r2 = 40 mm. Wo liegt der Gesamtschwerpunkt rS?",
    correctValue: 20,
    tolerance: 0.5,
    unit: "mm",
    explanation: "rS = (A1·r1 + A2·r2)/(A1+A2) = (800·10 + 400·40)/1200 = (8000+16000)/1200 = 20 mm.",
    source: "Kapitel 3.3, Zusammengesetzte Querschnitte",
    free: false,
  },

  // ---------- Kraftgruppen und Moment ----------
  {
    id: "kg-01",
    topic: "Kraftgruppen und Moment",
    type: "mc",
    prompt: "Was zeichnet eine zentrale Kraftgruppe aus?",
    options: [
      "Alle Kräfte sind gleich groß",
      "Die Wirkungslinien aller Kräfte schneiden sich in einem gemeinsamen Punkt",
      "Alle Kräfte greifen am selben Bauteil an",
      "Die Kraftgruppe erzeugt kein Moment",
    ],
    correctIndex: 1,
    explanation: "Eine zentrale Kraftgruppe liegt vor, wenn sich alle Wirkungslinien in einem gemeinsamen Punkt schneiden — sie ist dann immer durch eine Resultierende ersetzbar.",
    source: "Kapitel 4.1, Zentrale und nichtzentrale Kraftgruppen",
    free: false,
  },
  {
    id: "kg-02",
    topic: "Kraftgruppen und Moment",
    type: "numeric",
    prompt: "An einem zweiseitigen Hebel wirkt F1 = 80 N im Abstand ℓ1 = 1,2 m vom Drehpunkt. Wie groß muss F2 im Abstand ℓ2 = 0,4 m sein, damit Gleichgewicht herrscht?",
    correctValue: 240,
    tolerance: 2,
    unit: "N",
    explanation: "Hebelgesetz: F1·ℓ1 = F2·ℓ2 → F2 = F1·ℓ1/ℓ2 = 80·1,2/0,4 = 240 N.",
    source: "Kapitel 4.2, Hebelgesetz und das Kräftepaar",
    free: false,
  },
  {
    id: "kg-03",
    topic: "Kraftgruppen und Moment",
    type: "mc",
    prompt: "Welche Eigenschaft hat ein Kräftepaar?",
    options: [
      "Resultierende ungleich null, Moment null",
      "Resultierende null, Moment ungleich null und bezugspunktunabhängig",
      "Resultierende und Moment sind beide null",
      "Resultierende und Moment hängen beide vom Bezugspunkt ab",
    ],
    correctIndex: 1,
    explanation: "Ein Kräftepaar besteht aus zwei betragsgleichen, entgegengesetzten, parallelen Kräften: Die Resultierende ist null, das erzeugte Moment aber nicht — und ist unabhängig vom gewählten Bezugspunkt.",
    source: "Kapitel 4.2, Hebelgesetz und das Kräftepaar",
    free: false,
  },
  {
    id: "kg-04",
    topic: "Kraftgruppen und Moment",
    type: "numeric",
    prompt: "Eine Kraft F⃗ = (0, −150 N) greift im Punkt (0,6 m, 0) an. Wie groß ist der Betrag ihres Moments bezüglich des Ursprungs?",
    correctValue: 90,
    tolerance: 1,
    unit: "Nm",
    explanation: "Mz = x·Fy − y·Fx = 0,6·(−150) − 0·0 = −90 Nm, Betrag 90 Nm.",
    source: "Kapitel 4.3, Das Moment einer Kraft und die Dyname",
    free: false,
  },
  {
    id: "kg-05",
    topic: "Kraftgruppen und Moment",
    type: "mc",
    prompt: "Was ist eine Dyname?",
    options: [
      "Eine Kraft, die keine Wirkungslinie besitzt",
      "Die äquivalente Ersatzwirkung einer nichtzentralen Kraftgruppe: eine Einzelkraft plus ein zusätzliches Moment",
      "Ein anderer Name für das Kräftepaar",
      "Die Summe aller Lagerreaktionen eines Systems",
    ],
    correctIndex: 1,
    explanation: "Lässt sich eine Kraftgruppe nicht auf eine reine Resultierende reduzieren, bleibt als Ersatzwirkung eine Kombination aus Kraft und Moment — die Dyname.",
    source: "Kapitel 4.3, Das Moment einer Kraft und die Dyname",
    free: false,
  },

  // ---------- Knicken von Stäben ----------
  {
    id: "kn-01",
    topic: "Knicken von Stäben",
    type: "mc",
    prompt: "Worin unterscheidet sich das Knicken eines Stabes von einem klassischen Festigkeitsversagen?",
    options: [
      "Knicken ist ein Stabilitätsversagen, das schon unterhalb der Werkstofffestigkeit auftreten kann",
      "Knicken tritt nur bei Zugbelastung auf",
      "Knicken hängt ausschließlich von der Werkstofffestigkeit ab",
      "Knicken und Festigkeitsversagen sind identisch definiert",
    ],
    correctIndex: 0,
    explanation: "Knicken ist ein Stabilitätsproblem: Ein schlanker, druckbelasteter Stab kann seitlich ausweichen, obwohl die rechnerische Spannung noch weit unter der Werkstofffestigkeit liegt.",
    source: "Kapitel 5.1, Stabilitätsversagen statt Festigkeitsversagen",
    free: false,
  },
  {
    id: "kn-02",
    topic: "Knicken von Stäben",
    type: "mc",
    prompt: "Welcher der vier Euler-Knickfälle hat bei gleicher tatsächlicher Stablänge die GRÖSSTE Knicklänge ℓk (und damit die kleinste kritische Last)?",
    options: [
      "Beidseitig eingespannt (ℓk = 0,5ℓ)",
      "Einseitig eingespannt, andere Seite gelenkig geführt (ℓk ≈ 0,7ℓ)",
      "Beidseitig gelenkig gelagert (ℓk = ℓ)",
      "Einseitig eingespannt, anderes Ende frei — Kragstab (ℓk = 2ℓ)",
    ],
    correctIndex: 3,
    explanation: "Der Kragstab (einseitig eingespannt, frei am anderen Ende) hat mit ℓk = 2ℓ die größte Knicklänge und damit die kleinste kritische Knicklast.",
    source: "Kapitel 5.2, Die vier Eulerschen Knickfälle",
    free: false,
  },
  {
    id: "kn-03",
    topic: "Knicken von Stäben",
    type: "numeric",
    prompt: "Ein Stab hat EI = 900 kNm² und Knicklänge ℓk = 3 m. Wie groß ist die kritische Knicklast Fk?",
    correctValue: 987,
    tolerance: 5,
    unit: "kN",
    explanation: "Fk = π²·EI/ℓk² = π²·900/9 = π²·100 ≈ 987 kN.",
    source: "Kapitel 5.2, Die vier Eulerschen Knickfälle",
    free: false,
  },
  {
    id: "kn-04",
    topic: "Knicken von Stäben",
    type: "mc",
    prompt: "Welche Knicklänge ℓk gilt für einen beidseitig eingespannten Stab der Länge ℓ?",
    options: ["ℓk = 2ℓ", "ℓk = ℓ", "ℓk = 0,7ℓ", "ℓk = 0,5ℓ"],
    correctIndex: 3,
    explanation: "Beim beidseitig eingespannten Stab ist die Knicklänge ℓk = 0,5ℓ — die kleinste der vier Euler-Fälle.",
    source: "Kapitel 5.2, Die vier Eulerschen Knickfälle",
    free: false,
  },
  {
    id: "kn-05",
    topic: "Knicken von Stäben",
    type: "mc",
    prompt: "Wie verändert sich die kritische Knicklast Fk, wenn die Stablänge verdoppelt wird (bei gleichbleibendem EI und gleicher Lagerung)?",
    options: ["Sie verdoppelt sich", "Sie bleibt gleich", "Sie sinkt auf ein Viertel", "Sie vervierfacht sich"],
    correctIndex: 2,
    explanation: "Da Fk ∝ 1/ℓk² und ℓk proportional zu ℓ ist, sinkt Fk bei Verdopplung der Länge auf (1/2)² = 1/4 des ursprünglichen Werts.",
    source: "Kapitel 5.2, Die vier Eulerschen Knickfälle",
    free: false,
  },

  // ---------- Gleichgewicht und Lagerarten ----------
  {
    id: "gl-01",
    topic: "Gleichgewicht und Lagerarten",
    type: "mc",
    prompt: "Welche Lagerwertigkeit hat ein Festlager in der Ebene?",
    options: ["Einwertig", "Zweiwertig", "Dreiwertig", "Nullwertig"],
    correctIndex: 1,
    explanation: "Ein Festlager sperrt Verschiebungen in beide Richtungen der Ebene und liefert zwei Lagerkraftkomponenten — es ist zweiwertig.",
    source: "Kapitel 6.2, Lagerwertigkeiten",
    free: false,
  },
  {
    id: "gl-02",
    topic: "Gleichgewicht und Lagerarten",
    type: "mc",
    prompt: "Ein ebener Balken (n = 1) ist durch ein Festlager und ein Loslager gelagert. Ist die notwendige Bedingung für statische Bestimmtheit erfüllt?",
    options: [
      "Ja, da N = 3 = R = 2 + 1",
      "Nein, da zu wenige Lagerreaktionen vorhanden sind",
      "Nein, da zu viele Lagerreaktionen vorhanden sind",
      "Das lässt sich ohne genaue Lage der Lager nicht sagen",
    ],
    correctIndex: 0,
    explanation: "Für n = 1 sind N = 3 Gleichungen verfügbar. Festlager (2) + Loslager (1) ergeben R = 3, also N = R — die notwendige Bedingung ist erfüllt.",
    source: "Kapitel 6.3, Notwendige und hinreichende Bedingung, der Ausnahmefall",
    free: false,
  },
  {
    id: "gl-03",
    topic: "Gleichgewicht und Lagerarten",
    type: "mc",
    prompt: "Was kennzeichnet den 'Ausnahmefall' der statischen Bestimmtheit?",
    options: [
      "N = R ist erfüllt, aber det A = 0 — das System ist trotzdem kinematisch verschieblich",
      "N ≠ R, das System ist statisch unbestimmt",
      "Es handelt sich um ein System ganz ohne Lager",
      "Der Ausnahmefall tritt nur bei mehrteiligen Tragwerken auf",
    ],
    correctIndex: 0,
    explanation: "Im Ausnahmefall stimmt die Anzahl der Gleichungen und Unbekannten zwar überein (N = R), die Koeffizientenmatrix ist aber singulär (det A = 0) — das System bleibt verschieblich.",
    source: "Kapitel 6.3, Notwendige und hinreichende Bedingung, der Ausnahmefall",
    free: false,
  },
  {
    id: "gl-04",
    topic: "Gleichgewicht und Lagerarten",
    type: "mc",
    prompt: "Wie viele skalare Gleichgewichtsbedingungen stehen für einen ebenen starren Körper zur Verfügung?",
    options: ["Zwei", "Drei", "Vier", "Sechs"],
    correctIndex: 1,
    explanation: "In der Ebene gilt Σ Fx = 0, Σ Fy = 0 und Σ Mz = 0 — also drei Gleichungen.",
    source: "Kapitel 6.1, Gleichgewichtsbedingungen",
    free: false,
  },
  {
    id: "gl-05",
    topic: "Gleichgewicht und Lagerarten",
    type: "numeric",
    prompt: "Ein Steg der Länge L = 5 m ist bei A (Festlager) und bei B (Loslager, am anderen Ende) gelagert. Bei 2 m von A entfernt wirkt eine Last P = 10 kN senkrecht nach unten. Wie groß ist die Lagerkraft Ay?",
    correctValue: 6,
    tolerance: 0.2,
    unit: "kN",
    explanation: "Momentengleichgewicht um A: By·5 = P·2 → By = 10·2/5 = 4 kN. Kräftegleichgewicht: Ay = P − By = 10 − 4 = 6 kN.",
    source: "Kapitel 6.1, Gleichgewichtsbedingungen",
    free: false,
  },

  // ---------- Biegung und Biegelinie ----------
  {
    id: "bg-01",
    topic: "Biegung und Biegelinie",
    type: "mc",
    prompt: "Welche Differentialgleichung beschreibt die Biegelinie w(x) eines Balkens (technische Biegelehre, kleine Durchbiegungen)?",
    options: ["w'(x) = M(x)/(EIy(x))", "w''(x) = −M(x)/(EIy(x))", "w''(x) = M(x)·EIy(x)", "w(x) = −M(x)/EIy(x)"],
    correctIndex: 1,
    explanation: "Die Biegelinien-DGL lautet w''(x) = −M(x)/(EIy(x)).",
    source: "Kapitel 7.1, Die Differentialgleichung der Biegelinie",
    free: false,
  },
  {
    id: "bg-02",
    topic: "Biegung und Biegelinie",
    type: "numeric",
    prompt: "Ein Rechteckquerschnitt (b = 60 mm, h = 120 mm) wird mit einem Biegemoment M = 12 kNm belastet. Wie groß ist die maximale Biegespannung σmax?",
    correctValue: 83.3,
    tolerance: 1,
    unit: "N/mm²",
    explanation: "Iy = 60·120³/12 = 8 640 000 mm⁴, zmax = 60 mm, W = Iy/zmax = 144 000 mm³. σmax = M/W = 12·10⁶ Nmm / 144 000 mm³ ≈ 83,3 N/mm².",
    source: "Kapitel 7.2, Biegespannungen und das Widerstandsmoment",
    free: false,
  },
  {
    id: "bg-03",
    topic: "Biegung und Biegelinie",
    type: "mc",
    prompt: "Welche Randbedingungen gelten für die Biegelinie an einer festen Einspannung?",
    options: ["Nur w = 0", "Nur w' = 0", "w = 0 und w' = 0", "Weder w noch w' sind festgelegt"],
    correctIndex: 2,
    explanation: "An einer festen Einspannung verschwinden sowohl die Durchbiegung (w = 0) als auch die Neigung (w' = 0).",
    source: "Kapitel 7.3, Integrationskonstanten aus Rand- und Übergangsbedingungen",
    free: false,
  },
  {
    id: "bg-04",
    topic: "Biegung und Biegelinie",
    type: "mc",
    prompt: "Was fordert eine Übergangsbedingung an einer Bereichsgrenze der Biegelinie (ohne Gelenk an dieser Stelle)?",
    options: [
      "Durchbiegung und Neigung müssen stetig ineinander übergehen",
      "Die Durchbiegung muss dort null sein",
      "Das Biegemoment muss dort einen Sprung aufweisen",
      "Es gibt keine Anforderung an dieser Stelle",
    ],
    correctIndex: 0,
    explanation: "Ohne Gelenk darf die Biegelinie an der Bereichsgrenze weder springen noch knicken — Durchbiegung und Neigung müssen stetig übergehen.",
    source: "Kapitel 7.3, Integrationskonstanten aus Rand- und Übergangsbedingungen",
    free: false,
  },
  {
    id: "bg-05",
    topic: "Biegung und Biegelinie",
    type: "mc",
    prompt: "Wie hängt die Biegespannung σ(x,z) vom Abstand z zur neutralen Faser ab?",
    options: ["Quadratisch", "Linear", "Umgekehrt proportional", "Sie ist unabhängig von z"],
    correctIndex: 1,
    explanation: "σ(x,z) = M(x)/Iy(x) · z — die Biegespannung hängt linear vom Randabstand z ab.",
    source: "Kapitel 7.2, Biegespannungen und das Widerstandsmoment",
    free: false,
  },

  // ---------- Mehrteilige Tragwerke ----------
  {
    id: "mt-01",
    topic: "Mehrteilige Tragwerke",
    type: "mc",
    prompt: "Warum genügt bei einem mehrteiligen, über Gelenke verbundenen Tragwerk eine Gleichgewichtsbetrachtung am Gesamtsystem nicht?",
    options: [
      "Weil das Gesamtsystem nie im Gleichgewicht ist",
      "Weil die inneren Gelenkkräfte im Gesamtsystem gar nicht sichtbar sind, obwohl sie gesuchte Größen sind",
      "Weil Gesamtsysteme grundsätzlich statisch unbestimmt sind",
      "Weil Gelenke keine Kräfte übertragen können",
    ],
    correctIndex: 1,
    explanation: "Die Gelenkkräfte heben sich im Gesamtsystem gegenseitig auf und tauchen dort nicht auf — deshalb muss jeder Teilkörper einzeln freigeschnitten werden.",
    source: "Kapitel 8.1, Das Schnittprinzip bei mehrteiligen Systemen",
    free: false,
  },
  {
    id: "mt-02",
    topic: "Mehrteilige Tragwerke",
    type: "mc",
    prompt: "Wozu dient ein Gelenkbalken (Gerber-Träger) in der Praxis, z. B. bei langen Brücken?",
    options: [
      "Er erhöht das Eigengewicht der Konstruktion",
      "Er vermeidet Zwängungsspannungen aus Temperaturdehnung, die bei einem vollständig durchlaufenden, mehrfach gelagerten Träger sonst auftreten würden",
      "Er ersetzt sämtliche Lager",
      "Er macht das Tragwerk statisch unbestimmt",
    ],
    correctIndex: 1,
    explanation: "Durch die gelenkige Unterteilung in Teilträger können Temperaturdehnungen ohne Zwängungsspannungen aufgenommen werden.",
    source: "Kapitel 8.2, Der Gelenkbalken (Gerber-Träger)",
    free: false,
  },
  {
    id: "mt-03",
    topic: "Mehrteilige Tragwerke",
    type: "numeric",
    prompt: "Ein zweiteiliges Tragwerk (n = 2) hat ein Festlager (2), zwei Loslager (je 1) und ein zweiwertiges Gelenk (2). Wie groß ist R (Summe aller Wertigkeiten)?",
    correctValue: 6,
    tolerance: 0,
    unit: "",
    explanation: "R = 2 (Festlager) + 1 + 1 (Loslager) + 2 (Gelenk) = 6 — und stimmt damit mit N = 3n = 6 überein (notwendige Bedingung erfüllt).",
    source: "Kapitel 8.3, Statische Bestimmtheit mehrteiliger Systeme",
    free: false,
  },
  {
    id: "mt-04",
    topic: "Mehrteilige Tragwerke",
    type: "mc",
    prompt: "Wie verhalten sich die Gelenkkräfte an den beiden Schnittufern eines Gelenks nach dem Wechselwirkungsgesetz?",
    options: [
      "Sie sind unabhängig voneinander",
      "Betragsgleich und entgegengesetzt gerichtet",
      "Immer gleich null",
      "Immer doppelt so groß auf einer Seite",
    ],
    correctIndex: 1,
    explanation: "Nach actio = reactio müssen die Gelenkkräfte an beiden Schnittufern betragsgleich, aber entgegengesetzt gerichtet eingetragen werden.",
    source: "Kapitel 8.1, Das Schnittprinzip bei mehrteiligen Systemen",
    free: false,
  },
  {
    id: "mt-05",
    topic: "Mehrteilige Tragwerke",
    type: "mc",
    prompt: "Warum 'kostet' ein zusätzliches zweiwertiges Gelenk in der Bestimmtheitsabzählung netto keine zusätzliche Unbestimmtheit?",
    options: [
      "Weil es zwei zusätzliche Unbekannte einbringt, aber gleichzeitig die Anzahl der Teilkörper (und damit Gleichungen) um drei erhöht",
      "Weil Gelenke gar keine Kräfte übertragen",
      "Weil ein Gelenk die Anzahl der Unbekannten verringert",
      "Weil Gelenke nur bei statisch unbestimmten Systemen vorkommen",
    ],
    correctIndex: 0,
    explanation: "Ein Gelenk zwischen zwei Teilkörpern bringt zwei zusätzliche Unbekannte (Gelenkkraftkomponenten), erhöht aber gleichzeitig n und damit N = 3n um drei.",
    source: "Kapitel 8.3, Statische Bestimmtheit mehrteiliger Systeme",
    free: false,
  },

  // ---------- Mohrscher Spannungskreis ----------
  {
    id: "mo-01",
    topic: "Mohrscher Spannungskreis",
    type: "numeric",
    prompt: "Für einen ebenen Spannungszustand gilt σx = 80 N/mm², σy = 20 N/mm², τxy = 30 N/mm². Wie groß ist die Hauptspannung σ1?",
    correctValue: 92.4,
    tolerance: 0.5,
    unit: "N/mm²",
    explanation: "σ1,2 = (σx+σy)/2 ± √(((σx−σy)/2)² + τxy²) = 50 ± √(30²+30²) = 50 ± 42,43. σ1 ≈ 92,4 N/mm².",
    source: "Kapitel 9.1, Hauptspannungen und Hauptspannungsrichtungen",
    free: false,
  },
  {
    id: "mo-02",
    topic: "Mohrscher Spannungskreis",
    type: "mc",
    prompt: "Welchen Radius hat der Mohrsche Spannungskreis für σx, σy, τxy?",
    options: [
      "√(((σx−σy)/2)² + τxy²)",
      "(σx+σy)/2",
      "σx − σy",
      "τxy²",
    ],
    correctIndex: 0,
    explanation: "Der Radius des Mohrschen Kreises ist √(((σx−σy)/2)² + τxy²) — derselbe Term wie in der Hauptspannungsformel.",
    source: "Kapitel 9.2, Konstruktion des Mohrschen Spannungskreises",
    free: false,
  },
  {
    id: "mo-03",
    topic: "Mohrscher Spannungskreis",
    type: "mc",
    prompt: "Was gilt, wenn τxy = 0 ist?",
    options: [
      "σx und σy sind bereits die Hauptspannungen",
      "Es existieren keine Hauptspannungen",
      "Der Mohrsche Kreis entartet zu einem Punkt",
      "σ1 und σ2 sind beide null",
    ],
    correctIndex: 0,
    explanation: "Ist τxy = 0, verschwindet der Wurzelterm in der Hauptspannungsformel bereits für die gegebene Schnittrichtung — σx und σy sind dann selbst die Hauptspannungen.",
    source: "Kapitel 9.1, Hauptspannungen und Hauptspannungsrichtungen",
    free: false,
  },
  {
    id: "mo-04",
    topic: "Mohrscher Spannungskreis",
    type: "mc",
    prompt: "Wo liegt der Mittelpunkt des Mohrschen Spannungskreises auf der σ-Achse?",
    options: ["Bei σx − σy", "Bei (σx+σy)/2", "Bei τxy", "Immer im Ursprung"],
    correctIndex: 1,
    explanation: "Der Mittelpunkt liegt bei ((σx+σy)/2, 0) — dem invarianten Mittelwert der beiden Normalspannungen.",
    source: "Kapitel 9.2, Konstruktion des Mohrschen Spannungskreises",
    free: false,
  },
  {
    id: "mo-05",
    topic: "Mohrscher Spannungskreis",
    type: "numeric",
    prompt: "Die Hauptspannungen betragen σ1 = 100 N/mm² und σ2 = 20 N/mm². Wie groß ist die maximale Schubspannung τmax?",
    correctValue: 40,
    tolerance: 1,
    unit: "N/mm²",
    explanation: "τmax entspricht dem Radius des Mohrschen Kreises: τmax = (σ1−σ2)/2 = (100−20)/2 = 40 N/mm².",
    source: "Kapitel 9.2, Konstruktion des Mohrschen Spannungskreises",
    free: false,
  },

  // ---------- Fachwerke ----------
  {
    id: "fw-01",
    topic: "Fachwerke",
    type: "mc",
    prompt: "Welche Annahme gehört NICHT zu den Voraussetzungen eines idealen Fachwerks?",
    options: [
      "Alle Stäbe sind gerade",
      "Die Knoten sind reibungsfreie Gelenke",
      "Äußere Lasten greifen ausschließlich an den Knoten an",
      "Jeder Stab darf zusätzlich ein Biegemoment übertragen",
    ],
    correctIndex: 3,
    explanation: "Im idealen Fachwerk überträgt jeder Stab nur eine reine Längskraft — Biegemomente treten unter den getroffenen Annahmen nicht auf.",
    source: "Kapitel 10.1, Das ideale Fachwerk",
    free: false,
  },
  {
    id: "fw-02",
    topic: "Fachwerke",
    type: "mc",
    prompt: "Nach der üblichen Konvention: Was bedeutet eine positive Stabkraft (vom Knoten weg gezählt)?",
    options: ["Druckbeanspruchung", "Zugbeanspruchung", "Der Stab ist ein Nullstab", "Der Stab ist instabil"],
    correctIndex: 1,
    explanation: "Wird die Stabkraft positiv vom Knoten weg gezählt, bedeutet ein positiver Wert Zug- und ein negativer Wert Druckbeanspruchung.",
    source: "Kapitel 10.1, Das ideale Fachwerk",
    free: false,
  },
  {
    id: "fw-03",
    topic: "Fachwerke",
    type: "mc",
    prompt: "Worin unterscheiden sich äußere und innere statische Bestimmtheit bei Fachwerken?",
    options: [
      "Äußere Bestimmtheit betrifft die Lagerreaktionen (3n = R), innere Bestimmtheit betrifft die Stabkräfte (2k = s + r)",
      "Beide Begriffe meinen dasselbe",
      "Innere Bestimmtheit betrifft nur die Lager, äußere nur die Stäbe",
      "Äußere Bestimmtheit gibt es bei Fachwerken nicht",
    ],
    correctIndex: 0,
    explanation: "Äußere Bestimmtheit prüft die Lagerreaktionen wie bei jedem Tragwerk (3n = R), innere Bestimmtheit prüft, ob genügend Gleichungen für alle Stabkräfte vorhanden sind (2k = s+r).",
    source: "Kapitel 10.2, Äußere und innere statische Bestimmtheit",
    free: false,
  },
  {
    id: "fw-04",
    topic: "Fachwerke",
    type: "numeric",
    prompt: "Ein Fachwerk hat k = 6 Knoten, s = 9 Stäbe und r = 3 äußere Lagerreaktionen. Wie groß ist 2k?",
    correctValue: 12,
    tolerance: 0,
    unit: "",
    explanation: "2k = 2·6 = 12. Da s + r = 9 + 3 = 12 = 2k, ist die notwendige Bedingung für innere statische Bestimmtheit erfüllt.",
    source: "Kapitel 10.2, Äußere und innere statische Bestimmtheit",
    free: false,
  },
  {
    id: "fw-05",
    topic: "Fachwerke",
    type: "mc",
    prompt: "An einem unbelasteten Knoten treffen sich drei Stäbe, von denen zwei kollinear (in gleicher Richtung) liegen. Was folgt daraus für den dritten Stab?",
    options: [
      "Er ist ein Nullstab",
      "Er trägt die größte Zugkraft im gesamten Fachwerk",
      "Er muss auf Druck beansprucht sein",
      "Daraus folgt nichts Allgemeines",
    ],
    correctIndex: 0,
    explanation: "Nach der dritten Nullstab-Regel ist an einem unbelasteten Knoten mit drei Stäben, von denen zwei kollinear sind, der dritte (quer stehende) Stab ein Nullstab.",
    source: "Kapitel 10.5, Nullstäbe erkennen",
    free: false,
  },
  {
    id: "fw-06",
    topic: "Fachwerke",
    type: "numeric",
    prompt: "An einem Fachwerkknoten wirkt eine vertikale Last F = 50 kN. Zwei symmetrisch angeordnete Stäbe schließen jeweils einen Winkel von 45° mit der Vertikalen ein und tragen die Last gemeinsam. Wie groß ist die Kraft in jedem der beiden Stäbe?",
    correctValue: 35.4,
    tolerance: 0.5,
    unit: "kN",
    explanation: "Aus Symmetrie: 2·S·cos(45°) = F (vertikale Komponente je Stab cos 45°, da Winkel zur Vertikalen), also S = F/(2·cos 45°) = 50/(2·0,7071) ≈ 35,4 kN (Zug).",
    source: "Kapitel 10.3, Das Knotenschnittverfahren",
    free: false,
  },

  // ---------- Schnittgrößen am Balken ----------
  {
    id: "sg-01",
    topic: "Schnittgrößen am Balken",
    type: "mc",
    prompt: "Welche drei Schnittgrößen treten bei einem geraden Balken auf?",
    options: [
      "Normalkraft N, Querkraft Q, Biegemoment M",
      "Spannung σ, Dehnung ε, Elastizitätsmodul E",
      "Lagerkraft, Gelenkkraft, Stabkraft",
      "Nur das Biegemoment M",
    ],
    correctIndex: 0,
    explanation: "Beim Schnitt an einem geraden Balken treten Normalkraft N, Querkraft Q und Biegemoment M auf.",
    source: "Kapitel 11.1, Normalkraft, Querkraft und Biegemoment",
    free: false,
  },
  {
    id: "sg-02",
    topic: "Schnittgrößen am Balken",
    type: "mc",
    prompt: "Was passiert im Schnittgrößenverlauf an der Stelle einer äußeren Einzelkraft quer zur Balkenachse?",
    options: [
      "N(s) macht einen Sprung, Q(s) und M(s) bleiben stetig",
      "Q(s) macht einen Sprung, M(s) hat dort einen Knick",
      "M(s) macht einen Sprung, Q(s) bleibt stetig",
      "Weder N, Q noch M ändern sich"
    ],
    correctIndex: 1,
    explanation: "Eine äußere Querkraft erzeugt einen Sprung im Querkraftverlauf Q(s) und einen Knick im Momentenverlauf M(s).",
    source: "Kapitel 11.2, Vorzeichenkonvention und die Verrundungsregel",
    free: false,
  },
  {
    id: "sg-03",
    topic: "Schnittgrößen am Balken",
    type: "numeric",
    prompt: "Auf einem Bereich der Länge s = 4 m wirkt eine konstante Streckenlast q0 = 6 kN/m. Wie groß ist das daraus resultierende Schnittmoment Mq(s) am Ende des Bereichs?",
    correctValue: 48,
    tolerance: 1,
    unit: "kNm",
    explanation: "Fq = q0·s = 24 kN, Angriffspunkt bei s/2. Mq(s) = q0·s²/2 = 6·16/2 = 48 kNm.",
    source: "Kapitel 11.3, Differentielle Zusammenhänge und Integration von Streckenlasten",
    free: false,
  },
  {
    id: "sg-04",
    topic: "Schnittgrößen am Balken",
    type: "mc",
    prompt: "Welcher differentielle Zusammenhang gilt zwischen Streckenlast q(x) und Querkraft Q(x)?",
    options: ["dQ/dx = q(x)", "dQ/dx = −q(x)", "dQ/dx = M(x)", "dQ/dx = 0 immer"],
    correctIndex: 1,
    explanation: "Aus dem Gleichgewicht am infinitesimalen Balkenelement folgt dQ/dx = −q(x).",
    source: "Kapitel 11.3, Differentielle Zusammenhänge und Integration von Streckenlasten",
    free: false,
  },
  {
    id: "sg-05",
    topic: "Schnittgrößen am Balken",
    type: "mc",
    prompt: "Wofür sorgt die Verrundungsregel bei der grafischen Darstellung des Biegemomentenverlaufs?",
    options: [
      "Für eine einheitliche Konvention, wie das Biegemoment aufgetragen wird (i. d. R. positiv nach unten)",
      "Dafür, dass Sprünge in Q(s) unterdrückt werden",
      "Dafür, dass N(s) immer null ist",
      "Sie betrifft nur dreidimensionale Tragwerke",
    ],
    correctIndex: 0,
    explanation: "Die Verrundungsregel legt eine einheitliche Konvention zur Darstellung des Biegemomentenverlaufs fest, üblicherweise mit positivem Moment nach unten aufgetragen.",
    source: "Kapitel 11.2, Vorzeichenkonvention und die Verrundungsregel",
    free: false,
  },

  // ---------- Haftreibung und Seilreibung ----------
  {
    id: "hr-01",
    topic: "Haftreibung und Seilreibung",
    type: "numeric",
    prompt: "Zwischen zwei Bauteilen wirkt eine Normalkraft N = 200 N bei einem Haftreibungskoeffizienten μ0 = 0,35. Wie groß ist die maximale Haftkraft Hmax?",
    correctValue: 70,
    tolerance: 1,
    unit: "N",
    explanation: "Hmax = μ0·N = 0,35·200 N = 70 N.",
    source: "Kapitel 12.1, Das Coulombsche Haftreibungsgesetz",
    free: false,
  },
  {
    id: "hr-02",
    topic: "Haftreibung und Seilreibung",
    type: "mc",
    prompt: "Wie hängt der Öffnungswinkel φ0 des Kraftkegels mit dem Haftreibungskoeffizienten μ0 zusammen?",
    options: ["tan φ0 = μ0", "sin φ0 = μ0", "φ0 = μ0", "φ0 ist unabhängig von μ0"],
    correctIndex: 0,
    explanation: "Der Haftreibungswinkel ergibt sich aus tan φ0 = Hmax/N = μ0.",
    source: "Kapitel 12.2, Der Kraftkegel",
    free: false,
  },
  {
    id: "hr-03",
    topic: "Haftreibung und Seilreibung",
    type: "numeric",
    prompt: "Ein Seil wird mit μ0 = 0,25 um einen Umschlingungswinkel α = π (180°) geführt. Bei S1 = 50 N — wie groß ist die maximal haltbare Kraft S2 (Grenzfall)?",
    correctValue: 109.7,
    tolerance: 1,
    unit: "N",
    explanation: "S2 = S1·e^(μ0·α) = 50·e^(0,25π) = 50·e^0,785 ≈ 50·2,193 ≈ 109,7 N.",
    source: "Kapitel 12.3, Seilreibung: die Euler-Eytelwein-Formel",
    free: false,
  },
  {
    id: "hr-04",
    topic: "Haftreibung und Seilreibung",
    type: "mc",
    prompt: "Was passiert, wenn die Wirkungslinie der resultierenden Kontaktkraft den Kraftkegel verlässt?",
    options: [
      "Der Körper bleibt in jedem Fall in Ruhe",
      "Die Haftung reicht nicht mehr aus, der Körper beginnt zu rutschen",
      "Die Normalkraft wird automatisch größer",
      "Der Haftreibungskoeffizient ändert sich",
    ],
    correctIndex: 1,
    explanation: "Solange die Wirkungslinie innerhalb des Kraftkegels bleibt, haftet der Körper; verlässt sie ihn, ist die Haftbedingung verletzt und der Körper rutscht.",
    source: "Kapitel 12.2, Der Kraftkegel",
    free: false,
  },
  {
    id: "hr-05",
    topic: "Haftreibung und Seilreibung",
    type: "mc",
    prompt: "Wie verändert sich das Verhältnis S2/S1 bei der Euler-Eytelwein-Formel, wenn der Umschlingungswinkel α (bei gleichem μ0) vergrößert wird, z. B. durch mehrfaches Umschlingen einer Trommel?",
    options: [
      "Es bleibt konstant",
      "Es wächst exponentiell mit α",
      "Es sinkt exponentiell mit α",
      "Es hängt nicht von α ab, nur von μ0",
    ],
    correctIndex: 1,
    explanation: "Da S2 = S1·e^(μ0·α), wächst das Verhältnis S2/S1 exponentiell mit dem Umschlingungswinkel α — schon wenige zusätzliche Umschlingungen erhöhen die haltbare Kraft stark.",
    source: "Kapitel 12.3, Seilreibung: die Euler-Eytelwein-Formel",
    free: false,
  },
];
