export type QuestionType = "mc" | "numeric";

export interface Question {
  id: string;
  topic: string;
  type: QuestionType;
  prompt: string;
  options?: string[];
  correctIndex?: number;
  correctValue?: number;
  tolerance?: number;
  unit?: string;
  explanation: string;
  source: string;
  free: boolean;
}

// Hinweis: Die Übungsaufgaben in dieser Fragenbank orientieren sich der
// mathematischen Struktur nach an echten Tutoriums-/Übungsblättern und
// Klausuraufgaben, sind aber in den konkreten Zahlenwerten/Matrizen/
// Funktionen gegenüber dem Original verändert (Regel 2). Ein eigenes
// Szenario musste hier nicht ausgetauscht werden, da es sich bei
// sämtlichen Aufgaben dieses Moduls um rein abstrakte, symbolische
// Aufgaben ohne konkretes Szenario handelt (reine Rechnungen mit
// Matrizen, Vektoren, Grenzwerten, Ableitungen und Integralen) — genau
// der in CLAUDE.md vorgesehene Ausnahmefall. Alle neuen Zahlenwerte
// wurden vor Aufnahme in diese Datei per Selbstcheck (Regel 4) gegen die
// Quell-PDFs abgeglichen. Die "Kapitel"-Angaben im Feld "source"
// verweisen auf die aktuelle Kapitelnummerierung des Skripts (nach der
// Umsortierung von Skalarprodukten vor die lineare Abbildungen/Analysis-
// Kapitel).
export const TOPICS = [
  "Matrizen und lineare Gleichungssysteme",
  "Der Gauß-Algorithmus und die Lösungsmenge",
  "K-Vektorräume und das Untervektorraumkriterium",
  "Lineare Unabhängigkeit, Erzeugendensysteme und Basis",
  "Dimension und die Dimensionsformel für Untervektorräume",
  "Häufungspunkte und Funktionsgrenzwerte",
  "Stetigkeit und die ε-δ-Charakterisierung",
  "Zwischenwertsatz, Extrema stetiger Funktionen und Umkehrfunktionen",
  "Die allgemeine Exponential- und Logarithmusfunktion",
  "Wachstumsvergleich zwischen Potenz-, Exponential- und Logarithmusfunktionen",
  "Lineare Abbildungen, Kern und Bild",
  "Matrixdarstellung, Matrizenmultiplikation und Isomorphismen",
  "Reguläre Matrizen und die Inverse",
  "Die Ableitung und Differenzierbarkeit",
  "Ableitungsregeln: Produkt-, Quotienten- und Kettenregel",
  "Ableitung der Umkehrfunktion und elementare Ableitungen",
  "Lokale und globale Extrema",
  "Der Satz von Rolle und der Mittelwertsatz",
  "Konvexität, Wendepunkte und Kurvendiskussion",
  "Die Regel von de l'Hospital",
  "Der Satz von Taylor und Taylorpolynome",
  "Skalarprodukte, Norm und die Cauchy-Schwarz-Ungleichung",
  "Orthogonalität und das Gram-Schmidt-Verfahren",
  "Orthogonale Projektion und Abstandsaufgaben im Rⁿ",
  "Das Riemann-Integral: Ober- und Untersummen",
  "Der Hauptsatz der Differential- und Integralrechnung",
  "Integrationstechniken und uneigentliche Integrale",
] as const;

export const questions: Question[] = [
  // ---------- Matrizen und lineare Gleichungssysteme ----------
  {
    id: "lgs-01",
    topic: "Matrizen und lineare Gleichungssysteme",
    type: "mc",
    prompt: "Für das LGS x1+x2+x3=6, 2x1−x2+x3=3, x1+2x2−x3=2: Welche Lösung (x1,x2,x3) ist korrekt?",
    options: ["(1, 2, 3)", "(2, 1, 3)", "(3, 2, 1)", "(1, 3, 2)"],
    correctIndex: 0,
    explanation: "Auflösen des Systems (z. B. per Gauß-Algorithmus) liefert (x1,x2,x3)=(1,2,3). Probe: 1+2+3=6 ✓, 2·1−2+3=3 ✓, 1+4−3=2 ✓.",
    source: "Kapitel 1.1, LGS lösen",
    free: true,
  },
  {
    id: "lgs-02",
    topic: "Matrizen und lineare Gleichungssysteme",
    type: "mc",
    prompt: "Was enthält die erweiterte Koeffizientenmatrix (A|⃗b) eines LGS?",
    options: [
      "die Koeffizientenmatrix A mit der rechten Seite ⃗b als zusätzlicher Spalte",
      "nur die rechte Seite ⃗b",
      "die Inverse von A",
      "die transponierte Matrix von A",
    ],
    correctIndex: 0,
    explanation: "Die erweiterte Koeffizientenmatrix fasst A und ⃗b in einem Schema zusammen, um das LGS kompakt umzuformen.",
    source: "Kapitel 1.1, erweiterte Koeffizientenmatrix",
    free: false,
  },
  {
    id: "lgs-03",
    topic: "Matrizen und lineare Gleichungssysteme",
    type: "mc",
    prompt: "Welche der folgenden Umformungen der erweiterten Koeffizientenmatrix verändert die Lösungsmenge eines LGS NICHT?",
    options: [
      "Addition eines Vielfachen einer Zeile zu einer anderen Zeile",
      "Streichen einer beliebigen Spalte",
      "Ersetzen einer Zeile durch das Quadrat ihrer Einträge",
      "Vertauschen zweier Spalten ohne Anpassung der Variablenreihenfolge",
    ],
    correctIndex: 0,
    explanation: "Nur die drei elementaren Zeilenumformungen (Vertauschen, Skalieren mit ≠0, Addition eines Vielfachen einer Zeile zu einer anderen) sind äquivalente Umformungen, die die Lösungsmenge unverändert lassen.",
    source: "Kapitel 1.1, äquivalente Umformungen",
    free: false,
  },

  // ---------- Der Gauß-Algorithmus und die Lösungsmenge ----------
  {
    id: "ga-01",
    topic: "Der Gauß-Algorithmus und die Lösungsmenge",
    type: "mc",
    prompt: "Für das LGS x1+x2+2x3=4, 2x1+3x2+5x3=9: Welche Aussage über die Lösungsmenge ist korrekt?",
    options: [
      "Es gibt unendlich viele Lösungen, da eine Variable frei bleibt.",
      "Es gibt genau eine Lösung.",
      "Das System ist unlösbar.",
      "Es gibt genau zwei Lösungen.",
    ],
    correctIndex: 0,
    explanation: "Die Zeilenstufenform hat nur 2 Pivots bei 3 Unbekannten, also bleibt eine Variable frei — die Lösungsmenge ist unendlich (eine Gerade im Lösungsraum).",
    source: "Kapitel 1.2, Kardinalität der Lösungsmenge",
    free: false,
  },
  {
    id: "ga-02",
    topic: "Der Gauß-Algorithmus und die Lösungsmenge",
    type: "mc",
    prompt: "Woran erkennt man in der Zeilenstufenform, dass ein LGS unlösbar ist?",
    options: [
      "an einer Zeile der Form (0,...,0|c) mit c≠0",
      "an einer Nullzeile (0,...,0|0)",
      "daran, dass keine Variable frei ist",
      "daran, dass die Matrix quadratisch ist",
    ],
    correctIndex: 0,
    explanation: "Eine Zeile (0,...,0|c) mit c≠0 entspricht der widersprüchlichen Gleichung 0=c — das LGS ist dann unlösbar.",
    source: "Kapitel 1.2, Unlösbarkeit",
    free: false,
  },
  {
    id: "ga-03",
    topic: "Der Gauß-Algorithmus und die Lösungsmenge",
    type: "mc",
    prompt: "In der Zeilenstufenform eines LGS mit n Unbekannten seien alle n Variablen führend. Wie viele Lösungen hat das LGS?",
    options: ["genau eine", "unendlich viele", "keine", "hängt vom Wert der rechten Seite ab"],
    correctIndex: 0,
    explanation: "Sind alle Variablen führend (kein Freiheitsgrad übrig), ist die Lösung eindeutig bestimmt.",
    source: "Kapitel 1.2, eindeutige Lösung",
    free: false,
  },

  // ---------- K-Vektorräume und das Untervektorraumkriterium ----------
  {
    id: "vr-01",
    topic: "K-Vektorräume und das Untervektorraumkriterium",
    type: "mc",
    prompt: "Ist E={(x,y,z)∈ℝ³: 2x−y+z=0} ein Untervektorraum von ℝ³?",
    options: [
      "Ja, da der Nullvektor die Gleichung erfüllt und E abgeschlossen unter Addition/Skalierung ist.",
      "Nein, da E keine Ebene ist.",
      "Nein, da E nicht durch den Ursprung geht.",
      "Ja, aber nur weil E endlich ist.",
    ],
    correctIndex: 0,
    explanation: "E ist eine Ebene durch den Ursprung (0 erfüllt 2·0−0+0=0), und Summen sowie Vielfache von Lösungen der homogenen Gleichung bleiben Lösungen — alle drei Kriterien des UVR-Kriteriums sind erfüllt.",
    source: "Kapitel 2.1, UVR-Kriterium",
    free: false,
  },
  {
    id: "vr-02",
    topic: "K-Vektorräume und das Untervektorraumkriterium",
    type: "mc",
    prompt: "Ist F={(x,y,z)∈ℝ³: 2x−y+z=4} ein Untervektorraum von ℝ³?",
    options: [
      "Nein, da der Nullvektor die Gleichung nicht erfüllt.",
      "Ja, da F eine Ebene ist.",
      "Ja, da F abgeschlossen unter Addition ist.",
      "Nein, da F unendlich viele Punkte enthält.",
    ],
    correctIndex: 0,
    explanation: "Für (0,0,0) gilt 2·0−0+0=0≠4 — der Nullvektor liegt nicht in F, also kann F kein Untervektorraum sein (notwendige Bedingung des UVR-Kriteriums verletzt).",
    source: "Kapitel 2.1, Gegenbeispiel UVR",
    free: false,
  },
  {
    id: "vr-03",
    topic: "K-Vektorräume und das Untervektorraumkriterium",
    type: "mc",
    prompt: "Welche drei Bedingungen prüft das Untervektorraumkriterium für U⊂V?",
    options: [
      "⃗0∈U, Abgeschlossenheit unter Addition, Abgeschlossenheit unter skalarer Multiplikation",
      "U ist endlich, U ist konvex, U ist beschränkt",
      "U ist offen, U ist abgeschlossen, U ist kompakt",
      "U enthält mindestens zwei Elemente, U ist symmetrisch, U ist linear",
    ],
    correctIndex: 0,
    explanation: "Das UVR-Kriterium prüft genau diese drei Eigenschaften — sind sie erfüllt, ist U automatisch selbst ein Vektorraum.",
    source: "Kapitel 2.1, UVR-Kriterium",
    free: false,
  },

  // ---------- Lineare Unabhängigkeit, Erzeugendensysteme und Basis ----------
  {
    id: "li-01",
    topic: "Lineare Unabhängigkeit, Erzeugendensysteme und Basis",
    type: "mc",
    prompt: "Für ⃗v1=(1,2,0), ⃗v2=(0,1,3), ⃗v3=(2,0,1): Sind diese drei Vektoren linear unabhängig?",
    options: [
      "Ja, da det[⃗v1|⃗v2|⃗v3]=13≠0",
      "Nein, da die Summe der Vektoren der Nullvektor ist",
      "Nein, da alle drei Vektoren in einer Ebene liegen",
      "Das lässt sich ohne weitere Informationen nicht entscheiden",
    ],
    correctIndex: 0,
    explanation: "Die Determinante der Matrix mit diesen drei Vektoren als Spalten ist 13≠0 — die Vektoren sind linear unabhängig und bilden damit eine Basis von ℝ³.",
    source: "Kapitel 2.2, lineare Unabhängigkeit",
    free: true,
  },
  {
    id: "li-02",
    topic: "Lineare Unabhängigkeit, Erzeugendensysteme und Basis",
    type: "mc",
    prompt: "Was bedeutet es, dass eine Menge M⊂V ein Erzeugendensystem von V ist?",
    options: ["span(M)=V", "M ist endlich", "M ist eine Basis von V", "M enthält den Nullvektor"],
    correctIndex: 0,
    explanation: "Per Definition heißt M Erzeugendensystem von V, wenn sich jeder Vektor aus V als Linearkombination von Vektoren aus M schreiben lässt, also span(M)=V.",
    source: "Kapitel 2.2, Erzeugendensystem",
    free: false,
  },
  {
    id: "li-03",
    topic: "Lineare Unabhängigkeit, Erzeugendensysteme und Basis",
    type: "mc",
    prompt: "Welche zwei Eigenschaften zusammen definieren eine Basis eines Vektorraums?",
    options: [
      "linear unabhängig UND Erzeugendensystem",
      "endlich UND linear unabhängig",
      "Erzeugendensystem UND orthogonal",
      "linear abhängig UND Erzeugendensystem",
    ],
    correctIndex: 0,
    explanation: "Eine Basis ist per Definition ein linear unabhängiges Erzeugendensystem — jeder Vektor besitzt dann eine eindeutige Darstellung als Linearkombination der Basisvektoren.",
    source: "Kapitel 2.2, Basisbegriff",
    free: false,
  },

  // ---------- Dimension und die Dimensionsformel für Untervektorräume ----------
  {
    id: "dm-01",
    topic: "Dimension und die Dimensionsformel für Untervektorräume",
    type: "numeric",
    prompt: "U1={(x,y,z): x+y+z=0} und U2={(x,y,z): x−y+z=0} sind zwei Ebenen durch den Ursprung im ℝ³ (dim=2 jeweils). Wie groß ist dim(U1+U2)?",
    correctValue: 3,
    explanation: "Die Schnittgerade U1∩U2 hat Richtung n1×n2=(1,1,1)×(1,−1,1)=(2,0,−2), also dim(U1∩U2)=1. Dimensionsformel: dim(U1+U2)=dim(U1)+dim(U2)−dim(U1∩U2)=2+2−1=3.",
    source: "Kapitel 2.3, Dimensionsformel",
    free: false,
  },
  {
    id: "dm-02",
    topic: "Dimension und die Dimensionsformel für Untervektorräume",
    type: "mc",
    prompt: "Welche Formel verknüpft dim(U1+U2), dim(U1), dim(U2) und dim(U1∩U2)?",
    options: [
      "dim(U1+U2) = dim(U1)+dim(U2)−dim(U1∩U2)",
      "dim(U1+U2) = dim(U1)+dim(U2)+dim(U1∩U2)",
      "dim(U1+U2) = dim(U1)·dim(U2)",
      "dim(U1+U2) = max(dim(U1), dim(U2))",
    ],
    correctIndex: 0,
    explanation: "Die Dimensionsformel für Untervektorräume lautet dim(U1+U2)=dim(U1)+dim(U2)−dim(U1∩U2).",
    source: "Kapitel 2.3, Dimensionsformel",
    free: false,
  },
  {
    id: "dm-03",
    topic: "Dimension und die Dimensionsformel für Untervektorräume",
    type: "mc",
    prompt: "Wann spricht man von einer direkten Summe U1⊕U2?",
    options: ["wenn U1∩U2={⃗0} gilt", "wenn U1=U2 gilt", "wenn dim(U1)=dim(U2) gilt", "wenn U1∪U2 ein Untervektorraum ist"],
    correctIndex: 0,
    explanation: "Eine direkte Summe liegt genau dann vor, wenn sich U1 und U2 nur im Nullvektor schneiden; dann gilt dim(U1⊕U2)=dim(U1)+dim(U2).",
    source: "Kapitel 2.3, direkte Summe",
    free: false,
  },

  // ---------- Skalarprodukte, Norm und die Cauchy-Schwarz-Ungleichung ----------
  {
    id: "sk-01",
    topic: "Skalarprodukte, Norm und die Cauchy-Schwarz-Ungleichung",
    type: "numeric",
    prompt: "Für a=(2,3,6) und b=(6,2,3): Berechnen Sie s(a,b)=a·b.",
    correctValue: 36,
    explanation: "s(a,b) = 2·6+3·2+6·3 = 12+6+18 = 36.",
    source: "Kapitel 3.1, Standardskalarprodukt",
    free: false,
  },
  {
    id: "sk-02",
    topic: "Skalarprodukte, Norm und die Cauchy-Schwarz-Ungleichung",
    type: "mc",
    prompt: "Für a=(2,3,6), b=(6,2,3) mit ‖a‖=‖b‖=7 und s(a,b)=36: Ist die Cauchy-Schwarz-Ungleichung erfüllt?",
    options: ["Ja, denn 36 ≤ 7·7=49.", "Nein, 36>49 ist unmöglich.", "Nur wenn a und b orthogonal sind.", "Cauchy-Schwarz gilt nur für 2 Komponenten."],
    correctIndex: 0,
    explanation: "|s(a,b)| ≤ ‖a‖·‖b‖ ⟺ 36 ≤ 49 — die Ungleichung ist erfüllt.",
    source: "Kapitel 3.1, Cauchy-Schwarz-Ungleichung",
    free: false,
  },
  {
    id: "sk-03",
    topic: "Skalarprodukte, Norm und die Cauchy-Schwarz-Ungleichung",
    type: "mc",
    prompt: "Wie ist der Winkel ∢(x,y) zwischen zwei Vektoren x,y≠0 über das Skalarprodukt definiert?",
    options: ["cos(∢(x,y)) = s(x,y)/(‖x‖·‖y‖)", "cos(∢(x,y)) = s(x,y)", "∢(x,y) = s(x,y)/‖x‖", "cos(∢(x,y)) = ‖x‖·‖y‖/s(x,y)"],
    correctIndex: 0,
    explanation: "Dank Cauchy-Schwarz liegt s(x,y)/(‖x‖‖y‖) stets in [−1,1], sodass diese Definition des Winkels wohldefiniert ist.",
    source: "Kapitel 3.1, Winkel zwischen Vektoren",
    free: false,
  },

  // ---------- Orthogonalität und das Gram-Schmidt-Verfahren ----------
  {
    id: "gs-01",
    topic: "Orthogonalität und das Gram-Schmidt-Verfahren",
    type: "mc",
    prompt: "Für b1=(2,0,0), b2=(1,1,0): Was ist der normierte erste Vektor u1 im Gram-Schmidt-Verfahren?",
    options: ["(1,0,0)", "(2,0,0)", "(0,1,0)", "(0,5, 0, 0)"],
    correctIndex: 0,
    explanation: "u1 = b1/‖b1‖ = (2,0,0)/2 = (1,0,0).",
    source: "Kapitel 3.2, Gram-Schmidt erster Schritt",
    free: false,
  },
  {
    id: "gs-02",
    topic: "Orthogonalität und das Gram-Schmidt-Verfahren",
    type: "mc",
    prompt: "Was wird im j-ten Schritt des Gram-Schmidt-Verfahrens von bj abgezogen, bevor normiert wird?",
    options: [
      "die Summe der Projektionen von bj auf alle bereits konstruierten u1,...,u_{j−1}",
      "der Vektor b_{j−1}",
      "der Mittelwert aller vorherigen Vektoren",
      "nichts — es wird direkt normiert",
    ],
    correctIndex: 0,
    explanation: "wj := bj − Σ_{i<j} s(ui,bj)·ui entfernt genau den Anteil von bj, der bereits in span{u1,...,u_{j−1}} liegt; erst danach wird wj normiert.",
    source: "Kapitel 3.2, Gram-Schmidt-Konstruktion",
    free: false,
  },
  {
    id: "gs-03",
    topic: "Orthogonalität und das Gram-Schmidt-Verfahren",
    type: "mc",
    prompt: "Was ist eine Orthonormalbasis (ONB)?",
    options: [
      "eine Basis aus paarweise orthogonalen, auf Länge 1 normierten Vektoren",
      "eine Basis mit maximal 2 Vektoren",
      "jede beliebige Basis eines Vektorraums",
      "eine Basis, die nur aus Einheitsvektoren ⃗e_i besteht",
    ],
    correctIndex: 0,
    explanation: "Eine ONB kombiniert Orthogonalität (paarweise Skalarprodukt 0) mit Normiertheit (Länge 1 jedes Basisvektors).",
    source: "Kapitel 3.2, Orthonormalbasis",
    free: false,
  },

  // ---------- Orthogonale Projektion und Abstandsaufgaben im Rⁿ ----------
  {
    id: "op-01",
    topic: "Orthogonale Projektion und Abstandsaufgaben im Rⁿ",
    type: "numeric",
    prompt: "Für die Hyperebene H={⃗x∈ℝ³: 3x2+4x3=25} und den Punkt ⃗p=(5,5,5): Wie groß ist der Abstand d(⃗p,H)?",
    correctValue: 2,
    explanation: "Normalenvektor ⃗n=(0,3,4), ‖⃗n‖=√(0+9+16)=5. d(⃗p,H) = |⃗n·⃗p−25|/‖⃗n‖ = |0+15+20−25|/5 = |10|/5 = 2.",
    source: "Kapitel 3.3, Abstand Punkt–Hyperebene",
    free: false,
  },
  {
    id: "op-02",
    topic: "Orthogonale Projektion und Abstandsaufgaben im Rⁿ",
    type: "mc",
    prompt: "Was besagt der Approximationssatz über die orthogonale Projektion P_U(x)?",
    options: [
      "P_U(x) ist der Punkt in U, der x am nächsten liegt.",
      "P_U(x) ist immer der Nullvektor.",
      "P_U(x) liegt nie in U.",
      "P_U(x) ist unabhängig von x.",
    ],
    correctIndex: 0,
    explanation: "Der Approximationssatz zeigt ‖x−P_U(x)‖≤‖x−u‖ für alle u∈U, mit Gleichheit nur für u=P_U(x) — die orthogonale Projektion ist die beste Approximation aus U.",
    source: "Kapitel 3.3, Approximationssatz",
    free: false,
  },
  {
    id: "op-03",
    topic: "Orthogonale Projektion und Abstandsaufgaben im Rⁿ",
    type: "mc",
    prompt: "Wie lautet die Hessesche Normalform einer Hyperebene H mit Normalenvektor ⃗n und Konstante c?",
    options: ["H = {⃗x: ⃗n·⃗x = c}", "H = {⃗x: ⃗n+⃗x = c}", "H = {⃗x: ‖⃗x‖ = c}", "H = {⃗x: ⃗x = c·⃗n}"],
    correctIndex: 0,
    explanation: "Die Hessesche Normalform beschreibt eine Hyperebene über einen Normalenvektor ⃗n und eine Konstante c: alle Punkte ⃗x mit ⃗n·⃗x=c.",
    source: "Kapitel 3.3, Hessesche Normalform",
    free: false,
  },

  // ---------- Häufungspunkte und Funktionsgrenzwerte ----------
  {
    id: "hf-01",
    topic: "Häufungspunkte und Funktionsgrenzwerte",
    type: "mc",
    prompt: "Für f(x)=1/(x−3): Was gilt für die einseitigen Grenzwerte in x0=3?",
    options: [
      "lim_{x→3+} f(x)=∞ und lim_{x→3−} f(x)=−∞",
      "beide einseitigen Grenzwerte sind ∞",
      "beide einseitigen Grenzwerte sind −∞",
      "beide einseitigen Grenzwerte existieren und stimmen überein",
    ],
    correctIndex: 0,
    explanation: "Für x knapp über 3 ist x−3 eine kleine positive Zahl, also f(x)→∞; für x knapp unter 3 ist x−3 eine kleine negative Zahl, also f(x)→−∞.",
    source: "Kapitel 4.1, uneigentliche Funktionsgrenzwerte",
    free: false,
  },
  {
    id: "hf-02",
    topic: "Häufungspunkte und Funktionsgrenzwerte",
    type: "mc",
    prompt: "Welche Menge bildet die Häufungspunkte von M=(0,4)∪{7}?",
    options: ["[0,4]", "(0,4)∪{7}", "{7}", "[0,7]"],
    correctIndex: 0,
    explanation: "Jeder Punkt aus [0,4] (einschließlich der Randpunkte 0 und 4) lässt sich durch Punkte aus (0,4) annähern; der isolierte Punkt 7 ist dagegen kein Häufungspunkt, da er sich nicht durch andere Punkte aus M approximieren lässt.",
    source: "Kapitel 4.1, Häufungspunkte einer Menge",
    free: false,
  },
  {
    id: "hf-03",
    topic: "Häufungspunkte und Funktionsgrenzwerte",
    type: "mc",
    prompt: "Wann existiert der beidseitige Grenzwert lim_{x→x0} f(x)?",
    options: [
      "genau dann, wenn links- und rechtsseitiger Grenzwert existieren und übereinstimmen",
      "immer, wenn f in x0 definiert ist",
      "genau dann, wenn f monoton ist",
      "genau dann, wenn x0 kein Häufungspunkt ist",
    ],
    correctIndex: 0,
    explanation: "Der beidseitige Grenzwert existiert genau dann, wenn beide einseitigen Grenzwerte existieren und denselben Wert liefern.",
    source: "Kapitel 4.1, beidseitiger Grenzwert",
    free: false,
  },

  // ---------- Stetigkeit und die ε-δ-Charakterisierung ----------
  {
    id: "st-01",
    topic: "Stetigkeit und die ε-δ-Charakterisierung",
    type: "numeric",
    prompt: "f(x):=(cos(x)−1)/x² für x≠0, f(0):=α. Für welchen Wert α ist f stetig in 0?",
    correctValue: -0.5,
    explanation: "Aus der Taylor-Entwicklung cos(x)=1−x²/2+O(x⁴) folgt (cos(x)−1)/x² → −1/2 für x→0. Also muss α=−0,5 gewählt werden.",
    source: "Kapitel 4.2, stetige Fortsetzung",
    free: false,
  },
  {
    id: "st-02",
    topic: "Stetigkeit und die ε-δ-Charakterisierung",
    type: "mc",
    prompt: "Welche Aussage entspricht der ε-δ-Charakterisierung der Stetigkeit in x0?",
    options: [
      "∀ε>0 ∃δ>0: |x−x0|<δ, x∈D ⟹ |f(x)−f(x0)|<ε",
      "∀δ>0 ∃ε>0: |f(x)−f(x0)|<δ ⟹ |x−x0|<ε",
      "f ist stetig, wenn f(x0) existiert",
      "f ist stetig, wenn f monoton ist",
    ],
    correctIndex: 0,
    explanation: "Die ε-δ-Charakterisierung verlangt, dass zu jeder (beliebig kleinen) Fehlertoleranz ε eine Abweichung δ existiert, die den Funktionswert innerhalb von ε hält.",
    source: "Kapitel 4.2, ε-δ-Kriterium",
    free: false,
  },
  {
    id: "st-03",
    topic: "Stetigkeit und die ε-δ-Charakterisierung",
    type: "mc",
    prompt: "Welche Operationen erhalten Stetigkeit?",
    options: [
      "Summen, Produkte, Quotienten (Nenner≠0) und Verkettungen stetiger Funktionen",
      "nur Summen stetiger Funktionen",
      "nur Verkettungen stetiger Funktionen",
      "keine — Stetigkeit muss für jede zusammengesetzte Funktion neu bewiesen werden",
    ],
    correctIndex: 0,
    explanation: "Summen, Produkte, Quotienten (mit Nenner ≠0) und Verkettungen stetiger Funktionen sind stets wieder stetig.",
    source: "Kapitel 4.2, Rechenregeln für Stetigkeit",
    free: false,
  },

  // ---------- Zwischenwertsatz, Extrema stetiger Funktionen und Umkehrfunktionen ----------
  {
    id: "zw-01",
    topic: "Zwischenwertsatz, Extrema stetiger Funktionen und Umkehrfunktionen",
    type: "mc",
    prompt: "Für f(x)=x³−x−1 gilt f(1)=−1 und f(2)=5. Was folgt aus dem Zwischenwertsatz?",
    options: [
      "Es existiert ein ξ∈(1,2) mit f(ξ)=0.",
      "f hat in (1,2) kein Extremum.",
      "f ist auf (1,2) konstant.",
      "f(1,5)=0 muss exakt gelten.",
    ],
    correctIndex: 0,
    explanation: "Da f stetig ist und 0 zwischen f(1)=−1 und f(2)=5 liegt, garantiert der Zwischenwertsatz eine Nullstelle ξ∈(1,2) — ohne dass man ξ explizit berechnen muss.",
    source: "Kapitel 4.3, Zwischenwertsatz",
    free: false,
  },
  {
    id: "zw-02",
    topic: "Zwischenwertsatz, Extrema stetiger Funktionen und Umkehrfunktionen",
    type: "mc",
    prompt: "Was garantiert die Min-Max-Eigenschaft stetiger Funktionen?",
    options: [
      "Eine auf [a,b] stetige Funktion nimmt dort ihr Maximum und Minimum tatsächlich an.",
      "Jede stetige Funktion ist monoton.",
      "Jede stetige Funktion ist differenzierbar.",
      "Eine stetige Funktion auf (a,b) (offenes Intervall) nimmt stets ein Maximum an.",
    ],
    correctIndex: 0,
    explanation: "Die Min-Max-Eigenschaft gilt für abgeschlossene, beschränkte Intervalle [a,b] — auf offenen Intervallen kann das Maximum fehlen (z. B. f(x)=x auf (0,1)).",
    source: "Kapitel 4.3, Min-Max-Eigenschaft",
    free: false,
  },
  {
    id: "zw-03",
    topic: "Zwischenwertsatz, Extrema stetiger Funktionen und Umkehrfunktionen",
    type: "mc",
    prompt: "Ist f:[a,b]→ℝ stetig und streng monoton, was gilt für die Umkehrfunktion f⁻¹?",
    options: [
      "f⁻¹ ist auf dem Bildintervall ebenfalls stetig und streng monoton.",
      "f⁻¹ existiert nicht.",
      "f⁻¹ ist nur an einem Punkt definiert.",
      "f⁻¹ ist automatisch linear.",
    ],
    correctIndex: 0,
    explanation: "Stetigkeit und strenge Monotonie übertragen sich auf die Umkehrfunktion — dies liefert z. B. die Stetigkeit von Logarithmus und Arkusfunktionen.",
    source: "Kapitel 4.3, Umkehrfunktionen",
    free: false,
  },

  // ---------- Die allgemeine Exponential- und Logarithmusfunktion ----------
  {
    id: "el-01",
    topic: "Die allgemeine Exponential- und Logarithmusfunktion",
    type: "numeric",
    prompt: "Lösen Sie 2^x = 15 nach x auf (Angabe auf 2 Nachkommastellen).",
    correctValue: 3.91,
    tolerance: 0.02,
    explanation: "x = log_2(15) = ln(15)/ln(2) ≈ 3,91.",
    source: "Kapitel 5.1, allgemeine Exponentialgleichung",
    free: false,
  },
  {
    id: "el-02",
    topic: "Die allgemeine Exponential- und Logarithmusfunktion",
    type: "mc",
    prompt: "Wie ist die allgemeine Exponentialfunktion a^x (a>0, a≠1) definiert?",
    options: ["a^x := e^(x·ln a)", "a^x := x·ln(a)", "a^x := e^x·a", "a^x := ln(x)/a"],
    correctIndex: 0,
    explanation: "Die allgemeine Exponentialfunktion wird über die natürliche Exponentialfunktion definiert: a^x := e^(x ln a).",
    source: "Kapitel 5.1, Definition",
    free: false,
  },
  {
    id: "el-03",
    topic: "Die allgemeine Exponential- und Logarithmusfunktion",
    type: "mc",
    prompt: "Wie hängt der allgemeine Logarithmus log_a(x) mit dem natürlichen Logarithmus zusammen?",
    options: ["log_a(x) = ln(x)/ln(a)", "log_a(x) = ln(x)·ln(a)", "log_a(x) = ln(x)+ln(a)", "log_a(x) = ln(x·a)"],
    correctIndex: 0,
    explanation: "Der allgemeine Logarithmus lässt sich stets über log_a(x)=ln(x)/ln(a) auf den natürlichen Logarithmus zurückführen.",
    source: "Kapitel 5.1, Basiswechsel des Logarithmus",
    free: false,
  },

  // ---------- Wachstumsvergleich zwischen Potenz-, Exponential- und Logarithmusfunktionen ----------
  {
    id: "wa-01",
    topic: "Wachstumsvergleich zwischen Potenz-, Exponential- und Logarithmusfunktionen",
    type: "numeric",
    prompt: "Wie groß ist lim_{x→∞} x³/2^x?",
    correctValue: 0,
    explanation: "Jede Exponentialfunktion mit Basis >1 dominiert jede Potenzfunktion für x→∞, also gilt lim x³/2^x = 0.",
    source: "Kapitel 5.2, Wachstumshierarchie",
    free: false,
  },
  {
    id: "wa-02",
    topic: "Wachstumsvergleich zwischen Potenz-, Exponential- und Logarithmusfunktionen",
    type: "mc",
    prompt: "Welche Wachstumshierarchie gilt für x→∞?",
    options: [
      "Logarithmus ≪ Potenzfunktion ≪ Exponentialfunktion (Basis>1)",
      "Exponentialfunktion ≪ Potenzfunktion ≪ Logarithmus",
      "alle drei wachsen gleich schnell",
      "Potenzfunktion ≪ Logarithmus ≪ Exponentialfunktion",
    ],
    correctIndex: 0,
    explanation: "Für x→∞ gilt die feste Rangordnung: Logarithmus wächst am langsamsten, gefolgt von jeder Potenzfunktion, gefolgt von jeder Exponentialfunktion mit Basis>1.",
    source: "Kapitel 5.2, Wachstumshierarchie",
    free: false,
  },
  {
    id: "wa-03",
    topic: "Wachstumsvergleich zwischen Potenz-, Exponential- und Logarithmusfunktionen",
    type: "mc",
    prompt: "Mit welcher Technik lässt sich lim_{x→∞} x^r/a^x=0 (a>1) typischerweise beweisen?",
    options: [
      "wiederholte Anwendung der Regel von de l'Hospital",
      "das Sandwich-Theorem für Folgen ohne weitere Rechnung",
      "vollständige Induktion über r",
      "das Untervektorraumkriterium",
    ],
    correctIndex: 0,
    explanation: "Man wendet de l'Hospital so oft an, bis die Potenz im Zähler vollständig 'weggeleitet' ist — der Nenner bleibt dabei stets eine (wachsende) Exponentialfunktion.",
    source: "Kapitel 5.2, Beweistechnik",
    free: false,
  },

  // ---------- Lineare Abbildungen, Kern und Bild ----------
  {
    id: "la-01",
    topic: "Lineare Abbildungen, Kern und Bild",
    type: "mc",
    prompt: "Für A=[[1,2,3],[2,3,5],[1,1,2]] (Rang(A)=2): Welcher Vektor spannt Kern(A) auf?",
    options: ["(−1, −1, 1)", "(1, 1, 1)", "(1, −1, 1)", "(2, −1, 1)"],
    correctIndex: 0,
    explanation: "A·(−1,−1,1) = (−1−2+3, −2−3+5, −1−1+2) = (0,0,0) ✓ — und da Rang(A)=2, ist dim(Kern(A))=1, also Kern(A)=span{(−1,−1,1)}.",
    source: "Kapitel 6.1, Kernberechnung",
    free: false,
  },
  {
    id: "la-02",
    topic: "Lineare Abbildungen, Kern und Bild",
    type: "numeric",
    prompt: "Für dieselbe Abbildung φ mit Darstellungsmatrix A aus der vorigen Aufgabe (Rang 2, R³→R³): Wie groß ist dim(Kern(φ))?",
    correctValue: 1,
    explanation: "Dimensionsformel: dim(ℝ³)=Rang(φ)+dim(Kern(φ)) ⟹ 3=2+dim(Kern(φ)) ⟹ dim(Kern(φ))=1.",
    source: "Kapitel 6.1, Dimensionsformel",
    free: false,
  },
  {
    id: "la-03",
    topic: "Lineare Abbildungen, Kern und Bild",
    type: "mc",
    prompt: "Wann ist eine lineare Abbildung φ: V→W injektiv?",
    options: ["genau dann, wenn Kern(φ)={⃗0}", "genau dann, wenn Bild(φ)=W", "immer, wenn V endlichdimensional ist", "genau dann, wenn Rang(φ)=0"],
    correctIndex: 0,
    explanation: "φ ist injektiv genau dann, wenn nur der Nullvektor auf den Nullvektor abgebildet wird, also Kern(φ)={⃗0}.",
    source: "Kapitel 6.1, Injektivitätskriterium",
    free: false,
  },

  // ---------- Matrixdarstellung, Matrizenmultiplikation und Isomorphismen ----------
  {
    id: "mm-01",
    topic: "Matrixdarstellung, Matrizenmultiplikation und Isomorphismen",
    type: "mc",
    prompt: "Für B1=[[2,1],[0,3]] und B2=[[1,2],[4,1]]: Was ist B1·B2?",
    options: ["[[6,5],[12,3]]", "[[2,2],[0,3]]", "[[6,3],[4,3]]", "[[1,2],[8,3]]"],
    correctIndex: 0,
    explanation: "B1·B2 = [[2·1+1·4, 2·2+1·1],[0·1+3·4, 0·2+3·1]] = [[6,5],[12,3]].",
    source: "Kapitel 6.3, Matrizenmultiplikation",
    free: false,
  },
  {
    id: "mm-02",
    topic: "Matrixdarstellung, Matrizenmultiplikation und Isomorphismen",
    type: "mc",
    prompt: "Wann sind zwei endlichdimensionale K-Vektorräume V und W isomorph?",
    options: ["genau dann, wenn dim(V)=dim(W)", "genau dann, wenn V=W", "genau dann, wenn V⊂W", "nie, außer V=K^n"],
    correctIndex: 0,
    explanation: "Endlichdimensionale Vektorräume sind genau dann isomorph, wenn sie dieselbe Dimension besitzen.",
    source: "Kapitel 6.3, Isomorphismen",
    free: false,
  },
  {
    id: "mm-03",
    topic: "Matrixdarstellung, Matrizenmultiplikation und Isomorphismen",
    type: "mc",
    prompt: "Wie hängt die Verkettung ψ∘φ zweier linearer Abbildungen mit ihren Darstellungsmatrizen A (für φ) und B (für ψ) zusammen?",
    options: [
      "ψ∘φ hat die Darstellungsmatrix B·A",
      "ψ∘φ hat die Darstellungsmatrix A·B",
      "ψ∘φ hat die Darstellungsmatrix A+B",
      "ψ∘φ lässt sich nicht durch eine Matrix darstellen",
    ],
    correctIndex: 0,
    explanation: "Die Matrizenmultiplikation ist genau so definiert, dass sie der Hintereinanderausführung linearer Abbildungen entspricht: Darstellungsmatrix von ψ∘φ ist B·A.",
    source: "Kapitel 6.3, Verkettung linearer Abbildungen",
    free: false,
  },

  // ---------- Reguläre Matrizen und die Inverse ----------
  {
    id: "rm-01",
    topic: "Reguläre Matrizen und die Inverse",
    type: "mc",
    prompt: "Für C=[[3,2],[1,1]] (det(C)=1): Wie lautet C⁻¹?",
    options: ["[[1,−2],[−1,3]]", "[[1,2],[1,3]]", "[[3,−2],[−1,1]]", "[[1,−1],[−2,3]]"],
    correctIndex: 0,
    explanation: "Für eine 2×2-Matrix [[a,b],[c,d]] mit det=ad−bc gilt die Formel C⁻¹=(1/det)·[[d,−b],[−c,a]]. Mit a=3,b=2,c=1,d=1 und det=1 ergibt sich C⁻¹=[[1,−2],[−1,3]]. Probe: C·C⁻¹=[[3·1+2·(−1), 3·(−2)+2·3],[1·1+1·(−1), 1·(−2)+1·3]]=[[1,0],[0,1]] ✓.",
    source: "Kapitel 6.4, Inverse berechnen",
    free: false,
  },
  {
    id: "rm-02",
    topic: "Reguläre Matrizen und die Inverse",
    type: "mc",
    prompt: "Welche Aussagen sind äquivalent zu 'A ist regulär' für eine quadratische (n×n)-Matrix A?",
    options: [
      "Rang(A)=n UND det(A)≠0",
      "Rang(A)=0 UND det(A)=0",
      "A ist symmetrisch",
      "A hat mindestens eine Nullzeile",
    ],
    correctIndex: 0,
    explanation: "Regularität ist äquivalent zu vollem Rang (Rang(A)=n) und äquivalent zu det(A)≠0 — beide Kriterien beschreiben dasselbe Phänomen (Invertierbarkeit).",
    source: "Kapitel 6.4, Äquivalente Kriterien für Regularität",
    free: false,
  },
  {
    id: "rm-03",
    topic: "Reguläre Matrizen und die Inverse",
    type: "mc",
    prompt: "Wie berechnet man die Inverse einer Matrix A praktisch mit dem Gauß-Algorithmus?",
    options: [
      "(A|E) durch Zeilenumformungen auf (E|A⁻¹) bringen",
      "A transponieren und das Ergebnis als A⁻¹ verwenden",
      "A quadrieren",
      "die Zeilensumme von A berechnen",
    ],
    correctIndex: 0,
    explanation: "Wendet man dieselben Zeilenumformungen, die A in die Einheitsmatrix E überführen, gleichzeitig auf E an, entsteht dort A⁻¹.",
    source: "Kapitel 6.4, Berechnung der Inversen",
    free: false,
  },

  // ---------- Die Ableitung und Differenzierbarkeit ----------
  {
    id: "ab-01",
    topic: "Die Ableitung und Differenzierbarkeit",
    type: "numeric",
    prompt: "Für f(x)=x²+3x: Berechnen Sie f'(2).",
    correctValue: 7,
    explanation: "f'(x)=2x+3, also f'(2)=4+3=7.",
    source: "Kapitel 7.1, Ableitung berechnen",
    free: true,
  },
  {
    id: "ab-02",
    topic: "Die Ableitung und Differenzierbarkeit",
    type: "mc",
    prompt: "Warum ist f(x)=|x| in x0=0 nicht differenzierbar?",
    options: [
      "weil links- und rechtsseitige Ableitung existieren, aber nicht übereinstimmen (−1 bzw. 1)",
      "weil f in 0 nicht stetig ist",
      "weil f in 0 nicht definiert ist",
      "weil f nicht monoton ist",
    ],
    correctIndex: 0,
    explanation: "Die rechtsseitige Ableitung ist 1, die linksseitige −1 — da sie nicht übereinstimmen, existiert die (beidseitige) Ableitung in 0 nicht, obwohl f dort stetig ist.",
    source: "Kapitel 7.1, Beispiel Betragsfunktion",
    free: false,
  },
  {
    id: "ab-03",
    topic: "Die Ableitung und Differenzierbarkeit",
    type: "mc",
    prompt: "Welche Beziehung besteht zwischen Differenzierbarkeit und Stetigkeit in einem Punkt x0?",
    options: [
      "Differenzierbarkeit impliziert Stetigkeit, aber nicht umgekehrt.",
      "Stetigkeit impliziert Differenzierbarkeit.",
      "Beide Eigenschaften sind äquivalent.",
      "Es gibt keinen Zusammenhang.",
    ],
    correctIndex: 0,
    explanation: "Jede in x0 differenzierbare Funktion ist dort auch stetig; die Umkehrung gilt nicht (Gegenbeispiel: |x| in 0).",
    source: "Kapitel 7.1, Differenzierbarkeit ⟹ Stetigkeit",
    free: false,
  },

  // ---------- Ableitungsregeln: Produkt-, Quotienten- und Kettenregel ----------
  {
    id: "ar-01",
    topic: "Ableitungsregeln: Produkt-, Quotienten- und Kettenregel",
    type: "mc",
    prompt: "Für g(x)=x²·e^x: Wie lautet g'(x)?",
    options: ["x²·e^x + 2x·e^x", "2x·e^x", "x²·e^x", "2·e^x"],
    correctIndex: 0,
    explanation: "Produktregel: (x²)'·e^x + x²·(e^x)' = 2x·e^x + x²·e^x.",
    source: "Kapitel 7.2, Produktregel",
    free: false,
  },
  {
    id: "ar-02",
    topic: "Ableitungsregeln: Produkt-, Quotienten- und Kettenregel",
    type: "mc",
    prompt: "Für h(x)=cos(3x²+1): Wie lautet h'(x)?",
    options: ["−6x·sin(3x²+1)", "−sin(3x²+1)", "6x·sin(3x²+1)", "−6x·cos(3x²+1)"],
    correctIndex: 0,
    explanation: "Kettenregel: äußere Ableitung −sin(3x²+1) mal innere Ableitung 6x, also h'(x)=−6x·sin(3x²+1).",
    source: "Kapitel 7.2, Kettenregel",
    free: false,
  },
  {
    id: "ar-03",
    topic: "Ableitungsregeln: Produkt-, Quotienten- und Kettenregel",
    type: "mc",
    prompt: "Wie lautet die Quotientenregel für (f/g)'?",
    options: ["(f'g−fg')/g²", "(f'g+fg')/g²", "f'/g'", "(fg'−f'g)/g²"],
    correctIndex: 0,
    explanation: "Die Quotientenregel lautet (f/g)' = (f'g−fg')/g² (für g(x0)≠0).",
    source: "Kapitel 7.2, Quotientenregel",
    free: false,
  },

  // ---------- Ableitung der Umkehrfunktion und elementare Ableitungen ----------
  {
    id: "au-01",
    topic: "Ableitung der Umkehrfunktion und elementare Ableitungen",
    type: "numeric",
    prompt: "Berechnen Sie (arcsin)'(0,5).",
    correctValue: 1.1547,
    tolerance: 0.01,
    explanation: "(arcsin x)' = 1/√(1−x²). Bei x=0,5: 1/√(1−0,25) = 1/√0,75 = 2√3/3 ≈ 1,1547.",
    source: "Kapitel 7.3, Ableitung von arcsin",
    free: false,
  },
  {
    id: "au-02",
    topic: "Ableitung der Umkehrfunktion und elementare Ableitungen",
    type: "mc",
    prompt: "Wie lautet die allgemeine Formel für die Ableitung der Umkehrfunktion (f⁻¹)'(y0) mit y0=f(x0)?",
    options: ["(f⁻¹)'(y0) = 1/f'(x0)", "(f⁻¹)'(y0) = f'(x0)", "(f⁻¹)'(y0) = −f'(x0)", "(f⁻¹)'(y0) = f'(y0)"],
    correctIndex: 0,
    explanation: "Sofern f'(x0)≠0 und f⁻¹ in y0=f(x0) stetig ist, gilt (f⁻¹)'(y0)=1/f'(x0).",
    source: "Kapitel 7.3, Ableitung der Umkehrfunktion",
    free: false,
  },
  {
    id: "au-03",
    topic: "Ableitung der Umkehrfunktion und elementare Ableitungen",
    type: "mc",
    prompt: "Wie lautet die Ableitung der allgemeinen Potenzfunktion x^a (a∈ℝ, x>0)?",
    options: ["a·x^(a−1)", "x^a·ln(x)", "a^x·ln(a)", "x^(a−1)"],
    correctIndex: 0,
    explanation: "Über x^a:=e^(a·ln x) und die Kettenregel ergibt sich (x^a)' = a·x^(a−1) — dieselbe Formel wie für ganzzahlige Exponenten, jetzt für beliebige reelle a.",
    source: "Kapitel 7.3, allgemeine Potenzfunktion",
    free: false,
  },

  // ---------- Lokale und globale Extrema ----------
  {
    id: "ex-01",
    topic: "Lokale und globale Extrema",
    type: "mc",
    prompt: "Für f(x)=x³−12x: An welchen Stellen liegen die kritischen Punkte (f'(x)=0)?",
    options: ["x=−2 und x=2", "x=−12 und x=12", "x=0 nur", "x=−4 und x=4"],
    correctIndex: 0,
    explanation: "f'(x)=3x²−12=0 ⟺ x²=4 ⟺ x=±2.",
    source: "Kapitel 8.1, kritische Punkte",
    free: false,
  },
  {
    id: "ex-02",
    topic: "Lokale und globale Extrema",
    type: "mc",
    prompt: "Für f(x)=x³−12x mit f''(x)=6x: Welche Art von Extremum liegt bei x=−2 vor?",
    options: ["strenges lokales Maximum (f''(−2)=−12<0)", "strenges lokales Minimum", "kein Extremum, sondern ein Wendepunkt", "ein globales Minimum"],
    correctIndex: 0,
    explanation: "f''(−2)=6·(−2)=−12<0, also liegt nach dem hinreichenden Kriterium ein strenges lokales Maximum vor.",
    source: "Kapitel 8.1, hinreichendes Kriterium",
    free: false,
  },
  {
    id: "ex-03",
    topic: "Lokale und globale Extrema",
    type: "mc",
    prompt: "Was folgt aus f'(x0)=0 allein (ohne weitere Information)?",
    options: [
      "x0 ist ein extremwertverdächtiger Punkt, aber nicht notwendig ein Extremum.",
      "x0 ist automatisch eine lokale Maximalstelle.",
      "x0 ist automatisch eine lokale Minimalstelle.",
      "f ist bei x0 nicht differenzierbar.",
    ],
    correctIndex: 0,
    explanation: "f'(x0)=0 ist nur eine notwendige Bedingung — Gegenbeispiel f(x)=x³ mit f'(0)=0, aber x0=0 ist kein Extremum (Wendepunkt).",
    source: "Kapitel 8.1, notwendige vs. hinreichende Bedingung",
    free: false,
  },

  // ---------- Der Satz von Rolle und der Mittelwertsatz ----------
  {
    id: "mw-01",
    topic: "Der Satz von Rolle und der Mittelwertsatz",
    type: "numeric",
    prompt: "Für f(x)=x³ auf [0,3]: Welche Stelle ξ∈(0,3) garantiert der Mittelwertsatz (f'(ξ)=(f(3)−f(0))/3)?",
    correctValue: 1.732,
    tolerance: 0.01,
    explanation: "(f(3)−f(0))/3 = (27−0)/3 = 9. Aus f'(ξ)=3ξ²=9 folgt ξ²=3, also ξ=√3≈1,732 (die negative Lösung −√3 liegt nicht im Intervall (0,3)).",
    source: "Kapitel 8.2, Mittelwertsatz",
    free: false,
  },
  {
    id: "mw-02",
    topic: "Der Satz von Rolle und der Mittelwertsatz",
    type: "mc",
    prompt: "Was besagt der Satz von Rolle?",
    options: [
      "Gilt f(a)=f(b) für eine auf [a,b] stetige, auf (a,b) differenzierbare Funktion, existiert ein ξ∈(a,b) mit f'(ξ)=0.",
      "Jede stetige Funktion hat eine Nullstelle.",
      "Jede differenzierbare Funktion ist monoton.",
      "f'(a)=f'(b) für alle differenzierbaren Funktionen.",
    ],
    correctIndex: 0,
    explanation: "Der Satz von Rolle ist ein Spezialfall des Mittelwertsatzes für den Fall gleicher Randwerte f(a)=f(b).",
    source: "Kapitel 8.2, Satz von Rolle",
    free: false,
  },
  {
    id: "mw-03",
    topic: "Der Satz von Rolle und der Mittelwertsatz",
    type: "mc",
    prompt: "Was folgt aus f'(x)≥0 für alle x∈(a,b) (Monotoniekriterium)?",
    options: [
      "f ist auf [a,b] monoton wachsend.",
      "f ist auf [a,b] konstant.",
      "f ist auf [a,b] konvex.",
      "f hat auf [a,b] kein Extremum.",
    ],
    correctIndex: 0,
    explanation: "Aus dem Mittelwertsatz folgt: f'≥0 auf (a,b) impliziert monoton wachsend auf [a,b] (analog für >0, ≤0, <0).",
    source: "Kapitel 8.2, Monotoniekriterien",
    free: false,
  },

  // ---------- Konvexität, Wendepunkte und Kurvendiskussion ----------
  {
    id: "kv-01",
    topic: "Konvexität, Wendepunkte und Kurvendiskussion",
    type: "numeric",
    prompt: "Für f(x)=x³−12x (f''(x)=6x): An welcher Stelle liegt der Wendepunkt?",
    correctValue: 0,
    explanation: "f''(x)=6x wechselt bei x=0 das Vorzeichen (negativ für x<0, positiv für x>0) — notwendige und hinreichende Bedingung für einen Wendepunkt.",
    source: "Kapitel 8.3, Wendepunkt",
    free: false,
  },
  {
    id: "kv-02",
    topic: "Konvexität, Wendepunkte und Kurvendiskussion",
    type: "mc",
    prompt: "Wann heißt eine zweimal differenzierbare Funktion f auf einem Intervall I konvex?",
    options: ["wenn f''(x)≥0 für alle x∈I gilt", "wenn f'(x)≥0 für alle x∈I gilt", "wenn f(x)≥0 für alle x∈I gilt", "wenn f monoton fällt"],
    correctIndex: 0,
    explanation: "Konvexität ist über die zweite Ableitung definiert: f''≥0 bedeutet, dass der Graph stets oberhalb jeder Tangente liegt.",
    source: "Kapitel 8.3, Konvexität",
    free: false,
  },
  {
    id: "kv-03",
    topic: "Konvexität, Wendepunkte und Kurvendiskussion",
    type: "mc",
    prompt: "Welche notwendige Bedingung muss an einem Wendepunkt x0 erfüllt sein?",
    options: ["f''(x0)=0", "f'(x0)=0", "f(x0)=0", "f'''(x0)=0"],
    correctIndex: 0,
    explanation: "Notwendig für einen Wendepunkt ist f''(x0)=0; hinreichend ist zusätzlich ein Vorzeichenwechsel von f'' (bzw. f'''(x0)≠0).",
    source: "Kapitel 8.3, Kriterien für Wendepunkte",
    free: false,
  },

  // ---------- Die Regel von de l'Hospital ----------
  {
    id: "lh-01",
    topic: "Die Regel von de l'Hospital",
    type: "numeric",
    prompt: "Berechnen Sie lim_{x→0} (e^x−1−x)/x² mit der Regel von de l'Hospital.",
    correctValue: 0.5,
    explanation: "Zweifache Anwendung: erste Ableitung (e^x−1)/(2x) (wieder 0/0), zweite Ableitung e^x/2 → 1/2 für x→0.",
    source: "Kapitel 9.1, de l'Hospital",
    free: true,
  },
  {
    id: "lh-02",
    topic: "Die Regel von de l'Hospital",
    type: "mc",
    prompt: "Für welche unbestimmten Formen ist die Regel von de l'Hospital direkt anwendbar?",
    options: ["0/0 und ∞/∞", "0·∞ direkt, ohne Umformung", "jede beliebige Form", "nur 0/0"],
    correctIndex: 0,
    explanation: "De l'Hospital gilt direkt für die Formen 0/0 und ∞/∞; andere unbestimmte Formen (0·∞, ∞−∞, 1^∞ usw.) müssen zunächst algebraisch darauf zurückgeführt werden.",
    source: "Kapitel 9.1, Anwendungsbereich",
    free: false,
  },
  {
    id: "lh-03",
    topic: "Die Regel von de l'Hospital",
    type: "mc",
    prompt: "Was ist bei mehrfacher Anwendung von de l'Hospital zu beachten?",
    options: [
      "Nach jeder Anwendung muss der neue Quotient wieder die Form 0/0 oder ∞/∞ haben.",
      "Man darf die Regel höchstens einmal anwenden.",
      "Zähler und Nenner müssen vertauscht werden.",
      "Man muss vor jeder Anwendung integrieren statt ableiten.",
    ],
    correctIndex: 0,
    explanation: "De l'Hospital darf beliebig oft hintereinander angewendet werden, solange der jeweils neue Quotient erneut unbestimmt (0/0 oder ∞/∞) ist.",
    source: "Kapitel 9.1, mehrfache Anwendung",
    free: false,
  },

  // ---------- Der Satz von Taylor und Taylorpolynome ----------
  {
    id: "ty-01",
    topic: "Der Satz von Taylor und Taylorpolynome",
    type: "mc",
    prompt: "Wie lautet das Taylorpolynom vierten Grades von cos(x) um x0=0?",
    options: ["1 − x²/2 + x⁴/24", "1 + x²/2 + x⁴/24", "x − x³/6", "1 − x + x²/2"],
    correctIndex: 0,
    explanation: "Die geraden Ableitungen von cos bei 0 wechseln zwischen 1 und −1: T4(x;0) = 1 − x²/2! + x⁴/4! = 1 − x²/2 + x⁴/24.",
    source: "Kapitel 9.2, Taylorpolynom von cos",
    free: false,
  },
  {
    id: "ty-02",
    topic: "Der Satz von Taylor und Taylorpolynome",
    type: "mc",
    prompt: "Was beschreibt das Lagrange-Restglied R_n(x) im Satz von Taylor?",
    options: [
      "den Approximationsfehler zwischen f(x) und dem Taylorpolynom T_n(x;x0)",
      "die Steigung des Taylorpolynoms",
      "den Grenzwert der Taylorreihe",
      "die Ableitung n-ter Ordnung an der Stelle x",
    ],
    correctIndex: 0,
    explanation: "R_n(x) = f^(n+1)(ξ)/(n+1)!·(x−x0)^(n+1) für ein ξ zwischen x0 und x quantifiziert exakt den Fehler f(x)−T_n(x;x0).",
    source: "Kapitel 9.2, Lagrange-Restglied",
    free: false,
  },
  {
    id: "ty-03",
    topic: "Der Satz von Taylor und Taylorpolynome",
    type: "mc",
    prompt: "Für n=0 entspricht der Satz von Taylor mit Lagrange-Restglied welchem bereits bekannten Satz?",
    options: ["dem Mittelwertsatz der Differentialrechnung", "dem Satz von Rolle", "dem Zwischenwertsatz", "der Regel von de l'Hospital"],
    correctIndex: 0,
    explanation: "Für n=0 reduziert sich f(x)=T_0(x;x0)+R_0(x) auf f(x)=f(x0)+f'(ξ)(x−x0) — genau die Aussage des Mittelwertsatzes.",
    source: "Kapitel 9.2, Zusammenhang mit dem Mittelwertsatz",
    free: false,
  },

  // ---------- Das Riemann-Integral: Ober- und Untersummen ----------
  {
    id: "ri-01",
    topic: "Das Riemann-Integral: Ober- und Untersummen",
    type: "mc",
    prompt: "Welche Ungleichung gilt für Ober- und Untersumme derselben Zerlegung Z?",
    options: ["U(f;Z) ≤ O(f;Z)", "U(f;Z) ≥ O(f;Z)", "U(f;Z) = O(f;Z) immer", "es besteht kein fester Zusammenhang"],
    correctIndex: 0,
    explanation: "Da auf jedem Teilintervall das Infimum höchstens so groß wie das Supremum ist, gilt stets U(f;Z)≤O(f;Z).",
    source: "Kapitel 10.1, Ober-/Untersumme",
    free: true,
  },
  {
    id: "ri-02",
    topic: "Das Riemann-Integral: Ober- und Untersummen",
    type: "mc",
    prompt: "Wann heißt eine beschränkte Funktion f Riemann-integrierbar über [a,b]?",
    options: [
      "wenn oberes und unteres Integral übereinstimmen (J̄(f)=J_(f))",
      "wenn f monoton fallend ist",
      "wenn f stetig differenzierbar ist",
      "wenn f nur endlich viele Werte annimmt",
    ],
    correctIndex: 0,
    explanation: "Riemann-Integrierbarkeit bedeutet, dass das Infimum aller Obersummen mit dem Supremum aller Untersummen übereinstimmt.",
    source: "Kapitel 10.1, Definition des Riemann-Integrals",
    free: false,
  },
  {
    id: "ri-03",
    topic: "Das Riemann-Integral: Ober- und Untersummen",
    type: "mc",
    prompt: "Welche Funktionenklassen sind auf [a,b] stets Riemann-integrierbar?",
    options: ["stetige Funktionen und monotone Funktionen", "nur konstante Funktionen", "nur Polynome", "nur unbeschränkte Funktionen"],
    correctIndex: 0,
    explanation: "Sowohl stetige als auch monotone Funktionen auf [a,b] erfüllen stets das Riemannsche Integrabilitätskriterium.",
    source: "Kapitel 10.1, Klassen integrierbarer Funktionen",
    free: false,
  },

  // ---------- Der Hauptsatz der Differential- und Integralrechnung ----------
  {
    id: "hs-01",
    topic: "Der Hauptsatz der Differential- und Integralrechnung",
    type: "numeric",
    prompt: "Berechnen Sie ∫_1^3 (2x+1) dx.",
    correctValue: 10,
    explanation: "Stammfunktion F(x)=x²+x. F(3)−F(1) = (9+3)−(1+1) = 12−2 = 10.",
    source: "Kapitel 10.2, Hauptsatz anwenden",
    free: false,
  },
  {
    id: "hs-02",
    topic: "Der Hauptsatz der Differential- und Integralrechnung",
    type: "mc",
    prompt: "Was besagt der Hauptsatz der Differential- und Integralrechnung für eine stetige Funktion f auf [a,b]?",
    options: [
      "Die Integralfunktion F(x)=∫_a^x f(t)dt ist differenzierbar mit F'=f, und ∫_a^b f = F(b)−F(a) für jede Stammfunktion F.",
      "f besitzt keine Stammfunktion.",
      "∫_a^b f(x)dx hängt von der gewählten Zerlegung ab.",
      "f muss monoton sein, damit eine Stammfunktion existiert.",
    ],
    correctIndex: 0,
    explanation: "Der Hauptsatz verbindet Integration und Differentiation: jede stetige Funktion besitzt eine Stammfunktion, und das Integral lässt sich über die Auswertungsformel berechnen.",
    source: "Kapitel 10.2, Hauptsatz",
    free: false,
  },
  {
    id: "hs-03",
    topic: "Der Hauptsatz der Differential- und Integralrechnung",
    type: "mc",
    prompt: "Um wie viel unterscheiden sich zwei beliebige Stammfunktionen F1, F2 derselben Funktion f?",
    options: ["um eine additive Konstante", "um einen multiplikativen Faktor", "sie sind immer identisch", "das lässt sich nicht allgemein sagen"],
    correctIndex: 0,
    explanation: "Da (F1−F2)'=f−f=0, ist F1−F2 konstant — zwei Stammfunktionen unterscheiden sich stets nur additiv.",
    source: "Kapitel 10.2, Eigenschaften von Stammfunktionen",
    free: false,
  },

  // ---------- Integrationstechniken und uneigentliche Integrale ----------
  {
    id: "it-01",
    topic: "Integrationstechniken und uneigentliche Integrale",
    type: "numeric",
    prompt: "Berechnen Sie ∫_0^√3 x·√(x²+1) dx (Substitution u=x²+1).",
    correctValue: 2.333,
    tolerance: 0.01,
    explanation: "Mit u=x²+1, du=2x dx wird das Integral zu (1/2)∫_1^4 √u du = (1/3)[u^(3/2)]_1^4 = (1/3)(8−1) = 7/3 ≈ 2,333.",
    source: "Kapitel 10.3, Substitutionsregel",
    free: false,
  },
  {
    id: "it-02",
    topic: "Integrationstechniken und uneigentliche Integrale",
    type: "mc",
    prompt: "Welches uneigentliche Integral konvergiert: ∫_1^∞ 1/x³ dx oder ∫_1^∞ 1/x dx?",
    options: [
      "∫_1^∞ 1/x³ dx konvergiert (Wert 1/2), ∫_1^∞ 1/x dx divergiert.",
      "Beide konvergieren.",
      "Beide divergieren.",
      "∫_1^∞ 1/x dx konvergiert, ∫_1^∞ 1/x³ dx divergiert.",
    ],
    correctIndex: 0,
    explanation: "∫_1^∞ 1/x³ dx = lim_{t→∞}[−1/(2x²)]_1^t = 1/2 (konvergent), während ∫_1^∞ 1/x dx = lim_{t→∞} ln(t) = ∞ (divergent) — ein klassischer Kontrast.",
    source: "Kapitel 10.3, uneigentliche Integrale",
    free: false,
  },
  {
    id: "it-03",
    topic: "Integrationstechniken und uneigentliche Integrale",
    type: "mc",
    prompt: "Aus welcher Ableitungsregel ergibt sich die partielle Integration?",
    options: ["der Produktregel", "der Kettenregel", "der Quotientenregel", "dem Mittelwertsatz"],
    correctIndex: 0,
    explanation: "Partielle Integration ∫f'g=[fg]−∫fg' folgt direkt durch Integrieren der Produktregel (fg)'=f'g+fg'.",
    source: "Kapitel 10.3, partielle Integration",
    free: false,
  },
];
