export type QuestionType = "mc" | "numeric";

export interface Question {
  id: string;
  topic: string;
  type: QuestionType;
  prompt: string;
  options?: string[];
  correctIndex?: number;
  correctValue?: number;
  tolerance?: number;
  unit?: string;
  explanation: string;
  source: string;
  free: boolean;
}

// Hinweis: Alle Übungsaufgaben in dieser Fragenbank sind gegenüber den
// echten Übungs-/Lösungsblättern sowohl in den Zahlenwerten als auch (soweit
// ein konkretes, vom Dozenten erfundenes Szenario vorlag, z. B. das
// Restaurant-Personal-Beispiel oder das Telefonnetz-Beispiel) im Szenario
// selbst verändert. Rein abstrakte, symbolische Aufgaben (Formeln über
// A, B, C, ..., Pseudocode mit Variablen, nummerierte Graphknoten,
// Zahlenfolgen) sowie bereits allgemein bekannte, nicht professorenspezifische
// Beispiele (z. B. Auto/Rad, Gebäude/Raum, geometrische Figuren) wurden nur
// in den Zahlen bzw. gar nicht verändert, da hier kein erfundenes Szenario
// vorliegt.
export const TOPICS = [
  "Algorithmen: Grundbegriffe und Eigenschaften",
  "Aussagenlogik",
  "Datenstrukturen I",
  "Prädikatenlogik",
  "Entwurfsprinzipien und Testen von Algorithmen",
  "Datenstrukturen II",
  "Boolesche Algebra",
  "Sortierverfahren",
  "Datenstrukturen III",
  "Komplexität von Algorithmen",
  "UML: Einführung und Anwendungsfalldiagramme",
  "UML: Klassen- und Objektdiagramme",
  "UML: Verhaltensdiagramme",
] as const;

export const questions: Question[] = [
  // ---------- Algorithmen: Grundbegriffe und Eigenschaften ----------
  {
    id: "ag-01",
    topic: "Algorithmen: Grundbegriffe und Eigenschaften",
    type: "mc",
    prompt: "Was unterscheidet einen Algorithmus von einem Programm?",
    options: [
      "Ein Algorithmus ist die Implementierung eines Programms in einer Programmiersprache.",
      "Ein Programm ist die Implementierung eines Algorithmus in einer konkreten Programmiersprache.",
      "Es gibt keinen Unterschied, die Begriffe sind synonym.",
      "Ein Algorithmus muss zwingend in Java geschrieben sein.",
    ],
    correctIndex: 1,
    explanation:
      "Ein Algorithmus ist die sprachunabhängige, abstrakte Handlungsvorschrift; ein Programm ist ihre konkrete Umsetzung in einer Programmiersprache, sodass ein Rechner sie ausführen kann.",
    source: "Kapitel 1, Algorithmus versus Programm",
    free: true,
  },
  {
    id: "ag-02",
    topic: "Algorithmen: Grundbegriffe und Eigenschaften",
    type: "mc",
    prompt:
      "Ein Gerät zieht bei jedem Start eine Zufallszahl z zwischen 1 und 100 und gibt danach aus, ob z gerade oder ungerade war. Welche Eigenschaften treffen auf diesen Algorithmus zu?",
    options: [
      "Deterministisch und determiniert",
      "Nicht-deterministisch und determiniert",
      "Nicht-deterministisch und nicht determiniert",
      "Deterministisch und nicht determiniert",
    ],
    correctIndex: 2,
    explanation:
      "Der Ablauf ist nicht-deterministisch, da z zufällig gezogen wird. Da unterschiedliche z zu unterschiedlichen Ausgaben ('gerade' vs. 'ungerade') führen, ist der Algorithmus zusätzlich nicht determiniert.",
    source: "Kapitel 1, Determiniertheit und Determinismus",
    free: true,
  },
  {
    id: "ag-03",
    topic: "Algorithmen: Grundbegriffe und Eigenschaften",
    type: "mc",
    prompt:
      "Warum prüft man bei einem Algorithmus sinnvollerweise zuerst den Determinismus und erst danach die Determiniertheit?",
    options: [
      "Weil die Determiniertheit immer aus dem Determinismus folgt und daher redundant ist.",
      "Weil man so gezielt erkennt, an welchen Stellen Zufall den Ablauf beeinflusst, bevor man prüft, ob das Endergebnis trotzdem stets gleich ist.",
      "Weil Determinismus grundsätzlich schwerer zu prüfen ist als Determiniertheit.",
      "Weil beide Eigenschaften identisch definiert sind.",
    ],
    correctIndex: 1,
    explanation:
      "Kennt man die Stellen mit Zufallseinfluss, lässt sich gezielter beurteilen, ob dieser Zufall am Ende tatsächlich das Ergebnis verändert oder nicht.",
    source: "Kapitel 1, Determiniertheit und Determinismus",
    free: false,
  },
  {
    id: "ag-04",
    topic: "Algorithmen: Grundbegriffe und Eigenschaften",
    type: "mc",
    prompt: "Welche Aussage zu Finitheit und Terminierung ist korrekt?",
    options: [
      "Ein implementiertes Programm erfüllt automatisch die Terminierung, da der Quelltext endlich ist.",
      "Statische Finitheit bedeutet, dass der Algorithmus bei jeder Eingabe anhält.",
      "Terminierung muss auch bei einem implementierten Programm gesondert nachgewiesen werden, da Schleifen unter Umständen nicht enden.",
      "Terminierung und statische Finitheit sind dasselbe.",
    ],
    correctIndex: 2,
    explanation:
      "Statische Finitheit (endliche Beschreibung) ist bei einem Programm automatisch gegeben, die Terminierung (Anhalten bei jeder Eingabe) muss dagegen separat gezeigt werden.",
    source: "Kapitel 1, Finitheit, Terminierung und Universalität",
    free: false,
  },
  {
    id: "ag-05",
    topic: "Algorithmen: Grundbegriffe und Eigenschaften",
    type: "mc",
    prompt:
      "Ein Algorithmus arbeitet für Eingaben zwischen 1 und 50 korrekt, liefert aber für Eingaben über 50 fehlerhafte Ausgaben — obwohl die Spezifikation Eingaben bis 1000 vorsieht. Welche Eigenschaft ist verletzt?",
    options: ["Determiniertheit", "Universalität", "Determinismus", "Statische Finitheit"],
    correctIndex: 1,
    explanation:
      "Universalität fordert Korrektheit für die gesamte spezifizierte Eingabemenge — hier versagt der Algorithmus für einen Teil davon.",
    source: "Kapitel 1, Finitheit, Terminierung und Universalität",
    free: false,
  },
  {
    id: "ag-06",
    topic: "Algorithmen: Grundbegriffe und Eigenschaften",
    type: "mc",
    prompt: "Worin unterscheidet sich direkte von indirekter Rekursion?",
    options: [
      "Bei direkter Rekursion ruft sich eine Funktion unmittelbar selbst auf, bei indirekter Rekursion erfolgt der Selbstaufruf über eine oder mehrere andere Funktionen.",
      "Direkte Rekursion terminiert immer, indirekte nie.",
      "Indirekte Rekursion verwendet ausschließlich Schleifen statt Funktionsaufrufe.",
      "Es gibt keinen Unterschied zwischen beiden.",
    ],
    correctIndex: 0,
    explanation:
      "Direkte Rekursion: f ruft f auf. Indirekte Rekursion: f ruft g auf, das (ggf. über weitere Zwischenschritte) wieder f aufruft.",
    source: "Kapitel 1, Rekursion",
    free: false,
  },
  {
    id: "ag-07",
    topic: "Algorithmen: Grundbegriffe und Eigenschaften",
    type: "numeric",
    prompt:
      "Die rekursive Funktion fakultaet(n) berechnet n·fakultaet(n−1) für n>1 und liefert 1 für n≤1. Wie oft wird die Funktion bei der Berechnung von fakultaet(6) insgesamt aufgerufen (inklusive des ursprünglichen Aufrufs)?",
    correctValue: 6,
    explanation:
      "fakultaet(6) ruft fakultaet(5) auf, das fakultaet(4) aufruft, usw. bis fakultaet(1) — insgesamt 6 Aufrufe für n = 6, 5, 4, 3, 2, 1.",
    source: "Kapitel 1, Rekursion",
    free: false,
  },

  // ---------- Aussagenlogik ----------
  {
    id: "al-01",
    topic: "Aussagenlogik",
    type: "mc",
    prompt: "Welche Formel ist zu G äquivalent: (F ∧ ¬F) ∨ G ?",
    options: ["G", "F", "¬G", "F ∧ G"],
    correctIndex: 0,
    explanation:
      "F ∧ ¬F ist ein Widerspruch, also immer falsch. (falsch ∨ G) ist äquivalent zu G — das neutrale Element der Disjunktion.",
    source: "Kapitel 2, Aussagen und Junktoren",
    free: true,
  },
  {
    id: "al-02",
    topic: "Aussagenlogik",
    type: "mc",
    prompt: "Welche Formel ist äquivalent zu (F ⇒ G) ∧ (G ⇒ F)?",
    options: ["F ⇔ G", "F ∧ G", "F ∨ G", "¬F ∨ ¬G"],
    correctIndex: 0,
    explanation: "Die Äquivalenz A ⇔ B ist per Definition gleichbedeutend mit (A ⇒ B) ∧ (B ⇒ A).",
    source: "Kapitel 2, Aussagen und Junktoren",
    free: true,
  },
  {
    id: "al-03",
    topic: "Aussagenlogik",
    type: "mc",
    prompt:
      "Eine Formel liegt als Konjunktion von Disjunktionen von Literalen vor, z. B. (¬P ∨ Q) ∧ (P ∨ ¬R). In welcher Normalform liegt sie damit vor?",
    options: ["Konjunktive Normalform (KNF)", "Disjunktive Normalform (DNF)", "Pränexnormalform", "Skolemform"],
    correctIndex: 0,
    explanation: "Eine Konjunktion von Disjunktionen von Literalen ist per Definition die KNF.",
    source: "Kapitel 2, Äquivalenzumformung und Normalformen",
    free: false,
  },
  {
    id: "al-04",
    topic: "Aussagenlogik",
    type: "mc",
    prompt: "Was ist die Negation von (P ∧ ¬Q)?",
    options: ["¬P ∨ Q", "¬P ∧ Q", "P ∨ ¬Q", "¬P ∨ ¬Q"],
    correctIndex: 0,
    explanation: "Nach De Morgan: ¬(P ∧ ¬Q) ⇔ ¬P ∨ ¬¬Q ⇔ ¬P ∨ Q.",
    source: "Kapitel 2, Äquivalenzumformung und Normalformen",
    free: false,
  },
  {
    id: "al-05",
    topic: "Aussagenlogik",
    type: "mc",
    prompt: "Welche Eigenschaft trifft auf (A ∨ ¬B ∨ C) ∧ (¬A ∨ B ∨ ¬C) zu?",
    options: [
      "Erfüllbar, aber nicht allgemeingültig",
      "Allgemeingültig (Tautologie)",
      "Unerfüllbar",
      "Nicht entscheidbar",
    ],
    correctIndex: 0,
    explanation:
      "Für A=T,B=T,C=T ist die Formel wahr (erfüllbar), für A=F,B=T,C=F ist sie falsch (also keine Tautologie).",
    source: "Kapitel 2, Erfüllbarkeit, Allgemeingültigkeit und Modelle",
    free: false,
  },
  {
    id: "al-06",
    topic: "Aussagenlogik",
    type: "mc",
    prompt: "Welche Aussage beschreibt das Deduktionstheorem korrekt?",
    options: [
      "M ⊨ F gilt genau dann, wenn M ∪ {¬F} unerfüllbar ist.",
      "M ⊨ F gilt genau dann, wenn M ∪ {F} unerfüllbar ist.",
      "M ⊨ F gilt genau dann, wenn M erfüllbar ist.",
      "M ⊨ F gilt nie, wenn M unerfüllbar ist.",
    ],
    correctIndex: 0,
    explanation:
      "Das Deduktionstheorem führt den Nachweis einer logischen Folgerung auf einen Unerfüllbarkeitsnachweis zurück: M ⊨ F gdw. M ∪ {¬F} unerfüllbar ist.",
    source: "Kapitel 2, Exkurs: Resolution und automatisiertes Schließen",
    free: false,
  },
  {
    id: "al-07",
    topic: "Aussagenlogik",
    type: "mc",
    prompt:
      "Warum sollte man einen von einer generativen KI vorgeschlagenen Umformungsbeweis einer Aussagenlogik-Formel in einer Klausur nicht unkritisch übernehmen?",
    options: [
      "Weil KI-generierte Beweise oft Äquivalenzregeln verwenden, die über den im Kurs behandelten Regelsatz hinausgehen und damit in der Klausur nicht verwendbar sind.",
      "Weil KI-Systeme grundsätzlich falsche Endergebnisse liefern.",
      "Weil Wahrheitstafeln grundsätzlich unzuverlässiger sind als jede KI-Umformung.",
      "Weil KI-Systeme keine Aussagenlogik verarbeiten können.",
    ],
    correctIndex: 0,
    explanation:
      "Das Endergebnis kann korrekt sein, der Beweisweg aber Regeln nutzen, die nicht Teil des vereinbarten, in der Klausur zulässigen Regelsatzes sind.",
    source: "Kapitel 2, Exkurs: Resolution und automatisiertes Schließen",
    free: false,
  },

  // ---------- Datenstrukturen I ----------
  {
    id: "ds1-01",
    topic: "Datenstrukturen I",
    type: "mc",
    prompt: "Welche Eigenschaft hat ein Array im Vergleich zu einer Liste?",
    options: [
      "Ein Array hat feste Größe zur Laufzeit, eine Liste kann zur Laufzeit wachsen und schrumpfen.",
      "Ein Array kann zur Laufzeit wachsen, eine Liste hat feste Größe.",
      "Beide haben feste Größe.",
      "Beide können beliebig wachsen.",
    ],
    correctIndex: 0,
    explanation: "Das Array ist die statische, die Liste die dynamische Datenstruktur.",
    source: "Kapitel 3, Datenstrukturen und abstrakte Datentypen",
    free: true,
  },
  {
    id: "ds1-02",
    topic: "Datenstrukturen I",
    type: "mc",
    prompt: "Wodurch ist ein abstrakter Datentyp (ADT) definiert?",
    options: [
      "Durch seine erlaubten Operationen und deren Verhalten, unabhängig von der konkreten Implementierung.",
      "Durch die konkrete Programmiersprache, in der er implementiert ist.",
      "Durch die Speicheradresse seiner Elemente.",
      "Durch seine grafische Notation in UML.",
    ],
    correctIndex: 0,
    explanation:
      "Ein ADT abstrahiert von der Implementierung und legt nur fest, welche Operationen erlaubt sind und wie sie sich verhalten.",
    source: "Kapitel 3, Datenstrukturen und abstrakte Datentypen",
    free: true,
  },
  {
    id: "ds1-03",
    topic: "Datenstrukturen I",
    type: "mc",
    prompt: "Welchen Vorteil bietet eine doppelt verkettete Liste gegenüber einer einfach verketteten?",
    options: [
      "Sie erlaubt Rückwärtstraversierung und das Entfernen eines gegebenen Knotens in konstanter Zeit, da der Vorgänger direkt bekannt ist.",
      "Sie benötigt grundsätzlich weniger Speicher.",
      "Sie kann nur vorwärts traversiert werden.",
      "Sie ist immer schneller beim Einfügen am Kopf.",
    ],
    correctIndex: 0,
    explanation:
      "Da jeder Knoten zusätzlich seinen Vorgänger kennt, muss dieser beim Entfernen nicht erst gesucht werden.",
    source: "Kapitel 3, Einfach und doppelt verkettete Listen",
    free: false,
  },
  {
    id: "ds1-04",
    topic: "Datenstrukturen I",
    type: "mc",
    prompt:
      "Ein Keller ist anfangs leer. Es werden nacheinander PUSH(11), PUSH(22), POP(), PUSH(33), POP(), POP() ausgeführt. Welche Werte liefern die drei POP()-Aufrufe in dieser Reihenfolge?",
    options: ["22, 33, 11", "11, 22, 33", "33, 22, 11", "22, 11, 33"],
    correctIndex: 0,
    explanation:
      "Nach PUSH(11), PUSH(22) liegt oben 22 → erstes POP liefert 22. Danach PUSH(33) legt 33 oben ab → zweites POP liefert 33. Übrig bleibt 11 → drittes POP liefert 11.",
    source: "Kapitel 3, Der Keller (Stack)",
    free: false,
  },
  {
    id: "ds1-05",
    topic: "Datenstrukturen I",
    type: "mc",
    prompt:
      "Eine anfangs leere Warteschlange wird durch ein zirkuläres Array der Länge 4 realisiert. Nach ENQUEUE(12), ENQUEUE(19), ENQUEUE(31), DEQUEUE(), ENQUEUE(24), ENQUEUE(17), DEQUEUE(), ENQUEUE(9), DEQUEUE() — welche Werte liefern die drei DEQUEUE()-Aufrufe in dieser Reihenfolge?",
    options: ["12, 19, 31", "31, 19, 12", "12, 31, 19", "19, 12, 31"],
    correctIndex: 0,
    explanation:
      "Eine Schlange arbeitet nach dem FIFO-Prinzip: Die drei DEQUEUE-Aufrufe entnehmen die Elemente in der Reihenfolge ihres Einfügens, also 12, dann 19, dann 31.",
    source: "Kapitel 3, Die Schlange (Queue)",
    free: false,
  },
  {
    id: "ds1-06",
    topic: "Datenstrukturen I",
    type: "mc",
    prompt: "Wie lässt sich eine Schlange (Queue) mit zwei Kellern S1 und S2 implementieren?",
    options: [
      "Neue Elemente werden immer auf S1 gelegt; beim Entnehmen wird, falls S2 leer ist, der gesamte Inhalt von S1 nach S2 umgeschichtet und von dort entnommen.",
      "Neue Elemente werden abwechselnd auf S1 und S2 gelegt.",
      "S1 wird nur zum Entnehmen, S2 nur zum Einfügen verwendet, ohne je Inhalte zu verschieben.",
      "Ein Keller reicht aus, S2 wird nicht benötigt.",
    ],
    correctIndex: 0,
    explanation:
      "Das Umschichten von S1 nach S2 kehrt die Reihenfolge um, sodass das älteste Element oben auf S2 zu liegen kommt — genau das FIFO-Verhalten einer Queue.",
    source: "Kapitel 3, Die Schlange (Queue)",
    free: false,
  },

  // ---------- Prädikatenlogik ----------
  {
    id: "pl-01",
    topic: "Prädikatenlogik",
    type: "mc",
    prompt: "Wann heißt ein Vorkommen einer Variablen x in einer prädikatenlogischen Formel gebunden?",
    options: [
      "Wenn es im Wirkungsbereich eines Quantors ∀x oder ∃x liegt.",
      "Wenn es außerhalb jedes Quantors steht.",
      "Wenn x nie in der Formel vorkommt.",
      "Wenn x nur in Funktionszeichen vorkommt.",
    ],
    correctIndex: 0,
    explanation: "Gebunden ist ein Vorkommen genau dann, wenn ein Quantor über dieselbe Variable darüber steht.",
    source: "Kapitel 4, Terme, Formeln und Quantoren",
    free: true,
  },
  {
    id: "pl-02",
    topic: "Prädikatenlogik",
    type: "mc",
    prompt:
      "Wie werden bei der Skolemisierung existenzquantifizierte Variablen behandelt, die im Wirkungsbereich vorausgehender Allquantoren stehen?",
    options: [
      "Sie werden durch eine Skolemfunktion ersetzt, deren Argumente die vorausgehenden allquantifizierten Variablen sind.",
      "Sie werden ersatzlos gestrichen.",
      "Sie werden immer durch eine Konstante ersetzt, unabhängig von vorausgehenden Allquantoren.",
      "Sie bleiben unverändert.",
    ],
    correctIndex: 0,
    explanation:
      "Nur wenn keine Allquantoren vorausgehen, wird durch eine Skolemkonstante ersetzt — andernfalls durch eine von den vorausgehenden Variablen abhängige Skolemfunktion.",
    source: "Kapitel 4, Bereinigung, Pränexnormalform und Skolemform",
    free: true,
  },
  {
    id: "pl-03",
    topic: "Prädikatenlogik",
    type: "mc",
    prompt:
      "Sind die Literale {h(k(x), y), h(y, k(z))} unifizierbar? Falls ja, welcher allgemeinste Unifikator ergibt sich?",
    options: [
      "Ja, mit {x/z, y/k(z)}",
      "Ja, mit {x/y, z/k(x)}",
      "Nein, da k(x) und y nicht kompatibel sind",
      "Ja, mit {x/k(z), y/z}",
    ],
    correctIndex: 0,
    explanation:
      "Aus der ersten Position folgt y = k(x); aus der zweiten Position folgt k(x) = k(z), also x = z, und damit y = k(z).",
    source: "Kapitel 4, Unifikation",
    free: false,
  },
  {
    id: "pl-04",
    topic: "Prädikatenlogik",
    type: "mc",
    prompt:
      "Aus 'Alle Fahrzeuge, die elektrisch angetrieben werden und autonom fahren können, sind Robotaxis' und 'Fahrzeug X wird elektrisch angetrieben und kann autonom fahren' folgt unmittelbar 'X ist ein Robotaxi'. Welcher Schluss liegt hier vor?",
    options: [
      "Modus Ponens nach Instanziierung des Allquantors",
      "Modus Tollens",
      "Kontraposition",
      "Kein gültiger Schluss möglich",
    ],
    correctIndex: 0,
    explanation:
      "Nach Einsetzen von X für die allquantifizierte Variable liegt eine Implikation vor, deren Prämisse für X erfüllt ist — klassischer Modus Ponens.",
    source: "Kapitel 4, Resolution in der Prädikatenlogik",
    free: false,
  },
  {
    id: "pl-05",
    topic: "Prädikatenlogik",
    type: "mc",
    prompt: "Was legt die Basis B = (V, FZ, PZ) einer prädikatenlogischen Formel fest?",
    options: [
      "Die Menge der Variablen, Funktionszeichen und Prädikatzeichen.",
      "Nur die Wahrheitswerte der Formel.",
      "Die grafische Darstellung der Formel.",
      "Die Reihenfolge der Quantoren.",
    ],
    correctIndex: 0,
    explanation: "V, FZ und PZ sind die zulässigen Bausteine, aus denen Terme und Formeln über dieser Basis gebildet werden.",
    source: "Kapitel 4, Terme, Formeln und Quantoren",
    free: false,
  },
  {
    id: "pl-06",
    topic: "Prädikatenlogik",
    type: "mc",
    prompt: "Wann heißt eine prädikatenlogische Formel geschlossen?",
    options: [
      "Wenn sie keine freien Variablenvorkommen enthält.",
      "Wenn sie keine Quantoren enthält.",
      "Wenn sie nur aus Konstanten besteht.",
      "Wenn alle Variablen frei vorkommen.",
    ],
    correctIndex: 0,
    explanation: "Nur geschlossenen Formeln lässt sich unabhängig von einer Belegung ein Wahrheitswert zuordnen.",
    source: "Kapitel 4, Terme, Formeln und Quantoren",
    free: false,
  },

  // ---------- Entwurfsprinzipien und Testen von Algorithmen ----------
  {
    id: "et-01",
    topic: "Entwurfsprinzipien und Testen von Algorithmen",
    type: "mc",
    prompt: "Worin unterscheiden sich Entwurfsprinzipien von Entwurfstechniken?",
    options: [
      "Entwurfsprinzipien sind grundsätzliche Denkweisen (z. B. Backtracking, Divide & Conquer), Entwurfstechniken sind konkretere, oft algorithmenklassen-spezifische Vorgehensweisen (z. B. Greedy).",
      "Beide Begriffe sind identisch definiert.",
      "Entwurfstechniken sind immer abstrakter als Entwurfsprinzipien.",
      "Entwurfsprinzipien gelten nur für rekursive Algorithmen.",
    ],
    correctIndex: 0,
    explanation: "Entwurfsprinzipien sind die grundlegenderen, allgemeineren Denkweisen; Entwurfstechniken konkretisieren diese.",
    source: "Kapitel 5, Entwurfsprinzipien versus Entwurfstechniken",
    free: true,
  },
  {
    id: "et-02",
    topic: "Entwurfsprinzipien und Testen von Algorithmen",
    type: "mc",
    prompt: "Welche Aussage beschreibt Backtracking korrekt?",
    options: [
      "Es probiert Entscheidungen systematisch aus und macht sie rückgängig, sobald sich ein Pfad als Sackgasse erweist.",
      "Es zerlegt ein Problem stets in gleich große Teilprobleme.",
      "Es garantiert immer lineare Laufzeit.",
      "Es kommt ausschließlich bei Sortierverfahren zum Einsatz.",
    ],
    correctIndex: 0,
    explanation: "Backtracking ist ein systematisches Ausprobieren mit Zurücknehmen bereits getroffener Entscheidungen.",
    source: "Kapitel 5, Backtracking",
    free: true,
  },
  {
    id: "et-03",
    topic: "Entwurfsprinzipien und Testen von Algorithmen",
    type: "numeric",
    prompt:
      "Wie viele Multiplikationen benötigt die Berechnung von x¹⁶ mit dem Divide-&-Conquer-Prinzip (x^n = (x^(n/2))², ggf. mit zusätzlichem Faktor bei ungeradem n), verglichen mit 15 Multiplikationen bei naiver Berechnung?",
    correctValue: 4,
    explanation:
      "x², x⁴, x⁸, x¹⁶ entstehen durch jeweils eine Multiplikation (Quadrieren) — insgesamt 4 statt 15 Multiplikationen.",
    source: "Kapitel 5, Divide & Conquer",
    free: false,
  },
  {
    id: "et-04",
    topic: "Entwurfsprinzipien und Testen von Algorithmen",
    type: "mc",
    prompt: "Welche Aussage zu Verifikation und Test trifft zu?",
    options: [
      "Verifikation ist ein formaler Korrektheitsbeweis für alle zulässigen Eingaben; ein Test kann dagegen nur die Anwesenheit, nie die Abwesenheit von Fehlern nachweisen.",
      "Ein Test beweist immer die vollständige Korrektheit eines Programms.",
      "Verifikation erfordert die Ausführung des Programms mit Testdaten.",
      "Test und Verifikation sind identisch.",
    ],
    correctIndex: 0,
    explanation: "Ein Test deckt Fehler auf, kann aber wegen des typischerweise riesigen Eingaberaums deren Abwesenheit nicht beweisen.",
    source: "Kapitel 5, Verifikation, Test, Black-Box und White-Box",
    free: false,
  },
  {
    id: "et-05",
    topic: "Entwurfsprinzipien und Testen von Algorithmen",
    type: "mc",
    prompt: "Was kennzeichnet einen White-Box-Test im Unterschied zu einem Black-Box-Test?",
    options: [
      "Testfälle werden anhand der bekannten internen Programmstruktur gewählt, z. B. um jeden Zweig abzudecken.",
      "Testfälle werden ausschließlich aus der Spezifikation ohne Kenntnis der Implementierung abgeleitet.",
      "Beide Testarten sind identisch.",
      "White-Box-Tests benötigen keine Testfälle.",
    ],
    correctIndex: 0,
    explanation: "Beim White-Box-Test ist die interne Struktur bekannt und wird gezielt zur Testfallauswahl genutzt.",
    source: "Kapitel 5, Verifikation, Test, Black-Box und White-Box",
    free: false,
  },
  {
    id: "et-06",
    topic: "Entwurfsprinzipien und Testen von Algorithmen",
    type: "mc",
    prompt: "Warum wählt man Testfälle bei großem Eingaberaum über Äquivalenzklassen und Grenzwertanalyse aus?",
    options: [
      "Weil sich damit repräsentative und besonders fehleranfällige Fälle (Ränder zulässiger Bereiche) mit vertretbarem Aufwand abdecken lassen, statt den gesamten Eingaberaum durchzuprobieren.",
      "Weil dadurch garantiert alle Fehler gefunden werden.",
      "Weil es gesetzlich vorgeschrieben ist.",
      "Weil dadurch die Terminierung des zu testenden Programms bewiesen wird.",
    ],
    correctIndex: 0,
    explanation: "Äquivalenzklassen und Grenzwerte konzentrieren den begrenzten Testaufwand auf die aussagekräftigsten Fälle.",
    source: "Kapitel 5, Verifikation, Test, Black-Box und White-Box",
    free: false,
  },

  // ---------- Datenstrukturen II ----------
  {
    id: "ds2-01",
    topic: "Datenstrukturen II",
    type: "mc",
    prompt: "Welche Eigenschaft hat die Adjazenzmatrix eines ungerichteten Graphen im Vergleich zu der eines gerichteten Graphen?",
    options: [
      "Sie ist stets symmetrisch, während sie bei gerichteten Graphen im Allgemeinen nicht symmetrisch ist.",
      "Sie ist nie symmetrisch.",
      "Beide sind immer symmetrisch.",
      "Es gibt keinen Unterschied.",
    ],
    correctIndex: 0,
    explanation: "Bei ungerichteten Kanten gilt (i,j) genau dann, wenn auch (j,i) gilt — daher Symmetrie.",
    source: "Kapitel 6, Graphen: Grundbegriffe",
    free: true,
  },
  {
    id: "ds2-02",
    topic: "Datenstrukturen II",
    type: "mc",
    prompt: "Welche Datenstruktur wird typischerweise für die Tiefensuche bzw. die Breitensuche verwendet?",
    options: [
      "Tiefensuche: Keller, Breitensuche: Schlange",
      "Tiefensuche: Schlange, Breitensuche: Keller",
      "Beide verwenden ausschließlich Arrays",
      "Beide verwenden dieselbe Datenstruktur",
    ],
    correctIndex: 0,
    explanation: "DFS nutzt (rekursiv oder explizit) einen Keller, BFS eine Schlange.",
    source: "Kapitel 6, Tiefensuche und Breitensuche",
    free: true,
  },
  {
    id: "ds2-03",
    topic: "Datenstrukturen II",
    type: "mc",
    prompt: "Welche Formel gibt die minimale Höhe eines binären Baumes mit n Elementen an?",
    options: ["⌈log₂(n+1)⌉ − 1", "n − 1", "log₂(n)", "n / 2"],
    correctIndex: 0,
    explanation: "Ein vollständig balancierter binärer Baum minimiert die Höhe auf ⌈log₂(n+1)⌉ − 1.",
    source: "Kapitel 6, Bäume und Wurzelgraphen",
    free: false,
  },
  {
    id: "ds2-04",
    topic: "Datenstrukturen II",
    type: "numeric",
    prompt: "Wie hoch ist ein binärer Baum mit 15 Elementen im besten Fall (vollständig balanciert)?",
    correctValue: 3,
    explanation: "⌈log₂(15+1)⌉ − 1 = ⌈log₂16⌉ − 1 = 4 − 1 = 3.",
    source: "Kapitel 6, Bäume und Wurzelgraphen",
    free: false,
  },
  {
    id: "ds2-05",
    topic: "Datenstrukturen II",
    type: "mc",
    prompt: "Ist jeder Wurzelgraph gleichzeitig ein Baum?",
    options: [
      "Nein, nur wenn zusätzlich jeder Knoten (außer der Wurzel) genau einen Vorgänger hat — sonst kann ein Wurzelgraph ein DAG mit mehreren Wegen zu einem Knoten sein.",
      "Ja, per Definition immer.",
      "Nein, ein Wurzelgraph ist niemals ein Baum.",
      "Nur wenn der Graph ungerichtet ist.",
    ],
    correctIndex: 0,
    explanation: "Laufen mehrere Wege von der Wurzel auf einem Knoten zusammen, ist der Graph zwar ein Wurzelgraph, aber kein Baum mehr.",
    source: "Kapitel 6, Bäume und Wurzelgraphen",
    free: false,
  },
  {
    id: "ds2-06",
    topic: "Datenstrukturen II",
    type: "mc",
    prompt: "Welche Traversierung eines binären Suchbaums liefert die Elemente stets in aufsteigend sortierter Reihenfolge?",
    options: ["In-Order", "Pre-Order", "Post-Order", "Level-Order"],
    correctIndex: 0,
    explanation: "In-Order (linker Teilbaum, Knoten, rechter Teilbaum) nutzt genau die Ordnungseigenschaft des Suchbaums aus.",
    source: "Kapitel 6, Binäre Suchbäume",
    free: false,
  },
  {
    id: "ds2-07",
    topic: "Datenstrukturen II",
    type: "mc",
    prompt: "Welche drei Fälle unterscheidet man beim Löschen eines Knotens in einem binären Suchbaum?",
    options: [
      "Blatt ohne Kinder, Knoten mit genau einem Kind, Knoten mit zwei Kindern (ersetzt durch In-Order-Nachfolger oder -Vorgänger).",
      "Nur Blattknoten können gelöscht werden.",
      "Wurzel, Blatt, innerer Knoten.",
      "Es gibt nur einen einzigen Fall.",
    ],
    correctIndex: 0,
    explanation: "Die drei Fälle unterscheiden sich in der Anzahl der Kinder des zu löschenden Knotens (0, 1 oder 2).",
    source: "Kapitel 6, Binäre Suchbäume",
    free: false,
  },

  // ---------- Boolesche Algebra ----------
  {
    id: "ba-01",
    topic: "Boolesche Algebra",
    type: "mc",
    prompt: "Welche der folgenden Aussagen gehört zu den Huntingtonschen Axiomen einer Booleschen Algebra?",
    options: [
      "Für jedes a existiert ein Komplement a′ mit a·a′ = 0 und a+a′ = 1.",
      "Nur + ist kommutativ, · nicht.",
      "Es gibt kein neutrales Element für +.",
      "Distributivität gilt nicht.",
    ],
    correctIndex: 0,
    explanation: "Die Existenz von Komplementen ist eines der Huntingtonschen Axiome.",
    source: "Kapitel 7, Die Huntingtonschen Axiome",
    free: true,
  },
  {
    id: "ba-02",
    topic: "Boolesche Algebra",
    type: "mc",
    prompt: "Was besagt das Dualitätsprinzip der Booleschen Algebra?",
    options: [
      "Vertauscht man in einer gültigen Aussage durchgängig · mit + und 0 mit 1, erhält man wieder eine gültige Aussage.",
      "Jede Boolesche Algebra hat genau zwei Elemente.",
      "Komplemente sind niemals eindeutig.",
      "· und + sind stets identisch.",
    ],
    correctIndex: 0,
    explanation: "Da die Axiome selbst paarweise dual formuliert sind, überträgt sich Gültigkeit auf die duale Aussage.",
    source: "Kapitel 7, Das Dualitätsprinzip",
    free: true,
  },
  {
    id: "ba-03",
    topic: "Boolesche Algebra",
    type: "mc",
    prompt: "Welche Aussage folgt aus a·0 = 0 unmittelbar über das Dualitätsprinzip, ohne erneuten Beweis?",
    options: ["a + 1 = 1", "a + 0 = a", "a · 1 = 0", "a′ = 0"],
    correctIndex: 0,
    explanation: "Vertauscht man · mit + und 0 mit 1, wird aus a·0=0 die duale Aussage a+1=1.",
    source: "Kapitel 7, Das Dualitätsprinzip",
    free: false,
  },
  {
    id: "ba-04",
    topic: "Boolesche Algebra",
    type: "mc",
    prompt:
      "In einer Booleschen Algebra (M;·,+,′) mit M = {p,q,r,s} gilt: p·q=r, p·s=p, p+q=s, q+r=q. Welches Element ist das neutrale Element bezüglich der Booleschen Summe (≙0) und welches bezüglich des Booleschen Produkts (≙1)?",
    options: ["r ≙ 0, s ≙ 1", "s ≙ 0, r ≙ 1", "p ≙ 0, q ≙ 1", "q ≙ 0, p ≙ 1"],
    correctIndex: 0,
    explanation:
      "Aus p·s=p folgt, dass s neutral bezüglich · ist (s≙1). Aus q+r=q folgt, dass r neutral bezüglich + ist (r≙0). Damit sind p und q zueinander komplementär (p+q=1, p·q=0).",
    source: "Kapitel 7, Die Huntingtonschen Axiome",
    free: false,
  },
  {
    id: "ba-05",
    topic: "Boolesche Algebra",
    type: "mc",
    prompt: "Wie lässt sich (a·b)·(a′+b′) = 0 zeigen?",
    options: [
      "Durch Distributivität zu a·b·a′ + a·b·b′ umformen; da a·a′=0 und b·b′=0 gilt, verschwinden beide Summanden.",
      "Durch direktes Einsetzen von a = 1.",
      "Es lässt sich allgemein nicht zeigen.",
      "Nur durch eine Wahrheitstafel mit unendlich vielen Zeilen.",
    ],
    correctIndex: 0,
    explanation: "Die Distributivität zerlegt den Ausdruck in zwei Summanden, die beide wegen der Komplement-Gesetze verschwinden.",
    source: "Kapitel 7, Abgeleitete Gesetze und Bezug zur Aussagenlogik",
    free: false,
  },

  // ---------- Sortierverfahren ----------
  {
    id: "so-01",
    topic: "Sortierverfahren",
    type: "mc",
    prompt:
      "Bei Insertion Sort wird die Folge (7, 2, 9, 4, 6) sortiert. Wie sieht das Array direkt nach dem Einsortieren des Elements 4 aus?",
    options: ["(2, 4, 7, 9, 6)", "(2, 4, 6, 7, 9)", "(4, 2, 7, 9, 6)", "(2, 7, 4, 9, 6)"],
    correctIndex: 0,
    explanation:
      "Nach den ersten beiden Schritten liegt (2, 7, 9, 4, 6) vor. Die 4 wird an 9 und 7 vorbei bis hinter die 2 einsortiert: (2, 4, 7, 9, 6).",
    source: "Kapitel 8, Sortieren durch direktes Einfügen",
    free: true,
  },
  {
    id: "so-02",
    topic: "Sortierverfahren",
    type: "mc",
    prompt: "Wann tritt bei Quicksort der Worst-Case Tmax = O(n²) ein?",
    options: [
      "Wenn die Partitionen bei jedem Rekursionsschritt maximal unausgeglichen sind, z. B. bei bereits sortierter Eingabe und Wahl des ersten Elements als Pivot.",
      "Wenn das Array bereits vollständig sortiert ist und ein zufälliges Pivot gewählt wird.",
      "Nie — Quicksort hat immer O(n log n).",
      "Nur bei negativen Zahlen.",
    ],
    correctIndex: 0,
    explanation: "Maximal unausgeglichene Partitionen führen zu n Rekursionsebenen mit je O(n) Aufwand, insgesamt O(n²).",
    source: "Kapitel 8, Quicksort",
    free: true,
  },
  {
    id: "so-03",
    topic: "Sortierverfahren",
    type: "mc",
    prompt: "Welche durchschnittliche Laufzeit hat Quicksort?",
    options: ["O(n log₂n)", "O(n²)", "O(n)", "O(log n)"],
    correctIndex: 0,
    explanation: "Im Mittel teilt das Pivotelement die Folge einigermaßen ausgeglichen, was zu Tavg = O(n log₂n) führt.",
    source: "Kapitel 8, Quicksort",
    free: false,
  },
  {
    id: "so-04",
    topic: "Sortierverfahren",
    type: "mc",
    prompt: "Welche Eigenschaft muss ein Max-Heap erfüllen?",
    options: [
      "Jeder Elternknoten ist größer oder gleich seinen Kindknoten, sodass das größte Element an der Wurzel steht.",
      "Jeder Elternknoten ist kleiner als seine Kinder.",
      "Die Elemente müssen bereits sortiert sein.",
      "Ein Max-Heap ist immer auch ein binärer Suchbaum.",
    ],
    correctIndex: 0,
    explanation: "Die Heap-Eigenschaft fordert genau diese Beziehung zwischen Eltern- und Kindknoten.",
    source: "Kapitel 8, Heapsort",
    free: false,
  },
  {
    id: "so-05",
    topic: "Sortierverfahren",
    type: "mc",
    prompt: "Welche Laufzeitklasse hat Heapsort im besten und im schlechtesten Fall?",
    options: [
      "Tmax = Tavg = O(n log₂n) — Heapsort ist damit asymptotisch optimal für vergleichsbasierte Sortierverfahren.",
      "Tmax = O(n²), Tavg = O(n log n).",
      "Tmax = Tmin = O(n).",
      "Es gibt keine bekannte obere Schranke.",
    ],
    correctIndex: 0,
    explanation: "Sowohl Aufbau als auch Sortieren benötigen O(n log₂n), was zugleich der unteren Schranke für vergleichsbasierte Verfahren entspricht.",
    source: "Kapitel 8, Heapsort",
    free: false,
  },
  {
    id: "so-06",
    topic: "Sortierverfahren",
    type: "mc",
    prompt: "Welchen praktischen Vorteil bietet BottomUp-Heapsort gegenüber Standard-Heapsort?",
    options: [
      "Es reduziert die Anzahl der benötigten Vergleiche etwa um die Hälfte.",
      "Es verbessert die asymptotische Komplexitätsklasse auf O(n).",
      "Es funktioniert nur bei bereits sortierten Arrays.",
      "Es benötigt keinen Heap.",
    ],
    correctIndex: 0,
    explanation: "BottomUp-Heapsort ist eine praktische, nicht aber asymptotische Verbesserung: gleiche Komplexitätsklasse, aber weniger Vergleiche.",
    source: "Kapitel 8, Heapsort",
    free: false,
  },

  // ---------- Datenstrukturen III ----------
  {
    id: "ds3-01",
    topic: "Datenstrukturen III",
    type: "mc",
    prompt: "Unter welcher Bedingung besitzt ein zusammenhängender Graph einen Eulerschen Kreis?",
    options: [
      "Wenn jeder Knoten geraden Grad hat.",
      "Wenn jeder Knoten ungeraden Grad hat.",
      "Wenn der Graph ein Baum ist.",
      "Immer, unabhängig vom Grad der Knoten.",
    ],
    correctIndex: 0,
    explanation: "Gerader Grad an jedem Knoten stellt sicher, dass jede Kante beim Durchlaufen wieder 'verlassen' werden kann.",
    source: "Kapitel 9, Eulersche und Hamiltonsche Kreise",
    free: true,
  },
  {
    id: "ds3-02",
    topic: "Datenstrukturen III",
    type: "mc",
    prompt: "Welche Komplexität hat der naive Algorithmus zur Bestimmung eines Hamiltonschen Kreises?",
    options: ["O(m!), da im schlechtesten Fall alle Permutationen der Knoten durchprobiert werden.", "O(n log n)", "O(n²)", "O(n)"],
    correctIndex: 0,
    explanation: "Ohne bekanntes polynomielles Verfahren muss der naive Algorithmus alle m! Knotenpermutationen prüfen.",
    source: "Kapitel 9, Eulersche und Hamiltonsche Kreise",
    free: true,
  },
  {
    id: "ds3-03",
    topic: "Datenstrukturen III",
    type: "mc",
    prompt: "Welche Voraussetzung muss ein kantengewichteter Graph erfüllen, damit der Algorithmus von Dijkstra korrekt arbeitet?",
    options: [
      "Alle Kantengewichte müssen nicht-negativ sein.",
      "Der Graph muss ungerichtet sein.",
      "Der Graph darf keine Zyklen enthalten.",
      "Alle Kantengewichte müssen gleich groß sein.",
    ],
    correctIndex: 0,
    explanation: "Negative Gewichte können dazu führen, dass ein bereits als endgültig markierter Knoten zu kurz eingeschätzt wird.",
    source: "Kapitel 9, Kürzeste Wege: der Algorithmus von Dijkstra",
    free: false,
  },
  {
    id: "ds3-04",
    topic: "Datenstrukturen III",
    type: "mc",
    prompt:
      "Ein Graph enthält eine einzelne Kante mit negativem Gewicht, alle übrigen Kantengewichte sind positiv. Ist der Algorithmus von Dijkstra weiterhin uneingeschränkt anwendbar?",
    options: [
      "Nein, da Dijkstra nur bei ausschließlich nicht-negativen Kantengewichten korrekte Ergebnisse garantiert — hier sollte stattdessen Bellman-Ford verwendet werden.",
      "Ja, eine einzelne negative Kante ändert nichts an der Korrektheit.",
      "Ja, aber nur wenn der Graph ungerichtet ist.",
      "Nein, weil Dijkstra grundsätzlich nur mit ungerichteten Graphen arbeitet.",
    ],
    correctIndex: 0,
    explanation: "Schon eine einzige negative Kante kann die Greedy-Annahme von Dijkstra verletzen.",
    source: "Kapitel 9, Kürzeste Wege: der Algorithmus von Dijkstra",
    free: false,
  },
  {
    id: "ds3-05",
    topic: "Datenstrukturen III",
    type: "mc",
    prompt: "Was passiert beim Algorithmus von Bellman-Ford, wenn der Graph einen vom Startknoten aus erreichbaren negativen Zyklus enthält?",
    options: [
      "Es existiert kein kürzester Weg, da sich die Weglänge beliebig verkürzen lässt, und der Algorithmus liefert kein korrektes endliches Ergebnis.",
      "Der Algorithmus liefert trotzdem stets das korrekte Ergebnis.",
      "Negative Zyklen sind für Bellman-Ford irrelevant.",
      "Der Algorithmus bricht sofort mit einem Syntaxfehler ab.",
    ],
    correctIndex: 0,
    explanation: "Ein erreichbarer negativer Zyklus lässt die Weglänge beliebig sinken — ein kürzester Weg existiert dann nicht.",
    source: "Kapitel 9, Der Algorithmus von Bellman-Ford",
    free: false,
  },
  {
    id: "ds3-06",
    topic: "Datenstrukturen III",
    type: "mc",
    prompt: "Nach welchem Prinzip wählt der Algorithmus von Kruskal Kanten für den minimalen Spannbaum aus?",
    options: [
      "Er sortiert alle Kanten aufsteigend nach Gewicht und fügt sie hinzu, sofern sie keinen Zyklus mit bereits gewählten Kanten bilden.",
      "Er wählt zufällige Kanten, bis der Graph zusammenhängend ist.",
      "Er beginnt bei der teuersten Kante.",
      "Er ignoriert Kantengewichte vollständig.",
    ],
    correctIndex: 0,
    explanation: "Kruskal ist ein Greedy-Verfahren, das Kanten aufsteigend nach Gewicht betrachtet und Zyklen vermeidet.",
    source: "Kapitel 9, Minimale Spannbäume: Kruskal und Prim",
    free: false,
  },
  {
    id: "ds3-07",
    topic: "Datenstrukturen III",
    type: "mc",
    prompt: "Wann ist der Algorithmus von Prim gegenüber Kruskal effizienter?",
    options: [
      "Bei sehr dichten Graphen, bei denen die Kantenzahl |E| deutlich größer ist als die Knotenzahl |V|.",
      "Bei Graphen ohne Kanten.",
      "Nur bei gerichteten Graphen.",
      "Nie — Kruskal ist immer schneller.",
    ],
    correctIndex: 0,
    explanation: "Prims Laufzeit O(|E|+|V|·log|V|) ist bei |E| ≫ |V| günstiger als Kruskals O(|E|·log|E|).",
    source: "Kapitel 9, Minimale Spannbäume: Kruskal und Prim",
    free: false,
  },

  // ---------- Komplexität von Algorithmen ----------
  {
    id: "kx-01",
    topic: "Komplexität von Algorithmen",
    type: "mc",
    prompt: "Ordnen Sie folgende Funktionen nach aufsteigender asymptotischer Komplexität: n³, 2ⁿ, log n, n!, n log n, n, nⁿ, n².",
    options: [
      "log n, n, n log n, n², n³, 2ⁿ, n!, nⁿ",
      "log n, n, n², n log n, n³, 2ⁿ, n!, nⁿ",
      "n, log n, n log n, n², n³, n!, 2ⁿ, nⁿ",
      "log n, n log n, n, n², n³, 2ⁿ, nⁿ, n!",
    ],
    correctIndex: 0,
    explanation: "Die korrekte aufsteigende Reihenfolge ist: log n < n < n log n < n² < n³ < 2ⁿ < n! < nⁿ.",
    source: "Kapitel 10, Groß-O-, Ω- und Θ-Notation",
    free: true,
  },
  {
    id: "kx-02",
    topic: "Komplexität von Algorithmen",
    type: "mc",
    prompt:
      "Ein Algorithmus mit Eingabe n>0 halbiert n in einer Schleife so lange, bis n<2, und zählt dabei die Anzahl Iterationen. Welche Komplexitätsklasse hat dieser Algorithmus?",
    options: ["O(log₂n)", "O(n)", "O(n²)", "O(1)"],
    correctIndex: 0,
    explanation: "Wiederholtes Halbieren bis zu einer Schranke benötigt logarithmisch viele Schritte.",
    source: "Kapitel 10, Einflussfaktoren und Elementaroperationen",
    free: true,
  },
  {
    id: "kx-03",
    topic: "Komplexität von Algorithmen",
    type: "mc",
    prompt:
      "Ein Algorithmus begrenzt eine Eingabe n zunächst auf höchstens 25 (n=25, falls n>25) und summiert anschließend in einer Schleife die Zahlen von 1 bis n auf. Welche Komplexitätsklasse hat dieser Algorithmus in Abhängigkeit von der ursprünglichen Eingabegröße n?",
    options: [
      "O(1), da die Schleife durch die Begrenzung auf höchstens 25 Iterationen läuft, unabhängig von der ursprünglichen Eingabegröße.",
      "O(n)",
      "O(n²)",
      "O(log n)",
    ],
    correctIndex: 0,
    explanation: "Da die Schleife nach der Begrenzung höchstens 25-mal läuft, ist der Aufwand konstant bezüglich der ursprünglichen Eingabegröße.",
    source: "Kapitel 10, Tmin, Tavg und Tmax",
    free: false,
  },
  {
    id: "kx-04",
    topic: "Komplexität von Algorithmen",
    type: "mc",
    prompt:
      "Ein Algorithmus durchläuft eine äußere Schleife von 1 bis n und darin für jedes i eine innere Schleife von 1 bis i. Welche Komplexitätsklasse hat dieser Algorithmus?",
    options: ["O(n²)", "O(n)", "O(n log n)", "O(2ⁿ)"],
    correctIndex: 0,
    explanation: "Die Gesamtzahl der inneren Durchläufe ist 1+2+...+n = n(n+1)/2 = O(n²).",
    source: "Kapitel 10, Tmin, Tavg und Tmax",
    free: false,
  },
  {
    id: "kx-05",
    topic: "Komplexität von Algorithmen",
    type: "mc",
    prompt: "Welche Θ-Komplexität hat f(n) = n³ + 7 + 50·n⁶?",
    options: ["Θ(n⁶)", "Θ(n³)", "Θ(n^9)", "Θ(n)"],
    correctIndex: 0,
    explanation: "Für die Θ-Notation zählt allein der am schnellsten wachsende Summand — hier n⁶.",
    source: "Kapitel 10, Groß-O-, Ω- und Θ-Notation",
    free: false,
  },
  {
    id: "kx-06",
    topic: "Komplexität von Algorithmen",
    type: "mc",
    prompt: "Welche O-Komplexität hat f(n) = (n+a)^k für Konstanten a und k?",
    options: ["O(nᵏ)", "O(nᵃ)", "O(n^(a+k))", "O(kⁿ)"],
    correctIndex: 0,
    explanation: "(n+a)^k ist für konstantes a und k ein Polynom vom Grad k in n, also O(nᵏ).",
    source: "Kapitel 10, Groß-O-, Ω- und Θ-Notation",
    free: false,
  },
  {
    id: "kx-07",
    topic: "Komplexität von Algorithmen",
    type: "mc",
    prompt: "Welche Θ-Komplexität hat f(n) = 2ⁿ + 5·n³?",
    options: ["Θ(2ⁿ), da die Exponentialfunktion für große n jedes Polynom dominiert.", "Θ(n³)", "Θ(n³·2ⁿ)", "Θ(n)"],
    correctIndex: 0,
    explanation: "Exponentielles Wachstum dominiert jedes Polynom, sodass der n³-Term für die Θ-Klasse irrelevant wird.",
    source: "Kapitel 10, Groß-O-, Ω- und Θ-Notation",
    free: false,
  },
  {
    id: "kx-08",
    topic: "Komplexität von Algorithmen",
    type: "mc",
    prompt: "Was bedeutet eine Verdopplung der Eingabegröße n für einen Algorithmus mit Komplexität O(n²) für die Laufzeit?",
    options: [
      "Die Laufzeit vervierfacht sich näherungsweise.",
      "Die Laufzeit verdoppelt sich.",
      "Die Laufzeit bleibt gleich.",
      "Die Laufzeit halbiert sich.",
    ],
    correctIndex: 0,
    explanation: "(2n)² = 4n² — die Laufzeit steigt quadratisch mit n, eine Verdopplung von n vervierfacht sie also.",
    source: "Kapitel 10, Komplexitätsklassen und ihre praktische Bedeutung",
    free: false,
  },
  {
    id: "kx-09",
    topic: "Komplexität von Algorithmen",
    type: "mc",
    prompt: "Wie ist Tmax(A;n) definiert?",
    options: [
      "Als das Maximum von t(A;n,e) über alle Eingaben e der Größe n.",
      "Als das Minimum von t(A;n,e).",
      "Als der Mittelwert von t(A;n,e).",
      "Als die Anzahl der Eingaben der Größe n.",
    ],
    correctIndex: 0,
    explanation: "Tmax erfasst den ungünstigsten Fall — das Maximum des Aufwands über alle Eingaben derselben Größe.",
    source: "Kapitel 10, Tmin, Tavg und Tmax",
    free: false,
  },

  // ---------- UML: Einführung und Anwendungsfalldiagramme ----------
  {
    id: "uml1-01",
    topic: "UML: Einführung und Anwendungsfalldiagramme",
    type: "mc",
    prompt: "Wofür wird UML in erster Linie eingesetzt?",
    options: [
      "Als vereinheitlichte, standardisierte Notation zur Spezifikation, Visualisierung, Konstruktion und Dokumentation objektorientierter Systeme.",
      "Ausschließlich zur Erzeugung von Datenbankschemata.",
      "Als Programmiersprache zur direkten Ausführung.",
      "Nur zur Dokumentation bereits fertiggestellter Software.",
    ],
    correctIndex: 0,
    explanation: "UML vereint mehrere Zwecke: Spezifikation, Visualisierung, Konstruktion und Dokumentation.",
    source: "Kapitel 11, Warum modellieren?",
    free: true,
  },
  {
    id: "uml1-02",
    topic: "UML: Einführung und Anwendungsfalldiagramme",
    type: "mc",
    prompt: "Welche drei Diagrammfamilien unterscheidet UML grob?",
    options: [
      "Strukturdiagramme, Anwendungsfalldiagramm, Verhaltensdiagramme.",
      "Nur Klassendiagramme und Sequenzdiagramme.",
      "Datenflussdiagramme, ER-Diagramme, Flussdiagramme.",
      "Nur statische und dynamische Diagramme.",
    ],
    correctIndex: 0,
    explanation: "UML gliedert sich in Struktur-, Anwendungsfall- und Verhaltensdiagramme.",
    source: "Kapitel 11, UML-Diagrammarten im Überblick",
    free: true,
  },
  {
    id: "uml1-03",
    topic: "UML: Einführung und Anwendungsfalldiagramme",
    type: "mc",
    prompt:
      "In einer Fitnessstudio-Verwaltungssoftware gilt: Ein Trainer berechnet Mitgliedsbeiträge; die Studioleitung kann Mitglieder anmelden und deren Mitgliedschaft kündigen; die Kündigung eines Standortleiters ist eine Erweiterung des Anwendungsfalls 'Mitgliedschaft kündigen' unter der Bedingung, dass gegen diesen wiederholt begründete Beschwerden vorliegen; bei jeder Kündigung bzw. Anmeldung wird zusätzlich zwingend eine Mitgliederhistorie protokolliert. Welche UML-Beziehung modelliert den letzten Punkt (Mitgliederhistorie wird immer mit protokolliert)?",
    options: ["Eine include-Beziehung", "Eine extend-Beziehung", "Eine Generalisierung", "Eine Aggregation"],
    correctIndex: 0,
    explanation: "Da die Mitgliederliste zwingend bei jeder Ausführung mit erstellt wird, handelt es sich um eine include-Beziehung.",
    source: "Kapitel 11, include, extend und Generalisierung",
    free: false,
  },
  {
    id: "uml1-04",
    topic: "UML: Einführung und Anwendungsfalldiagramme",
    type: "mc",
    prompt: "Wodurch unterscheidet sich eine extend-Beziehung von einer include-Beziehung in einem Anwendungsfalldiagramm?",
    options: [
      "extend modelliert eine optionale Erweiterung unter einer Bedingung an einem benannten Erweiterungspunkt, include einen zwingend mit ausgeführten Teilschritt.",
      "Beide sind identisch.",
      "extend ist immer zwingend, include optional.",
      "Nur include kann Bedingungen enthalten.",
    ],
    correctIndex: 0,
    explanation: "extend ist die bedingte, optionale Erweiterung; include der obligatorische Teilschritt.",
    source: "Kapitel 11, include, extend und Generalisierung",
    free: false,
  },
  {
    id: "uml1-05",
    topic: "UML: Einführung und Anwendungsfalldiagramme",
    type: "mc",
    prompt: "Was bedeutet eine Generalisierungsbeziehung zwischen zwei Akteuren, z. B. einem Abteilungsleiter und einem gewöhnlichen Sachbearbeiter?",
    options: [
      "Der spezialisierte Akteur (Abteilungsleiter) übernimmt alle Anwendungsfälle des allgemeineren Akteurs und besitzt zusätzlich eigene.",
      "Beide Akteure sind völlig unabhängig voneinander.",
      "Der allgemeinere Akteur übernimmt die Anwendungsfälle des spezialisierten.",
      "Es gibt keine Beziehung zwischen den Anwendungsfällen beider Akteure.",
    ],
    correctIndex: 0,
    explanation: "Generalisierung bei Akteuren funktioniert wie Vererbung: der spezialisierte Akteur erbt die Anwendungsfälle des allgemeineren.",
    source: "Kapitel 11, include, extend und Generalisierung",
    free: false,
  },
  {
    id: "uml1-06",
    topic: "UML: Einführung und Anwendungsfalldiagramme",
    type: "mc",
    prompt: "Welche UML-Diagrammart eignet sich besonders für die Phase der Anforderungsermittlung?",
    options: ["Anwendungsfalldiagramme", "Klassendiagramme", "Sequenzdiagramme", "Zustandsdiagramme"],
    correctIndex: 0,
    explanation: "Anwendungsfalldiagramme geben die Außensicht auf ein System wieder und eignen sich daher für die Anforderungsermittlung.",
    source: "Kapitel 11, UML-Diagrammarten im Überblick",
    free: false,
  },

  // ---------- UML: Klassen- und Objektdiagramme ----------
  {
    id: "uml2-01",
    topic: "UML: Klassen- und Objektdiagramme",
    type: "mc",
    prompt: "Welche Sichtbarkeit wird durch das Symbol '#' vor einem Attribut in einem UML-Klassendiagramm ausgedrückt?",
    options: ["Geschützt (protected)", "Öffentlich (public)", "Privat (private)", "Paketsichtbar"],
    correctIndex: 0,
    explanation: "+ steht für öffentlich, − für privat, # für geschützt.",
    source: "Kapitel 12, Klassennotation: Attribute und Operationen",
    free: true,
  },
  {
    id: "uml2-02",
    topic: "UML: Klassen- und Objektdiagramme",
    type: "mc",
    prompt: "Worin unterscheiden sich Aggregation und Komposition in UML?",
    options: [
      "Bei der Komposition ist das Teil existenzabhängig vom Ganzen (Kardinalität am Ganzen muss 1 sein), bei der Aggregation besteht keine Existenzabhängigkeit.",
      "Aggregation wird durch eine ausgefüllte Raute dargestellt, Komposition durch eine leere.",
      "Beide sind identisch.",
      "Komposition erlaubt keine Kardinalitäten.",
    ],
    correctIndex: 0,
    explanation: "Existenzabhängigkeit ist der zentrale Unterschied: bei Komposition endet das Teil mit dem Ganzen, bei Aggregation nicht.",
    source: "Kapitel 12, Assoziation, Aggregation und Komposition",
    free: true,
  },
  {
    id: "uml2-03",
    topic: "UML: Klassen- und Objektdiagramme",
    type: "mc",
    prompt:
      "In einer Fahrschule implementiert die Klasse Fahrlehrer sowohl das Interface Pruefer (Methode abnehmen(kandidat:String)) als auch das Interface Angestellter (Methode unterrichten(stunden:int)). Warum bietet es sich an, Pruefer und Angestellter als separate Interfaces statt als eine gemeinsame Klasse zu modellieren?",
    options: [
      "Weil eine Person mehrere unabhängige Rollen gleichzeitig einnehmen kann (z. B. Angestellter und amtlich zugelassener Prüfer), und UML nur Mehrfachrealisierung von Interfaces, nicht aber Mehrfachvererbung von Klassen erlaubt.",
      "Weil Interfaces schneller ausgeführt werden als Klassen.",
      "Weil Attribute in Interfaces grundsätzlich verboten sind und deshalb jede Klasse mit Attributen zwingend ein Interface braucht.",
      "Weil UML für Klassen maximal eine Methode pro Klasse erlaubt.",
    ],
    correctIndex: 0,
    explanation: "Interfaces erlauben die flexible Kombination unabhängiger Rollen über Mehrfachrealisierung, was mit einfacher Klassenvererbung nicht ginge.",
    source: "Kapitel 12, Vererbung, abstrakte Klassen und Interfaces",
    free: false,
  },
  {
    id: "uml2-04",
    topic: "UML: Klassen- und Objektdiagramme",
    type: "mc",
    prompt: "Was unterscheidet eine abstrakte Klasse von einem Interface in UML?",
    options: [
      "Eine abstrakte Klasse kann Attribute und teilweise implementierte Operationen enthalten, ein Interface enthält ausschließlich Operationssignaturen ohne Attribute und ohne Implementierung.",
      "Beide sind identisch.",
      "Ein Interface kann instanziiert werden, eine abstrakte Klasse nicht.",
      "Nur abstrakte Klassen dürfen Methoden deklarieren.",
    ],
    correctIndex: 0,
    explanation: "Interfaces sind reine Signaturverträge; abstrakte Klassen können bereits teilweise Verhalten und Zustand mitbringen.",
    source: "Kapitel 12, Vererbung, abstrakte Klassen und Interfaces",
    free: false,
  },
  {
    id: "uml2-05",
    topic: "UML: Klassen- und Objektdiagramme",
    type: "mc",
    prompt: "Wie lässt sich Redundanz vermeiden, wenn mehrere Klassen dieselben Attribute (z. B. Name und Adresse) besitzen?",
    options: [
      "Indem die gemeinsamen Attribute in eine gemeinsame (ggf. abstrakte) Oberklasse ausgelagert werden, von der die spezialisierten Klassen erben.",
      "Indem jede Klasse die Attribute redundant selbst definiert.",
      "Indem alle Klassen zu einem einzigen Interface zusammengefasst werden.",
      "Redundanz lässt sich in UML grundsätzlich nicht vermeiden.",
    ],
    correctIndex: 0,
    explanation: "Vererbung aus einer gemeinsamen Oberklasse ist das Standardmittel zur Redundanzvermeidung.",
    source: "Kapitel 12, Assoziation, Aggregation und Komposition",
    free: false,
  },
  {
    id: "uml2-06",
    topic: "UML: Klassen- und Objektdiagramme",
    type: "mc",
    prompt: "Wie wird eine konkrete Instanz in einem UML-Objektdiagramm notiert?",
    options: [
      "Als Instanzname:Klassenname, unterstrichen, wobei Instanzname oder Klassenname auch weggelassen werden können.",
      "Als Klassenname(Instanzname) ohne Unterstreichung.",
      "Nur durch den Klassennamen ohne weitere Angaben.",
      "Als Zahl, die die Instanz eindeutig identifiziert.",
    ],
    correctIndex: 0,
    explanation: "Die unterstrichene Schreibweise Instanzname:Klassenname ist die Standardnotation für Objekte.",
    source: "Kapitel 12, Objektdiagramme",
    free: false,
  },
  {
    id: "uml2-07",
    topic: "UML: Klassen- und Objektdiagramme",
    type: "mc",
    prompt:
      "Ein Krankenhausverbund gliedert sich in mehrere Klinikstandorte: Jeder Standort hat genau eine Zentralapotheke, von der aus ein oder mehrere Stationsapotheken beliefert werden; jede Stationsapotheke versorgt wiederum fünf oder mehr Krankenzimmer mit Medikamenten. Zentralapotheken verschiedener Standorte tauschen bei Engpässen direkt untereinander Bestände aus. Welche UML-Kardinalität muss die Assoziation zwischen einer Zentralapotheke und ihren belieferten Stationsapotheken mindestens haben (auf Seite der Stationsapotheken)?",
    options: ["1..*", "0..1", "genau 1", "0..*"],
    correctIndex: 0,
    explanation: "'Ein oder mehrere' entspricht der Kardinalität 1..* (mindestens eins, beliebig viele).",
    source: "Kapitel 12, Assoziation, Aggregation und Komposition",
    free: false,
  },

  // ---------- UML: Verhaltensdiagramme ----------
  {
    id: "uml3-01",
    topic: "UML: Verhaltensdiagramme",
    type: "mc",
    prompt: "Wie wird ein synchroner Methodenaufruf in einem UML-Sequenzdiagramm von einem asynchronen unterschieden?",
    options: [
      "Synchron: durchgezogener Pfeil mit gefüllter Pfeilspitze; asynchron: offene Pfeilspitze.",
      "Synchron: gestrichelter Pfeil; asynchron: durchgezogener Pfeil.",
      "Es gibt keinen notationellen Unterschied.",
      "Nur asynchrone Aufrufe werden überhaupt dargestellt.",
    ],
    correctIndex: 0,
    explanation: "Die Pfeilspitze (gefüllt vs. offen) unterscheidet synchrone von asynchronen Aufrufen.",
    source: "Kapitel 13, Sequenzdiagramme: Lebenslinien und Nachrichten",
    free: true,
  },
  {
    id: "uml3-02",
    topic: "UML: Verhaltensdiagramme",
    type: "mc",
    prompt: "Welcher Sequenzdiagramm-Operator modelliert eine Wiederholung eines Ablaufs?",
    options: ["loop", "alt", "opt", "par"],
    correctIndex: 0,
    explanation: "loop steht für einen wiederholt ausgeführten Ablaufabschnitt.",
    source: "Kapitel 13, Kontrollstrukturen in Sequenzdiagrammen",
    free: true,
  },
  {
    id: "uml3-03",
    topic: "UML: Verhaltensdiagramme",
    type: "mc",
    prompt: "Welcher Operator stellt sicher, dass ein Ablauf als atomare, nicht unterbrechbare Einheit ausgeführt wird?",
    options: ["critical", "par", "strict", "opt"],
    correctIndex: 0,
    explanation: "critical markiert einen Ablauf, der nicht durch andere Nachrichten unterbrochen werden darf.",
    source: "Kapitel 13, Kontrollstrukturen in Sequenzdiagrammen",
    free: false,
  },
  {
    id: "uml3-04",
    topic: "UML: Verhaltensdiagramme",
    type: "mc",
    prompt: "Auf wessen Arbeit gehen UML-Zustandsdiagramme (Statecharts) zurück?",
    options: ["David Harel (1987)", "Grady Booch", "Ivar Jacobson", "James Rumbaugh"],
    correctIndex: 0,
    explanation: "David Harel stellte 1987 die Statecharts vor, die UML für Zustandsdiagramme adaptiert.",
    source: "Kapitel 13, Zustandsdiagramme",
    free: false,
  },
  {
    id: "uml3-05",
    topic: "UML: Verhaltensdiagramme",
    type: "mc",
    prompt: "Für welche Art von Verhalten sind Zustandsdiagramme schlecht geeignet?",
    options: [
      "Für kontinuierliches Verhalten, das sich nicht sinnvoll in eine endliche Anzahl diskreter Zustände zerlegen lässt.",
      "Für ereignisgesteuertes Verhalten.",
      "Für Verhalten mit klar abgrenzbaren Zuständen.",
      "Für hierarchisch verschachtelte Zustände.",
    ],
    correctIndex: 0,
    explanation: "Zustandsdiagramme setzen eine diskrete Zustandsmenge voraus und eignen sich daher nicht für kontinuierliches Verhalten.",
    source: "Kapitel 13, Zustandsdiagramme",
    free: false,
  },
  {
    id: "uml3-06",
    topic: "UML: Verhaltensdiagramme",
    type: "mc",
    prompt:
      "Bei einer Ruderregatta gibt es drei Akteure: Startrichter, Ruderer und Trainer am Ufer. Das Rennen beginnt mit dem Startsignal; danach misst der Startrichter die Zwischenzeiten, der Ruderer rudert, und der Trainer ruft Anweisungen über Funk zu — alle drei Aktivitäten beginnen gleichzeitig. Welches UML-Konstrukt modelliert diesen gleichzeitigen (parallelen) Start?",
    options: ["Ein Fork (paralleler Split) direkt nach dem Startschuss", "Eine Entscheidungsraute", "Ein Zustandsübergang", "Eine Swimlane ohne Fork"],
    correctIndex: 0,
    explanation: "Ein Fork spaltet den Kontrollfluss in mehrere parallel ablaufende Zweige auf.",
    source: "Kapitel 13, Aktivitätsdiagramme und Swimlanes",
    free: false,
  },
  {
    id: "uml3-07",
    topic: "UML: Verhaltensdiagramme",
    type: "mc",
    prompt: "Wozu dienen Swimlanes in einem Aktivitätsdiagramm?",
    options: [
      "Sie ordnen einzelne Aktivitäten den dafür verantwortlichen Akteuren oder Abteilungen zu.",
      "Sie ersetzen die Notwendigkeit von Entscheidungsrauten.",
      "Sie modellieren ausschließlich Zeitverläufe.",
      "Sie sind nur in Zustandsdiagrammen erlaubt.",
    ],
    correctIndex: 0,
    explanation: "Swimlanes strukturieren ein Aktivitätsdiagramm nach Verantwortlichkeit, ohne den Kontrollfluss selbst zu verändern.",
    source: "Kapitel 13, Aktivitätsdiagramme und Swimlanes",
    free: false,
  },
];
