export type QuestionType = "mc" | "numeric";

export interface Question {
  id: string;
  topic: string;
  type: QuestionType;
  prompt: string;
  options?: string[];
  correctIndex?: number;
  correctValue?: number;
  tolerance?: number;
  unit?: string;
  explanation: string;
  source: string;
  free: boolean;
}

// Hinweis: Die Übungsaufgaben in dieser Fragenbank orientieren sich der
// mathematischen Struktur nach an echten Tutoriumsblättern und
// Klausuraufgaben, sind aber in den konkreten Zahlenwerten/Matrizen
// gegenüber dem Original verändert (Regel 2). Ein eigenes Szenario
// (Kontext, Gegenstände, Namen, Branchen) musste hier nicht ausgetauscht
// werden, da es sich bei sämtlichen Aufgaben dieses Moduls um rein
// abstrakte, symbolische Aufgaben ohne konkretes Szenario handelt (reine
// Rechnungen mit komplexen Zahlen, Matrizen, Vektoren und Funktionen) —
// genau der in CLAUDE.md vorgesehene Ausnahmefall. Alle neuen Zahlenwerte
// wurden vor Aufnahme in diese Datei per Selbstcheck (Regel 4) gegen die
// Quell-PDFs abgeglichen. Ein Copyright-Audit (2 unabhängige Agenten,
// Juli 2026) hat zusätzlich die `examples`-Felder in
// lib/content/mathematik-2-semester.ts geprüft und dort eine zu enge
// Übernahme (Häufungspunkt-Gegenbeispiel, Kapitel 2) gefunden und durch
// eine eigenständige Konstruktion ersetzt — der Selbstcheck deckt seither
// nachweislich auch die Skript-Beispiele ab, nicht nur diese Fragenbank.
export const TOPICS = [
  "Grundrechenarten und Betrag komplexer Zahlen",
  "Polarform, Eulersche Formel und n-te Wurzeln",
  "Komplexe Gleichungssysteme",
  "Folgen und Reihen komplexer Zahlen",
  "Konvergenz von Folgen im Rⁿ",
  "Häufungspunkte und Teilfolgen",
  "Die Determinante als multilineare alternierende Abbildung",
  "Laplace-Entwicklung und Permutationen",
  "Rechenregeln für Determinanten",
  "Basisdarstellung linearer Abbildungen",
  "Basiswechsel und Transformationsmatrizen",
  "Kern, Bild und die Dimensionsformel",
  "Charakteristisches Polynom und Eigenwerte",
  "Eigenräume und Vielfachheiten",
  "Diagonalisierbarkeit",
  "Quadratische Formen und Definitheit",
  "Kriterien für Definitheit",
  "Normen und Normäquivalenz",
  "Skalarprodukte und die Cauchy-Schwarz-Ungleichung",
  "Orthogonalität, Gram-Schmidt-Verfahren und Projektionen",
  "Grenzwerte und Stetigkeit im Rⁿ",
  "Nachweis von Unstetigkeit und stetige Fortsetzung",
  "Gradient und Richtungsableitung",
  "Tangentialebene",
] as const;

export const questions: Question[] = [
  // ---------- Grundrechenarten und Betrag komplexer Zahlen ----------
  {
    id: "kz-01",
    topic: "Grundrechenarten und Betrag komplexer Zahlen",
    type: "mc",
    prompt: "Für z1 = 2+3i und z2 = 4−i: Was ist z1 · z2?",
    options: ["11 + 10i", "8 − 3i", "5 + 2i", "11 − 10i"],
    correctIndex: 0,
    explanation: "z1·z2 = (2·4 − 3·(−1)) + i(2·(−1)+3·4) = (8+3) + i(−2+12) = 11+10i.",
    source: "Kapitel 1.1, nach 1./2. Tutoriumsblatt",
    free: true,
  },
  {
    id: "kz-02",
    topic: "Grundrechenarten und Betrag komplexer Zahlen",
    type: "numeric",
    prompt: "Berechnen Sie den Betrag |z| von z = 2+3i.",
    correctValue: 3.6056,
    tolerance: 0.01,
    explanation: "|z| = √(2²+3²) = √13 ≈ 3,606.",
    source: "Kapitel 1.1, Betrag",
    free: false,
  },
  {
    id: "kz-03",
    topic: "Grundrechenarten und Betrag komplexer Zahlen",
    type: "mc",
    prompt: "Für z3 = 5−2i und z4 = 1+i: Was ist z3/z4?",
    options: ["1,5 − 3,5i", "3 − i", "1,5 + 3,5i", "3 + i"],
    correctIndex: 0,
    explanation: "Erweitern mit z̄4=1−i: z3/z4 = (5−2i)(1−i)/((1)²+1²) = (5−5i−2i+2i²)/2 = (3−7i)/2 = 1,5−3,5i.",
    source: "Kapitel 1.1, Division komplexer Zahlen",
    free: false,
  },

  // ---------- Polarform, Eulersche Formel und n-te Wurzeln ----------
  {
    id: "pf-01",
    topic: "Polarform, Eulersche Formel und n-te Wurzeln",
    type: "mc",
    prompt: "Welche der drei dritten Wurzeln von w = −27 ist rein reell?",
    options: ["−3", "3", "1,5 + 2,6i", "−1,5 − 2,6i"],
    correctIndex: 0,
    explanation: "Mit w=27·e^(iπ) sind die dritten Wurzeln 3·e^(i(π+2πk)/3) für k=0,1,2. Für k=1 ergibt sich 3·e^(iπ)=−3 — die einzige reelle der drei Wurzeln.",
    source: "Kapitel 1.2, nach 2. Tutoriumsblatt",
    free: false,
  },
  {
    id: "pf-02",
    topic: "Polarform, Eulersche Formel und n-te Wurzeln",
    type: "numeric",
    prompt: "Wie viele verschiedene komplexe Lösungen hat die Gleichung z⁵ = 32i?",
    correctValue: 5,
    explanation: "Für zⁿ = w ≠ 0 gibt es stets genau n verschiedene komplexe Lösungen (gleichmäßig verteilt auf einem Kreis) — hier also 5.",
    source: "Kapitel 1.2, n-te Wurzeln",
    free: false,
  },
  {
    id: "pf-03",
    topic: "Polarform, Eulersche Formel und n-te Wurzeln",
    type: "mc",
    prompt: "z = 4·e^(iπ/3) und w = 2·e^(iπ/6). Was ist z·w in Polarform?",
    options: ["8·e^(iπ/2)", "2·e^(iπ/2)", "8·e^(iπ/6)", "6·e^(iπ/3)"],
    correctIndex: 0,
    explanation: "Beträge werden multipliziert (4·2=8), Winkel addiert (π/3+π/6=π/2): z·w=8·e^(iπ/2).",
    source: "Kapitel 1.2, Multiplikation in Polarform",
    free: false,
  },

  // ---------- Komplexe Gleichungssysteme ----------
  {
    id: "kg-01",
    topic: "Komplexe Gleichungssysteme",
    type: "mc",
    prompt: "Lösen Sie (2+i)x + 3y = 7+i und x + (1−i)y = 3 nach x. Welcher Wert stimmt?",
    options: ["x = 6 − i", "x = 6 + i", "x = 3 − i", "x = −2 − i"],
    correctIndex: 0,
    explanation: "Auflösen des Systems (Einsetzen/Elimination in ℂ) liefert x=6−i und y=−2−i. Probe: (2+i)(6−i)+3(−2−i)=12+4i+1−6−3i=7+i ✓.",
    source: "Kapitel 1.3, nach 2. Tutoriumsblatt (komplexe LGS)",
    free: false,
  },
  {
    id: "kg-02",
    topic: "Komplexe Gleichungssysteme",
    type: "numeric",
    prompt: "Beim selben System wie oben ((2+i)x+3y=7+i, x+(1−i)y=3): Wie groß ist Re(y)?",
    correctValue: -2,
    explanation: "Die Lösung ist y = −2−i, also Re(y) = −2.",
    source: "Kapitel 1.3, komplexe LGS",
    free: false,
  },
  {
    id: "kg-03",
    topic: "Komplexe Gleichungssysteme",
    type: "mc",
    prompt: "Beim Lösen eines linearen Gleichungssystems mit komplexen Koeffizienten mittels Gauß-Algorithmus gilt:",
    options: [
      "Alle Umformungsregeln aus dem Reellen gelten unverändert, nur mit komplexen Rechenoperationen.",
      "Zeilenvertauschungen sind bei komplexen Koeffizienten nicht erlaubt.",
      "Man muss zuerst alle Gleichungen komplex konjugieren.",
      "Der Gauß-Algorithmus funktioniert nur, wenn alle Koeffizienten reell sind.",
    ],
    correctIndex: 0,
    explanation: "Der Gauß-Algorithmus überträgt sich unverändert auf ℂ — alle elementaren Zeilenumformungen bleiben gültig, nur die Arithmetik findet in ℂ statt.",
    source: "Kapitel 1.3, Gauß-Algorithmus in ℂ",
    free: false,
  },

  // ---------- Folgen und Reihen komplexer Zahlen ----------
  {
    id: "kf-01",
    topic: "Folgen und Reihen komplexer Zahlen",
    type: "numeric",
    prompt: "Gegen welchen (reellen) Grenzwert konvergiert zₙ = (3n−i)/(n+2i) für n→∞?",
    correctValue: 3,
    explanation: "Für große n dominieren die Terme mit n: zₙ ≈ 3n/n = 3. Formal folgt dies aus Re(zₙ)→3 und Im(zₙ)→0.",
    source: "Kapitel 1.4, Folgengrenzwert",
    free: true,
  },
  {
    id: "kf-02",
    topic: "Folgen und Reihen komplexer Zahlen",
    type: "numeric",
    prompt: "Welchen Konvergenzradius R hat die Potenzreihe Σ (2+i)ⁿ·zⁿ?",
    correctValue: 0.4472,
    tolerance: 0.01,
    explanation: "Für Σ cⁿzⁿ mit c=2+i ist R=1/|c|=1/√5≈0,447.",
    source: "Kapitel 1.4, Konvergenzradius (nach 3. Tutoriumsblatt)",
    free: false,
  },
  {
    id: "kf-03",
    topic: "Folgen und Reihen komplexer Zahlen",
    type: "mc",
    prompt: "Eine Folge komplexer Zahlen (zₙ) konvergiert genau dann gegen z, wenn:",
    options: [
      "Re(zₙ)→Re(z) und Im(zₙ)→Im(z)",
      "nur |zₙ|→|z| gilt",
      "nur Re(zₙ)→Re(z) gilt",
      "zₙ eine Cauchy-Folge in ℝ ist",
    ],
    correctIndex: 0,
    explanation: "Konvergenz in ℂ ist äquivalent zur getrennten Konvergenz von Real- und Imaginärteil.",
    source: "Kapitel 1.4, Konvergenzkriterium",
    free: false,
  },

  // ---------- Konvergenz von Folgen im Rⁿ ----------
  {
    id: "fn-01",
    topic: "Konvergenz von Folgen im Rⁿ",
    type: "mc",
    prompt: "Gegen welchen Vektor konvergiert ⃗xₖ = (3/k, (2k−1)/k) für k→∞?",
    options: ["(0, 2)", "(0, 1)", "(3, 2)", "(1, 2)"],
    correctIndex: 0,
    explanation: "Komponentenweise: 3/k→0 und (2k−1)/k=2−1/k→2. Also ⃗xₖ→(0,2).",
    source: "Kapitel 2.1, Konvergenz im Rⁿ",
    free: false,
  },
  {
    id: "fn-02",
    topic: "Konvergenz von Folgen im Rⁿ",
    type: "mc",
    prompt: "Eine Folge (⃗xₖ) im ℝⁿ konvergiert gegen ⃗x. Welche Aussage ist richtig?",
    options: [
      "Jede Komponentenfolge konvergiert gegen die entsprechende Komponente von ⃗x.",
      "Nur die erste Komponentenfolge muss konvergieren.",
      "Die Folge muss monoton sein.",
      "Konvergenz im ℝⁿ hängt von der gewählten Norm ab.",
    ],
    correctIndex: 0,
    explanation: "Konvergenz einer Vektorfolge ist äquivalent zur komponentenweisen Konvergenz; welche (äquivalente) Norm man zur Definition nutzt, ändert daran nichts.",
    source: "Kapitel 2.1, komponentenweise Konvergenz",
    free: false,
  },
  {
    id: "fn-03",
    topic: "Konvergenz von Folgen im Rⁿ",
    type: "numeric",
    prompt: "Für ⃗yₖ = ((k+3)/k, 5/k²): Gegen welchen Wert konvergiert die erste Komponente?",
    correctValue: 1,
    explanation: "(k+3)/k = 1+3/k → 1 für k→∞.",
    source: "Kapitel 2.1, Konvergenz im Rⁿ",
    free: false,
  },

  // ---------- Häufungspunkte und Teilfolgen ----------
  {
    id: "hp-01",
    topic: "Häufungspunkte und Teilfolgen",
    type: "mc",
    prompt: "Die Folge ⃗cₖ = ((−1)ᵏ·2, k/(k+2)) hat welche Häufungspunkte?",
    options: ["(2,1) und (−2,1)", "nur (2,1)", "(2,0) und (−2,0)", "keine, die Folge divergiert ohne Häufungspunkte"],
    correctIndex: 0,
    explanation: "Für gerade k ist (−1)ᵏ=1, und k/(k+2)→1, also Teilfolge → (2,1). Für ungerade k analog → (−2,1). Beides sind Häufungspunkte.",
    source: "Kapitel 2.2, nach 4. Tutoriumsblatt (Häufungspunkte)",
    free: false,
  },
  {
    id: "hp-02",
    topic: "Häufungspunkte und Teilfolgen",
    type: "mc",
    prompt: "Ist a Häufungspunkt von (aₖ) und b Häufungspunkt von (bₖ), folgt daraus zwingend, dass (a,b) Häufungspunkt der Folge ((aₖ,bₖ)) ist?",
    options: [
      "Nein — es müssen dieselben Indizes gleichzeitig gegen a bzw. b konvergieren.",
      "Ja, das folgt immer direkt aus der Definition.",
      "Ja, aber nur wenn beide Folgen monoton sind.",
      "Nein, Häufungspunkte im ℝⁿ existieren generell nicht für Paare.",
    ],
    correctIndex: 0,
    explanation: "Die Umkehrung gilt nicht: Es kann sein, dass a und b je für sich Häufungspunkte ihrer Folgen sind, aber niemals zur gleichen Zeit (also für dieselben Indizes k) gleichzeitig nahe a bzw. b liegen.",
    source: "Kapitel 2.2, Häufungspunkte von Produktfolgen",
    free: false,
  },
  {
    id: "hp-03",
    topic: "Häufungspunkte und Teilfolgen",
    type: "numeric",
    prompt: "Wie viele Häufungspunkte kann eine konvergente Folge im ℝⁿ höchstens haben?",
    correctValue: 1,
    explanation: "Eine konvergente Folge hat genau einen Häufungspunkt — ihren Grenzwert.",
    source: "Kapitel 2.2, Häufungspunkte",
    free: false,
  },

  // ---------- Die Determinante als multilineare alternierende Abbildung ----------
  {
    id: "da-01",
    topic: "Die Determinante als multilineare alternierende Abbildung",
    type: "mc",
    prompt: "D sei eine Determinantenform mit D(⃗a1,⃗a2)=4. Für ⃗b1=2⃗a1+3⃗a2 und ⃗b2=⃗a1−⃗a2 gilt D(⃗b1,⃗b2)=?",
    options: ["−20", "20", "−5", "8"],
    correctIndex: 0,
    explanation: "Mit Multilinearität und Alternierung: D(⃗b1,⃗b2)=D(2⃗a1+3⃗a2,⃗a1−⃗a2)=2D(⃗a1,⃗a1)−2D(⃗a1,⃗a2)+3D(⃗a2,⃗a1)−3D(⃗a2,⃗a2)=0−2·4−3·4−0=−8−12=−20.",
    source: "Kapitel 3.1, Determinantenform (abstrakt)",
    free: true,
  },
  {
    id: "da-02",
    topic: "Die Determinante als multilineare alternierende Abbildung",
    type: "mc",
    prompt: "Was folgt für eine Determinantenform D, wenn zwei ihrer Argumente linear abhängig sind?",
    options: ["D = 0", "D ist maximal", "D wechselt nur das Vorzeichen", "D bleibt unbestimmt"],
    correctIndex: 0,
    explanation: "Aus der alternierenden Eigenschaft folgt direkt: Sind zwei Argumente linear abhängig, ist D=0.",
    source: "Kapitel 3.1, Eigenschaften der Determinantenform",
    free: false,
  },
  {
    id: "da-03",
    topic: "Die Determinante als multilineare alternierende Abbildung",
    type: "mc",
    prompt: "Zwei Determinantenformen D1, D2 auf ℝⁿ unterscheiden sich stets:",
    options: [
      "um einen konstanten Faktor λ ∈ ℝ",
      "sie sind immer identisch",
      "nur im Vorzeichen",
      "sie können beliebig verschieden sein, ohne Zusammenhang",
    ],
    correctIndex: 0,
    explanation: "Je zwei Determinantenformen auf ℝⁿ sind bis auf einen festen skalaren Faktor gleich — das folgt aus der (bis auf diesen Faktor eindeutigen) axiomatischen Charakterisierung.",
    source: "Kapitel 3.1, Eindeutigkeit der Determinantenform",
    free: false,
  },

  // ---------- Laplace-Entwicklung und Permutationen ----------
  {
    id: "le-01",
    topic: "Laplace-Entwicklung und Permutationen",
    type: "numeric",
    prompt: "Berechnen Sie det(A) für A = [[1,2,1],[3,0,2],[1,1,4]].",
    correctValue: -19,
    explanation: "Entwicklung nach der zweiten Zeile (mittlerer Eintrag 0 spart Arbeit): det(A) = −3·det([[2,1],[1,4]]) + 0 − 2·det([[1,2],[1,1]]) = −3·7 − 2·(−1) = −21+2 = −19.",
    source: "Kapitel 3.2, Laplace-Entwicklung (nach 1. Tutoriumsblatt)",
    free: false,
  },
  {
    id: "le-02",
    topic: "Laplace-Entwicklung und Permutationen",
    type: "numeric",
    prompt: "Berechnen Sie det(A) für A = [[2,0,3],[1,4,1],[3,2,0]].",
    correctValue: -34,
    explanation: "Entwicklung nach der ersten Zeile: det(A) = 2·det([[4,1],[2,0]]) − 0 + 3·det([[1,4],[3,2]]) = 2·(0−2) + 3·(2−12) = −4 − 30 = −34.",
    source: "Kapitel 3.2, Laplace-Entwicklung",
    free: false,
  },
  {
    id: "le-03",
    topic: "Laplace-Entwicklung und Permutationen",
    type: "mc",
    prompt: "Für die Permutation π mit π(1,2,3,4) = (2,4,1,3): Wie viele Fehlstände (Inversionen) hat π, und welches Signum ergibt sich?",
    options: ["3 Fehlstände, sgn(π) = −1", "2 Fehlstände, sgn(π) = +1", "4 Fehlstände, sgn(π) = +1", "1 Fehlstand, sgn(π) = −1"],
    correctIndex: 0,
    explanation: "Fehlstände (i<j mit π(i)>π(j)): (1,3): 2>1 ✓, (2,3): 4>1 ✓, (2,4): 4>3 ✓ — macht 3 Fehlstände, also sgn(π)=(−1)³=−1.",
    source: "Kapitel 3.2, Signum einer Permutation",
    free: false,
  },

  // ---------- Rechenregeln für Determinanten ----------
  {
    id: "rd-01",
    topic: "Rechenregeln für Determinanten",
    type: "numeric",
    prompt: "Für A = [[3,1],[2,4]] mit det(A)=10: Wie groß ist det(3A)?",
    correctValue: 90,
    explanation: "det(cA)=cⁿ·det(A) mit c=3, n=2: det(3A)=3²·10=9·10=90.",
    source: "Kapitel 3.3, det(cA)=cⁿdet(A)",
    free: false,
  },
  {
    id: "rd-02",
    topic: "Rechenregeln für Determinanten",
    type: "numeric",
    prompt: "Für dieselbe Matrix A=[[3,1],[2,4]] (det(A)=10): Wie groß ist det(A⁻¹)?",
    correctValue: 0.1,
    explanation: "det(A⁻¹) = 1/det(A) = 1/10 = 0,1.",
    source: "Kapitel 3.3, det(A⁻¹)=1/det(A)",
    free: false,
  },
  {
    id: "rd-03",
    topic: "Rechenregeln für Determinanten",
    type: "numeric",
    prompt: "Für die Blockdiagonalmatrix M mit Blöcken B1=[[3,2],[1,4]] (det=10) und B2=[[2,1],[3,5]] (det=7): Wie groß ist det(M)?",
    correctValue: 70,
    explanation: "Für Blockdiagonalmatrizen gilt det(M)=det(B1)·det(B2)=10·7=70.",
    source: "Kapitel 3.3, Blockdiagonalmatrix",
    free: false,
  },

  // ---------- Basisdarstellung linearer Abbildungen ----------
  {
    id: "bd-01",
    topic: "Basisdarstellung linearer Abbildungen",
    type: "mc",
    prompt: "Eine lineare Abbildung f: ℝ²→ℝ² erfüllt f(⃗e1)=(2,3) und f(⃗e2)=(1,−1). Was ist f((4,2))?",
    options: ["(10, 10)", "(6, 4)", "(8, 6)", "(9, 8)"],
    correctIndex: 0,
    explanation: "Darstellungsmatrix bzgl. Standardbasis: A=[[2,1],[3,−1]]. f((4,2))=A·(4,2)=(2·4+1·2, 3·4+(−1)·2)=(10,10).",
    source: "Kapitel 4.1, Darstellungsmatrix",
    free: false,
  },
  {
    id: "bd-02",
    topic: "Basisdarstellung linearer Abbildungen",
    type: "mc",
    prompt: "Was enthält die j-te Spalte der Darstellungsmatrix M_{B,A}(f)?",
    options: [
      "die Koordinaten von f(⃗aⱼ) bzgl. der Basis B",
      "die Koordinaten von ⃗aⱼ bzgl. der Basis B",
      "die Eigenwerte von f",
      "die Koeffizienten des charakteristischen Polynoms",
    ],
    correctIndex: 0,
    explanation: "Per Definition der Darstellungsmatrix steht in Spalte j gerade der Koordinatenvektor von f(⃗aⱼ) bezüglich der Basis B des Bildraums.",
    source: "Kapitel 4.1, Definition der Darstellungsmatrix",
    free: false,
  },
  {
    id: "bd-03",
    topic: "Basisdarstellung linearer Abbildungen",
    type: "mc",
    prompt: "Sind A und B jeweils die Standardbasis von ℝⁿ bzw. ℝᵐ, dann gilt für die Darstellungsmatrix M_{B,A}(f):",
    options: [
      "Sie stimmt mit der gewöhnlichen Matrix von f überein (Spalten = f(⃗eⱼ)).",
      "Sie ist stets die Einheitsmatrix.",
      "Sie existiert nur, wenn f bijektiv ist.",
      "Sie hat andere Einträge als die gewöhnliche Matrix von f.",
    ],
    correctIndex: 0,
    explanation: "Bei Standardbasen fällt die Darstellungsmatrix mit der gewöhnlichen Abbildungsmatrix zusammen.",
    source: "Kapitel 4.1, Standardbasis-Spezialfall",
    free: false,
  },

  // ---------- Basiswechsel und Transformationsmatrizen ----------
  {
    id: "bw-01",
    topic: "Basiswechsel und Transformationsmatrizen",
    type: "mc",
    prompt: "Basis B̃={⃗v1,⃗v2} mit ⃗v1=(2,1), ⃗v2=(1,1). Welche Koordinaten hat ⃗x=(5,3) bezüglich B̃?",
    options: ["(2, 1)", "(1, 2)", "(3, 1)", "(2, 3)"],
    correctIndex: 0,
    explanation: "Man löst V·⃗c=⃗x mit V=[[2,1],[1,1]]: 2c1+c2=5, c1+c2=3 ⟹ c1=2, c2=1. Probe: 2·(2,1)+1·(1,1)=(4,2)+(1,1)=(5,3) ✓.",
    source: "Kapitel 4.2, Basiswechsel (nach 3. Tutoriumsblatt)",
    free: false,
  },
  {
    id: "bw-02",
    topic: "Basiswechsel und Transformationsmatrizen",
    type: "mc",
    prompt: "V sei die Matrix, deren Spalten die Vektoren einer Basis B̃ des ℝⁿ sind. Wie rechnet man Standardkoordinaten ⃗x in Koordinaten bzgl. B̃ um?",
    options: ["Koordinaten bzgl. B̃ = V⁻¹·⃗x", "Koordinaten bzgl. B̃ = V·⃗x", "Koordinaten bzgl. B̃ = Vᵀ·⃗x", "Koordinaten bzgl. B̃ = det(V)·⃗x"],
    correctIndex: 0,
    explanation: "Da ⃗x = V·(Koordinaten bzgl. B̃), erhält man die Koordinaten bzgl. B̃ durch Anwenden von V⁻¹ auf ⃗x.",
    source: "Kapitel 4.2, Transformationsmatrix",
    free: false,
  },
  {
    id: "bw-03",
    topic: "Basiswechsel und Transformationsmatrizen",
    type: "mc",
    prompt: "Welche Voraussetzung muss die Matrix V erfüllen, deren Spalten die Basis B̃ bilden, damit ein Basiswechsel überhaupt möglich ist?",
    options: ["V muss invertierbar sein.", "V muss symmetrisch sein.", "V muss eine Diagonalmatrix sein.", "V muss positiv definit sein."],
    correctIndex: 0,
    explanation: "Nur wenn V invertierbar ist (äquivalent: die Spalten sind tatsächlich eine Basis), existiert V⁻¹ und der Basiswechsel ist eindeutig durchführbar.",
    source: "Kapitel 4.2, Voraussetzung für Basiswechsel",
    free: false,
  },

  // ---------- Kern, Bild und die Dimensionsformel ----------
  {
    id: "kb-01",
    topic: "Kern, Bild und die Dimensionsformel",
    type: "mc",
    prompt: "Für f: ℝ³→ℝ² mit Darstellungsmatrix A=[[1,2,1],[2,4,3]]: Welcher Vektor spannt Kern(f) auf?",
    options: ["(−2, 1, 0)", "(2, −1, 0)", "(1, 2, 1)", "(0, 1, −2)"],
    correctIndex: 0,
    explanation: "A·(−2,1,0) = (1·(−2)+2·1+1·0, 2·(−2)+4·1+3·0) = (0,0) — also liegt (−2,1,0) im Kern; da Rang(A)=2, ist dim(Kern)=1, also Kern(f)=span{(−2,1,0)}.",
    source: "Kapitel 4.3, Kernberechnung (nach 3. Tutoriumsblatt)",
    free: false,
  },
  {
    id: "kb-02",
    topic: "Kern, Bild und die Dimensionsformel",
    type: "numeric",
    prompt: "Für dieselbe Abbildung f: ℝ³→ℝ² wie oben (Rang(A)=2): Wie groß ist dim(Kern(f))?",
    correctValue: 1,
    explanation: "Dimensionsformel: dim(ℝ³)=Rang(f)+dim(Kern(f)) ⟹ 3=2+dim(Kern(f)) ⟹ dim(Kern(f))=1.",
    source: "Kapitel 4.3, Dimensionsformel",
    free: false,
  },
  {
    id: "kb-03",
    topic: "Kern, Bild und die Dimensionsformel",
    type: "mc",
    prompt: "Welche Aussage über Kern(f) einer linearen Abbildung f: V→W ist korrekt?",
    options: [
      "Kern(f) ist stets ein Untervektorraum von V.",
      "Kern(f) ist stets ein Untervektorraum von W.",
      "Kern(f) enthält niemals den Nullvektor.",
      "Kern(f) ist nur definiert, wenn f injektiv ist.",
    ],
    correctIndex: 0,
    explanation: "Kern(f)={⃗x∈V: f(⃗x)=⃗0} ist immer ein Untervektorraum von V (Summen und Vielfache von Kernelementen bleiben im Kern).",
    source: "Kapitel 4.3, Kern als Untervektorraum",
    free: false,
  },

  // ---------- Charakteristisches Polynom und Eigenwerte ----------
  {
    id: "ce-01",
    topic: "Charakteristisches Polynom und Eigenwerte",
    type: "mc",
    prompt: "A = [[4,−1],[2,1]]. Welche Eigenwerte hat A?",
    options: ["3 und 2", "4 und 1", "5 und 0", "3 und −2"],
    correctIndex: 0,
    explanation: "PA(λ)=det(A−λE)=(4−λ)(1−λ)+2=λ²−5λ+6=(λ−3)(λ−2). Eigenwerte: 3 und 2.",
    source: "Kapitel 5.1, charakteristisches Polynom (nach 4. Tutoriumsblatt)",
    free: true,
  },
  {
    id: "ce-02",
    topic: "Charakteristisches Polynom und Eigenwerte",
    type: "mc",
    prompt: "Für dieselbe Matrix A=[[4,−1],[2,1]]: Welcher Vektor ist Eigenvektor zum Eigenwert λ=3?",
    options: ["(1, 1)", "(1, 2)", "(2, 1)", "(−1, 1)"],
    correctIndex: 0,
    explanation: "A·(1,1)=(4−1,2+1)=(3,3)=3·(1,1) ✓ — (1,1) ist Eigenvektor zu λ=3.",
    source: "Kapitel 5.1, Eigenvektor-Berechnung",
    free: false,
  },
  {
    id: "ce-03",
    topic: "Charakteristisches Polynom und Eigenwerte",
    type: "mc",
    prompt: "Für eine reelle Matrix B tritt der komplexe Eigenwert 2i auf. Welche weitere Aussage ist zwingend korrekt?",
    options: [
      "Auch −2i ist Eigenwert von B (konjugiert komplexes Paar).",
      "B kann keine reellen Eigenwerte mehr haben.",
      "B ist automatisch nicht diagonalisierbar.",
      "B muss eine 4×4-Matrix sein.",
    ],
    correctIndex: 0,
    explanation: "Da das charakteristische Polynom einer reellen Matrix reelle Koeffizienten hat, treten komplexe Nullstellen stets in konjugiert komplexen Paaren auf.",
    source: "Kapitel 5.1, komplexe Eigenwerte reeller Matrizen",
    free: false,
  },

  // ---------- Eigenräume und Vielfachheiten ----------
  {
    id: "ev-01",
    topic: "Eigenräume und Vielfachheiten",
    type: "mc",
    prompt: "Für E = [[3,1],[0,3]]: Welche algebraische und geometrische Vielfachheit hat der Eigenwert λ=3?",
    options: ["algebraisch 2, geometrisch 1", "algebraisch 1, geometrisch 1", "algebraisch 2, geometrisch 2", "algebraisch 1, geometrisch 2"],
    correctIndex: 0,
    explanation: "PE(λ)=(3−λ)², also algebraische Vielfachheit 2. Eig(E;3)=Kern([[0,1],[0,0]])=span{(1,0)}, also geometrische Vielfachheit 1 < 2 — E ist defekt.",
    source: "Kapitel 5.2, Vielfachheiten (nach 4. Tutoriumsblatt)",
    free: false,
  },
  {
    id: "ev-02",
    topic: "Eigenräume und Vielfachheiten",
    type: "mc",
    prompt: "Welche Ungleichung gilt stets zwischen algebraischer und geometrischer Vielfachheit eines Eigenwerts λ?",
    options: [
      "1 ≤ geometrische Vielfachheit ≤ algebraische Vielfachheit",
      "geometrische Vielfachheit ≥ algebraische Vielfachheit",
      "geometrische Vielfachheit = algebraische Vielfachheit immer",
      "algebraische Vielfachheit ≤ 1 immer",
    ],
    correctIndex: 0,
    explanation: "Die geometrische Vielfachheit liegt stets zwischen 1 und der algebraischen Vielfachheit (nie darüber).",
    source: "Kapitel 5.2, Ungleichung der Vielfachheiten",
    free: false,
  },
  {
    id: "ev-03",
    topic: "Eigenräume und Vielfachheiten",
    type: "mc",
    prompt: "Was ist der Eigenraum Eig(A;λ) formal definiert als?",
    options: ["Kern(A−λE)", "Bild(A−λE)", "Kern(A)", "das charakteristische Polynom von A"],
    correctIndex: 0,
    explanation: "Eig(A;λ) = {⃗v : A⃗v=λ⃗v} = {⃗v : (A−λE)⃗v=⃗0} = Kern(A−λE).",
    source: "Kapitel 5.2, Definition Eigenraum",
    free: false,
  },

  // ---------- Diagonalisierbarkeit ----------
  {
    id: "dg-01",
    topic: "Diagonalisierbarkeit",
    type: "mc",
    prompt: "A=[[4,−1],[2,1]] hat die Eigenwerte 3 und 2 mit Eigenvektoren (1,1) bzw. (1,2). Für S=[[1,1],[1,2]] gilt S⁻¹AS = ?",
    options: ["diag(3,2)", "diag(2,3)", "[[3,1],[0,2]]", "A selbst"],
    correctIndex: 0,
    explanation: "Da die Spalten von S Eigenvektoren zu den Eigenwerten 3 (erste Spalte) und 2 (zweite Spalte) sind, gilt S⁻¹AS=diag(3,2).",
    source: "Kapitel 5.3, Diagonalisierung",
    free: false,
  },
  {
    id: "dg-02",
    topic: "Diagonalisierbarkeit",
    type: "mc",
    prompt: "Eine n×n-Matrix A hat n paarweise verschiedene Eigenwerte. Was folgt daraus?",
    options: [
      "A ist automatisch diagonalisierbar.",
      "A ist automatisch defekt.",
      "A hat keinen Eigenwert 0.",
      "A ist automatisch symmetrisch.",
    ],
    correctIndex: 0,
    explanation: "Bei n verschiedenen Eigenwerten ist jede algebraische Vielfachheit 1, also auch die geometrische — Diagonalisierbarkeit folgt automatisch.",
    source: "Kapitel 5.3, hinreichendes Kriterium",
    free: false,
  },
  {
    id: "dg-03",
    topic: "Diagonalisierbarkeit",
    type: "mc",
    prompt: "Matrix G=[[0,−4],[1,0]] hat die Eigenwerte ±2i. Welcher Vektor ist Eigenvektor zu λ=2i?",
    options: ["(2i, 1)", "(1, 2i)", "(2, i)", "(1, −2i)"],
    correctIndex: 0,
    explanation: "(G−2iE)=[[−2i,−4],[1,−2i]]. Aus der zweiten Zeile folgt v1=2i·v2; mit v2=1 ergibt sich v1=2i, also Eigenvektor (2i,1). Probe: G·(2i,1)=(−4, 2i)=2i·(2i,1) ✓ (da 2i·2i=−4).",
    source: "Kapitel 5.3, komplexe Diagonalisierung",
    free: false,
  },

  // ---------- Quadratische Formen und Definitheit ----------
  {
    id: "qf-01",
    topic: "Quadratische Formen und Definitheit",
    type: "numeric",
    prompt: "Für C=[[5,2],[2,5]] und ⃗x=(2,−1): Berechnen Sie q(⃗x)=⃗xᵀC⃗x.",
    correctValue: 17,
    explanation: "q(2,−1) = 5·2²+2·2·2·(−1)+5·(−1)² = 20−8+5 = 17.",
    source: "Kapitel 6.1, quadratische Form",
    free: false,
  },
  {
    id: "qf-02",
    topic: "Quadratische Formen und Definitheit",
    type: "mc",
    prompt: "C=[[5,2],[2,5]] hat die Eigenwerte 7 und 3. Welche Definitheit liegt vor?",
    options: ["positiv definit", "negativ definit", "indefinit", "positiv semidefinit, aber nicht definit"],
    correctIndex: 0,
    explanation: "Beide Eigenwerte sind positiv (7 und 3) — nach dem Eigenwertkriterium ist C positiv definit.",
    source: "Kapitel 6.1, Eigenwertkriterium",
    free: false,
  },
  {
    id: "qf-03",
    topic: "Quadratische Formen und Definitheit",
    type: "mc",
    prompt: "Wann heißt eine symmetrische Matrix C indefinit?",
    options: [
      "wenn q(⃗x)=⃗xᵀC⃗x sowohl positive als auch negative Werte annimmt",
      "wenn q(⃗x) für alle ⃗x gleich 0 ist",
      "wenn C nicht symmetrisch ist",
      "wenn alle Eigenwerte von C gleich sind",
    ],
    correctIndex: 0,
    explanation: "Indefinit bedeutet, dass die quadratische Form sowohl positive als auch negative Werte liefert (äquivalent: C hat sowohl positive als auch negative Eigenwerte).",
    source: "Kapitel 6.1, Definition indefinit",
    free: false,
  },

  // ---------- Kriterien für Definitheit ----------
  {
    id: "kd-01",
    topic: "Kriterien für Definitheit",
    type: "mc",
    prompt: "D=[[0,3],[3,0]] hat Eigenwerte 3 und −3, sowie führende Hauptminoren d1=0 und d2=−9. Welche Definitheit liegt vor?",
    options: ["indefinit", "positiv definit", "negativ definit", "positiv semidefinit"],
    correctIndex: 0,
    explanation: "Eigenwerte mit gemischtem Vorzeichen (3 und −3) bedeuten indefinit — weder das Muster für positiv definit (alle dₖ>0) noch für negativ definit (alternierend, beginnend negativ) ist erfüllt.",
    source: "Kapitel 6.2, Hauptminoren-Kriterium (nach Klausurmuster)",
    free: false,
  },
  {
    id: "kd-02",
    topic: "Kriterien für Definitheit",
    type: "mc",
    prompt: "Welche Bedingung an die führenden Hauptminoren d1,...,dₙ charakterisiert positive Definitheit?",
    options: ["d1,...,dₙ sind alle > 0", "d1,...,dₙ sind alle < 0", "d1<0, d2>0, d3<0, ...", "mindestens ein dₖ ist 0"],
    correctIndex: 0,
    explanation: "Nach dem Hauptminoren-Kriterium (Sylvester) ist C genau dann positiv definit, wenn alle führenden Hauptminoren positiv sind.",
    source: "Kapitel 6.2, Sylvester-Kriterium",
    free: false,
  },
  {
    id: "kd-03",
    topic: "Kriterien für Definitheit",
    type: "mc",
    prompt: "Welches Vorzeichenmuster der führenden Hauptminoren charakterisiert negative Definitheit?",
    options: ["d1<0, d2>0, d3<0, ... (alternierend)", "alle dₖ>0", "alle dₖ=0", "d1>0, d2<0, d3>0, ..."],
    correctIndex: 0,
    explanation: "Negative Definitheit liegt vor, wenn die führenden Hauptminoren streng alternierend beginnend mit einem negativen Wert auftreten.",
    source: "Kapitel 6.2, Sylvester-Kriterium (negativ)",
    free: false,
  },

  // ---------- Normen und Normäquivalenz ----------
  {
    id: "nm-01",
    topic: "Normen und Normäquivalenz",
    type: "numeric",
    prompt: "Für ⃗v=(5,−12): Berechnen Sie ‖⃗v‖1.",
    correctValue: 17,
    explanation: "‖⃗v‖1 = |5|+|−12| = 5+12 = 17.",
    source: "Kapitel 7.1, 1-Norm",
    free: true,
  },
  {
    id: "nm-02",
    topic: "Normen und Normäquivalenz",
    type: "numeric",
    prompt: "Für dasselbe ⃗v=(5,−12): Berechnen Sie ‖⃗v‖2 (euklidische Norm).",
    correctValue: 13,
    explanation: "‖⃗v‖2 = √(5²+12²) = √(25+144) = √169 = 13.",
    source: "Kapitel 7.1, euklidische Norm",
    free: false,
  },
  {
    id: "nm-03",
    topic: "Normen und Normäquivalenz",
    type: "mc",
    prompt: "Was besagt die Normäquivalenz auf ℝⁿ?",
    options: [
      "Zu je zwei Normen ‖·‖, ‖·‖' gibt es Konstanten c,C>0 mit c‖⃗x‖≤‖⃗x‖'≤C‖⃗x‖ für alle ⃗x.",
      "Alle Normen auf ℝⁿ sind identisch.",
      "Nur die euklidische Norm ist eine gültige Norm auf ℝⁿ.",
      "Normäquivalenz gilt nur für n≤2.",
    ],
    correctIndex: 0,
    explanation: "Auf endlichdimensionalen Räumen wie ℝⁿ sind alle Normen äquivalent in diesem Sinne — insbesondere hängt Konvergenz nicht von der gewählten Norm ab.",
    source: "Kapitel 7.1, Normäquivalenz",
    free: false,
  },

  // ---------- Skalarprodukte und die Cauchy-Schwarz-Ungleichung ----------
  {
    id: "sp-01",
    topic: "Skalarprodukte und die Cauchy-Schwarz-Ungleichung",
    type: "numeric",
    prompt: "Für ⃗a=(1,4,8) und ⃗b=(4,8,1): Berechnen Sie ⟨⃗a,⃗b⟩.",
    correctValue: 44,
    explanation: "⟨⃗a,⃗b⟩ = 1·4+4·8+8·1 = 4+32+8 = 44.",
    source: "Kapitel 7.2, Standardskalarprodukt",
    free: false,
  },
  {
    id: "sp-02",
    topic: "Skalarprodukte und die Cauchy-Schwarz-Ungleichung",
    type: "mc",
    prompt: "Für dieselben Vektoren ⃗a=(1,4,8), ⃗b=(4,8,1) mit ‖⃗a‖=‖⃗b‖=9 und ⟨⃗a,⃗b⟩=44: Ist die Cauchy-Schwarz-Ungleichung erfüllt?",
    options: ["Ja, denn 44 ≤ 9·9=81.", "Nein, 44 > 81.", "Nur wenn ⃗a und ⃗b orthogonal sind.", "Cauchy-Schwarz gilt hier nicht, da die Vektoren 3 Komponenten haben."],
    correctIndex: 0,
    explanation: "|⟨⃗a,⃗b⟩| ≤ ‖⃗a‖·‖⃗b‖ ⟺ 44 ≤ 81 — die Ungleichung ist (mit deutlichem Abstand zur Gleichheit) erfüllt.",
    source: "Kapitel 7.2, Cauchy-Schwarz-Ungleichung",
    free: false,
  },
  {
    id: "sp-03",
    topic: "Skalarprodukte und die Cauchy-Schwarz-Ungleichung",
    type: "mc",
    prompt: "Wann gilt in der Cauchy-Schwarz-Ungleichung |⟨⃗x,⃗y⟩|≤‖⃗x‖‖⃗y‖ die Gleichheit?",
    options: [
      "genau dann, wenn ⃗x und ⃗y linear abhängig sind",
      "immer, für jedes Vektorpaar",
      "nur wenn ⃗x=⃗y=⃗0",
      "genau dann, wenn ⃗x und ⃗y orthogonal sind",
    ],
    correctIndex: 0,
    explanation: "Gleichheit in Cauchy-Schwarz tritt genau bei linear abhängigen Vektoren auf (z. B. wenn einer ein skalares Vielfaches des anderen ist).",
    source: "Kapitel 7.2, Gleichheitsfall Cauchy-Schwarz",
    free: false,
  },

  // ---------- Orthogonalität, Gram-Schmidt-Verfahren und Projektionen ----------
  {
    id: "og-01",
    topic: "Orthogonalität, Gram-Schmidt-Verfahren und Projektionen",
    type: "mc",
    prompt: "Für ⃗v1=(1,1,1) liefert Gram-Schmidt als ersten normierten Vektor ⃗u1 = ?",
    options: ["(1,1,1)/√3", "(1,1,1)/3", "(1,0,0)", "(1,1,1)"],
    correctIndex: 0,
    explanation: "⃗u1 = ⃗v1/‖⃗v1‖ = (1,1,1)/√3, da ‖(1,1,1)‖=√3.",
    source: "Kapitel 7.3, Gram-Schmidt (nach SS23-Klausurmuster)",
    free: false,
  },
  {
    id: "og-02",
    topic: "Orthogonalität, Gram-Schmidt-Verfahren und Projektionen",
    type: "numeric",
    prompt: "⃗c=(4,0,3) wird orthogonal auf U=span{(1,1,0)} projiziert. Wie groß ist der Abstand d(⃗c,U)?",
    correctValue: 4.123,
    tolerance: 0.01,
    explanation: "Mit ⃗u=(1,1,0)/√2 ist P_U(⃗c)=⟨⃗u,⃗c⟩⃗u=(2,2,0). Abstand: ‖(4,0,3)−(2,2,0)‖=‖(2,−2,3)‖=√(4+4+9)=√17≈4,123.",
    source: "Kapitel 7.3, orthogonale Projektion",
    free: false,
  },
  {
    id: "og-03",
    topic: "Orthogonalität, Gram-Schmidt-Verfahren und Projektionen",
    type: "mc",
    prompt: "Was berechnet das Gram-Schmidt-Verfahren?",
    options: [
      "eine Orthonormalbasis aus einer beliebigen Basis",
      "die Eigenwerte einer Matrix",
      "die Determinante eines Untervektorraums",
      "die Inverse einer Matrix",
    ],
    correctIndex: 0,
    explanation: "Gram-Schmidt konstruiert aus einer beliebigen Basis schrittweise eine Orthonormalbasis, indem bei jedem Schritt die Projektion auf bereits konstruierte Basisvektoren abgezogen wird.",
    source: "Kapitel 7.3, Gram-Schmidt-Verfahren",
    free: false,
  },

  // ---------- Grenzwerte und Stetigkeit im Rⁿ ----------
  {
    id: "gs-01",
    topic: "Grenzwerte und Stetigkeit im Rⁿ",
    type: "mc",
    prompt: "f(x,y) := (cos(x²+y²)−1)/(x²+y²) für (x,y)≠(0,0), f(0,0):=α. Für welchen Wert α ist f stetig in (0,0)?",
    options: ["α = 0", "α = 1", "α = −1", "kein α macht f stetig"],
    correctIndex: 0,
    explanation: "Mit z:=x²+y²→0 gilt (cos z −1)/z → 0 (aus der Taylor-Entwicklung cos(z)−1 ≈ −z²/2, also (cos z−1)/z ≈ −z/2 → 0). Damit muss α=0 gewählt werden.",
    source: "Kapitel 8.1, stetige Fortsetzung (nach SS22-Klausurmuster)",
    free: false,
  },
  {
    id: "gs-02",
    topic: "Grenzwerte und Stetigkeit im Rⁿ",
    type: "mc",
    prompt: "Nach dem Folgenkriterium hat f: D⊆ℝⁿ→ℝ im Punkt ⃗x0 den Grenzwert L, wenn:",
    options: [
      "für JEDE Folge ⃗xₖ→⃗x0 in D\\{⃗x0} auch f(⃗xₖ)→L gilt",
      "für EINE Folge ⃗xₖ→⃗x0 gilt f(⃗xₖ)→L",
      "f(⃗x0) definiert ist",
      "f monoton ist",
    ],
    correctIndex: 0,
    explanation: "Das Folgenkriterium verlangt Konvergenz gegen denselben Wert L für ALLE Annäherungsfolgen, nicht nur eine.",
    source: "Kapitel 8.1, Folgenkriterium",
    free: false,
  },
  {
    id: "gs-03",
    topic: "Grenzwerte und Stetigkeit im Rⁿ",
    type: "mc",
    prompt: "Welche Operationen erhalten Stetigkeit (analog zum Eindimensionalen)?",
    options: [
      "Summen, Produkte, Quotienten (Nenner≠0) und Verkettungen stetiger Funktionen",
      "nur Summen",
      "nur Verkettungen",
      "keine — Stetigkeit im ℝⁿ folgt anderen Regeln",
    ],
    correctIndex: 0,
    explanation: "Wie im Eindimensionalen bleiben Summen, Produkte, Quotienten (mit Nenner ≠0) und Verkettungen stetiger Funktionen stetig.",
    source: "Kapitel 8.1, Rechenregeln für Stetigkeit",
    free: false,
  },

  // ---------- Nachweis von Unstetigkeit und stetige Fortsetzung ----------
  {
    id: "nu-01",
    topic: "Nachweis von Unstetigkeit und stetige Fortsetzung",
    type: "numeric",
    prompt: "g(x,y):=xy/(x²+y²) für (x,y)≠(0,0). Welchen Grenzwert liefert die Annäherung entlang y=3x (also g(x,3x))?",
    correctValue: 0.3,
    explanation: "g(x,3x) = 3x²/(x²+9x²) = 3x²/(10x²) = 3/10 = 0,3 — unabhängig von x, aber abhängig von der gewählten Steigung m=3.",
    source: "Kapitel 8.2, Wegabhängigkeit des Grenzwerts",
    free: true,
  },
  {
    id: "nu-02",
    topic: "Nachweis von Unstetigkeit und stetige Fortsetzung",
    type: "mc",
    prompt: "Für g(x,y)=xy/(x²+y²): Warum ist g in (0,0) NICHT stetig fortsetzbar?",
    options: [
      "Weil die Grenzwerte entlang verschiedener Geraden y=mx unterschiedlich ausfallen (abhängig von m).",
      "Weil g in (0,0) nicht definiert werden kann.",
      "Weil g unbeschränkt ist.",
      "Weil g nicht differenzierbar ist.",
    ],
    correctIndex: 0,
    explanation: "g(x,mx)=m/(1+m²) hängt von m ab — verschiedene Wege liefern verschiedene Grenzwerte, also existiert der Grenzwert in (0,0) nicht.",
    source: "Kapitel 8.2, Unstetigkeitsnachweis",
    free: false,
  },
  {
    id: "nu-03",
    topic: "Nachweis von Unstetigkeit und stetige Fortsetzung",
    type: "mc",
    prompt: "Eine Funktion f ist auf D\\{⃗x0} definiert. Wann ist sie stetig in ⃗x0 fortsetzbar?",
    options: [
      "genau dann, wenn lim_{⃗x→⃗x0} f(⃗x) existiert (unabhängig vom Weg)",
      "immer, unabhängig vom Grenzwert",
      "nur wenn f linear ist",
      "nur wenn D beschränkt ist",
    ],
    correctIndex: 0,
    explanation: "Stetige Fortsetzbarkeit erfordert die Existenz eines eindeutigen (wegunabhängigen) Grenzwerts in ⃗x0; man setzt dann f(⃗x0) gleich diesem Wert.",
    source: "Kapitel 8.2, stetige Fortsetzbarkeit",
    free: false,
  },

  // ---------- Gradient und Richtungsableitung ----------
  {
    id: "gr-01",
    topic: "Gradient und Richtungsableitung",
    type: "mc",
    prompt: "f(x,y) = x²−2xy−y². Wie lautet ∇f(1,−2)?",
    options: ["(6, 2)", "(2, 6)", "(1, −2)", "(−2, 1)"],
    correctIndex: 0,
    explanation: "∇f(x,y)=(2x−2y, −2x−2y). Bei (1,−2): (2·1−2·(−2), −2·1−2·(−2)) = (2+4, −2+4) = (6,2).",
    source: "Kapitel 9.1, Gradient",
    free: false,
  },
  {
    id: "gr-02",
    topic: "Gradient und Richtungsableitung",
    type: "mc",
    prompt: "In welche Richtung zeigt der Gradient ∇f(⃗x) einer Funktion f?",
    options: [
      "in Richtung des steilsten Anstiegs von f",
      "immer in Richtung der x-Achse",
      "in Richtung des steilsten Abfalls von f",
      "senkrecht zur x-Achse, unabhängig von f",
    ],
    correctIndex: 0,
    explanation: "Der Gradient zeigt stets in die Richtung, in der f am schnellsten zunimmt; die Gegenrichtung ist die Richtung des steilsten Abfalls.",
    source: "Kapitel 9.1, Bedeutung des Gradienten",
    free: false,
  },
  {
    id: "gr-03",
    topic: "Gradient und Richtungsableitung",
    type: "mc",
    prompt: "Wie berechnet man die Richtungsableitung ∂f/∂⃗w(⃗x) in Richtung eines Einheitsvektors ⃗w?",
    options: ["als Skalarprodukt ⟨∇f(⃗x), ⃗w⟩", "als Betrag |∇f(⃗x)|", "als Kreuzprodukt ∇f(⃗x)×⃗w", "als Determinante von ∇f(⃗x) und ⃗w"],
    correctIndex: 0,
    explanation: "Für total differenzierbares f gilt ∂f/∂⃗w(⃗x) = ⟨∇f(⃗x), ⃗w⟩ (mit ‖⃗w‖=1).",
    source: "Kapitel 9.1, Richtungsableitung",
    free: false,
  },

  // ---------- Tangentialebene ----------
  {
    id: "tg-01",
    topic: "Tangentialebene",
    type: "mc",
    prompt: "f(x,y)=x²−2xy−y² mit f(1,−2)=1 und ∇f(1,−2)=(6,2). Wie lautet die Tangentialebene in (1,−2)?",
    options: ["z = 6x + 2y − 1", "z = x + 2y + 1", "z = 6x + 2y + 1", "z = 1 + 6x − 2y"],
    correctIndex: 0,
    explanation: "z = f(1,−2) + ⟨∇f(1,−2),(x−1,y+2)⟩ = 1 + 6(x−1) + 2(y+2) = 1 + 6x−6 + 2y+4 = 6x+2y−1.",
    source: "Kapitel 9.2, Tangentialebene",
    free: false,
  },
  {
    id: "tg-02",
    topic: "Tangentialebene",
    type: "mc",
    prompt: "Was beschreibt die Tangentialebene einer total differenzierbaren Funktion f: ℝ²→ℝ in einem Punkt?",
    options: [
      "die beste lineare (affine) Näherung von f in der Nähe dieses Punktes",
      "den maximalen Funktionswert von f",
      "die zweite Ableitung von f",
      "eine Kurve auf dem Graphen von f",
    ],
    correctIndex: 0,
    explanation: "Analog zur Tangente im Eindimensionalen liefert die Tangentialebene die beste lokale lineare Approximation des Funktionsgraphen.",
    source: "Kapitel 9.2, Bedeutung der Tangentialebene",
    free: false,
  },
  {
    id: "tg-03",
    topic: "Tangentialebene",
    type: "mc",
    prompt: "Welche Formel beschreibt die Tangentialebene an f in (x0,y0)?",
    options: [
      "z = f(x0,y0) + ⟨∇f(x0,y0), (x−x0, y−y0)⟩",
      "z = f(x0,y0) · ⟨∇f(x0,y0), (x,y)⟩",
      "z = ∇f(x0,y0)",
      "z = f(x0,y0) − ⟨∇f(x0,y0), (x−x0,y−y0)⟩",
    ],
    correctIndex: 0,
    explanation: "Die Tangentialebenengleichung lautet z = f(x0,y0) + ⟨∇f(x0,y0), (x−x0,y−y0)⟩ — Funktionswert plus linearer Korrekturterm über den Gradienten.",
    source: "Kapitel 9.2, Formel der Tangentialebene",
    free: false,
  },
];
