export type QuestionType = "mc" | "numeric";

export interface Question {
  id: string;
  topic: string;
  type: QuestionType;
  prompt: string;
  options?: string[];
  correctIndex?: number;
  correctValue?: number;
  tolerance?: number;
  unit?: string;
  explanation: string;
  source: string;
  free: boolean;
}

// Hinweis: Alle Übungsaufgaben in dieser Fragenbank stammen der mathematischen
// Struktur nach aus echten Tutoriumsblättern und Klausuren, sind aber in den
// konkreten Zahlenwerten/Funktionen gegenüber dem Original verändert. Ein
// eigenes Szenario (Kontext, Gegenstände, Namen, Branchen) musste hier nicht
// ausgetauscht werden, da es sich bei sämtlichen Aufgaben dieses Moduls um
// rein abstrakte, symbolische Aufgaben ohne konkretes Szenario handelt (reine
// Funktionsanalyse, Mengen, Integrale) — genau der in CLAUDE.md vorgesehene
// Ausnahmefall.
export const TOPICS = [
  "Jordan-Inhalt und messbare Mengen im Rⁿ",
  "Partielle Differenzierbarkeit und der Gradient",
  "Ober- und Untersummen: das Riemann-Integral im Rⁿ",
  "Richtungsableitungen",
  "Eigenschaften des Jordan-Inhalts und der Satz von Fubini",
  "Totale Differenzierbarkeit und die Tangentialebene",
  "Normalbereiche und das Prinzip von Cavalieri",
  "Kettenregel, Jacobi-Matrix und vektorwertige Funktionen",
  "Treppenfunktionen, gleichmäßige Stetigkeit und Integrierbarkeit stetiger Funktionen",
  "Höhere Ableitungen und der Satz von Schwarz",
  "Der Gradient als Richtung des steilsten Anstiegs",
  "Der Transformationssatz und Koordinatenwechsel",
  "Taylorpolynome und der Mittelwertsatz im Rⁿ",
  "Lokale Extrema, die Hessematrix und Sattelpunkte",
] as const;

export const questions: Question[] = [
  // ---------- Jordan-Inhalt und messbare Mengen im Rⁿ ----------
  {
    id: "ji-01",
    topic: "Jordan-Inhalt und messbare Mengen im Rⁿ",
    type: "numeric",
    prompt:
      "Gegeben sei M := ([0,3] × [0,2]) ∪ ([3,6] × [2,4]) ⊂ ℝ². Bestimmen Sie den Jordan-Inhalt |M|.",
    correctValue: 12,
    explanation:
      "Die beiden Rechtecke überlappen sich höchstens in der gemeinsamen Kante {3} × [2] (einer Jordan-Nullmenge), sind also additiv: |M| = 3·2 + 3·2 = 6 + 6 = 12.",
    source: "Kapitel 1, Jordan-Inhalt",
    free: true,
  },
  {
    id: "ji-02",
    topic: "Jordan-Inhalt und messbare Mengen im Rⁿ",
    type: "mc",
    prompt: "Welchen Jordan-Inhalt hat eine endliche Menge von Punkten M = {⃗x₁, ..., ⃗xₗ} ⊂ ℝ²?",
    options: ["0", "1", "Unendlich", "Hängt von der Lage der Punkte ab"],
    correctIndex: 0,
    explanation:
      "Jeder einzelne Punkt lässt sich durch einen Quader mit beliebig kleinem Inhalt überdecken; da nur endlich viele Punkte vorliegen, ist auch die Gesamtüberdeckung beliebig klein, also |M| = 0.",
    source: "Kapitel 1, Jordan-Inhalt",
    free: false,
  },
  {
    id: "ji-03",
    topic: "Jordan-Inhalt und messbare Mengen im Rⁿ",
    type: "numeric",
    prompt:
      "Gegeben sei M := {(x,y) ∈ ℝ² : x ∈ [−2,2], y ∈ [0,5]} ∪ {(x,y) ∈ ℝ² : x²+y² ≤ 4}. Bestimmen Sie den Flächeninhalt |M|.",
    correctValue: 26.28,
    tolerance: 0.05,
    explanation:
      "Das Rechteck hat Fläche 4·5 = 20. Der Kreis vom Radius 2 ist bis auf seine untere Hälfte (y < 0) bereits im Rechteck enthalten; die untere Halbkreisfläche beträgt π·4/2 = 2π. Insgesamt |M| = 20 + 2π ≈ 26,28.",
    source: "Kapitel 1, Jordan-Inhalt (nach Klausur SS22 Nachtermin)",
    free: false,
  },
  {
    id: "ji-04",
    topic: "Jordan-Inhalt und messbare Mengen im Rⁿ",
    type: "mc",
    prompt: "Was besagt das Randkriterium für Jordan-Messbarkeit einer beschränkten Menge M ⊂ ℝⁿ?",
    options: [
      "M ist genau dann Jordan-messbar, wenn ihr Rand ∂M eine Jordan-Nullmenge ist.",
      "M ist genau dann Jordan-messbar, wenn M offen ist.",
      "M ist genau dann Jordan-messbar, wenn M konvex ist.",
      "M ist genau dann Jordan-messbar, wenn M unbeschränkt ist.",
    ],
    correctIndex: 0,
    explanation:
      "Nach dem Randkriterium stimmen äußerer und innerer Jordan-Inhalt genau dann überein, wenn der Rand von M keinen positiven Inhalt beiträgt, also selbst eine Jordan-Nullmenge ist.",
    source: "Kapitel 1, Randkriterium",
    free: false,
  },
  {
    id: "ji-05",
    topic: "Jordan-Inhalt und messbare Mengen im Rⁿ",
    type: "numeric",
    prompt: "Gegeben sei M := ([0,4] × [0,3]) ∪ ([4,7] × [3,5]) ⊂ ℝ². Bestimmen Sie |M|.",
    correctValue: 18,
    explanation: "|M| = 4·3 + 3·2 = 12 + 6 = 18, da die beiden Rechtecke nur eine gemeinsame Kante (Inhalt 0) teilen.",
    source: "Kapitel 1, Jordan-Inhalt",
    free: false,
  },

  // ---------- Partielle Differenzierbarkeit und der Gradient ----------
  {
    id: "pd-01",
    topic: "Partielle Differenzierbarkeit und der Gradient",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := x³ + 2xy² − 3x. Berechnen Sie ∂f/∂x(1,1).",
    correctValue: 2,
    explanation: "∂f/∂x(x,y) = 3x² + 2y² − 3. Einsetzen von (1,1) liefert 3 + 2 − 3 = 2.",
    source: "Kapitel 2, Partielle Ableitungen",
    free: true,
  },
  {
    id: "pd-02",
    topic: "Partielle Differenzierbarkeit und der Gradient",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := 4x²y³ − 5x. Berechnen Sie ∂f/∂y(1,1).",
    correctValue: 12,
    explanation: "∂f/∂y(x,y) = 12x²y². Einsetzen von (1,1) liefert 12·1·1 = 12.",
    source: "Kapitel 2, Partielle Ableitungen",
    free: false,
  },
  {
    id: "pd-03",
    topic: "Partielle Differenzierbarkeit und der Gradient",
    type: "mc",
    prompt: "Welche der folgenden Aussagen zur partiellen Differenzierbarkeit ist korrekt?",
    options: [
      "Eine Funktion kann in einem Punkt partiell differenzierbar sein, dort aber unstetig.",
      "Partielle Differenzierbarkeit in einem Punkt impliziert stets Stetigkeit dort.",
      "Partielle Differenzierbarkeit impliziert stets totale Differenzierbarkeit.",
      "Eine partiell differenzierbare Funktion ist automatisch stetig partiell differenzierbar.",
    ],
    correctIndex: 0,
    explanation:
      "Anders als im Eindimensionalen folgt aus partieller Differenzierbarkeit nicht einmal Stetigkeit — ein Standardgegenbeispiel ist f(x,y) = 3xy²/(x²+y⁴) für (x,y)≠(0,0), f(0,0)=0, das im Ursprung partiell differenzierbar, aber unstetig ist.",
    source: "Kapitel 2, Partielle Ableitungen",
    free: false,
  },
  {
    id: "pd-04",
    topic: "Partielle Differenzierbarkeit und der Gradient",
    type: "numeric",
    prompt:
      "Gegeben sei f(x,y) := x⁴ + y⁴ − 6x² − 6y². Wie viele stationäre Punkte besitzt f?",
    correctValue: 9,
    explanation:
      "∇f(x,y) = (4x³−12x, 4y³−12y) = (4x(x²−3), 4y(y²−3)). Dies verschwindet genau für x,y ∈ {−√3, 0, √3}, also für 3·3 = 9 Kombinationen.",
    source: "Kapitel 2, Gradient und stationäre Punkte",
    free: false,
  },
  {
    id: "pd-05",
    topic: "Partielle Differenzierbarkeit und der Gradient",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := x²y − 3x. Berechnen Sie ∂f/∂x(2,1).",
    correctValue: 1,
    explanation: "∂f/∂x(x,y) = 2xy − 3. Einsetzen von (2,1) liefert 2·2·1 − 3 = 1.",
    source: "Kapitel 2, Partielle Ableitungen",
    free: false,
  },

  // ---------- Ober- und Untersummen: das Riemann-Integral im Rⁿ ----------
  {
    id: "ri-01",
    topic: "Ober- und Untersummen: das Riemann-Integral im Rⁿ",
    type: "numeric",
    prompt:
      "Gegeben sei f : [0,1]² → ℝ, f(x,y) := 3y, sowie für n ∈ ℕ die Partition Zn in n gleich breite Vertikalstreifen [(i−1)/n, i/n] × [0,1]. Bestimmen Sie die Obersumme O(f;Zn) (unabhängig von n).",
    correctValue: 3,
    explanation: "Auf jedem Streifen gilt max f = 3 (bei y=1) und Σ Streifenbreiten = 1, also O(f;Zn) = 3·1 = 3 für jedes n.",
    source: "Kapitel 3, Ober- und Untersummen",
    free: true,
  },
  {
    id: "ri-02",
    topic: "Ober- und Untersummen: das Riemann-Integral im Rⁿ",
    type: "numeric",
    prompt: "Für dieselbe Funktion f(x,y) := 3y und Partition wie in der vorherigen Aufgabe: Bestimmen Sie die Untersumme U(f;Zn).",
    correctValue: 0,
    explanation: "Auf jedem Streifen gilt min f = 0 (bei y=0), also U(f;Zn) = 0 für jedes n.",
    source: "Kapitel 3, Ober- und Untersummen",
    free: false,
  },
  {
    id: "ri-03",
    topic: "Ober- und Untersummen: das Riemann-Integral im Rⁿ",
    type: "numeric",
    prompt: "Bestimmen Sie das Riemann-Integral von f(x,y) := x+2y über [0,2]×[0,1] als Grenzwert von Ober- und Untersummen.",
    correctValue: 4,
    explanation: "Für eine Partition in n×n gleich große Rechtecke konvergieren Ober- und Untersumme gegen ∫₀²∫₀¹ (x+2y) dy dx = ∫₀² (x+1) dx = [x²/2+x]₀² = 2+2 = 4.",
    source: "Kapitel 3, Riemann-Integral",
    free: false,
  },
  {
    id: "ri-04",
    topic: "Ober- und Untersummen: das Riemann-Integral im Rⁿ",
    type: "mc",
    prompt:
      "Warum reicht es für den Nachweis der Integrierbarkeit einer Funktion nicht aus, nur für eine einzige Partitionenfolge (z. B. ausschließlich vertikale Streifen) zu zeigen, dass Ober- und Untersumme gegen denselben Wert konvergieren?",
    options: [
      "Weil das ε-Kriterium verlangt, dass sich Ober- und Untersumme für JEDE Partition beliebig annähern lassen — eine einzelne Partitionsfolge reicht nicht, da andere Folgen im Prinzip einen anderen Grenzwert liefern könnten.",
      "Weil Ober- und Untersummen bei jeder Partitionsfolge automatisch gegen denselben Wert konvergieren, sodass die Wahl der Folge irrelevant ist.",
      "Weil man ausschließlich horizontale Streifen verwenden darf.",
      "Weil Riemann-Integrale grundsätzlich nur über Kreisscheiben definiert sind.",
    ],
    correctIndex: 0,
    explanation:
      "Integrierbarkeit ist über das Infimum aller Obersummen bzw. Supremum aller Untersummen definiert — eine einzelne, geschickt gewählte Partitionsfolge kann zufällig konvergieren, ohne dass die Funktion tatsächlich integrierbar ist.",
    source: "Kapitel 3, Integrierbarkeitskriterien",
    free: false,
  },
  {
    id: "ri-05",
    topic: "Ober- und Untersummen: das Riemann-Integral im Rⁿ",
    type: "numeric",
    prompt:
      "Gegeben sei f : [0,1]² → ℝ mit f(x,y) := 2 falls x ≤ 1/2 und f(x,y) := 5 falls x > 1/2. Berechnen Sie ∫_{[0,1]²} f(x,y) d(x,y).",
    correctValue: 3.5,
    explanation: "f ist eine Treppenfunktion; das Integral ist 2·(1/2) + 5·(1/2) = 1 + 2,5 = 3,5.",
    source: "Kapitel 3, Riemann-Integral (nach 11. Tutoriumsblatt)",
    free: false,
  },

  // ---------- Richtungsableitungen ----------
  {
    id: "ra-01",
    topic: "Richtungsableitungen",
    type: "numeric",
    prompt:
      "Gegeben sei f(x,y) := x² + 3y² und ⃗v := (3/5, 4/5)ᵀ. Berechnen Sie ∂f/∂⃗v(1,2).",
    correctValue: 10.8,
    explanation: "∇f(1,2) = (2, 12)ᵀ. Damit ∂f/∂⃗v(1,2) = ⟨∇f(1,2), ⃗v⟩ = 2·(3/5) + 12·(4/5) = 6/5 + 48/5 = 54/5 = 10,8.",
    source: "Kapitel 4, Richtungsableitungen",
    free: true,
  },
  {
    id: "ra-02",
    topic: "Richtungsableitungen",
    type: "mc",
    prompt:
      "Gegeben sei h(x,y) := 2xy/(x²+y²) für (x,y)≠(0,0) und h(0,0):=0. Für welche Einheitsvektoren ⃗v existiert die Richtungsableitung ∂h/∂⃗v(0,0)?",
    options: [
      "Nur entlang der Koordinatenachsen (⃗v = ±⃗e₁ oder ⃗v = ±⃗e₂), dort mit Wert 0.",
      "Für alle Richtungen ⃗v, jeweils mit Wert 0.",
      "Nur für ⃗v = (1,1)ᵀ/√2.",
      "Für keine einzige Richtung.",
    ],
    correctIndex: 0,
    explanation:
      "Für ⃗v=(v₁,v₂) mit ‖⃗v‖₂=1 gilt (h(t⃗v)−h(0))/t = 2v₁v₂/t, was nur für v₁v₂=0 (also entlang der Achsen) gegen einen endlichen Wert (nämlich 0) konvergiert.",
    source: "Kapitel 4, Richtungsableitungen",
    free: false,
  },
  {
    id: "ra-03",
    topic: "Richtungsableitungen",
    type: "mc",
    prompt:
      "Es sei g : ℝ² → ℝ differenzierbar, (a,b) kein stationärer Punkt von g, und es gelte ∂g/∂x(a,b) = ∂g/∂y(a,b) ≠ 0. Welche Menge L aller Richtungen ⃗v mit ‖⃗v‖₂=1 und ∂g/∂⃗v(a,b)=0 ergibt sich?",
    options: [
      "L = {±(1,−1)ᵀ/√2}",
      "L = {±(1,1)ᵀ/√2}",
      "L = {(1,0)ᵀ, (0,1)ᵀ}",
      "L = ∅",
    ],
    correctIndex: 0,
    explanation:
      "Mit ∇g(a,b)=(c,c)ᵀ, c≠0, gilt ∂g/∂⃗v(a,b) = c·(v₁+v₂) = 0 genau dann, wenn v₁ = −v₂, also ⃗v = ±(1,−1)ᵀ/√2.",
    source: "Kapitel 4, Richtungsableitungen (nach Klausur SS2025 Haupttermin)",
    free: false,
  },
  {
    id: "ra-04",
    topic: "Richtungsableitungen",
    type: "numeric",
    prompt:
      "Gegeben sei f(x,y) := ln(x²+y²+1) und ⃗v := (3/5, 4/5)ᵀ. Berechnen Sie ∂f/∂⃗v(1,0).",
    correctValue: 0.6,
    explanation: "∇f(1,0) = (2·1/2, 2·0/2)ᵀ = (1,0)ᵀ. Damit ∂f/∂⃗v(1,0) = ⟨(1,0), (3/5,4/5)⟩ = 3/5 = 0,6.",
    source: "Kapitel 4, Richtungsableitungen",
    free: false,
  },
  {
    id: "ra-05",
    topic: "Richtungsableitungen",
    type: "numeric",
    prompt:
      "Es sei f : ℝ² → ℝ differenzierbar mit f(3,y) = y² + 2y für alle y ∈ ℝ. Berechnen Sie ∂f/∂y(3,2).",
    correctValue: 6,
    explanation: "Die erste Schnittfunktion p(y):=f(3,y)=y²+2y hat Ableitung p′(y)=2y+2, also ∂f/∂y(3,2) = p′(2) = 6.",
    source: "Kapitel 4, Richtungsableitungen (nach Klausur SS2025 Nachtermin)",
    free: false,
  },

  // ---------- Eigenschaften des Jordan-Inhalts und der Satz von Fubini ----------
  {
    id: "fu-01",
    topic: "Eigenschaften des Jordan-Inhalts und der Satz von Fubini",
    type: "numeric",
    prompt: "Gegeben sei M := [1,3] × [2,4]. Berechnen Sie ∫_M x/y² d(x,y).",
    correctValue: 1,
    tolerance: 0.01,
    explanation: "Mit Fubini gilt ∫_M x/y² d(x,y) = (∫₁³ x dx)·(∫₂⁴ y⁻² dy) = 4 · 0,25 = 1.",
    source: "Kapitel 5, Satz von Fubini",
    free: true,
  },
  {
    id: "fu-02",
    topic: "Eigenschaften des Jordan-Inhalts und der Satz von Fubini",
    type: "numeric",
    prompt: "Gegeben sei M := [0,3] × [0,2] × [0, log(2)]. Berechnen Sie ∫_M (2x + y)·eᶻ d(x,y,z).",
    correctValue: 24,
    explanation:
      "Mit Fubini: ∫₀³ (2x+y) dx = 9+3y, also ∫₀² (9+3y) dy = [9y+1,5y²]₀² = 18+6 = 24. Der z-Faktor ist [eᶻ]₀^{log 2} = 2−1 = 1. Insgesamt 24·1 = 24.",
    source: "Kapitel 5, Satz von Fubini",
    free: false,
  },
  {
    id: "fu-03",
    topic: "Eigenschaften des Jordan-Inhalts und der Satz von Fubini",
    type: "mc",
    prompt: "Welche Voraussetzung benötigt der Satz von Fubini, um ein Integral über einen Quader als iteriertes Integral zu berechnen?",
    options: [
      "f muss auf dem Quader integrierbar sein, und für jedes feste x muss das innere Integral über y existieren.",
      "f muss auf dem gesamten ℝⁿ definiert sein.",
      "Der Quader muss ein Würfel sein.",
      "f muss monoton wachsend in jeder Variablen sein.",
    ],
    correctIndex: 0,
    explanation: "Fubini setzt Integrierbarkeit von f auf dem Quader sowie die Existenz des inneren (eindimensionalen) Integrals für jedes feste x voraus.",
    source: "Kapitel 5, Satz von Fubini",
    free: false,
  },
  {
    id: "fu-04",
    topic: "Eigenschaften des Jordan-Inhalts und der Satz von Fubini",
    type: "numeric",
    prompt: "Berechnen Sie ∫_{[0,1]×[0,π]} e^{2x}·sin(y) d(x,y).",
    correctValue: 6.389,
    tolerance: 0.01,
    explanation: "Mit Fubini: (∫₀¹ e^{2x} dx)·(∫₀^π sin(y) dy) = [(e²−1)/2]·2 = e²−1 ≈ 6,389.",
    source: "Kapitel 5, Satz von Fubini (nach Klausur AK HT 2024)",
    free: false,
  },
  {
    id: "fu-05",
    topic: "Eigenschaften des Jordan-Inhalts und der Satz von Fubini",
    type: "mc",
    prompt: "Es seien M₁, M₂ ⊂ ℝⁿ Jordan-messbar mit |M₁ ∩ M₂| = 0. Welche Aussage ist korrekt?",
    options: [
      "M₁ ∪ M₂ ist Jordan-messbar mit |M₁ ∪ M₂| = |M₁| + |M₂|.",
      "M₁ ∪ M₂ ist niemals Jordan-messbar.",
      "|M₁ ∪ M₂| = |M₁| · |M₂|.",
      "M₁ ∪ M₂ ist nur messbar, wenn M₁ = M₂ gilt.",
    ],
    correctIndex: 0,
    explanation: "Der Jordan-Inhalt ist additiv für Mengen, deren Schnitt eine Nullmenge ist — genau die hier vorausgesetzte Bedingung.",
    source: "Kapitel 5, Eigenschaften des Jordan-Inhalts",
    free: false,
  },

  // ---------- Totale Differenzierbarkeit und die Tangentialebene ----------
  {
    id: "td-01",
    topic: "Totale Differenzierbarkeit und die Tangentialebene",
    type: "numeric",
    prompt:
      "Gegeben sei f(x,y) := x²y + 2x + y. Bestimmen Sie den Wert z der Tangentialebene Tf(1,2) an der Stelle (x,y) = (2,3).",
    correctValue: 14,
    explanation:
      "f(1,2)=1·2+2+2=6, ∇f(1,2)=(2·1·2+2, 1²+1)=(6,2). Die Tangentialebene lautet z=6+6(x−1)+2(y−2). Bei (2,3): z=6+6·1+2·1=14.",
    source: "Kapitel 6, Tangentialebene",
    free: true,
  },
  {
    id: "td-02",
    topic: "Totale Differenzierbarkeit und die Tangentialebene",
    type: "mc",
    prompt: "Welches hinreichende Kriterium garantiert totale Differenzierbarkeit in ⃗x₀?",
    options: [
      "Alle partiellen Ableitungen existieren in einer Umgebung von ⃗x₀ und sind dort stetig.",
      "f ist irgendwo im Definitionsbereich stetig.",
      "f besitzt einen stationären Punkt in ⃗x₀.",
      "Die Richtungsableitung existiert nur entlang der Koordinatenachsen.",
    ],
    correctIndex: 0,
    explanation: "Stetige partielle Differenzierbarkeit in einer Umgebung von ⃗x₀ impliziert totale Differenzierbarkeit in ⃗x₀.",
    source: "Kapitel 6, Totale Differenzierbarkeit",
    free: false,
  },
  {
    id: "td-03",
    topic: "Totale Differenzierbarkeit und die Tangentialebene",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := e^{3xy} + 2x. Berechnen Sie ∂f/∂x(0,1).",
    correctValue: 5,
    explanation: "∂f/∂x(x,y) = 3y·e^{3xy} + 2. Einsetzen von (0,1) liefert 3·1·1 + 2 = 5.",
    source: "Kapitel 6, Totale Differenzierbarkeit",
    free: false,
  },
  {
    id: "td-04",
    topic: "Totale Differenzierbarkeit und die Tangentialebene",
    type: "mc",
    prompt: "Welche Bedingung definiert totale Differenzierbarkeit von f in ⃗x₀ korrekt?",
    options: [
      "Es gibt ⃗a mit f(⃗x₀+⃗h) = f(⃗x₀) + ⟨⃗a,⃗h⟩ + r(⃗h), wobei r(⃗h)/‖⃗h‖₂ → 0 für ⃗h → ⃗0.",
      "Es gibt ⃗a mit f(⃗x₀+⃗h) = f(⃗x₀) + ⟨⃗a,⃗h⟩ für alle ⃗h.",
      "f ist in ⃗x₀ partiell differenzierbar.",
      "f ist auf dem gesamten Definitionsbereich beschränkt.",
    ],
    correctIndex: 0,
    explanation: "Totale Differenzierbarkeit verlangt eine affine Approximation mit einem Restterm, der schneller als linear (bezüglich ‖⃗h‖₂) verschwindet.",
    source: "Kapitel 6, Totale Differenzierbarkeit",
    free: false,
  },
  {
    id: "td-05",
    topic: "Totale Differenzierbarkeit und die Tangentialebene",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := x² + y³. Der Normalenvektor der Tangentialebene an (1,1) ist ⃗v = (∇f(1,1), c)ᵀ. Bestimmen Sie c.",
    correctValue: -1,
    explanation: "Der Normalenvektor der Tangentialebene ist stets (∇f(⃗x₀), −1)ᵀ, also c = −1.",
    source: "Kapitel 6, Tangentialebene",
    free: false,
  },

  // ---------- Normalbereiche und das Prinzip von Cavalieri ----------
  {
    id: "nc-01",
    topic: "Normalbereiche und das Prinzip von Cavalieri",
    type: "numeric",
    prompt: "Gegeben sei ein verallgemeinerter Kegel mit Grundfläche B := [0,3] × [0,2] und Höhe h = 4. Bestimmen Sie das Volumen des Kegels.",
    correctValue: 8,
    explanation: "|B| = 6, also Volumen = h·|B|/3 = 4·6/3 = 8.",
    source: "Kapitel 7, Prinzip von Cavalieri",
    free: true,
  },
  {
    id: "nc-02",
    topic: "Normalbereiche und das Prinzip von Cavalieri",
    type: "numeric",
    prompt:
      "Für u ∈ [0,3] sei Ku ein Kreisring mit innerem Radius u und äußerem Radius u+2. Bestimmen Sie mit dem Prinzip von Cavalieri das Volumen |K| = ∫₀³ |Ku| du.",
    correctValue: 94.25,
    tolerance: 0.05,
    explanation: "|Ku| = π((u+2)²−u²) = π(4u+4). ∫₀³ π(4u+4) du = π[2u²+4u]₀³ = π(18+12) = 30π ≈ 94,25.",
    source: "Kapitel 7, Prinzip von Cavalieri",
    free: false,
  },
  {
    id: "nc-03",
    topic: "Normalbereiche und das Prinzip von Cavalieri",
    type: "mc",
    prompt: "Welche Darstellung ist ein Normalbereich bezüglich der x-Achse für die Menge F oberhalb der Parabel x↦x² und unterhalb der Geraden x↦x+6?",
    options: [
      "F = {(x,y) : −2 ≤ x ≤ 3, x² ≤ y ≤ x+6}",
      "F = {(x,y) : 0 ≤ x ≤ 3, 0 ≤ y ≤ x+6}",
      "F = {(x,y) : −2 ≤ x ≤ 3, x+6 ≤ y ≤ x²}",
      "F = {(x,y) : −3 ≤ x ≤ 2, x² ≤ y ≤ x+6}",
    ],
    correctIndex: 0,
    explanation: "Die Schnittpunkte von x² und x+6 liegen bei x²=x+6 ⟺ x∈{−2,3}. Zwischen diesen Werten liegt die Gerade oberhalb der Parabel.",
    source: "Kapitel 7, Normalbereiche",
    free: false,
  },
  {
    id: "nc-04",
    topic: "Normalbereiche und das Prinzip von Cavalieri",
    type: "numeric",
    prompt: "Berechnen Sie den Flächeninhalt der Menge F aus der vorherigen Aufgabe (oberhalb x², unterhalb x+6).",
    correctValue: 20.833,
    tolerance: 0.01,
    explanation: "∫₋₂³ (x+6−x²) dx = [x²/2+6x−x³/3]₋₂³ = 13,5 − (−7,333) = 20,833 = 125/6.",
    source: "Kapitel 7, Normalbereiche",
    free: false,
  },
  {
    id: "nc-05",
    topic: "Normalbereiche und das Prinzip von Cavalieri",
    type: "mc",
    prompt: "Wie lautet das Prinzip von Cavalieri für eine Jordan-messbare Menge K ⊂ ℝ³ mit Schnittflächen Ku := {(x,y) : (x,y,u) ∈ K}?",
    options: ["|K| = ∫ₐᵇ |Ku| du", "|K| = Σ Ku", "|K| = max_u |Ku|", "|K| = ∫ₐᵇ |Ku|² du"],
    correctIndex: 0,
    explanation: "Das Volumen von K ergibt sich als Integral über die Flächeninhalte der horizontalen Schnitte Ku.",
    source: "Kapitel 7, Prinzip von Cavalieri",
    free: false,
  },

  // ---------- Kettenregel, Jacobi-Matrix und vektorwertige Funktionen ----------
  {
    id: "kj-01",
    topic: "Kettenregel, Jacobi-Matrix und vektorwertige Funktionen",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := (x²−y², 3xy)ᵀ. Berechnen Sie det(Jf(1,1)).",
    correctValue: 12,
    explanation: "Jf(x,y) = ((2x,−2y);(3y,3x)). Bei (1,1): ((2,−2);(3,3)), det = 2·3 − (−2)·3 = 6+6 = 12.",
    source: "Kapitel 8, Jacobi-Matrix",
    free: true,
  },
  {
    id: "kj-02",
    topic: "Kettenregel, Jacobi-Matrix und vektorwertige Funktionen",
    type: "numeric",
    prompt: "Gegeben seien g(t) := (t³, cos(t))ᵀ und f(x,y) := 2x + y². Berechnen Sie d/dt (f∘g)(t) an der Stelle t=0.",
    correctValue: 0,
    explanation: "(f∘g)(t) = 2t³ + cos²(t), Ableitung 6t² − 2cos(t)sin(t). Bei t=0: 0 − 0 = 0.",
    source: "Kapitel 8, Kettenregel",
    free: false,
  },
  {
    id: "kj-03",
    topic: "Kettenregel, Jacobi-Matrix und vektorwertige Funktionen",
    type: "mc",
    prompt: "Wie lautet die allgemeine Kettenregel für differenzierbare Funktionen g : D₁→ℝᵏ und f : D₂→ℝᵐ mit g(D₁)⊂D₂?",
    options: [
      "J_{f∘g}(⃗x) = Jf(g(⃗x)) · Jg(⃗x)",
      "J_{f∘g}(⃗x) = Jg(⃗x) · Jf(g(⃗x))",
      "J_{f∘g}(⃗x) = Jf(⃗x) + Jg(⃗x)",
      "J_{f∘g}(⃗x) = Jf(⃗x) · Jg(⃗x)",
    ],
    correctIndex: 0,
    explanation: "Die Jacobi-Matrix der Komposition ist das Matrizenprodukt Jf(g(⃗x))·Jg(⃗x), in dieser Reihenfolge.",
    source: "Kapitel 8, Kettenregel",
    free: false,
  },
  {
    id: "kj-04",
    topic: "Kettenregel, Jacobi-Matrix und vektorwertige Funktionen",
    type: "numeric",
    prompt: "Für Zylinderkoordinaten T(r,φ,z) := (r cos φ, r sin φ, z) gilt det(JT(r,φ,z)) = r. Bestimmen Sie diesen Wert für r=2.",
    correctValue: 2,
    explanation: "Die Jacobi-Determinante der Zylinderkoordinaten ist unabhängig von φ und z gleich r, also 2 für r=2.",
    source: "Kapitel 8, Jacobi-Matrix",
    free: false,
  },
  {
    id: "kj-05",
    topic: "Kettenregel, Jacobi-Matrix und vektorwertige Funktionen",
    type: "numeric",
    prompt: "Gegeben sei g(x,y) := (x+y, x−y, xy)ᵀ. Berechnen Sie den Eintrag ∂g₃/∂x an der Stelle (2,1).",
    correctValue: 1,
    explanation: "g₃(x,y)=xy, also ∂g₃/∂x = y. Bei (2,1): y=1.",
    source: "Kapitel 8, Jacobi-Matrix",
    free: false,
  },

  // ---------- Treppenfunktionen, gleichmäßige Stetigkeit und Integrierbarkeit stetiger Funktionen ----------
  {
    id: "ts-01",
    topic: "Treppenfunktionen, gleichmäßige Stetigkeit und Integrierbarkeit stetiger Funktionen",
    type: "mc",
    prompt: "Was unterscheidet gleichmäßige Stetigkeit von gewöhnlicher Stetigkeit?",
    options: [
      "Bei gleichmäßiger Stetigkeit darf δ nicht vom betrachteten Punkt abhängen, nur von ε.",
      "Gleichmäßige Stetigkeit ist eine schwächere Eigenschaft als Stetigkeit.",
      "Gleichmäßige Stetigkeit gilt nur für Treppenfunktionen.",
      "Es gibt keinen Unterschied.",
    ],
    correctIndex: 0,
    explanation: "Bei gewöhnlicher Stetigkeit darf δ vom Punkt x abhängen, bei gleichmäßiger Stetigkeit muss ein einziges δ für alle Punkte funktionieren.",
    source: "Kapitel 9, Gleichmäßige Stetigkeit",
    free: true,
  },
  {
    id: "ts-02",
    topic: "Treppenfunktionen, gleichmäßige Stetigkeit und Integrierbarkeit stetiger Funktionen",
    type: "mc",
    prompt: "Was besagt der Satz von Heine?",
    options: [
      "Jede auf einer kompakten Menge stetige Funktion ist dort gleichmäßig stetig.",
      "Jede stetige Funktion ist überall gleichmäßig stetig.",
      "Jede gleichmäßig stetige Funktion ist beschränkt.",
      "Jede Treppenfunktion ist stetig.",
    ],
    correctIndex: 0,
    explanation: "Der Satz von Heine garantiert gleichmäßige Stetigkeit stetiger Funktionen speziell auf kompakten (abgeschlossenen und beschränkten) Mengen.",
    source: "Kapitel 9, Satz von Heine",
    free: false,
  },
  {
    id: "ts-03",
    topic: "Treppenfunktionen, gleichmäßige Stetigkeit und Integrierbarkeit stetiger Funktionen",
    type: "numeric",
    prompt: "Gegeben sei die Treppenfunktion h(x,y) := 2 falls x ≤ 1/2, sonst 6, auf [0,1]². Berechnen Sie ∫ h(x,y) d(x,y).",
    correctValue: 4,
    explanation: "∫h = 2·(1/2) + 6·(1/2) = 1 + 3 = 4.",
    source: "Kapitel 9, Treppenfunktionen",
    free: false,
  },
  {
    id: "ts-04",
    topic: "Treppenfunktionen, gleichmäßige Stetigkeit und Integrierbarkeit stetiger Funktionen",
    type: "mc",
    prompt: "Wie lautet der Mittelwertsatz für Integrale (M Jordan-messbar mit |M|>0, c≤f≤d auf M)?",
    options: [
      "Es gibt µ ∈ [c,d] mit (1/|M|)·∫_M f d⃗x = µ.",
      "Es gilt stets ∫_M f d⃗x = c·|M|.",
      "Es gilt stets ∫_M f d⃗x = d·|M|.",
      "µ liegt immer außerhalb von [c,d].",
    ],
    correctIndex: 0,
    explanation: "Der Mittelwertsatz für Integrale garantiert einen 'mittleren' Wert µ zwischen den Schranken c und d.",
    source: "Kapitel 9, Mittelwertsatz für Integrale",
    free: false,
  },
  {
    id: "ts-05",
    topic: "Treppenfunktionen, gleichmäßige Stetigkeit und Integrierbarkeit stetiger Funktionen",
    type: "numeric",
    prompt:
      "Es sei M Jordan-messbar mit |M|=3, f auf M integrierbar mit 1 ≤ f ≤ 5 und ∫_M f(⃗x) d⃗x = 9. Bestimmen Sie den Mittelwert µ = (1/|M|)·∫_M f(⃗x) d⃗x.",
    correctValue: 3,
    explanation: "µ = 9/3 = 3, und tatsächlich liegt µ=3 im Intervall [1,5], wie vom Mittelwertsatz gefordert.",
    source: "Kapitel 9, Mittelwertsatz für Integrale",
    free: false,
  },

  // ---------- Höhere Ableitungen und der Satz von Schwarz ----------
  {
    id: "hs-01",
    topic: "Höhere Ableitungen und der Satz von Schwarz",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := x³y² + 2xy. Berechnen Sie ∂²f/(∂x∂y) an der Stelle (1,1).",
    correctValue: 8,
    explanation: "f_y = 2x³y+2x, also f_yx = 6x²y+2. Bei (1,1): 6+2=8.",
    source: "Kapitel 10, Satz von Schwarz",
    free: true,
  },
  {
    id: "hs-02",
    topic: "Höhere Ableitungen und der Satz von Schwarz",
    type: "mc",
    prompt: "Welche Voraussetzung benötigt der Satz von Schwarz, damit fₓᵧ = fᵧₓ gilt?",
    options: [
      "f muss von der Klasse C² sein (alle zweiten partiellen Ableitungen existieren und sind stetig).",
      "f muss nur partiell differenzierbar sein.",
      "f muss beschränkt sein.",
      "f muss ein Polynom sein.",
    ],
    correctIndex: 0,
    explanation: "Der Satz von Schwarz benötigt Stetigkeit der zweiten partiellen Ableitungen (C²), sonst kann fₓᵧ ≠ fᵧₓ gelten.",
    source: "Kapitel 10, Satz von Schwarz",
    free: false,
  },
  {
    id: "hs-03",
    topic: "Höhere Ableitungen und der Satz von Schwarz",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := e^{xy} + x². Berechnen Sie ∂²f/∂x²(0,1).",
    correctValue: 3,
    explanation: "f_x = y·e^{xy}+2x, f_xx = y²e^{xy}+2. Bei (0,1): 1·1+2=3.",
    source: "Kapitel 10, Höhere Ableitungen",
    free: false,
  },
  {
    id: "hs-04",
    topic: "Höhere Ableitungen und der Satz von Schwarz",
    type: "mc",
    prompt: "Für f(x,y) := xy(x²−y²)/(x²+y²) (f(0,0):=0) gilt fₓᵧ(0,0)=1 ≠ −1=fᵧₓ(0,0). Was folgt daraus notwendigerweise?",
    options: [
      "Mindestens eine der beiden gemischten zweiten Ableitungen ist im Ursprung nicht stetig.",
      "f ist im Ursprung nicht partiell differenzierbar.",
      "f ist unstetig im Ursprung.",
      "Der Satz von Schwarz enthält einen Fehler.",
    ],
    correctIndex: 0,
    explanation: "Da der Satz von Schwarz unter C²-Voraussetzung fₓᵧ=fᵧₓ garantiert, muss hier die Stetigkeitsvoraussetzung verletzt sein.",
    source: "Kapitel 10, Satz von Schwarz",
    free: false,
  },
  {
    id: "hs-05",
    topic: "Höhere Ableitungen und der Satz von Schwarz",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := sin(xy) + y³. Berechnen Sie ∂²f/∂y²(0,1).",
    correctValue: 6,
    explanation: "f_y = x·cos(xy) + 3y², f_yy = −x²sin(xy) + 6y. Bei (0,1): 0+6=6.",
    source: "Kapitel 10, Höhere Ableitungen",
    free: false,
  },

  // ---------- Der Gradient als Richtung des steilsten Anstiegs ----------
  {
    id: "gs-01",
    topic: "Der Gradient als Richtung des steilsten Anstiegs",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := (x²+y²)·e^{−x²}. Bestimmen Sie ‖∇f(0,1)‖₂ (die maximale Anstiegsrate im Punkt (0,1)).",
    correctValue: 2,
    explanation: "∂f/∂x = 2x·e^{−x²} − 2x(x²+y²)e^{−x²}, bei x=0 gleich 0. ∂f/∂y = 2y·e^{−x²}, bei (0,1) gleich 2. Also ‖∇f(0,1)‖₂ = 2.",
    source: "Kapitel 11, Steilster Anstieg",
    free: true,
  },
  {
    id: "gs-02",
    topic: "Der Gradient als Richtung des steilsten Anstiegs",
    type: "mc",
    prompt: "In welche Richtung zeigt der steilste Abstieg von f in ⃗x₀ (bei ∇f(⃗x₀)≠⃗0)?",
    options: ["−∇f(⃗x₀)/‖∇f(⃗x₀)‖₂", "∇f(⃗x₀)/‖∇f(⃗x₀)‖₂", "Senkrecht zu ∇f(⃗x₀), im Uhrzeigersinn", "Es gibt keine eindeutige Richtung"],
    correctIndex: 0,
    explanation: "Der steilste Abstieg zeigt in die dem Gradienten entgegengesetzte Richtung.",
    source: "Kapitel 11, Steilster Anstieg",
    free: false,
  },
  {
    id: "gs-03",
    topic: "Der Gradient als Richtung des steilsten Anstiegs",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := x² + 4y². Bestimmen Sie die Anstiegsrate ‖∇f(1,1)‖₂ (steilster Anstieg).",
    correctValue: 8.246,
    tolerance: 0.01,
    explanation: "∇f(1,1) = (2,8)ᵀ, ‖∇f(1,1)‖₂ = √(4+64) = √68 ≈ 8,246.",
    source: "Kapitel 11, Steilster Anstieg",
    free: false,
  },
  {
    id: "gs-04",
    topic: "Der Gradient als Richtung des steilsten Anstiegs",
    type: "mc",
    prompt: "Warum steht der Gradient ∇f(⃗x₀) senkrecht auf der Höhenlinie durch ⃗x₀?",
    options: [
      "Weil die Richtungsableitung tangential zur Höhenlinie verschwindet (f ändert sich dort nicht) und der Gradient über das Skalarprodukt genau diese Richtungen ausblendet.",
      "Weil Höhenlinien immer Kreise sind.",
      "Weil der Gradient per Definition eine Tangente an die Höhenlinie ist.",
      "Das ist nur ein Zufall bei quadratischen Funktionen.",
    ],
    correctIndex: 0,
    explanation: "Da ⟨∇f(⃗x₀), ⃗v⟩=0 für jede Tangentialrichtung ⃗v an die Höhenlinie gilt, muss ∇f(⃗x₀) orthogonal zu allen solchen ⃗v, also zur Höhenlinie, stehen.",
    source: "Kapitel 11, Gradient und Höhenlinien",
    free: false,
  },
  {
    id: "gs-05",
    topic: "Der Gradient als Richtung des steilsten Anstiegs",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := 3x² + y². Bestimmen Sie die erste Komponente des normierten Richtungsvektors ⃗v₀ des steilsten Anstiegs im Punkt (1,2).",
    correctValue: 0.832,
    tolerance: 0.01,
    explanation: "∇f(1,2) = (6,4)ᵀ, ‖∇f(1,2)‖₂ = √52 = 2√13. Erste Komponente von ⃗v₀ = 6/(2√13) = 3/√13 ≈ 0,832.",
    source: "Kapitel 11, Steilster Anstieg",
    free: false,
  },

  // ---------- Der Transformationssatz und Koordinatenwechsel ----------
  {
    id: "tk-01",
    topic: "Der Transformationssatz und Koordinatenwechsel",
    type: "numeric",
    prompt:
      "Gegeben sei B := {(x,y) ∈ ℝ² : x ≤ 0, x²+y² ≤ 16} (linke Hälfte einer Kreisscheibe vom Radius 4). Berechnen Sie ∫_B √(x²+y²) d(x,y) mithilfe von Polarkoordinaten.",
    correctValue: 67.02,
    tolerance: 0.1,
    explanation: "In Polarkoordinaten: ∫_{π/2}^{3π/2} ∫₀⁴ r·r dr dφ = π·[r³/3]₀⁴ = π·64/3 ≈ 67,02.",
    source: "Kapitel 12, Polarkoordinaten",
    free: true,
  },
  {
    id: "tk-02",
    topic: "Der Transformationssatz und Koordinatenwechsel",
    type: "numeric",
    prompt: "Berechnen Sie mithilfe von Kugelkoordinaten das Volumen einer Kugel vom Radius R=2.",
    correctValue: 33.51,
    tolerance: 0.05,
    explanation: "Volumen einer Kugel = (4/3)πR³ = (4/3)π·8 = 32π/3 ≈ 33,51.",
    source: "Kapitel 12, Kugelkoordinaten",
    free: false,
  },
  {
    id: "tk-03",
    topic: "Der Transformationssatz und Koordinatenwechsel",
    type: "mc",
    prompt: "Wie lautet die Jacobi-Determinante der Kugelkoordinaten T(r,ϑ,φ) = (r sinϑ cosφ, r sinϑ sinφ, r cosϑ)?",
    options: ["r²·sin(ϑ)", "r·sin(ϑ)", "r²", "r"],
    correctIndex: 0,
    explanation: "Die Jacobi-Determinante der Kugelkoordinaten ist r²·sin(ϑ).",
    source: "Kapitel 12, Kugelkoordinaten",
    free: false,
  },
  {
    id: "tk-04",
    topic: "Der Transformationssatz und Koordinatenwechsel",
    type: "numeric",
    prompt: "Berechnen Sie mithilfe von Polarkoordinaten den Flächeninhalt eines Viertelkreises mit Radius 5.",
    correctValue: 19.63,
    tolerance: 0.05,
    explanation: "Flächeninhalt = (1/4)·π·5² = 25π/4 ≈ 19,63.",
    source: "Kapitel 12, Polarkoordinaten",
    free: false,
  },
  {
    id: "tk-05",
    topic: "Der Transformationssatz und Koordinatenwechsel",
    type: "mc",
    prompt: "Warum darf der Faktor r beim Übergang zu Polarkoordinaten im Integral nicht vergessen werden?",
    options: [
      "Weil er die Jacobi-Determinante der Transformation ist, die nach dem Transformationssatz zwingend im Integranden auftritt.",
      "Weil r immer gleich 1 ist und daher irrelevant erscheint.",
      "Weil er nur bei negativen Radien benötigt wird.",
      "Weil er ausschließlich bei Kugelkoordinaten auftritt.",
    ],
    correctIndex: 0,
    explanation: "Der Transformationssatz verlangt den Betrag der Jacobi-Determinante als zusätzlichen Faktor — bei Polarkoordinaten ist das genau r.",
    source: "Kapitel 12, Transformationssatz",
    free: false,
  },

  // ---------- Taylorpolynome und der Mittelwertsatz im Rⁿ ----------
  {
    id: "tm-01",
    topic: "Taylorpolynome und der Mittelwertsatz im Rⁿ",
    type: "numeric",
    prompt:
      "Gegeben sei f(x,y) := x³ + y² und ⃗x₀ = (1,2). Bestimmen Sie den Koeffizienten von (x−1) im Taylorpolynom T₂ von f um ⃗x₀ (also ∂f/∂x(⃗x₀)).",
    correctValue: 3,
    explanation: "∂f/∂x(x,y) = 3x², bei (1,2): 3·1 = 3.",
    source: "Kapitel 13, Taylorpolynome",
    free: true,
  },
  {
    id: "tm-02",
    topic: "Taylorpolynome und der Mittelwertsatz im Rⁿ",
    type: "mc",
    prompt: "Wie lautet der Mittelwertsatz im ℝⁿ für differenzierbares f und Punkte ⃗a, ⃗x mit Verbindungsstrecke in D?",
    options: [
      "Es gibt ϑ ∈ (0,1) mit f(⃗x) = f(⃗a) + ⟨∇f(⃗a+ϑ(⃗x−⃗a)), ⃗x−⃗a⟩.",
      "Es gilt stets f(⃗x) = f(⃗a) + ⟨∇f(⃗x), ⃗x−⃗a⟩.",
      "Es gibt ϑ ∈ (0,1) mit f(⃗x) = f(⃗a)·ϑ.",
      "f(⃗x) = f(⃗a) für alle differenzierbaren f.",
    ],
    correctIndex: 0,
    explanation: "Der Mittelwertsatz im ℝⁿ verallgemeinert den eindimensionalen MWS über die Schnittfunktion entlang der Verbindungsstrecke.",
    source: "Kapitel 13, Mittelwertsatz im ℝⁿ",
    free: false,
  },
  {
    id: "tm-03",
    topic: "Taylorpolynome und der Mittelwertsatz im Rⁿ",
    type: "numeric",
    prompt: "Es sei f : ℝ³ → ℝ differenzierbar mit ∇f(⃗x)=⃗0 für alle ⃗x und f(⃗0)=7. Bestimmen Sie f(5,5,5).",
    correctValue: 7,
    explanation: "Verschwindet der Gradient überall auf einer konvexen Menge, ist f nach dem Mittelwertsatz konstant, also f(5,5,5)=f(0,0,0)=7.",
    source: "Kapitel 13, Mittelwertsatz im ℝⁿ",
    free: false,
  },
  {
    id: "tm-04",
    topic: "Taylorpolynome und der Mittelwertsatz im Rⁿ",
    type: "numeric",
    prompt:
      "Gegeben sei f(x,y) := x²y mit Hf(1,1) = ((2,2);(2,0)). Berechnen Sie den quadratischen Taylorterm ½·(Δx,Δy)·Hf(1,1)·(Δx,Δy)ᵀ für (Δx,Δy) = (1,0).",
    correctValue: 1,
    explanation: "½·(1,0)·((2,2);(2,0))·(1,0)ᵀ = ½·(2·1+2·0) = ½·2 = 1.",
    source: "Kapitel 13, Taylorpolynome",
    free: false,
  },
  {
    id: "tm-05",
    topic: "Taylorpolynome und der Mittelwertsatz im Rⁿ",
    type: "mc",
    prompt: "Welchen maximalen Grad hat das Taylorpolynom T₂(⃗x;f;⃗x₀) als Polynom in (⃗x−⃗x₀)?",
    options: ["2", "1", "3", "Es hat keinen festen Grad"],
    correctIndex: 0,
    explanation: "T₂ besteht aus konstantem, linearem und quadratischem Term — Grad höchstens 2.",
    source: "Kapitel 13, Taylorpolynome",
    free: false,
  },

  // ---------- Lokale Extrema, die Hessematrix und Sattelpunkte ----------
  {
    id: "he-01",
    topic: "Lokale Extrema, die Hessematrix und Sattelpunkte",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := x⁴ + y⁴ − 18x² − 18y². Berechnen Sie min f(ℝ²).",
    correctValue: -162,
    explanation:
      "∇f=⃗0 für x,y∈{−3,0,3}. Die Hessematrix ist in (±3,±3) positiv definit (lokale Minima) mit f(3,3)=81+81−162−162=−162; dies ist wegen f(x,y)→∞ für ‖(x,y)‖₂→∞ das globale Minimum.",
    source: "Kapitel 14, Lokale Extrema",
    free: true,
  },
  {
    id: "he-02",
    topic: "Lokale Extrema, die Hessematrix und Sattelpunkte",
    type: "mc",
    prompt: "Ist Hf(⃗x₀) in einem stationären Punkt ⃗x₀ indefinit, welche Art von Punkt liegt vor?",
    options: ["Ein Sattelpunkt", "Eine strenge lokale Minimalstelle", "Eine strenge lokale Maximalstelle", "Keine Aussage möglich"],
    correctIndex: 0,
    explanation: "Indefinite Hessematrix bedeutet, dass f in manchen Richtungen wächst und in anderen fällt — genau die Definition eines Sattelpunkts.",
    source: "Kapitel 14, Hessematrix",
    free: false,
  },
  {
    id: "he-03",
    topic: "Lokale Extrema, die Hessematrix und Sattelpunkte",
    type: "mc",
    prompt: "Gegeben sei f(x,y) := x³ − 6xy² (ein 'Affensattel'). Was liefert die Hessematrix von f im Ursprung?",
    options: [
      "Sie ist semidefinit, aber nicht definit — keine Entscheidung über den stationären Punkt möglich.",
      "Sie ist positiv definit — lokales Minimum.",
      "Sie ist negativ definit — lokales Maximum.",
      "Sie ist indefinit — Sattelpunkt.",
    ],
    correctIndex: 0,
    explanation: "Hf(0,0) ist hier die Nullmatrix (fₓₓ=fₓᵧ=fᵧᵧ=0 im Ursprung), also positiv und negativ semidefinit zugleich, aber nicht definit — obwohl f dort tatsächlich keine Extremstelle besitzt.",
    source: "Kapitel 14, Sattelpunkte",
    free: false,
  },
  {
    id: "he-04",
    topic: "Lokale Extrema, die Hessematrix und Sattelpunkte",
    type: "numeric",
    prompt: "Gegeben sei f(x,y) := e^{2xy} + 3x. Bestimmen Sie die y-Koordinate des (einzigen) stationären Punkts von f.",
    correctValue: -1.5,
    explanation: "∇f=(2y·e^{2xy}+3, 2x·e^{2xy}). Aus der zweiten Gleichung folgt x=0 (da e^{2xy}≠0), eingesetzt in die erste: 2y+3=0, also y=−1,5.",
    source: "Kapitel 14, Stationäre Punkte",
    free: false,
  },
  {
    id: "he-05",
    topic: "Lokale Extrema, die Hessematrix und Sattelpunkte",
    type: "mc",
    prompt: "Wann ist eine symmetrische 2×2-Matrix H = ((a,b);(b,c)) indefinit?",
    options: ["Wenn det(H) = ac−b² < 0 gilt.", "Wenn det(H) > 0 gilt.", "Wenn a > 0 und c > 0 gelten.", "Wenn a = c gilt."],
    correctIndex: 0,
    explanation: "Eine negative Determinante bedeutet unterschiedliche Vorzeichen der Eigenwerte — genau die Definition von indefinit.",
    source: "Kapitel 14, Hessematrix",
    free: false,
  },
];
