export type QuestionType = "mc" | "numeric";

export interface Question {
  id: string;
  topic: string;
  type: QuestionType;
  prompt: string;
  options?: string[];
  correctIndex?: number;
  correctValue?: number;
  tolerance?: number;
  unit?: string;
  explanation: string;
  source: string;
  free: boolean;
}

// Hinweis: Alle Übungsaufgaben in dieser Fragenbank sind gegenüber echten
// Tutorien-/Klausuraufgaben sowohl in den Zahlenwerten als auch (soweit ein
// konkretes Szenario vorlag) im Szenario selbst verändert. Rein abstrakte,
// symbolische Aufgaben (Mengen, Folgen, Reihen etc. ohne erzähltes Szenario)
// wurden nur in den Zahlen verändert.
export const TOPICS = [
  "Aussagenlogik",
  "Mengenlehre",
  "Gruppen, Ringe, Körper",
  "Relationen",
  "Vollständige Induktion",
  "Abbildungen",
  "Kombinatorik & Laplace",
  "Reelle Zahlen",
  "Folgen: Grenzwerte",
  "Folgen: Monotonie & Cauchy",
  "Reihen",
  "Potenzreihen",
  "Spezielle Funktionen",
] as const;

export const questions: Question[] = [
  // ---------- Aussagenlogik ----------
  {
    id: "al-01",
    topic: "Aussagenlogik",
    type: "mc",
    prompt:
      "Welchen Wahrheitswert hat die Aussage 'Wenn 4 eine ungerade Zahl ist, dann ist 10 eine Primzahl'?",
    options: [
      "Wahr, da die Prämisse falsch ist",
      "Falsch, da die Konklusion falsch ist",
      "Wahr, da die Konklusion falsch ist",
      "Nicht bestimmbar",
    ],
    correctIndex: 0,
    explanation:
      "A ⇒ B ist nur falsch, wenn A wahr und B falsch ist. Hier ist A ('4 ist ungerade') bereits falsch, also ist die Implikation unabhängig vom Wahrheitswert von B wahr.",
    source: "Kapitel 1, Aussagenlogik",
    free: true,
  },
  {
    id: "al-02",
    topic: "Aussagenlogik",
    type: "mc",
    prompt: "Was ist die Negation der Aussage 'x > 5 und y < 2'?",
    options: ["x ≤ 5 und y ≥ 2", "x ≤ 5 oder y ≥ 2", "x > 5 oder y < 2", "x ≤ 5 oder y < 2"],
    correctIndex: 1,
    explanation:
      "Nach De Morgan gilt ¬(A ∧ B) ⇔ ¬A ∨ ¬B. Die Negation von 'x > 5' ist 'x ≤ 5', die von 'y < 2' ist 'y ≥ 2', verknüpft mit 'oder'.",
    source: "Kapitel 1, Aussagenlogik",
    free: true,
  },
  {
    id: "al-03",
    topic: "Aussagenlogik",
    type: "mc",
    prompt: "Welcher der folgenden Sätze ist eine Aussage im Sinne der Aussagenlogik?",
    options: [
      "Ist 12 durch 4 teilbar?",
      "12 ist durch 4 teilbar.",
      "Teile 12 durch 4!",
      "x ist durch 4 teilbar",
    ],
    correctIndex: 1,
    explanation:
      "Nur '12 ist durch 4 teilbar.' hat einen eindeutigen Wahrheitswert (wahr). Fragen und Befehle sind keine Aussagen, und 'x ist durch 4 teilbar' enthält eine freie Variable x ohne festgelegten Wert.",
    source: "Kapitel 1, Aussagenlogik",
    free: true,
  },
  {
    id: "al-04",
    topic: "Aussagenlogik",
    type: "mc",
    prompt:
      "Wie lautet die Kontraposition der Aussage 'Ist n durch 6 teilbar, so ist n durch 3 teilbar'?",
    options: [
      "Ist n durch 3 teilbar, so ist n durch 6 teilbar.",
      "Ist n nicht durch 3 teilbar, so ist n nicht durch 6 teilbar.",
      "Ist n nicht durch 6 teilbar, so ist n nicht durch 3 teilbar.",
      "Ist n nicht durch 6 teilbar, so ist n durch 3 teilbar.",
    ],
    correctIndex: 1,
    explanation:
      "Die Kontraposition von A ⇒ B ist ¬B ⇒ ¬A. Mit A = 'n durch 6 teilbar' und B = 'n durch 3 teilbar' ergibt sich: 'Ist n nicht durch 3 teilbar, so ist n nicht durch 6 teilbar.'",
    source: "Kapitel 1, Aussagenlogik",
    free: true,
  },
  {
    id: "al-05",
    topic: "Aussagenlogik",
    type: "mc",
    prompt: "Für welche Wahrheitswertbelegung von A und B ist die Implikation A ⇒ B falsch?",
    options: ["A wahr, B wahr", "A wahr, B falsch", "A falsch, B wahr", "A falsch, B falsch"],
    correctIndex: 1,
    explanation:
      "A ⇒ B ist per Definition genau dann falsch, wenn A wahr und B falsch ist — in allen anderen drei Fällen ist die Implikation wahr.",
    source: "Kapitel 1, Aussagenlogik",
    free: true,
  },

  // ---------- Mengenlehre ----------
  {
    id: "me-01",
    topic: "Mengenlehre",
    type: "numeric",
    prompt: "Sei A := {p, q}. Bestimmen Sie |P(A × A)|.",
    correctValue: 16,
    explanation:
      "Es gilt |A × A| = 2 · 2 = 4, womit |P(A×A)| = 2⁴ = 16 folgt.",
    source: "Kapitel 2, Mengenlehre",
    free: true,
  },
  {
    id: "me-02",
    topic: "Mengenlehre",
    type: "numeric",
    prompt:
      "Von 800 Beschäftigten eines Unternehmens nutzen 350 die Kantine A, 260 die Kantine B und 150 die Kantine C. Davon nutzen 70 sowohl A als auch B, 60 sowohl A als auch C, 20 sowohl B als auch C, und 10 nutzen alle drei Kantinen. Wie viele Beschäftigte nutzen mindestens eine der drei Kantinen?",
    correctValue: 620,
    explanation:
      "Inklusions-Exklusions-Prinzip: |A∪B∪C| = 350+260+150 − (70+60+20) + 10 = 760 − 150 + 10 = 620.",
    source: "Übungsaufgabe, Mengenoperationen",
    free: true,
  },
  {
    id: "me-03",
    topic: "Mengenlehre",
    type: "mc",
    prompt: "Für Teilmengen A, B einer Grundmenge Ω gilt (A ∩ B)ᶜ = ?",
    options: ["Aᶜ ∩ Bᶜ", "Aᶜ ∪ Bᶜ", "A ∪ B", "(A ∪ B)ᶜ"],
    correctIndex: 1,
    explanation: "Regel von De Morgan für Mengen: (A ∩ B)ᶜ = Aᶜ ∪ Bᶜ.",
    source: "Kapitel 2, Mengenlehre",
    free: false,
  },
  {
    id: "me-04",
    topic: "Mengenlehre",
    type: "numeric",
    prompt: "Sei M := {n ∈ Z : n² ≤ 25}. Wie viele Elemente hat M?",
    correctValue: 11,
    explanation:
      "n² ≤ 25 ⇔ −5 ≤ n ≤ 5. Das sind die 11 ganzen Zahlen −5, −4, ..., 4, 5.",
    source: "Kapitel 2, Mengenlehre",
    free: false,
  },
  {
    id: "me-05",
    topic: "Mengenlehre",
    type: "numeric",
    prompt: "Seien A, B Mengen mit |A| = 5 und |B| = 7. Wie groß ist |A × B|?",
    correctValue: 35,
    explanation: "|A × B| = |A| · |B| = 5 · 7 = 35.",
    source: "Kapitel 2, Mengenlehre",
    free: false,
  },

  // ---------- Gruppen, Ringe, Körper ----------
  {
    id: "gr-01",
    topic: "Gruppen, Ringe, Körper",
    type: "mc",
    prompt: "Welches der folgenden Verknüpfungsgebilde ist KEINE Gruppe?",
    options: ["(Z, +)", "(N, +)", "(Q \\ {0}, ·)", "(R, +)"],
    correctIndex: 1,
    explanation:
      "(N, +) ist zwar eine Halbgruppe, besitzt aber weder ein neutrales Element in N noch inverse Elemente (zu 3 gibt es kein n ∈ N mit 3+n=0) — also keine Gruppe.",
    source: "Kapitel 3, Gruppen",
    free: false,
  },
  {
    id: "gr-02",
    topic: "Gruppen, Ringe, Körper",
    type: "mc",
    prompt:
      "Auf G := {w, x, y, z} sei eine kommutative Verknüpfung ∘ gegeben, bei der w das neutrale Element ist, jedes Element sein eigenes Inverses ist, und x ∘ y = z gilt. Bestimmen Sie y ∘ z.",
    options: ["w", "x", "y", "z"],
    correctIndex: 1,
    explanation:
      "Da jedes Element sein eigenes Inverses ist und x∘y=z gilt, folgt mit Assoziativität und Kommutativität: y∘z = y∘(x∘y) = x∘(y∘y) = x∘w = x.",
    source: "Übungsaufgabe, Gruppentafel",
    free: false,
  },
  {
    id: "gr-03",
    topic: "Gruppen, Ringe, Körper",
    type: "mc",
    prompt:
      "Welche Eigenschaft besitzt ein Körper zusätzlich zu einem kommutativen Ring mit Eins?",
    options: [
      "Die Addition ist kommutativ",
      "Jedes Element außer 0 besitzt ein multiplikatives Inverses",
      "Es gibt ein neutrales Element der Addition",
      "Die Multiplikation ist assoziativ",
    ],
    correctIndex: 1,
    explanation:
      "Ein Körper ist ein kommutativer Ring mit Eins, in dem (K\\{0}, ·) zusätzlich eine abelsche Gruppe ist — jedes Element außer 0 hat also ein multiplikatives Inverses.",
    source: "Kapitel 3, Körper",
    free: false,
  },
  {
    id: "gr-04",
    topic: "Gruppen, Ringe, Körper",
    type: "mc",
    prompt: "Ist (Z, +, ·) ein Körper?",
    options: [
      "Ja, da Z ein kommutativer Ring mit Eins ist",
      "Nein, da 2 kein multiplikatives Inverses in Z besitzt",
      "Ja, da Z eine abelsche Gruppe bezüglich + ist",
      "Nein, da + auf Z nicht assoziativ ist",
    ],
    correctIndex: 1,
    explanation:
      "Z ist zwar ein kommutativer Ring mit Eins, aber kein Körper: Es gibt kein n ∈ Z mit 2 · n = 1, also fehlt das multiplikative Inverse zu 2.",
    source: "Kapitel 3, Körper",
    free: false,
  },

  // ---------- Relationen ----------
  {
    id: "re-01",
    topic: "Relationen",
    type: "numeric",
    prompt: "Sei A eine Menge mit |A| = 4. Wie viele verschiedene reflexive Relationen gibt es auf A?",
    correctValue: 4096,
    explanation:
      "Eine Relation R ⊂ A×A ist reflexiv, wenn sie alle 4 Diagonalelemente enthält. Über die restlichen 16−4=12 Elemente kann frei entschieden werden: 2¹² = 4096.",
    source: "Kapitel 4, Relationen",
    free: false,
  },
  {
    id: "re-02",
    topic: "Relationen",
    type: "mc",
    prompt:
      "Auf Z sei die Relation x R y :⇔ ∃k ∈ Z: x = y + 4k + 2 definiert. Welche Eigenschaften besitzt R?",
    options: [
      "nur reflexiv",
      "nur symmetrisch",
      "reflexiv und transitiv",
      "symmetrisch und transitiv",
    ],
    correctIndex: 1,
    explanation:
      "Reflexivität scheitert, da 0 = 4k+2 keine ganzzahlige Lösung hat. Symmetrie gilt: aus x=y+4k+2 folgt y=x+4(−k−1)+2. Transitivität scheitert, da die Summe zweier Differenzen der Form 4k+2 stets ≡ 0 (statt 2) mod 4 ist.",
    source: "Übungsaufgabe, Relationseigenschaften",
    free: false,
  },
  {
    id: "re-03",
    topic: "Relationen",
    type: "numeric",
    prompt: "Wie viele Äquivalenzklassen besitzt die Kongruenzrelation modulo 5 auf Z?",
    correctValue: 5,
    explanation: "Modulo 5 zerfällt Z in genau 5 Äquivalenzklassen: [0], [1], [2], [3], [4].",
    source: "Kapitel 4, Äquivalenzrelationen",
    free: false,
  },
  {
    id: "re-04",
    topic: "Relationen",
    type: "mc",
    prompt: "Welche drei Eigenschaften muss eine Ordnungsrelation besitzen?",
    options: [
      "reflexiv, symmetrisch, transitiv",
      "reflexiv, antisymmetrisch, transitiv",
      "symmetrisch, antisymmetrisch, transitiv",
      "reflexiv, symmetrisch, antisymmetrisch",
    ],
    correctIndex: 1,
    explanation: "Eine Ordnungsrelation ist per Definition reflexiv, antisymmetrisch und transitiv.",
    source: "Kapitel 4, Ordnungsrelationen",
    free: false,
  },
  {
    id: "re-05",
    topic: "Relationen",
    type: "numeric",
    prompt:
      "Auf M := {1,...,6} sei x ~ y :⇔ x mod 3 = y mod 3. Wie viele Äquivalenzklassen besitzt diese Relation?",
    correctValue: 3,
    explanation: "Die Reste modulo 3 teilen M in {3,6} (Rest 0), {1,4} (Rest 1) und {2,5} (Rest 2) ein — 3 Klassen.",
    source: "Übungsaufgabe, Äquivalenzklassen",
    free: false,
  },

  // ---------- Vollständige Induktion ----------
  {
    id: "in-01",
    topic: "Vollständige Induktion",
    type: "numeric",
    prompt: "Berechnen Sie mit der Formel Σ_{k=1}^{n} k² = n(n+1)(2n+1)/6 den Wert für n = 10.",
    correctValue: 385,
    explanation: "10·11·21/6 = 2310/6 = 385.",
    source: "Kapitel 5, Vollständige Induktion",
    free: false,
  },
  {
    id: "in-02",
    topic: "Vollständige Induktion",
    type: "numeric",
    prompt: "Berechnen Sie 1 + 2 + ... + 40 mithilfe der Gaußschen Summenformel.",
    correctValue: 820,
    explanation: "Σ_{k=1}^{40} k = 40·41/2 = 820.",
    source: "Kapitel 5, Vollständige Induktion",
    free: false,
  },
  {
    id: "in-03",
    topic: "Vollständige Induktion",
    type: "mc",
    prompt: "Für welche x ∈ R gilt die Bernoulli-Ungleichung (1+x)ⁿ ≥ 1 + n·x für alle n ∈ N₀?",
    options: ["x ≥ 0", "x ≥ −1", "x ≤ 1", "alle x ∈ R"],
    correctIndex: 1,
    explanation: "Die Bernoulli-Ungleichung gilt für alle x ≥ −1 (und alle n ∈ N₀).",
    source: "Kapitel 5, Vollständige Induktion",
    free: false,
  },
  {
    id: "in-04",
    topic: "Vollständige Induktion",
    type: "mc",
    prompt: "Welche zwei Bestandteile besitzt ein Beweis durch vollständige Induktion?",
    options: [
      "Existenzbeweis und Eindeutigkeitsbeweis",
      "Induktionsanfang und Induktionsschritt",
      "Kontraposition und Widerspruchsbeweis",
      "Hinreichende und notwendige Bedingung",
    ],
    correctIndex: 1,
    explanation:
      "Ein Induktionsbeweis besteht aus dem Induktionsanfang (Nachweis für den kleinsten Index) und dem Induktionsschritt (Nachweis von A(n) ⇒ A(n+1)).",
    source: "Kapitel 5, Vollständige Induktion",
    free: false,
  },
  {
    id: "in-05",
    topic: "Vollständige Induktion",
    type: "numeric",
    prompt: "Wie groß ist die Summe der ersten 15 ungeraden natürlichen Zahlen (1+3+5+...)?",
    correctValue: 225,
    explanation: "Es gilt Σ_{k=1}^{n}(2k−1) = n². Für n=15 ergibt sich 15² = 225.",
    source: "Kapitel 5, Vollständige Induktion",
    free: false,
  },

  // ---------- Abbildungen ----------
  {
    id: "ab-01",
    topic: "Abbildungen",
    type: "numeric",
    prompt:
      "Auf M := {a,b,c,d,e,f,g} sei g: M → R gegeben durch g(a)=4, g(b)=4, g(c)=9, g(d)=9, g(e)=9, g(f)=15, g(g)=20. Wie groß ist |Bild(g)|?",
    correctValue: 4,
    explanation: "Bild(g) = {4, 9, 15, 20}, also |Bild(g)| = 4.",
    source: "Übungsaufgabe, Bild und Urbild",
    free: false,
  },
  {
    id: "ab-02",
    topic: "Abbildungen",
    type: "numeric",
    prompt:
      "Mit derselben Abbildung g wie oben: Wie groß ist |g⁻¹({9})|?",
    correctValue: 3,
    explanation: "g⁻¹({9}) = {c, d, e}, also |g⁻¹({9})| = 3.",
    source: "Übungsaufgabe, Bild und Urbild",
    free: false,
  },
  {
    id: "ab-03",
    topic: "Abbildungen",
    type: "numeric",
    prompt:
      "Mit derselben Abbildung g (Definitionsbereich M mit |M|=7, g(a)=g(b)=4): Wie viele Teilmengen A ⊂ M erfüllen 4 ∈ g(A)?",
    correctValue: 96,
    explanation:
      "4 ∈ g(A) gilt genau dann, wenn a ∈ A oder b ∈ A. Von den restlichen 5 Elementen darf beliebig ausgewählt werden: 2⁷ − 2⁵ = 128 − 32 = 96.",
    source: "Übungsaufgabe, Bild und Urbild",
    free: false,
  },
  {
    id: "ab-04",
    topic: "Abbildungen",
    type: "mc",
    prompt:
      "Sei f: (0,∞) → (0,∞) definiert durch f(x) = 1/x für x ∈ (0,1] und f(x) = x−1 für x > 1. Ist f injektiv bzw. surjektiv?",
    options: [
      "injektiv, nicht surjektiv",
      "nicht injektiv, surjektiv",
      "injektiv und surjektiv",
      "weder injektiv noch surjektiv",
    ],
    correctIndex: 1,
    explanation:
      "f(1) = 1 und f(2) = 1, also nicht injektiv. Da x ↦ x−1 für x>1 bereits alle Werte in (0,∞) durchläuft, ist f surjektiv.",
    source: "Übungsaufgabe, Injektivität und Surjektivität",
    free: false,
  },
  {
    id: "ab-05",
    topic: "Abbildungen",
    type: "mc",
    prompt: "Seien f: A → B und g: B → C beide surjektiv. Ist g ∘ f dann surjektiv?",
    options: ["Ja, immer", "Nein, nie", "Nur wenn A = C", "Nicht bestimmbar"],
    correctIndex: 0,
    explanation:
      "Ist g surjektiv, wird jedes c ∈ C von einem b ∈ B getroffen; ist f surjektiv, wird jedes solche b von einem a ∈ A getroffen. Also ist g∘f surjektiv.",
    source: "Kapitel 6, Abbildungen",
    free: false,
  },
  {
    id: "ab-06",
    topic: "Abbildungen",
    type: "numeric",
    prompt: "Wie viele injektive Abbildungen gibt es von einer Menge mit 3 Elementen in eine Menge mit 5 Elementen?",
    correctValue: 60,
    explanation: "Für das erste Element gibt es 5, für das zweite 4, für das dritte 3 Möglichkeiten: 5·4·3 = 60.",
    source: "Kapitel 6, Abbildungen",
    free: false,
  },

  // ---------- Kombinatorik & Laplace ----------
  {
    id: "ko-01",
    topic: "Kombinatorik & Laplace",
    type: "numeric",
    prompt: "Wie viele verschiedene Anordnungen der Buchstaben des Wortes BANANE gibt es?",
    correctValue: 180,
    explanation:
      "BANANE hat 6 Buchstaben, davon A zweimal und N zweimal: 6!/(2!·2!) = 720/4 = 180.",
    source: "Kapitel 7, Kombinatorik",
    free: false,
  },
  {
    id: "ko-02",
    topic: "Kombinatorik & Laplace",
    type: "numeric",
    prompt:
      "Ein Fuhrunternehmen hat 12 Stellplätze in einer Reihe für 5 Kleintransporter, 4 Lastwagen und 3 Anhänger (Fahrzeuge desselben Typs gelten als nicht unterscheidbar). Wie viele verschiedene Anordnungen der Fahrzeuge gibt es?",
    correctValue: 27720,
    explanation: "12!/(5!·4!·3!) = 479001600/17280 = 27720.",
    source: "Kapitel 7, Kombinatorik",
    free: false,
  },
  {
    id: "ko-03",
    topic: "Kombinatorik & Laplace",
    type: "numeric",
    prompt:
      "Ein Kleinstaat führt Kennzeichen ein, die aus 3 Buchstaben (aus K, F, T, mit Wiederholung, Reihenfolge zählt) gefolgt von 4 Ziffern (0–9, mit Wiederholung) bestehen. Wie viele verschiedene Kennzeichen sind möglich?",
    correctValue: 270000,
    explanation: "3³ · 10⁴ = 27 · 10000 = 270000.",
    source: "Kapitel 7, Kombinatorik",
    free: false,
  },
  {
    id: "ko-04",
    topic: "Kombinatorik & Laplace",
    type: "numeric",
    prompt:
      "Ein Kiosk führt 3 Sorten Kaffee und 2 Sorten Tee (ausreichend Vorrat). Ein Kunde kauft 5 Getränke, davon mindestens 1 Tee. Wie viele verschiedene Zusammenstellungen (Mengenangabe pro Sorte, Reihenfolge egal) sind möglich?",
    correctValue: 105,
    explanation:
      "Kombinationen mit Wiederholung: insgesamt C(9,5)=126 Möglichkeiten (5 aus 5 Sorten), davon C(7,5)=21 rein aus Kaffee (3 Sorten). 126 − 21 = 105.",
    source: "Kapitel 7, Kombinatorik",
    free: false,
  },
  {
    id: "ko-05",
    topic: "Kombinatorik & Laplace",
    type: "numeric",
    tolerance: 0.001,
    prompt:
      "Zwei faire Würfel werden geworfen. Wie hoch ist die Wahrscheinlichkeit, dass die Augensumme 9 beträgt?",
    correctValue: 0.1111,
    explanation: "Günstige Kombinationen: (3,6),(4,5),(5,4),(6,3) — 4 von 36 Fällen: 4/36 ≈ 0.1111.",
    source: "Kapitel 7, Laplace-Modell",
    free: false,
  },
  {
    id: "ko-06",
    topic: "Kombinatorik & Laplace",
    type: "numeric",
    prompt: "Berechnen Sie den Binomialkoeffizienten C(9,4).",
    correctValue: 126,
    explanation: "C(9,4) = 9!/(4!·5!) = 126.",
    source: "Kapitel 7, Kombinatorik",
    free: false,
  },

  // ---------- Reelle Zahlen ----------
  {
    id: "rz-01",
    topic: "Reelle Zahlen",
    type: "numeric",
    prompt: "Sei M := [−2, 2] ∪ (5, 7). Bestimmen Sie sup M.",
    correctValue: 7,
    explanation: "M ist durch 7 nach oben beschränkt, und 7 ist die kleinste obere Schranke (7 selbst gehört wegen des offenen Intervallendes nicht zu M).",
    source: "Kapitel 8, Reelle Zahlen",
    free: false,
  },
  {
    id: "rz-02",
    topic: "Reelle Zahlen",
    type: "numeric",
    prompt: "Sei M := [−2, 2] ∪ (5, 7) (wie in der vorigen Aufgabe). Bestimmen Sie inf M.",
    correctValue: -2,
    explanation: "−2 ist die größte untere Schranke und liegt selbst in M, ist also sogar Minimum.",
    source: "Kapitel 8, Reelle Zahlen",
    free: false,
  },
  {
    id: "rz-03",
    topic: "Reelle Zahlen",
    type: "numeric",
    prompt: "Sei M := {1 − 1/n : n ∈ N}. Bestimmen Sie sup M.",
    correctValue: 1,
    explanation: "Die Folge 1−1/n wächst streng monoton gegen 1, erreicht 1 aber nie: sup M = 1, kein Maximum.",
    source: "Kapitel 8, Reelle Zahlen",
    free: false,
  },
  {
    id: "rz-04",
    topic: "Reelle Zahlen",
    type: "mc",
    prompt: "Welche Eigenschaft unterscheidet R von Q als angeordnetem Körper?",
    options: [
      "In R gilt das Kommutativgesetz der Addition",
      "In R besitzt jede nichtleere, nach oben beschränkte Menge ein Supremum",
      "In R ist die Multiplikation assoziativ",
      "In R existiert ein neutrales Element der Addition",
    ],
    correctIndex: 1,
    explanation:
      "Das Vollständigkeitsaxiom (jede nichtleere, nach oben beschränkte Teilmenge von R besitzt ein Supremum in R) gilt für Q nicht — z. B. hat {q∈Q : q²<2} in Q kein Supremum.",
    source: "Kapitel 8, Vollständigkeitsaxiom",
    free: false,
  },
  {
    id: "rz-05",
    topic: "Reelle Zahlen",
    type: "numeric",
    prompt: "Bestimmen Sie das kleinste n ∈ N mit n > 1/0.0001 (also n > 10000).",
    correctValue: 10001,
    explanation: "1/0.0001 = 10000, die kleinste natürliche Zahl größer als 10000 ist 10001.",
    source: "Kapitel 8, Satz von Archimedes",
    free: false,
  },
  {
    id: "rz-06",
    topic: "Reelle Zahlen",
    type: "mc",
    prompt: "Für x = −7, y = 3: Wie verhalten sich |x+y| und |x|+|y| zueinander?",
    options: ["|x+y| = |x|+|y|", "|x+y| < |x|+|y|", "|x+y| > |x|+|y|", "Nicht vergleichbar"],
    correctIndex: 1,
    explanation: "|x+y| = |−4| = 4, |x|+|y| = 7+3 = 10. Es gilt 4 < 10, im Einklang mit der Dreiecksungleichung.",
    source: "Kapitel 8, Dreiecksungleichung",
    free: false,
  },
  {
    id: "rz-07",
    topic: "Reelle Zahlen",
    type: "numeric",
    prompt: "Sei C := {n/(n+2) : n ∈ N}. Bestimmen Sie sup C.",
    correctValue: 1,
    explanation: "n/(n+2) wächst streng monoton gegen 1 (für n→∞), erreicht 1 aber nie: sup C = 1.",
    source: "Kapitel 8, Reelle Zahlen",
    free: false,
  },

  // ---------- Folgen: Grenzwerte ----------
  {
    id: "fg-01",
    topic: "Folgen: Grenzwerte",
    type: "numeric",
    prompt: "Bestimmen Sie lim_{n→∞} (5n² − 3n + 7) / (2n² + 4n).",
    correctValue: 2.5,
    explanation: "Nach Division durch n²: (5 − 3/n + 7/n²)/(2 + 4/n) → 5/2 = 2.5.",
    source: "Kapitel 9, Folgen",
    free: false,
  },
  {
    id: "fg-02",
    topic: "Folgen: Grenzwerte",
    type: "numeric",
    prompt: "Bestimmen Sie lim_{n→∞} (√(n² + 5n + 9) − n).",
    correctValue: 2.5,
    explanation: "Erweitern mit der dritten binomischen Formel: (5n+9)/(√(n²+5n+9)+n) → 5n/(2n) = 2.5.",
    source: "Kapitel 9, Folgen",
    free: false,
  },
  {
    id: "fg-03",
    topic: "Folgen: Grenzwerte",
    type: "numeric",
    tolerance: 0.05,
    prompt: "Bestimmen Sie lim_{n→∞} (1 + 4/n)ⁿ.",
    correctValue: 54.598,
    explanation: "Es gilt lim_{n→∞}(1+x/n)ⁿ = eˣ. Für x=4 ergibt sich e⁴ ≈ 54.598.",
    source: "Kapitel 9, Eulersche Zahl",
    free: false,
  },
  {
    id: "fg-04",
    topic: "Folgen: Grenzwerte",
    type: "mc",
    prompt: "Welchen Grenzwert besitzt die Folge aₙ := (1 − 3/n)ⁿ?",
    options: ["e³", "e⁻³", "1", "0"],
    correctIndex: 1,
    explanation: "lim_{n→∞}(1+x/n)ⁿ = eˣ, hier mit x=−3: Grenzwert e⁻³.",
    source: "Kapitel 9, Eulersche Zahl",
    free: false,
  },
  {
    id: "fg-05",
    topic: "Folgen: Grenzwerte",
    type: "numeric",
    prompt: "Bestimmen Sie lim_{n→∞} (3n² + (−1)ⁿ·n + 2) / (6n² − 5n + 1).",
    correctValue: 0.5,
    explanation:
      "Division durch n²: (3 + (−1)ⁿ/n + 2/n²)/(6 − 5/n + 1/n²) → 3/6 = 0.5, da (−1)ⁿ/n eine Nullfolge ist.",
    source: "Kapitel 9, Folgen",
    free: false,
  },
  {
    id: "fg-06",
    topic: "Folgen: Grenzwerte",
    type: "numeric",
    prompt: "Bestimmen Sie lim_{n→∞} ⁿ√5.",
    correctValue: 1,
    explanation: "Für jede feste Konstante c > 0 gilt lim_{n→∞} ⁿ√c = 1.",
    source: "Kapitel 9, Folgen",
    free: false,
  },
  {
    id: "fg-07",
    topic: "Folgen: Grenzwerte",
    type: "numeric",
    prompt: "Bestimmen Sie lim_{n→∞} n · (1 − √(1 + 3/n)).",
    correctValue: -1.5,
    explanation:
      "Mit der Näherung √(1+x) ≈ 1 + x/2 für kleine x (x=3/n) folgt n·(1−√(1+3/n)) → n·(−3/(2n)) = −1.5.",
    source: "Kapitel 9, Folgen",
    free: false,
  },

  // ---------- Folgen: Monotonie & Cauchy ----------
  {
    id: "fm-01",
    topic: "Folgen: Monotonie & Cauchy",
    type: "mc",
    prompt: "Welche Voraussetzungen garantieren nach dem Satz über monotone Konvergenz die Konvergenz einer Folge?",
    options: [
      "Monotonie und Beschränktheit",
      "Monotonie allein",
      "Beschränktheit allein",
      "Monotonie und Cauchy-Eigenschaft",
    ],
    correctIndex: 0,
    explanation: "Jede monotone und beschränkte reelle Folge konvergiert (gegen ihr Supremum bzw. Infimum).",
    source: "Kapitel 9, Monotone Konvergenz",
    free: false,
  },
  {
    id: "fm-02",
    topic: "Folgen: Monotonie & Cauchy",
    type: "numeric",
    tolerance: 0.001,
    prompt: "Sei a₁ := 3, a_{n+1} := aₙ / (1 + aₙ). Berechnen Sie a₃.",
    correctValue: 0.4286,
    explanation: "a₂ = 3/4 = 0.75, a₃ = 0.75/1.75 ≈ 0.4286.",
    source: "Übungsaufgabe, rekursive Folgen",
    free: false,
  },
  {
    id: "fm-03",
    topic: "Folgen: Monotonie & Cauchy",
    type: "numeric",
    tolerance: 0.01,
    prompt: "Sei a₁ := 2, a_{n+1} := (aₙ + 3/aₙ)/2. Gegen welchen Grenzwert konvergiert (aₙ)?",
    correctValue: 1.7321,
    explanation: "Dies ist das Heron-Verfahren zur Berechnung von √3 ≈ 1.7321; die Folge ist monoton fallend und nach unten beschränkt.",
    source: "Übungsaufgabe, rekursive Folgen",
    free: false,
  },
  {
    id: "fm-04",
    topic: "Folgen: Monotonie & Cauchy",
    type: "mc",
    prompt: "Eine reelle Folge ist genau dann konvergent, wenn sie ...",
    options: ["monoton ist", "beschränkt ist", "eine Cauchy-Folge ist", "eine Teilfolge besitzt"],
    correctIndex: 2,
    explanation: "Das Cauchy-Kriterium: Eine reelle Folge konvergiert genau dann, wenn sie eine Cauchy-Folge ist.",
    source: "Kapitel 10, Cauchy-Folgen",
    free: false,
  },
  {
    id: "fm-05",
    topic: "Folgen: Monotonie & Cauchy",
    type: "mc",
    prompt: "Welche Eigenschaften treffen auf bₙ := (2 + (−1)ⁿ)/n³ zu?",
    options: [
      "beschränkt, monoton, konvergent",
      "beschränkt, nicht monoton, konvergent",
      "unbeschränkt, nicht monoton, divergent",
      "beschränkt, nicht monoton, divergent",
    ],
    correctIndex: 1,
    explanation:
      "Die Folge ist beschränkt (Zähler zwischen 1 und 3) und konvergiert gegen 0. Sie ist aber nicht monoton: b₁=1, b₂=0.375, b₃≈0.037, b₄≈0.047 — b₃ < b₄ unterbricht die Monotonie.",
    source: "Übungsaufgabe, Folgenklassifikation",
    free: false,
  },
  {
    id: "fm-06",
    topic: "Folgen: Monotonie & Cauchy",
    type: "numeric",
    prompt:
      "Sei c₁ := 7 und c_{n+1} := −2cₙ + 14 falls cₙ < 5, cₙ − 1 falls cₙ ≥ 5. Bestimmen Sie lim sup_{n→∞} cₙ.",
    correctValue: 6,
    explanation:
      "Die Folge lautet 7,6,5,4,6,5,4,6,5,4,... — ab c₂ zyklisch mit Häufungspunkten {4,5,6}. Der größte Häufungspunkt ist 6.",
    source: "Übungsaufgabe, Limes superior/inferior",
    free: false,
  },
  {
    id: "fm-07",
    topic: "Folgen: Monotonie & Cauchy",
    type: "numeric",
    prompt:
      "Mit derselben Folge wie in der vorigen Aufgabe (c₁:=7, c_{n+1} := −2cₙ+14 falls cₙ<5, cₙ−1 falls cₙ≥5): Bestimmen Sie lim inf_{n→∞} cₙ.",
    correctValue: 4,
    explanation: "Die Häufungspunkte sind {4,5,6}; der kleinste Häufungspunkt ist 4.",
    source: "Übungsaufgabe, Limes superior/inferior",
    free: false,
  },

  // ---------- Reihen ----------
  {
    id: "rh-01",
    topic: "Reihen",
    type: "numeric",
    tolerance: 0.001,
    prompt: "Berechnen Sie den Reihenwert Σ_{n=0}^{∞} (2/5)ⁿ.",
    correctValue: 1.6667,
    explanation: "Geometrische Reihe mit q=2/5<1: Σqⁿ = 1/(1−q) = 1/(3/5) = 5/3 ≈ 1.6667.",
    source: "Kapitel 11, Geometrische Reihe",
    free: false,
  },
  {
    id: "rh-02",
    topic: "Reihen",
    type: "mc",
    prompt: "Wie verhält sich die Reihe Σ_{k=1}^{∞} (−1)ᵏ / (k+3)?",
    options: [
      "divergent",
      "konvergent nach dem Leibnizkriterium",
      "konvergent nach dem Quotientenkriterium",
      "absolut konvergent",
    ],
    correctIndex: 1,
    explanation: "1/(k+3) ist eine monoton fallende Nullfolge, also liefert das Leibnizkriterium Konvergenz (aber keine absolute Konvergenz).",
    source: "Kapitel 11, Leibnizkriterium",
    free: false,
  },
  {
    id: "rh-03",
    topic: "Reihen",
    type: "mc",
    prompt: "Wie verhält sich die Reihe Σ_{n=1}^{∞} (n² + 5n + 2) / (9n³ − 2n² − 1)?",
    options: ["konvergent", "divergent", "absolut konvergent", "nicht bestimmbar"],
    correctIndex: 1,
    explanation: "Die Summanden verhalten sich wie n²/(9n³) = 1/(9n); ein Minorantenvergleich mit der (divergenten) harmonischen Reihe zeigt Divergenz.",
    source: "Kapitel 11, Minorantenkriterium",
    free: false,
  },
  {
    id: "rh-04",
    topic: "Reihen",
    type: "numeric",
    tolerance: 0.01,
    prompt: "Berechnen Sie den Reihenwert Σ_{n=1}^{∞} (1/n − 1/(n+3)).",
    correctValue: 1.8333,
    explanation: "Teleskopsumme: die Partialsummen konvergieren gegen 1 + 1/2 + 1/3 = 11/6 ≈ 1.8333.",
    source: "Kapitel 11, Teleskopsummen",
    free: false,
  },
  {
    id: "rh-05",
    topic: "Reihen",
    type: "mc",
    prompt: "Was liefert das Quotientenkriterium für die Reihe Σ_{n=1}^{∞} 1/n²?",
    options: [
      "Konvergenz",
      "Divergenz",
      "Keine Aussage, da der Grenzwert des Quotienten gleich 1 ist",
      "Absolute Divergenz",
    ],
    correctIndex: 2,
    explanation: "Der Grenzwert von |a_{n+1}/aₙ| ist genau 1, weshalb das Quotientenkriterium keine Entscheidung liefert (die Reihe konvergiert dennoch, aus anderen Gründen).",
    source: "Kapitel 11, Quotientenkriterium",
    free: false,
  },
  {
    id: "rh-06",
    topic: "Reihen",
    type: "numeric",
    prompt: "Berechnen Sie den Reihenwert Σ_{k=1}^{∞} 1/(k(k+2)).",
    correctValue: 0.75,
    explanation: "Partialbruchzerlegung und Teleskopsumme liefern Σ1/(k(k+2)) = (1/2)(1+1/2) = 3/4.",
    source: "Kapitel 11, Teleskopsummen",
    free: false,
  },
  {
    id: "rh-07",
    topic: "Reihen",
    type: "mc",
    prompt: "Wie ist die Reihe Σ_{n=1}^{∞} (−1)ⁿ/√n einzuordnen?",
    options: [
      "absolut konvergent",
      "konvergent, aber nicht absolut konvergent",
      "divergent",
      "nur für gerade n konvergent",
    ],
    correctIndex: 1,
    explanation: "Nach Leibniz konvergiert die Reihe, da 1/√n monoton fallende Nullfolge ist. Σ1/√n divergiert jedoch (p-Reihe mit p=1/2<1) — also keine absolute Konvergenz.",
    source: "Kapitel 11, Absolute Konvergenz",
    free: false,
  },
  {
    id: "rh-08",
    topic: "Reihen",
    type: "mc",
    prompt: "Damit das Cauchy-Produkt zweier konvergenter Reihen wieder konvergiert, sollte zusätzlich gelten:",
    options: [
      "Beide Reihen sind alternierend",
      "Beide Reihen sind absolut konvergent",
      "Beide Reihen haben denselben Grenzwert",
      "Mindestens eine Reihe ist eine Nullreihe",
    ],
    correctIndex: 1,
    explanation:
      "Sind beide Reihen absolut konvergent, ist auch das Cauchy-Produkt absolut konvergent mit dem erwarteten Wert. Ohne absolute Konvergenz kann das Cauchy-Produkt sogar divergieren.",
    source: "Kapitel 11, Cauchy-Produkt",
    free: false,
  },

  // ---------- Potenzreihen ----------
  {
    id: "pr-01",
    topic: "Potenzreihen",
    type: "numeric",
    prompt: "Bestimmen Sie den Konvergenzradius der Potenzreihe Σ_{n=1}^{∞} (2 − 3/n)ⁿ xⁿ.",
    correctValue: 0.5,
    explanation: "ⁿ√|aₙ| = |2−3/n| → 2, also r = 1/2 = 0.5.",
    source: "Kapitel 12, Konvergenzradius",
    free: false,
  },
  {
    id: "pr-02",
    topic: "Potenzreihen",
    type: "numeric",
    prompt: "Bestimmen Sie den Konvergenzradius der Potenzreihe Σ_{n=2}^{∞} (4ⁿ / C(n,2)) xⁿ.",
    correctValue: 0.25,
    explanation: "ⁿ√|aₙ| = 4 / ⁿ√(C(n,2)) → 4 (da der polynomielle Term unter der n-ten Wurzel gegen 1 strebt), also r = 1/4 = 0.25.",
    source: "Kapitel 12, Konvergenzradius",
    free: false,
  },
  {
    id: "pr-03",
    topic: "Potenzreihen",
    type: "mc",
    prompt: "Wie lautet der Konvergenzbereich K der Potenzreihe Σ_{n=1}^{∞} ((−3)ⁿ/(n·2ⁿ)) xⁿ?",
    options: ["(−2/3, 2/3)", "[−2/3, 2/3]", "(−2/3, 2/3]", "[−2/3, 2/3)"],
    correctIndex: 2,
    explanation:
      "Der Konvergenzradius ist r=2/3. Bei x=2/3 ergibt sich die konvergente alternierende harmonische Reihe, bei x=−2/3 die divergente harmonische Reihe — also K=(−2/3, 2/3].",
    source: "Kapitel 12, Konvergenzbereich",
    free: false,
  },
  {
    id: "pr-04",
    topic: "Potenzreihen",
    type: "mc",
    prompt: "Die Funktion f(x) = 1/(1−x) + 1/(1+x) besitzt auf (−1,1) die Potenzreihendarstellung Σaₙxⁿ mit:",
    options: [
      "aₙ = 1 für alle n",
      "aₙ = 2 falls n gerade, aₙ = 0 falls n ungerade",
      "aₙ = 0 falls n gerade, aₙ = 2 falls n ungerade",
      "aₙ = 2 für alle n",
    ],
    correctIndex: 1,
    explanation: "1/(1−x)=Σxⁿ und 1/(1+x)=Σ(−x)ⁿ. Summiert: Σ(1+(−1)ⁿ)xⁿ — die Koeffizienten sind 2 für gerade n und 0 für ungerade n.",
    source: "Kapitel 12, Potenzreihendarstellung",
    free: false,
  },
  {
    id: "pr-05",
    topic: "Potenzreihen",
    type: "numeric",
    prompt: "Bestimmen Sie den Konvergenzradius der Potenzreihe Σ_{n=1}^{∞} (x+3)ⁿ/√n.",
    correctValue: 1,
    explanation: "ⁿ√(1/√n) = n^{−1/(2n)} → 1, also r = 1.",
    source: "Kapitel 12, Konvergenzradius",
    free: false,
  },
  {
    id: "pr-06",
    topic: "Potenzreihen",
    type: "mc",
    prompt: "Für eine Potenzreihe mit Entwicklungspunkt x₀ und Konvergenzradius r gilt für den Konvergenzbereich K stets:",
    options: [
      "K = (x₀−r, x₀+r)",
      "(x₀−r, x₀+r) ⊂ K ⊂ [x₀−r, x₀+r]",
      "K = [x₀−r, x₀+r]",
      "K = R",
    ],
    correctIndex: 1,
    explanation: "Im offenen Intervall liegt stets Konvergenz vor, außerhalb des abgeschlossenen Intervalls stets Divergenz; das Randverhalten muss einzeln geprüft werden.",
    source: "Kapitel 12, Konvergenzbereich",
    free: false,
  },

  // ---------- Spezielle Funktionen ----------
  {
    id: "sf-01",
    topic: "Spezielle Funktionen",
    type: "mc",
    prompt: "Welche Gleichung folgt aus der Potenzreihendarstellung von exp und dem Cauchy-Produkt?",
    options: [
      "exp(x+y) = exp(x) + exp(y)",
      "exp(x+y) = exp(x) · exp(y)",
      "exp(x·y) = exp(x) · exp(y)",
      "exp(x+y) = exp(x) · exp(x)",
    ],
    correctIndex: 1,
    explanation: "Die Funktionalgleichung exp(x+y) = exp(x)·exp(y) wird über das Cauchy-Produkt der Potenzreihen von exp(x) und exp(y) bewiesen.",
    source: "Kapitel 13, Exponentialfunktion",
    free: false,
  },
  {
    id: "sf-02",
    topic: "Spezielle Funktionen",
    type: "mc",
    prompt: "Warum gilt sin(−x) = −sin(x) für alle x ∈ R?",
    options: [
      "Weil sin periodisch mit Periode 2π ist",
      "Weil in der Potenzreihe von sin nur ungerade Potenzen von x auftreten",
      "Weil sin²+cos²=1 gilt",
      "Weil sin(0)=0 gilt",
    ],
    correctIndex: 1,
    explanation: "sin(x) = Σ(−1)ⁿx^{2n+1}/(2n+1)! enthält nur ungerade Potenzen von x, daher ändert x↦−x das Vorzeichen jedes Summanden.",
    source: "Kapitel 13, Sinus und Kosinus",
    free: false,
  },
  {
    id: "sf-03",
    topic: "Spezielle Funktionen",
    type: "numeric",
    prompt: "Bestimmen Sie die kleinste Periode a > 0 der Funktion f(x) := sin(x · π/3).",
    correctValue: 6,
    explanation: "sin hat Periode 2π. Aus (x+a)π/3 = xπ/3 + 2π folgt a = 6.",
    source: "Kapitel 13, Periodische Funktionen",
    free: false,
  },
  {
    id: "sf-04",
    topic: "Spezielle Funktionen",
    type: "mc",
    prompt: "Bestimmen Sie die Menge M aller x ∈ R mit cos(x·π/4) = 0.",
    options: [
      "M = {x ∈ R : x/4 ∈ Z}",
      "M = {x ∈ R : (x−2)/4 ∈ Z}",
      "M = {x ∈ R : x/2 ∈ Z}",
      "M = {x ∈ R : (x−1)/4 ∈ Z}",
    ],
    correctIndex: 1,
    explanation: "cos(xπ/4)=0 ⇔ xπ/4 = π/2 + mπ (m∈Z) ⇔ x = 2 + 4m ⇔ (x−2)/4 ∈ Z.",
    source: "Kapitel 13, Nullstellen von Sinus/Kosinus",
    free: false,
  },
  {
    id: "sf-05",
    topic: "Spezielle Funktionen",
    type: "mc",
    prompt: "Ist es möglich, dass eine gerade Funktion f: R → R den Wert f(0) ≠ 0 besitzt?",
    options: [
      "Ja, das steht nicht im Widerspruch zur Definition",
      "Nein, jede gerade Funktion erfüllt f(0)=0",
      "Nur wenn f zusätzlich ungerade ist",
      "Nur für periodische Funktionen",
    ],
    correctIndex: 0,
    explanation: "Geradheit (f(−x)=f(x)) erzwingt keine Aussage über f(0); z. B. ist cos gerade mit cos(0)=1≠0. Nur bei ungeraden Funktionen folgt zwingend f(0)=0.",
    source: "Kapitel 13, Gerade und ungerade Funktionen",
    free: false,
  },
  {
    id: "sf-06",
    topic: "Spezielle Funktionen",
    type: "numeric",
    tolerance: 0.001,
    prompt: "Berechnen Sie √(1 − cos(π/3)).",
    correctValue: 0.7071,
    explanation: "cos(π/3) = 1/2, also 1−cos(π/3) = 1/2 und √(1/2) ≈ 0.7071.",
    source: "Kapitel 13, Additionstheoreme",
    free: false,
  },
];
