import type { Question } from "@/lib/questions";

// Themen entsprechen (in Kurzform) den Kapiteltiteln aus lib/content/bwl-2.ts.
// Alle Übungsaufgaben, die auf reale Vorlesungen/Tutorien/Klausuren zurückgehen,
// wurden gemäß den Projektregeln (CLAUDE.md) sowohl in den Zahlen als auch im
// Szenario verändert — es taucht nie derselbe Zahlensatz UND dasselbe Szenario
// wie im Original gleichzeitig auf.
export const TOPICS = [
  "Grundsätze der Rechnungslegung",
  "Zeitwert des Geldes",
  "Der Worksheet Approach",
  "Rentenrechnung",
  "Kosten- und Leistungsrechnung: Grundlagen",
  "Anleihenbewertung",
  "Bewertungswahlrechte",
  "Investitionsrechnung: Kapitalwert und Payback",
  "Betriebsabrechnungsbogen",
  "Interner Zinssatz und Kapitalwertrate",
  "Kalkulationsverfahren",
  "Eigenkapitalfinanzierung",
  "Deckungsbeitragsrechnung",
  "Portfoliotheorie und CAPM",
] as const;

export const questions: Question[] = [
  // ---------- Grundsätze der Rechnungslegung (frei zugänglich) ----------
  {
    id: "gr-01",
    topic: "Grundsätze der Rechnungslegung",
    type: "mc",
    prompt: "Worin unterscheidet sich das externe vom internen Rechnungswesen primär?",
    options: [
      "Das externe Rechnungswesen ist nur für börsennotierte Unternehmen verpflichtend",
      "Das externe Rechnungswesen richtet sich an außenstehende Adressaten und folgt gesetzlichen Regeln, das interne dient der Unternehmenssteuerung und ist freier gestaltbar",
      "Das interne Rechnungswesen ist gesetzlich strenger reguliert als das externe",
      "Beide Systeme verwenden identische Bewertungsregeln",
    ],
    correctIndex: 1,
    explanation:
      "Das externe Rechnungswesen dokumentiert die Lage für außenstehende Adressaten nach gesetzlichen GoB, während das interne Rechnungswesen der Unternehmensleitung zur Steuerung dient und z. B. kalkulatorische Kosten kennt.",
    source: "Kapitel 1.1, Zweck und Adressaten der Rechnungslegung",
    free: true,
  },
  {
    id: "gr-02",
    topic: "Grundsätze der Rechnungslegung",
    type: "mc",
    prompt: "Ein Kunde zahlt im November eine Anzahlung für eine Ware, die erst im Februar geliefert wird. Wann darf der Ertrag nach dem Realisationsprinzip gebucht werden?",
    options: ["Im November, bei Zahlungseingang", "Im Februar, bei Lieferung", "Anteilig auf November und Februar verteilt", "Erst am Ende des Geschäftsjahres"],
    correctIndex: 1,
    explanation: "Das Realisationsprinzip verlangt, Erträge erst bei wirtschaftlicher Erbringung der Leistung zu erfassen, nicht bei Zahlungseingang.",
    source: "Kapitel 1.2, Realisationsprinzip",
    free: true,
  },
  {
    id: "gr-03",
    topic: "Grundsätze der Rechnungslegung",
    type: "mc",
    prompt: "Was verlangt das Matching Principle?",
    options: [
      "Aufwendungen werden in der Periode erfasst, in der die zugehörige Zahlung erfolgt",
      "Aufwendungen werden der Periode zugeordnet, in der die durch sie verursachten Erträge entstehen",
      "Erträge und Aufwendungen dürfen nie in derselben Periode gebucht werden",
      "Nur Zahlungen ohne zugehörigen Ertrag dürfen aktiviert werden",
    ],
    correctIndex: 1,
    explanation: "Das Matching Principle ordnet Aufwendungen der Periode zu, in der die zugehörigen Erträge entstehen, unabhängig vom Zahlungszeitpunkt.",
    source: "Kapitel 1.3, Matching Principle",
    free: true,
  },
  {
    id: "gr-04",
    topic: "Grundsätze der Rechnungslegung",
    type: "numeric",
    prompt: "Ein Weingroßhändler hält Aktien mit ursprünglichem Wert von 30.000 €. Der Marktwert fällt zum Bilanzstichtag auf 21.000 €. Welcher Verlust muss nach dem Imparitätsprinzip sofort erfasst werden (in €)?",
    correctValue: 9000,
    tolerance: 0,
    unit: "€",
    explanation: "Nach dem Imparitätsprinzip müssen unrealisierte Verluste sofort erfasst werden: 30.000 − 21.000 = 9.000 €.",
    source: "Kapitel 1.4, Vorsichtsprinzip und Imparitätsprinzip",
    free: true,
  },
  {
    id: "gr-05",
    topic: "Grundsätze der Rechnungslegung",
    type: "mc",
    prompt: "Welches Prinzip verletzt ein Unternehmen, das ohne sachlichen Grund von linearer zu degressiver Abschreibung wechselt, nur weil das den Gewinn dieses Jahr senkt?",
    options: ["Realisationsprinzip", "Going-Concern-Prinzip", "Konsistenzprinzip (Stetigkeitsprinzip)", "Matching Principle"],
    correctIndex: 2,
    explanation: "Das Konsistenzprinzip verlangt, einmal gewählte Bewertungsmethoden beizubehalten, sofern kein sachlicher Grund für einen Wechsel vorliegt.",
    source: "Kapitel 1.5, Going-Concern-Prinzip und Konsistenzprinzip",
    free: true,
  },
  // ---------- Zeitwert des Geldes ----------
  {
    id: "zw-01",
    topic: "Zeitwert des Geldes",
    type: "numeric",
    prompt: "Ein Sparer legt 5.000 € für 3 Jahre zu einem Jahreszinssatz von 8% an (Zinseszins). Wie hoch ist der Endwert (in €, auf 2 Nachkommastellen)?",
    correctValue: 6298.56,
    tolerance: 1,
    unit: "€",
    explanation: "EW = 5.000 · (1,08)³ = 5.000 · 1,259712 = 6.298,56 €.",
    source: "Kapitel 2.1, Endwert bei ein- und mehrperiodiger Verzinsung",
    free: false,
  },
  {
    id: "zw-02",
    topic: "Zeitwert des Geldes",
    type: "numeric",
    prompt: "Wie viel muss heute angelegt werden, um bei einem Zinssatz von 6% in 5 Jahren genau 20.000 € zu erhalten (Barwert, auf 2 Nachkommastellen)?",
    correctValue: 14945.16,
    tolerance: 5,
    unit: "€",
    explanation: "BW = 20.000 / (1,06)^5 = 20.000 / 1,338226 ≈ 14.945,16 €.",
    source: "Kapitel 2.2, Barwert einer einzelnen Zahlung",
    free: false,
  },
  {
    id: "zw-03",
    topic: "Zeitwert des Geldes",
    type: "mc",
    prompt: "Was passiert mit dem effektiven Jahreszinssatz im Vergleich zum nominalen Jahreszinssatz, wenn mehrmals pro Jahr verzinst wird (m > 1)?",
    options: ["Er ist immer niedriger als der nominale Zinssatz", "Er ist immer gleich dem nominalen Zinssatz", "Er ist immer höher als der nominale Zinssatz", "Das Verhältnis hängt vom Anlagebetrag ab"],
    correctIndex: 2,
    explanation: "Durch häufigeren Zinseszins ist der effektive Jahreszinssatz bei unterjähriger Verzinsung stets höher als der nominale Zinssatz (bei m > 1).",
    source: "Kapitel 2.3, Unterjährige Verzinsung und effektiver Jahreszins",
    free: false,
  },
  {
    id: "zw-04",
    topic: "Zeitwert des Geldes",
    type: "numeric",
    prompt: "Wie hoch ist der effektive Jahreszinssatz bei einem nominalen Jahreszinssatz von 12% und monatlicher Verzinsung (m = 12), in Prozent, auf 2 Nachkommastellen?",
    correctValue: 12.68,
    tolerance: 0.1,
    unit: "%",
    explanation: "EJZ = (1 + 0,12/12)^12 − 1 = (1,01)^12 − 1 ≈ 1,1268 − 1 = 12,68%.",
    source: "Kapitel 2.3, Unterjährige Verzinsung und effektiver Jahreszins",
    free: false,
  },
  {
    id: "zw-05",
    topic: "Zeitwert des Geldes",
    type: "numeric",
    prompt: "Ein Anleger legt 4.000 € für 5 Jahre bei stetiger Verzinsung zu 8% p.a. an. Wie hoch ist der Endwert (in €, auf 2 Nachkommastellen)?",
    correctValue: 5967.30,
    tolerance: 5,
    unit: "€",
    explanation: "EW = 4.000 · e^(0,08·5) = 4.000 · e^0,4 ≈ 4.000 · 1,49182 ≈ 5.967,30 €.",
    source: "Kapitel 2.4, Stetige Verzinsung",
    free: false,
  },
  // ---------- Der Worksheet Approach ----------
  {
    id: "wa-01",
    topic: "Der Worksheet Approach",
    type: "mc",
    prompt: "Welche Bilanzgleichung muss nach jedem Geschäftsvorfall im Worksheet Approach gelten?",
    options: ["ΔL − ΔV = ΔE − ΔF", "ΔL + ΔV = ΔE + ΔF", "ΔL · ΔV = ΔE · ΔF", "ΔL = ΔV = ΔE = ΔF"],
    correctIndex: 1,
    explanation: "Die Bilanzgleichung des Worksheet Approach lautet ΔL + ΔV = ΔE + ΔF (Änderung liquider Mittel plus Änderung nicht-liquider Vermögensgegenstände = Änderung Eigenkapital plus Änderung Fremdkapital).",
    source: "Kapitel 3.1, Die Bilanzgleichung des Worksheet Approach",
    free: false,
  },
  {
    id: "wa-02",
    topic: "Der Worksheet Approach",
    type: "mc",
    prompt: "Nadja verkauft Keramikschalen im März auf Ziel und erhält die Zahlung erst im April. Welche Grundform liegt im März vor?",
    options: ["Grundform 4 (Einzahlung und Umsatzerlös gleichzeitig)", "Grundform 5a (Umsatzerlös jetzt, Einzahlung später)", "Grundform 6a (Einzahlung jetzt, Umsatzerlös später)", "Grundform 1 (Auszahlung und Aufwand gleichzeitig)"],
    correctIndex: 1,
    explanation: "Da der Umsatzerlös bereits im März entsteht, die Einzahlung aber erst im April erfolgt, handelt es sich um Grundform 5a.",
    source: "Kapitel 3.2, Die sechs Grundformen der Verbuchung",
    free: false,
  },
  {
    id: "wa-03",
    topic: "Der Worksheet Approach",
    type: "mc",
    prompt: "Ein Unternehmen zahlt am 1. Oktober die Miete für 6 Monate im Voraus. Welcher Rechnungsabgrenzungsposten entsteht zum 31. Dezember für die restlichen 3 Monate?",
    options: ["Ein passiver RAP", "Ein aktiver RAP", "Eine Rückstellung", "Kein RAP nötig, da die Zahlung bereits erfolgt ist"],
    correctIndex: 1,
    explanation: "Weil die Auszahlung bereits erfolgt ist, der Aufwand für die restlichen 3 Monate aber erst im Folgejahr anfällt, entsteht ein aktiver Rechnungsabgrenzungsposten.",
    source: "Kapitel 3.3, Rechnungsabgrenzungsposten (RAP)",
    free: false,
  },
  {
    id: "wa-04",
    topic: "Der Worksheet Approach",
    type: "numeric",
    prompt: "Eine Werkstatt zahlt im Oktober die Miete für 8 Monate im Voraus in Höhe von 4.800 €. Wie hoch ist der aktive RAP zum 31. Dezember (2 Monate bereits verbraucht), in €?",
    correctValue: 3600,
    tolerance: 0,
    unit: "€",
    explanation: "Monatliche Miete = 4.800/8 = 600 €. Bereits verbraucht: 2 Monate = 1.200 €. Verbleibender aktiver RAP für 6 Monate = 6 · 600 = 3.600 €.",
    source: "Kapitel 3.3, Rechnungsabgrenzungsposten (RAP)",
    free: false,
  },
  // ---------- Rentenrechnung ----------
  {
    id: "re-01",
    topic: "Rentenrechnung",
    type: "numeric",
    prompt: "Eine Genossenschaft least ihre Dachfläche unbefristet für jährlich 60 € (beginnend in Periode 1). Bei einem Zinssatz von 6% — wie hoch ist der Barwert dieser ewigen Rente (in €)?",
    correctValue: 1000,
    tolerance: 0,
    unit: "€",
    explanation: "BW = C / r = 60 / 0,06 = 1.000 €.",
    source: "Kapitel 4.2, Ewige Rente (Perpetuity)",
    free: false,
  },
  {
    id: "re-02",
    topic: "Rentenrechnung",
    type: "numeric",
    prompt: "Eine Anlage erwirtschaftet 4 Jahre lang konstant 50 € pro Jahr (beginnend in Periode 1). Bei einem Zinssatz von 8% — wie hoch ist der Barwert dieser endlichen Rente (in €, auf 2 Nachkommastellen)?",
    correctValue: 165.61,
    tolerance: 1,
    unit: "€",
    explanation: "BW = (50/0,08) · [1 − 1/(1,08)^4] = 625 · [1 − 0,7350] = 625 · 0,2650 ≈ 165,61 €.",
    source: "Kapitel 4.3, Endliche Rente (Annuität)",
    free: false,
  },
  {
    id: "re-03",
    topic: "Rentenrechnung",
    type: "mc",
    prompt: "Für welche Bedingung ist die Formel der ewigen wachsenden Rente BW = C / (r − g) überhaupt gültig?",
    options: ["r muss größer als g sein", "g muss größer als r sein", "r und g müssen gleich groß sein", "Die Formel gilt immer, unabhängig vom Verhältnis von r und g"],
    correctIndex: 0,
    explanation: "Die Formel für die ewige wachsende Rente konvergiert nur, wenn der Zinssatz r größer als die Wachstumsrate g ist.",
    source: "Kapitel 4.4, Renten mit konstantem Wachstum",
    free: false,
  },
  {
    id: "re-04",
    topic: "Rentenrechnung",
    type: "numeric",
    prompt: "Ein Zahlungsstrom beginnt in Periode 1 unbegrenzt mit anfänglich 30 €, die jährlich um 4% wachsen. Bei einem Zinssatz von 9% — wie hoch ist der Barwert (in €)?",
    correctValue: 600,
    tolerance: 0,
    unit: "€",
    explanation: "BW = C / (r − g) = 30 / (0,09 − 0,04) = 30 / 0,05 = 600 €.",
    source: "Kapitel 4.4, Renten mit konstantem Wachstum",
    free: false,
  },
  {
    id: "re-05",
    topic: "Rentenrechnung",
    type: "numeric",
    prompt: "Ein Zahlungsstrom liefert in den nächsten 2 Jahren die Zahlungen 25 € und 45 €. Bei einem Zinssatz von 10% — wie hoch ist der Barwert (in €, auf 2 Nachkommastellen)?",
    correctValue: 60.95,
    tolerance: 0.5,
    unit: "€",
    explanation: "BW = 25/1,1 + 45/1,1² = 22,73 + 37,19 ≈ 59,92 €. Genauer: 25/1,1=22,727, 45/1,21=37,190, Summe=59,92 €.",
    source: "Kapitel 4.1, Barwert eines mehrperiodigen Zahlungsstroms",
    free: false,
  },
  // ---------- Kosten- und Leistungsrechnung: Grundlagen ----------
  {
    id: "kg-01",
    topic: "Kosten- und Leistungsrechnung: Grundlagen",
    type: "mc",
    prompt: "Was sind kalkulatorische Kosten?",
    options: [
      "Kosten, die extern und intern immer identisch erfasst werden",
      "Kosten des internen Rechnungswesens, die extern entweder in anderer Höhe (Anderskosten) oder gar nicht (Zusatzkosten) erfasst werden",
      "Nur die im externen Rechnungswesen ausgewiesenen Abschreibungen",
      "Ausschließlich Materialkosten",
    ],
    correctIndex: 1,
    explanation: "Kalkulatorische Kosten sind Kosten des internen Rechnungswesens, die im externen entweder anders (Anderskosten) oder gar nicht (Zusatzkosten) erscheinen.",
    source: "Kapitel 5.1, Internes versus externes Rechnungswesen und kalkulatorische Kosten",
    free: false,
  },
  {
    id: "kg-02",
    topic: "Kosten- und Leistungsrechnung: Grundlagen",
    type: "numeric",
    prompt: "Eine Kantenanleimmaschine wurde für 60.000 € angeschafft, Restwert 6.000 €, Kalkulationszinssatz 5%. Wie hoch sind die kalkulatorischen Zinsen pro Jahr nach der Durchschnittsmethode (in €)?",
    correctValue: 1650,
    tolerance: 0,
    unit: "€",
    explanation: "kalk. Zinsen = [(60.000+6.000)/2] · 0,05 = 33.000 · 0,05 = 1.650 €.",
    source: "Kapitel 5.1, Internes versus externes Rechnungswesen und kalkulatorische Kosten",
    free: false,
  },
  {
    id: "kg-03",
    topic: "Kosten- und Leistungsrechnung: Grundlagen",
    type: "mc",
    prompt: "Welche Frage beantwortet die Kostenstellenrechnung?",
    options: ["Welche Kosten sind angefallen?", "Wo sind die Kosten angefallen?", "Wofür (für welches Produkt) sind die Kosten angefallen?", "Wann werden die Kosten bezahlt?"],
    correctIndex: 1,
    explanation: "Die Kostenstellenrechnung verteilt die Kosten auf die organisatorischen Bereiche, in denen sie angefallen sind — sie beantwortet die 'Wo'-Frage.",
    source: "Kapitel 5.2, Kostenarten-, Kostenstellen- und Kostenträgerrechnung",
    free: false,
  },
  {
    id: "kg-04",
    topic: "Kosten- und Leistungsrechnung: Grundlagen",
    type: "mc",
    prompt: "Die Miete der Lackiererhalle einer Fahrradmanufaktur ist relativ zu einem einzelnen Fahrrad ein Beispiel für:",
    options: ["Einzelkosten", "Gemeinkosten", "Kalkulatorische Zinsen", "Variable Stückkosten"],
    correctIndex: 1,
    explanation: "Die Hallenmiete lässt sich nicht eindeutig einem einzelnen Fahrrad zurechnen und muss über einen Verteilungsschlüssel aufgeteilt werden — sie ist damit Gemeinkosten.",
    source: "Kapitel 5.3, Einzelkosten versus Gemeinkosten",
    free: false,
  },
  {
    id: "kg-05",
    topic: "Kosten- und Leistungsrechnung: Grundlagen",
    type: "numeric",
    prompt: "Ein Hersteller professioneller Küchenmaschinen verkauft ein Modell für 3.000 € pro Stück, variable Stückkosten 1.700 €, fixe Kosten 390.000 € pro Jahr. Wie hoch ist die Break-even-Menge (in Stück)?",
    correctValue: 300,
    tolerance: 0,
    unit: "Stück",
    explanation: "Deckungsbeitrag pro Einheit = 3.000 − 1.700 = 1.300 €. Break-even-Menge = 390.000 / 1.300 = 300 Stück.",
    source: "Kapitel 5.4, Fixe und variable Kosten: die Break-even-Analyse",
    free: false,
  },
  // ---------- Anleihenbewertung ----------
  {
    id: "an-01",
    topic: "Anleihenbewertung",
    type: "numeric",
    prompt: "Ein zweijähriger Zerobond mit Nennwert 1.000 € notiert bei 907,03 €. Wie hoch ist die Yield to Maturity (in %, auf 1 Nachkommastelle)?",
    correctValue: 5.0,
    tolerance: 0.2,
    unit: "%",
    explanation: "y = (1.000/907,03)^(1/2) − 1 ≈ 1,05 − 1 = 5,0%.",
    source: "Kapitel 6.1, Zerobonds und Yield to Maturity",
    free: false,
  },
  {
    id: "an-02",
    topic: "Anleihenbewertung",
    type: "mc",
    prompt: "Wann notiert eine Kuponanleihe über ihrem Nennwert?",
    options: ["Wenn der Kupon niedriger ist als der Marktzinssatz", "Wenn der Kupon höher ist als der Marktzinssatz", "Immer, unabhängig vom Marktzinssatz", "Nie, Kuponanleihen notieren stets zum Nennwert"],
    correctIndex: 1,
    explanation: "Ist der Kupon höher als der aktuelle Marktzinssatz, ist die Anleihe für Anleger attraktiver und notiert über dem Nennwert (Aufgeld).",
    source: "Kapitel 6.2, Kuponanleihen",
    free: false,
  },
  {
    id: "an-03",
    topic: "Anleihenbewertung",
    type: "numeric",
    prompt: "Eine zweijährige Kuponanleihe mit Nennwert 1.000 € zahlt einen jährlichen Kupon von 6%. Bei einem Marktzinssatz von 4% — wie hoch ist der Preis (in €, auf 2 Nachkommastellen)?",
    correctValue: 1037.72,
    tolerance: 2,
    unit: "€",
    explanation: "P = 60/1,04 + 1.060/1,04² = 57,69 + 980,03 ≈ 1.037,72 €.",
    source: "Kapitel 6.2, Kuponanleihen",
    free: false,
  },
  {
    id: "an-04",
    topic: "Anleihenbewertung",
    type: "mc",
    prompt: "Was passiert mit dem Preis einer bereits ausgegebenen, festverzinslichen Anleihe, wenn der Marktzinssatz nach der Emission steigt?",
    options: ["Der Preis steigt", "Der Preis bleibt unverändert", "Der Preis sinkt", "Der Preis wird unabhängig vom Zinssatz"],
    correctIndex: 2,
    explanation: "Steigt der Marktzinssatz, werden die fixen Kupons bestehender Anleihen im Vergleich zu neuen Anleihen weniger attraktiv, weshalb ihr Preis sinkt.",
    source: "Kapitel 6.2, Kuponanleihen",
    free: false,
  },
  {
    id: "an-05",
    topic: "Anleihenbewertung",
    type: "mc",
    prompt: "Welche Aussage über Ratings ist korrekt?",
    options: [
      "Ratings werden ausschließlich vom Emittenten selbst vergeben",
      "Ratings sind eine Bonitätsbeurteilung, meist durch unabhängige Ratingagenturen vergeben, und beeinflussen den Finanzierungszinssatz",
      "Ein schlechteres Rating führt zu einem niedrigeren geforderten Zinssatz",
      "Ratings spielen für die Preisbildung von Anleihen keine Rolle",
    ],
    correctIndex: 1,
    explanation: "Ratings sind unabhängige Bonitätsbeurteilungen und beeinflussen direkt den Zinssatz: Ein schlechteres Rating führt zu einem höheren geforderten Zinssatz.",
    source: "Kapitel 6.3, Ratings",
    free: false,
  },
  // ---------- Bewertungswahlrechte ----------
  {
    id: "bw-01",
    topic: "Bewertungswahlrechte",
    type: "numeric",
    prompt: "Eine Konditorei kauft einen Kombidämpfer für 60.000 €, Nutzungsdauer 4 Jahre, Restwert 6.000 €. Wie hoch ist die jährliche lineare Abschreibung (in €)?",
    correctValue: 13500,
    tolerance: 0,
    unit: "€",
    explanation: "ABt = (AW − RW)/T = (60.000 − 6.000)/4 = 13.500 €.",
    source: "Kapitel 7.1, Planmäßige Abschreibung: linear und degressiv",
    free: false,
  },
  {
    id: "bw-02",
    topic: "Bewertungswahlrechte",
    type: "numeric",
    prompt: "Ein Freizeitpark hat eine Achterbahn mit Buchwert 2.400.000 €. Nach einem Vorfall beträgt der beizulegende Wert nur noch 150.000 €. Wie hoch ist die außerplanmäßige Abschreibung (in €)?",
    correctValue: 2250000,
    tolerance: 0,
    unit: "€",
    explanation: "außerplanmäßige Abschreibung = 2.400.000 − 150.000 = 2.250.000 €.",
    source: "Kapitel 7.2, Außerplanmäßige Abschreibung",
    free: false,
  },
  {
    id: "bw-03",
    topic: "Bewertungswahlrechte",
    type: "mc",
    prompt: "Warum führt die Bildung einer Rückstellung bereits zu einem Aufwand, obwohl die Auszahlung erst später erfolgt?",
    options: [
      "Weil Rückstellungen immer sofort ausgezahlt werden müssen",
      "Aufgrund des Imparitätsprinzips: absehbare zukünftige Verpflichtungen werden bereits jetzt erfasst",
      "Weil Rückstellungen keine Verbindlichkeiten sind",
      "Weil das Realisationsprinzip dies für alle Aufwendungen so vorschreibt",
    ],
    correctIndex: 1,
    explanation: "Nach dem Imparitätsprinzip müssen absehbare künftige Verpflichtungen bereits in der laufenden Periode als Aufwand erfasst werden.",
    source: "Kapitel 7.3, Rückstellungen",
    free: false,
  },
  {
    id: "bw-04",
    topic: "Bewertungswahlrechte",
    type: "mc",
    prompt: "Bei steigenden Einkaufspreisen führt welches Vorratsbewertungsverfahren tendenziell zum höchsten ausgewiesenen Periodengewinn?",
    options: ["LIFO", "FIFO", "Gleitender Durchschnitt", "Alle drei Verfahren liefern immer denselben Gewinn"],
    correctIndex: 1,
    explanation: "Bei FIFO werden die günstigeren, älteren Einkaufspreise als Aufwand verbucht, was bei steigenden Preisen zum höchsten Gewinn führt.",
    source: "Kapitel 7.4, Vorratsbewertung: FIFO, LIFO und gleitender Durchschnitt",
    free: false,
  },
  {
    id: "bw-05",
    topic: "Bewertungswahlrechte",
    type: "numeric",
    prompt: "Eine Kaffeerösterei hat Anfangsbestand 100 kg zu 5 €/kg und kauft 400 kg zu 7 €/kg hinzu. Sie verbraucht 300 kg. Wie hoch ist der Wareneinsatz bei FIFO (in €)?",
    correctValue: 1900,
    tolerance: 0,
    unit: "€",
    explanation: "FIFO: zuerst 100 kg zu 5 € (=500 €), dann 200 kg zu 7 € (=1.400 €). Wareneinsatz = 500+1.400 = 1.900 €.",
    source: "Kapitel 7.4, Vorratsbewertung: FIFO, LIFO und gleitender Durchschnitt",
    free: false,
  },
  {
    id: "bw-06",
    topic: "Bewertungswahlrechte",
    type: "mc",
    prompt: "Was unterscheidet Vollkostenrechnung (AC) von Teilkostenrechnung (VC) bei der Herstellungskostenbewertung?",
    options: [
      "Bei AC werden gar keine Fertigungskosten aktiviert",
      "Bei AC werden fixe und variable Fertigungskosten aktiviert, bei VC nur variable",
      "Bei VC werden fixe und variable Fertigungskosten aktiviert, bei AC nur variable",
      "AC und VC unterscheiden sich nur beim Umsatzerlös, nie bei den Kosten",
    ],
    correctIndex: 1,
    explanation: "Bei der Vollkostenrechnung (AC) werden sowohl variable als auch fixe Fertigungskosten in den Herstellungskosten aktiviert, bei der Teilkostenrechnung (VC) nur die variablen.",
    source: "Kapitel 7.5, Voll- versus Teilkostenrechnung (AC vs. VC)",
    free: false,
  },
  // ---------- Investitionsrechnung: Kapitalwert und Payback ----------
  {
    id: "ir-01",
    topic: "Investitionsrechnung: Kapitalwert und Payback",
    type: "numeric",
    prompt: "Eine Investition kostet heute 18.000 € und liefert in einem Jahr 20.000 €. Bei einem Kapitalkostensatz von 8% — wie hoch ist der Kapitalwert (in €, auf 2 Nachkommastellen)?",
    correctValue: 518.52,
    tolerance: 2,
    unit: "€",
    explanation: "KW = −18.000 + 20.000/1,08 = −18.000 + 18.518,52 ≈ 518,52 €.",
    source: "Kapitel 8.1, Der Kapitalwert (Net Present Value)",
    free: false,
  },
  {
    id: "ir-02",
    topic: "Investitionsrechnung: Kapitalwert und Payback",
    type: "mc",
    prompt: "Nach der Entscheidungsregel der Kapitalwertmethode sollte ein Investitionsprojekt durchgeführt werden, wenn:",
    options: ["sein Kapitalwert kleiner als 0 ist", "sein Kapitalwert größer als 0 ist", "seine Amortisationsdauer kürzer als 1 Jahr ist", "der interne Zinssatz gleich 0 ist"],
    correctIndex: 1,
    explanation: "Die Kapitalwertmethode empfiehlt, ein Projekt genau dann durchzuführen, wenn sein Kapitalwert positiv ist.",
    source: "Kapitel 8.1, Der Kapitalwert (Net Present Value)",
    free: false,
  },
  {
    id: "ir-03",
    topic: "Investitionsrechnung: Kapitalwert und Payback",
    type: "numeric",
    prompt: "Eine Anlage mit Anfangsauszahlung 60.000 € liefert Rückflüsse von 15.000 €, 25.000 €, 20.000 € und 30.000 € in den Jahren 1 bis 4. Wie hoch ist die Amortisationsdauer (in Jahren)?",
    correctValue: 3,
    tolerance: 0,
    unit: "Jahre",
    explanation: "Kumulierte Rückflüsse: Jahr 1: 15.000, Jahr 2: 40.000, Jahr 3: 60.000 — die Anfangsauszahlung ist nach 3 Jahren gedeckt.",
    source: "Kapitel 8.2, Amortisationsrechnung (Payback-Methode)",
    free: false,
  },
  {
    id: "ir-04",
    topic: "Investitionsrechnung: Kapitalwert und Payback",
    type: "mc",
    prompt: "Was ist ein zentrales Problem der Amortisationsrechnung?",
    options: [
      "Sie berücksichtigt Zahlungen nach Ablauf der Amortisationsdauer und den Zeitpunkt der Zahlungen sehr genau",
      "Sie ignoriert sowohl den Zeitpunkt der Zahlungen innerhalb der Amortisationsdauer als auch Zahlungen danach",
      "Sie kann nur bei unendlicher Laufzeit angewendet werden",
      "Sie liefert immer dieselbe Rangfolge wie die Kapitalwertmethode",
    ],
    correctIndex: 1,
    explanation: "Die Payback-Methode berücksichtigt weder den Diskontierungseffekt innerhalb der Amortisationsdauer noch Zahlungen, die danach anfallen.",
    source: "Kapitel 8.2, Amortisationsrechnung (Payback-Methode)",
    free: false,
  },
  {
    id: "ir-05",
    topic: "Investitionsrechnung: Kapitalwert und Payback",
    type: "numeric",
    prompt: "Ein Café investiert 9.000 € in eine neue Kaffeemaschine, die im Folgejahr 9.900 € zurückfließen lässt. Bei einem Kapitalkostensatz von 5% — wie hoch ist der Kapitalwert (in €, auf 2 Nachkommastellen)?",
    correctValue: 428.57,
    tolerance: 2,
    unit: "€",
    explanation: "KW = −9.000 + 9.900/1,05 = −9.000 + 9.428,57 ≈ 428,57 €.",
    source: "Kapitel 8.1, Der Kapitalwert (Net Present Value)",
    free: false,
  },
  // ---------- Betriebsabrechnungsbogen ----------
  {
    id: "ba-01",
    topic: "Betriebsabrechnungsbogen",
    type: "mc",
    prompt: "Was unterscheidet eine Vorkostenstelle von einer Endkostenstelle?",
    options: [
      "Vorkostenstellen bedienen primär andere Kostenstellen, Endkostenstellen werden über die Kostenträgerrechnung direkt den Produkten zugerechnet",
      "Vorkostenstellen entstehen nur in Dienstleistungsunternehmen",
      "Endkostenstellen fallen immer vor Vorkostenstellen im BAB an",
      "Es gibt keinen Unterschied, beide Begriffe sind Synonyme",
    ],
    correctIndex: 0,
    explanation: "Vorkostenstellen (Hilfskostenstellen) bedienen andere Kostenstellen, während Endkostenstellen letztlich den Produkten (Kostenträgern) zugerechnet werden.",
    source: "Kapitel 9.1, Aufbau des Betriebsabrechnungsbogens",
    free: false,
  },
  {
    id: "ba-02",
    topic: "Betriebsabrechnungsbogen",
    type: "numeric",
    prompt: "Eine Reinigungsstelle hat primäre Gemeinkosten von 9.000 € und liefert 450 Stunden an Endkostenstellen (Leistungen an andere Vorkostenstellen werden beim Anbauverfahren ignoriert). Wie hoch ist der Verrechnungspreis pro Stunde (in €)?",
    correctValue: 20,
    tolerance: 0,
    unit: "€",
    explanation: "Anbauverfahren: Verrechnungspreis = 9.000 / 450 = 20 € pro Stunde.",
    source: "Kapitel 9.2, Anbauverfahren",
    free: false,
  },
  {
    id: "ba-03",
    topic: "Betriebsabrechnungsbogen",
    type: "mc",
    prompt: "Was ist der zentrale Unterschied zwischen Stufenleiterverfahren und Gleichungsverfahren?",
    options: [
      "Das Stufenleiterverfahren berücksichtigt wechselseitige Leistungsbeziehungen zwischen Vorkostenstellen, das Gleichungsverfahren nicht",
      "Das Gleichungsverfahren berücksichtigt wechselseitige Leistungsbeziehungen zwischen Vorkostenstellen, das Stufenleiterverfahren nicht",
      "Beide Verfahren liefern immer identische Ergebnisse",
      "Das Stufenleiterverfahren wird nur bei genau zwei Vorkostenstellen angewendet",
    ],
    correctIndex: 1,
    explanation: "Nur das Gleichungsverfahren lässt wechselseitige Leistungsbeziehungen zwischen Vorkostenstellen zu und löst sie über ein Gleichungssystem simultan auf.",
    source: "Kapitel 9.4, Gleichungsverfahren",
    free: false,
  },
  {
    id: "ba-04",
    topic: "Betriebsabrechnungsbogen",
    type: "numeric",
    prompt: "Beim Stufenleiterverfahren wird die Reinigung (primäre Kosten 9.000 €, Gesamtoutput 500 Stunden) zuerst abgerechnet. Wie hoch ist ihr Verrechnungspreis pro Stunde (in €)?",
    correctValue: 18,
    tolerance: 0,
    unit: "€",
    explanation: "Im Stufenleiterverfahren wird beim zuerst abgerechneten Kostenstelle der gesamte Output berücksichtigt: 9.000 / 500 = 18 € pro Stunde.",
    source: "Kapitel 9.3, Stufenleiterverfahren",
    free: false,
  },
  {
    id: "ba-05",
    topic: "Betriebsabrechnungsbogen",
    type: "mc",
    prompt: "Ändert sich die Gesamtsumme der Kosten durch die Wahl des Sekundärkostenverrechnungsverfahrens (Anbau-, Stufenleiter- oder Gleichungsverfahren)?",
    options: ["Ja, das Gleichungsverfahren erhöht immer die Gesamtkosten", "Nein, die Gesamtsumme bleibt gleich, nur die Verteilung auf die Kostenstellen ändert sich", "Ja, das Anbauverfahren senkt immer die Gesamtkosten", "Das hängt von der Anzahl der Endkostenstellen ab"],
    correctIndex: 1,
    explanation: "Alle drei Verfahren verändern lediglich die Verteilung der Kosten auf die Kostenstellen, nicht die Gesamtsumme.",
    source: "Kapitel 9.1, Aufbau des Betriebsabrechnungsbogens",
    free: false,
  },
  // ---------- Interner Zinssatz und Kapitalwertrate ----------
  {
    id: "iz-01",
    topic: "Interner Zinssatz und Kapitalwertrate",
    type: "numeric",
    prompt: "Eine Investition von 50 € liefert im Folgejahr 60 €. Wie hoch ist der interne Zinssatz (in %)?",
    correctValue: 20,
    tolerance: 0,
    unit: "%",
    explanation: "IZS löst 0 = −50 + 60/(1+IZS), also IZS = 60/50 − 1 = 20%.",
    source: "Kapitel 10.1, Der interne Zinssatz und seine Entscheidungsregel",
    free: false,
  },
  {
    id: "iz-02",
    topic: "Interner Zinssatz und Kapitalwertrate",
    type: "mc",
    prompt: "Wie viele interne Zinssätze können bei einem Zahlungsstrom mit n Vorzeichenwechseln höchstens auftreten?",
    options: ["Immer genau 1", "Höchstens n", "Immer n+1", "Nie mehr als 2, unabhängig von n"],
    correctIndex: 1,
    explanation: "Bei n Vorzeichenwechseln im Zahlungsstrom können bis zu n unterschiedliche interne Zinssätze auftreten.",
    source: "Kapitel 10.2, Problem: mehrere interne Zinssätze",
    free: false,
  },
  {
    id: "iz-03",
    topic: "Interner Zinssatz und Kapitalwertrate",
    type: "mc",
    prompt: "Was ist eine typische Ursache dafür, dass die IZSM bei sich gegenseitig ausschließenden Projekten zu einer anderen Rangfolge führt als die Kapitalwertmethode?",
    options: [
      "Beide Projekte haben exakt dieselbe Anfangsauszahlung und denselben Zahlungsverlauf",
      "Größenunterschiede (Scale Problem) oder unterschiedliche zeitliche Verteilung der Zahlungen (Timing-Problem)",
      "Die IZSM kann grundsätzlich nur bei einem einzigen Projekt angewendet werden",
      "Die Kapitalwertmethode ist bei sich ausschließenden Projekten nicht anwendbar",
    ],
    correctIndex: 1,
    explanation: "Größenprobleme und Timing-Probleme können dazu führen, dass IZSM und Kapitalwertmethode bei sich ausschließenden Projekten unterschiedliche Rangfolgen liefern.",
    source: "Kapitel 10.3, Problem: sich gegenseitig ausschließende Projekte",
    free: false,
  },
  {
    id: "iz-04",
    topic: "Interner Zinssatz und Kapitalwertrate",
    type: "mc",
    prompt: "Wie lässt sich das Größen- bzw. Timing-Problem bei sich ausschließenden Projekten lösen?",
    options: [
      "Indem man beide Projekte gleichzeitig durchführt",
      "Durch Anwendung der IZSM auf das Differenzprojekt (Zahlungsstrom-Differenz beider Projekte)",
      "Indem man ausschließlich die Amortisationsdauer betrachtet",
      "Das Problem lässt sich grundsätzlich nicht lösen",
    ],
    correctIndex: 1,
    explanation: "Die Betrachtung des Differenzprojekts (Projekt A minus Projekt B) liefert eine mit der Kapitalwertmethode konsistente Entscheidung.",
    source: "Kapitel 10.3, Problem: sich gegenseitig ausschließende Projekte",
    free: false,
  },
  {
    id: "iz-05",
    topic: "Interner Zinssatz und Kapitalwertrate",
    type: "numeric",
    prompt: "Ein Projekt hat eine Anfangsauszahlung von 30 € und liefert Zahlungen mit einem Barwert der zukünftigen Zahlungen von 33,60 €. Wie hoch ist die Kapitalwertrate (auf 2 Nachkommastellen)?",
    correctValue: 1.12,
    tolerance: 0.02,
    unit: "",
    explanation: "KWR = BW(zukünftige Zahlungen) / Anfangsauszahlung = 33,60 / 30 = 1,12.",
    source: "Kapitel 10.4, Exkurs: Die Kapitalwertrate (Profitability Index)",
    free: false,
  },
  // ---------- Kalkulationsverfahren ----------
  {
    id: "ka-01",
    topic: "Kalkulationsverfahren",
    type: "numeric",
    prompt: "Ein Mineralwasserabfüller hat Herstellkosten von 90.000 € bei 500.000 Litern Produktion und Verwaltungs-/Vertriebskosten von 19.200 € bei 480.000 Litern Absatz. Wie hoch sind die Selbstkosten pro Liter (zweistufige Divisionskalkulation, in €)?",
    correctValue: 0.22,
    tolerance: 0.005,
    unit: "€",
    explanation: "Selbstkosten/Liter = 90.000/500.000 + 19.200/480.000 = 0,18 + 0,04 = 0,22 €.",
    source: "Kapitel 11.1, Divisionskalkulation",
    free: false,
  },
  {
    id: "ka-02",
    topic: "Kalkulationsverfahren",
    type: "mc",
    prompt: "Wofür werden Äquivalenzziffern in der Äquivalenzziffernkalkulation verwendet?",
    options: [
      "Um völlig unterschiedliche Produkte gleich zu behandeln",
      "Um ähnliche Produktvarianten über ein einheitliches Recheneinheiten-Schema vergleichbar zu machen",
      "Um ausschließlich Gemeinkosten von Einzelkosten zu unterscheiden",
      "Um den internen Zinssatz eines Investitionsprojekts zu berechnen",
    ],
    correctIndex: 1,
    explanation: "Äquivalenzziffern rechnen ähnliche Produktvarianten in ein einheitliches 'Einheitsprodukt' um, um sie einheitlich zu kalkulieren.",
    source: "Kapitel 11.2, Äquivalenzziffernkalkulation",
    free: false,
  },
  {
    id: "ka-03",
    topic: "Kalkulationsverfahren",
    type: "numeric",
    prompt: "Eine Kerzenmanufaktur hat eine Gesamt-Einheitsmenge von 80.000 RE bei Gesamtkosten von 56.000 €. Ein Produkt mit ÄZ 1,6 — wie hoch sind seine Selbstkosten pro Stück (in €)?",
    correctValue: 1.12,
    tolerance: 0.02,
    unit: "€",
    explanation: "Selbstkosten/RE = 56.000/80.000 = 0,70 €. Stückkosten = 1,6 · 0,70 = 1,12 €.",
    source: "Kapitel 11.2, Äquivalenzziffernkalkulation",
    free: false,
  },
  {
    id: "ka-04",
    topic: "Kalkulationsverfahren",
    type: "mc",
    prompt: "Welche Annahme liegt der Zuschlagskalkulation zugrunde?",
    options: [
      "Gemeinkosten sind völlig unabhängig von den Einzelkosten",
      "Die Höhe der Einzelkosten verursacht proportional die Höhe der zugehörigen Gemeinkosten",
      "Alle Kosten sind Einzelkosten",
      "Nur variable Kosten dürfen zugeschlagen werden",
    ],
    correctIndex: 1,
    explanation: "Die Zuschlagskalkulation unterstellt, dass die Höhe der Einzelkosten proportional die Höhe der zugehörigen Gemeinkosten verursacht.",
    source: "Kapitel 11.3, Zuschlagskalkulation",
    free: false,
  },
  {
    id: "ka-05",
    topic: "Kalkulationsverfahren",
    type: "mc",
    prompt: "Wann eignet sich die Maschinenstundensatzkalkulation besonders gut gegenüber einer reinen Zuschlagskalkulation?",
    options: [
      "Wenn ein Fertigungsbereich stark maschinenintensiv ist und maschinenabhängige Gemeinkosten hoch sind",
      "Wenn ein Unternehmen nur ein einziges homogenes Massenprodukt herstellt",
      "Wenn alle Kosten variabel sind",
      "Nur bei Dienstleistungsunternehmen ohne Maschineneinsatz",
    ],
    correctIndex: 0,
    explanation: "Die Maschinenstundensatzkalkulation trennt maschinenabhängige Gemeinkosten heraus und ist daher bei stark maschinenintensiven Bereichen genauer als eine reine Zuschlagskalkulation.",
    source: "Kapitel 11.4, Maschinenstundensatzkalkulation",
    free: false,
  },
  // ---------- Eigenkapitalfinanzierung ----------
  {
    id: "ek-01",
    topic: "Eigenkapitalfinanzierung",
    type: "mc",
    prompt: "Was ist ein typisches Merkmal von Vorzugsaktien gegenüber Stammaktien?",
    options: [
      "Sie haben immer ein Mehrfachstimmrecht",
      "Sie können einen höheren Dividendenanspruch bei Verzicht auf das Stimmrecht bieten",
      "Sie haben eine begrenzte Laufzeit wie Anleihen",
      "Sie gewähren kein Recht auf Dividende",
    ],
    correctIndex: 1,
    explanation: "Vorzugsaktien kombinieren häufig einen höheren Dividendenanspruch mit dem Verzicht auf das Stimmrecht.",
    source: "Kapitel 12.1, Aktien: Stamm- und Vorzugsaktien",
    free: false,
  },
  {
    id: "ek-02",
    topic: "Eigenkapitalfinanzierung",
    type: "numeric",
    prompt: "Ein Unternehmen hat 8 Mio. Aktien zu 20 € und gibt 2 Mio. junge Aktien zu einem Bezugspreis von 12 € aus. Wie hoch ist der Mischkurs (in €, auf 2 Nachkommastellen)?",
    correctValue: 18.40,
    tolerance: 0.1,
    unit: "€",
    explanation: "Mischkurs = (20·8.000.000 + 12·2.000.000) / 10.000.000 = (160.000.000+24.000.000)/10.000.000 = 18,40 €.",
    source: "Kapitel 12.3, Kapitalerhöhung und Bezugsrecht",
    free: false,
  },
  {
    id: "ek-03",
    topic: "Eigenkapitalfinanzierung",
    type: "mc",
    prompt: "Was unterscheidet ein Cum-Ex- von einem Cum-Cum-Geschäft?",
    options: [
      "Bei Cum-Ex wird die Steuer einmal gezahlt, aber zweimal erstattet; bei Cum-Cum einmal gezahlt und einmal erstattet",
      "Bei Cum-Cum wird die Steuer zweimal gezahlt und zweimal erstattet",
      "Cum-Ex-Geschäfte betreffen ausschließlich Anleihen, nie Aktien",
      "Es gibt keinen Unterschied zwischen beiden Konstruktionen",
    ],
    correctIndex: 0,
    explanation: "Bei Cum-Cum wird die Steuer einmal gezahlt und einmal erstattet (an einen eigentlich nicht Berechtigten), bei Cum-Ex wird sie einmal gezahlt, aber zweimal erstattet.",
    source: "Kapitel 12.4, Exkurs: Cum-Cum- und Cum-Ex-Geschäfte",
    free: false,
  },
  {
    id: "ek-04",
    topic: "Eigenkapitalfinanzierung",
    type: "mc",
    prompt: "Was passiert mit dem Aktienkurs bei einem Aktienrückkauf in einem perfekten Kapitalmarkt?",
    options: [
      "Der Kurs sinkt um den Rückkaufbetrag pro Aktie",
      "Der Kurs bleibt unverändert, nur die Anzahl ausstehender Aktien sinkt",
      "Der Kurs steigt automatisch um 10%",
      "Der Kurs wird unabhängig von der Marktbewertung neu festgesetzt",
    ],
    correctIndex: 1,
    explanation: "In perfekten Kapitalmärkten bleibt der Kurs beim Aktienrückkauf unverändert; lediglich die Anzahl ausstehender Aktien verringert sich.",
    source: "Kapitel 12.5, Ausschüttungspolitik: Dividende versus Aktienrückkauf",
    free: false,
  },
  {
    id: "ek-05",
    topic: "Eigenkapitalfinanzierung",
    type: "mc",
    prompt: "Wie reagiert der Aktienkurs typischerweise auf eine unerwartete Dividendenkürzung (Signalwirkung von Dividenden)?",
    options: ["Meist positiv, da Kapital im Unternehmen verbleibt", "Meist negativ, da sie als schlechtes Signal über die Unternehmenszukunft interpretiert wird", "Immer neutral, da Dividenden keine Signalwirkung haben", "Nur bei Vorzugsaktien reagiert der Kurs überhaupt"],
    correctIndex: 1,
    explanation: "Eine Dividendenkürzung wird meist als negatives Signal über die Zukunftsaussichten interpretiert und löst typischerweise eine negative Kursreaktion aus.",
    source: "Kapitel 12.5, Ausschüttungspolitik: Dividende versus Aktienrückkauf",
    free: false,
  },
  // ---------- Deckungsbeitragsrechnung ----------
  {
    id: "db-01",
    topic: "Deckungsbeitragsrechnung",
    type: "numeric",
    prompt: "Ein Produkt hat einen Verkaufspreis von 90 € und variable Kosten von 55 € pro Stück. Bei einer Absatzmenge von 600 Stück — wie hoch ist der Deckungsbeitrag pro Produkt (in €)?",
    correctValue: 21000,
    tolerance: 0,
    unit: "€",
    explanation: "DB pro Stück = 90 − 55 = 35 €. DB pro Produkt = 35 · 600 = 21.000 €.",
    source: "Kapitel 13.1, Deckungsbeitrag pro Produkt und insgesamt",
    free: false,
  },
  {
    id: "db-02",
    topic: "Deckungsbeitragsrechnung",
    type: "mc",
    prompt: "Welchen Vorteil hat die Deckungsbeitragsrechnung gegenüber der Vollkostenrechnung bei kurzfristigen Entscheidungen?",
    options: [
      "Sie ignoriert alle Kosten vollständig",
      "Sie vermeidet die oft willkürliche Verteilung von Fixkosten auf einzelne Produkte und zeigt direkt deren Beitrag zur Fixkostendeckung",
      "Sie berücksichtigt automatisch auch steuerliche Effekte",
      "Sie ist ausschließlich für einprodukt-Unternehmen geeignet",
    ],
    correctIndex: 1,
    explanation: "Die Deckungsbeitragsrechnung vermeidet die willkürliche Fixkostenverteilung und zeigt direkt, wie viel jedes Produkt zur Fixkostendeckung beiträgt.",
    source: "Kapitel 13.1, Deckungsbeitrag pro Produkt und insgesamt",
    free: false,
  },
  {
    id: "db-03",
    topic: "Deckungsbeitragsrechnung",
    type: "numeric",
    prompt: "Ein Unternehmen erzielt einen Gesamtdeckungsbeitrag von 65.400 € bei Fixkosten von 44.000 €. Wie hoch ist das Betriebsergebnis (in €)?",
    correctValue: 21400,
    tolerance: 0,
    unit: "€",
    explanation: "Betriebsergebnis = Gesamtdeckungsbeitrag − Fixkosten = 65.400 − 44.000 = 21.400 €.",
    source: "Kapitel 13.2, Vom Gesamtdeckungsbeitrag zum Betriebsergebnis",
    free: false,
  },
  {
    id: "db-04",
    topic: "Deckungsbeitragsrechnung",
    type: "mc",
    prompt: "Ein Produkt hat einen positiven Deckungsbeitrag, das Unternehmen macht insgesamt aber Verlust. Was folgt daraus?",
    options: [
      "Das Produkt sollte sofort aus dem Sortiment genommen werden",
      "Das Produkt trägt trotzdem positiv zur Fixkostendeckung bei; der Verlust liegt an zu geringem Gesamtdeckungsbeitrag im Verhältnis zu den Fixkosten",
      "Der Deckungsbeitrag ist in diesem Fall bedeutungslos",
      "Das Unternehmen sollte den Verkaufspreis dieses Produkts sofort auf null senken",
    ],
    correctIndex: 1,
    explanation: "Ein positiver Deckungsbeitrag bedeutet, dass das Produkt zur Fixkostendeckung beiträgt — der Gesamtverlust entsteht, wenn die Summe aller Deckungsbeiträge die Fixkosten nicht vollständig deckt.",
    source: "Kapitel 13.2, Vom Gesamtdeckungsbeitrag zum Betriebsergebnis",
    free: false,
  },
  // ---------- Portfoliotheorie und CAPM ----------
  {
    id: "pf-01",
    topic: "Portfoliotheorie und CAPM",
    type: "numeric",
    prompt: "Ein Fonds liefert in drei gleich wahrscheinlichen Szenarien Renditen von 0%, 10% und 20%. Wie hoch ist die erwartete Rendite μ (in %)?",
    correctValue: 10,
    tolerance: 0,
    unit: "%",
    explanation: "μ = (0+10+20)/3 = 10%.",
    source: "Kapitel 14.1, Erwartete Rendite und Risiko einzelner Wertpapiere",
    free: false,
  },
  {
    id: "pf-02",
    topic: "Portfoliotheorie und CAPM",
    type: "mc",
    prompt: "Warum ergibt sich die Varianz eines Portfolios aus zwei Wertpapieren nicht als einfache gewichtete Summe der Einzelvarianzen?",
    options: [
      "Weil Portfoliorenditen immer normalverteilt sind",
      "Weil die Kovarianz zwischen den beiden Renditen zusätzlich berücksichtigt werden muss",
      "Weil Portfolios grundsätzlich risikofrei sind",
      "Weil die Portfolioanteile immer gleich groß sein müssen",
    ],
    correctIndex: 1,
    explanation: "Die Portfoliovarianz σw² = w1²σ1² + w2²σ2² + 2w1w2·cov1,2 enthält zusätzlich einen Kovarianzterm, der bei der einfachen gewichteten Summe fehlen würde.",
    source: "Kapitel 14.2, Portfoliorendite und Kovarianz",
    free: false,
  },
  {
    id: "pf-03",
    topic: "Portfoliotheorie und CAPM",
    type: "mc",
    prompt: "Was bewirkt eine negative Korrelation zwischen zwei Wertpapieren in einem Portfolio?",
    options: [
      "Sie erhöht das Portfoliorisiko über den gewichteten Durchschnitt der Einzelrisiken hinaus",
      "Sie kann das Portfoliorisiko deutlich unter den gewichteten Durchschnitt der Einzelrisiken senken (Diversifikationseffekt)",
      "Sie hat keinerlei Einfluss auf das Portfoliorisiko",
      "Sie macht die Berechnung der Portfoliorendite unmöglich",
    ],
    correctIndex: 1,
    explanation: "Eine negative Korrelation führt zu einem starken Diversifikationseffekt, der das Portfoliorisiko deutlich senken kann.",
    source: "Kapitel 14.3, Effizienzlinie und Diversifikation",
    free: false,
  },
  {
    id: "pf-04",
    topic: "Portfoliotheorie und CAPM",
    type: "numeric",
    prompt: "Bei einem risikolosen Zinssatz von 3%, einer erwarteten Marktrendite von 10% und einem Beta von 1,5 — wie hoch ist die erwartete Rendite nach dem CAPM (in %)?",
    correctValue: 13.5,
    tolerance: 0.2,
    unit: "%",
    explanation: "μj = r + (μM − r)·βj = 3% + (10% − 3%)·1,5 = 3% + 10,5% = 13,5%.",
    source: "Kapitel 14.4, Kapitalmarktlinie und Wertpapiermarktlinie (CAPM)",
    free: false,
  },
  {
    id: "pf-05",
    topic: "Portfoliotheorie und CAPM",
    type: "mc",
    prompt: "Was besagt der Beta-Faktor eines Wertpapiers im CAPM?",
    options: [
      "Er misst die absolute erwartete Rendite eines Wertpapiers unabhängig vom Markt",
      "Er misst den Beitrag des Wertpapiers zum Risiko des Marktportfolios (covj,M / varM)",
      "Er ist immer exakt 1 für jedes Wertpapier",
      "Er beschreibt ausschließlich das unternehmensspezifische, diversifizierbare Risiko",
    ],
    correctIndex: 1,
    explanation: "Der Beta-Faktor βj = covj,M / varM misst, wie stark ein Wertpapier zum systematischen Risiko des Marktportfolios beiträgt.",
    source: "Kapitel 14.4, Kapitalmarktlinie und Wertpapiermarktlinie (CAPM)",
    free: false,
  },
];
