import type { Question } from "@/lib/questions";

// Themen entsprechen (in Kurzform) den Kapiteltiteln aus lib/content/bwl-1.ts.
// Alle Übungsaufgaben, die auf reale Saalübungen/Klausuren zurückgehen, wurden
// gemäß den Projektregeln (CLAUDE.md) sowohl in den Zahlen als auch im
// Szenario verändert — es taucht nie derselbe Zahlensatz UND dasselbe
// Szenario wie im Original gleichzeitig auf.
export const TOPICS = [
  "Grundlagen des Unternehmertums",
  "Gründerpersonen und Gelegenheiten",
  "Entscheiden unter Unsicherheit",
  "Geschäftsmodelle",
  "Planung und Effectuation",
  "Lean Startup und Design Thinking",
  "Organisation",
  "Strategische Analyse",
  "Strategische Optionen",
  "Corporate Governance",
  "Personalführung",
  "Kundenverhalten und Daten",
  "Produktgestaltung und Preispolitik",
  "Kommunikationspolitik",
  "Erfolgsmessung: CLV",
] as const;

export const questions: Question[] = [
  // ---------- Grundlagen des Unternehmertums (frei zugänglich) ----------
  {
    id: "gr-01",
    topic: "Grundlagen des Unternehmertums",
    type: "mc",
    prompt: "Was betont Joseph Schumpeter (1911) als Kern des Unternehmertums, im Unterschied zu Jean-Baptiste Say (1803)?",
    options: [
      "Die Verlagerung von Ressourcen in produktivere Sektoren",
      "Neue Faktorenkombinationen, die zu neuen Produkten, Verfahren oder Märkten führen",
      "Die reine Risikobereitschaft der Gründerperson",
      "Die Optimierung bestehender Produktionsprozesse ohne Innovation",
    ],
    correctIndex: 1,
    explanation:
      "Schumpeter stellte neue Faktorenkombinationen und die daraus entstehende 'schöpferische Zerstörung' in den Mittelpunkt, während Say die Ressourcenverlagerung in produktivere Bereiche betonte.",
    source: "Kapitel 1.1, Historische Wurzeln",
    free: true,
  },
  {
    id: "gr-02",
    topic: "Grundlagen des Unternehmertums",
    type: "mc",
    prompt: "Was versteht man unter 'schöpferischer Zerstörung'?",
    options: [
      "Den Konkurs eines Unternehmens durch Missmanagement",
      "Den Prozess, bei dem neue Faktorenkombinationen bestehende Produkte, Verfahren oder Geschäftsmodelle verdrängen",
      "Die Zerstörung von Vermögenswerten durch eine Wirtschaftskrise",
      "Die gezielte Abschaffung veralteter Gesetze",
    ],
    correctIndex: 1,
    explanation:
      "Schöpferische Zerstörung beschreibt, wie Innovationen bestehendes Marktverhalten verdrängen — etwa das Smartphone das klassische Mobiltelefon.",
    source: "Kapitel 1.1, Historische Wurzeln",
    free: true,
  },
  {
    id: "gr-03",
    topic: "Grundlagen des Unternehmertums",
    type: "mc",
    prompt: "Warum scheiterte Kodak laut dem 'Dilemma des Innovators' (Christensen), obwohl das Unternehmen die Digitalkamera selbst miterfunden hatte?",
    options: [
      "Kodak hatte schlicht kein technisches Wissen über Digitalfotografie",
      "Kodak hielt am erfolgreichen Filmrollen-Geschäft fest und übersah die wachsende Leistungsfähigkeit der zunächst unterlegenen Digitaltechnik",
      "Der Markt für Fotografie schrumpfte insgesamt zu schnell",
      "Ein Patentstreit verhinderte den Verkauf von Digitalkameras",
    ],
    correctIndex: 1,
    explanation:
      "Kodak orientierte sich am etablierten, erfolgreichen Geschäftsmodell und übersah, dass die anfangs leistungsschwächere Digitaltechnik in Nischenmärkten heranreifte und den Massenmarkt irgendwann übertraf.",
    source: "Kapitel 1.2, Statisches versus dynamisches Marktparadigma",
    free: true,
  },
  {
    id: "gr-04",
    topic: "Grundlagen des Unternehmertums",
    type: "mc",
    prompt: "Welches der fünf Kernelemente von Entrepreneurship fehlt in dieser Liste: Unternehmer/in, unternehmerische Gelegenheit, Ressourcen, Organisation, ______?",
    options: ["Ein günstiges Umfeld", "Ein Patentportfolio", "Ein Businessplan", "Ein Investor"],
    correctIndex: 0,
    explanation:
      "Die fünf Kernelemente sind Unternehmer/in, unternehmerische Gelegenheit, hinreichende Ressourcen, eine Form der Organisation und ein günstiges Umfeld.",
    source: "Kapitel 1.3, Die fünf Kernelemente von Entrepreneurship",
    free: true,
  },
  {
    id: "gr-05",
    topic: "Grundlagen des Unternehmertums",
    type: "mc",
    prompt: "Was unterscheidet 'Kairos' von 'Chronos' im übertragenen Sinn für unternehmerisches Handeln?",
    options: [
      "Kairos ist die lineare, messbare Zeit, Chronos der günstige Augenblick",
      "Kairos ist der günstige, richtige Augenblick, Chronos die linear ablaufende, messbare Zeit",
      "Beide Begriffe sind Synonyme für Unternehmertum",
      "Kairos bezeichnet nur die Gründungsphase eines Unternehmens",
    ],
    correctIndex: 1,
    explanation:
      "Kairos meint den richtigen, oft flüchtigen Moment, um eine Gelegenheit zu ergreifen — im Unterschied zu Chronos als linear ablaufende Zeit.",
    source: "Kapitel 1.4, Der richtige Moment: Kairos und Ikigai",
    free: true,
  },
  {
    id: "gr-06",
    topic: "Grundlagen des Unternehmertums",
    type: "mc",
    prompt: "Welche vier Elemente bilden nach dem Ikigai-Konzept den idealen Ausgangspunkt einer unternehmerischen Idee?",
    options: [
      "Kapital, Team, Markt, Zeitpunkt",
      "Was man liebt, was man gut kann, was die Welt braucht, wofür man bezahlt werden kann",
      "Produkt, Preis, Promotion, Platzierung",
      "Vision, Mission, Strategie, Kultur",
    ],
    correctIndex: 1,
    explanation: "Ikigai beschreibt den Schnittpunkt aus Leidenschaft, Fähigkeit, gesellschaftlichem Bedarf und Zahlungsbereitschaft.",
    source: "Kapitel 1.4, Der richtige Moment: Kairos und Ikigai",
    free: true,
  },

  // ---------- Gründerpersonen und Gelegenheiten ----------
  {
    id: "gg-01",
    topic: "Gründerpersonen und Gelegenheiten",
    type: "mc",
    prompt: "Welche Altersgruppe stellt gemäß empirischen Gründungsstatistiken den größten Anteil der Gründerinnen und Gründer?",
    options: ["Unter 25 Jahre", "30 bis 39 Jahre", "50 bis 59 Jahre", "Über 65 Jahre"],
    correctIndex: 1,
    explanation: "Die Altersgruppe der 30- bis 39-Jährigen macht mit gut 40 % den größten Anteil der Gründungen aus; das Durchschnittsalter liegt bei rund 38 Jahren.",
    source: "Kapitel 2.1, Wer gründet?",
    free: false,
  },
  {
    id: "gg-02",
    topic: "Gründerpersonen und Gelegenheiten",
    type: "mc",
    prompt: "Wie stark ist der empirische Zusammenhang zwischen Persönlichkeitsmerkmalen (z. B. Risikobereitschaft, Selbstwirksamkeit) und Gründungserfolg laut Rauch & Frese (2007)?",
    options: [
      "Es gibt keinerlei messbaren Zusammenhang",
      "Der Zusammenhang ist von mittlerer Stärke — relevant, aber nicht zu überschätzen",
      "Persönlichkeitsmerkmale sind der stärkste bekannte Erfolgsfaktor überhaupt",
      "Der Zusammenhang gilt nur für Frauen, nicht für Männer",
    ],
    correctIndex: 1,
    explanation: "Rauch & Frese (2007) fanden signifikante, aber nur mittelstarke Zusammenhänge zwischen Persönlichkeitsmerkmalen und unternehmerischem Verhalten.",
    source: "Kapitel 2.1, Wer gründet?",
    free: false,
  },
  {
    id: "gg-03",
    topic: "Gründerpersonen und Gelegenheiten",
    type: "mc",
    prompt: "Worin unterscheiden sich laut Carter et al. (2003) angehende Unternehmer/innen am deutlichsten von anderen Erwerbstätigen?",
    options: [
      "Sie legen deutlich weniger Wert auf Anerkennung und Rollenvorbilder",
      "Sie legen deutlich mehr Wert auf finanziellen Erfolg",
      "Sie streben grundsätzlich keine Selbstverwirklichung an",
      "Sie legen deutlich mehr Wert auf Anerkennung durch andere",
    ],
    correctIndex: 0,
    explanation: "Bei Selbstverwirklichung, finanziellem Erfolg, Innovation und Unabhängigkeit zeigten sich keine Unterschiede — nur bei Rolle und Anerkennung bewerteten angehende Unternehmer/innen deutlich niedriger.",
    source: "Kapitel 2.1, Wer gründet?",
    free: false,
  },
  {
    id: "gg-04",
    topic: "Gründerpersonen und Gelegenheiten",
    type: "mc",
    prompt: "Welche Beziehung fanden Wennekers, Thurik & Reynolds (2005) zwischen Pro-Kopf-Einkommen und Gründungsraten über viele Länder hinweg?",
    options: ["Eine streng lineare, positive Beziehung", "Eine U-förmige Beziehung", "Keinerlei Zusammenhang", "Eine streng negative, lineare Beziehung"],
    correctIndex: 1,
    explanation: "Sowohl sehr arme als auch sehr reiche Länder weisen relativ hohe Gründungsraten auf — daraus ergibt sich eine U-förmige Kurve.",
    source: "Kapitel 2.2, Unternehmertum und Volkswirtschaft",
    free: false,
  },
  {
    id: "gg-05",
    topic: "Gründerpersonen und Gelegenheiten",
    type: "mc",
    prompt: "Welches der folgenden Merkmale gehört NICHT zu den fünf Merkmalen einer attraktiven unternehmerischen Gelegenheit?",
    options: ["Zeitlich passend", "Rentabel", "Vollständig risikofrei", "Wichtig für die Kundschaft"],
    correctIndex: 2,
    explanation: "Die fünf Merkmale sind zeitlich passend, lösbar, wichtig, rentabel und in einen günstigen Kontext eingebettet — 'vollständig risikofrei' gehört nicht dazu, da unternehmerisches Handeln stets mit Risiko verbunden ist.",
    source: "Kapitel 2.3, Die unternehmerische Gelegenheit erkennen und bewerten",
    free: false,
  },
  {
    id: "gg-06",
    topic: "Gründerpersonen und Gelegenheiten",
    type: "numeric",
    prompt: "Ein Kondratieff-Zyklus wird durch einen grundlegenden technischen Paradigmenwechsel ausgelöst und dauert typischerweise wie viele Jahre?",
    correctValue: 55,
    tolerance: 5,
    unit: "Jahre",
    explanation: "Ein Kondratieff-Zyklus dauert nach der klassischen Theorie ungefähr 50 bis 60 Jahre.",
    source: "Kapitel 2.4, Exkurs: Trends systematisch erkennen",
    free: false,
  },
  {
    id: "gg-07",
    topic: "Gründerpersonen und Gelegenheiten",
    type: "mc",
    prompt: "In welcher Phase des Gartner Hype Cycle befindet sich eine Technologie, wenn die anfängliche Euphorie bereits abgeflaut ist, sich aber noch kein produktiver Nutzen etabliert hat?",
    options: ["Innovationsauslöser", "Spitze der übertriebenen Erwartungen", "Tal der Desillusionierung", "Plateau der Produktivität"],
    correctIndex: 2,
    explanation: "Das 'Tal der Desillusionierung' folgt auf die übertriebenen Erwartungen, bevor eine Technologie über die 'Rampe der Aufklärung' das 'Plateau der Produktivität' erreicht.",
    source: "Kapitel 2.4, Exkurs: Trends systematisch erkennen",
    free: false,
  },

  // ---------- Entscheiden unter Unsicherheit ----------
  {
    id: "eu-01",
    topic: "Entscheiden unter Unsicherheit",
    type: "mc",
    prompt: "Was unterscheidet eine Entscheidung 'bei Risiko' von einer Entscheidung 'bei Ungewissheit'?",
    options: [
      "Bei Risiko sind die Zustandswahrscheinlichkeiten bekannt, bei Ungewissheit nicht",
      "Bei Ungewissheit ist der Umweltzustand von vornherein bekannt",
      "Beide Begriffe sind austauschbar",
      "Risiko bezieht sich nur auf finanzielle Entscheidungen",
    ],
    correctIndex: 0,
    explanation: "Bei Risiko sind die Eintrittswahrscheinlichkeiten der Umweltzustände bekannt oder schätzbar, bei Ungewissheit fehlen selbst diese.",
    source: "Kapitel 3.1, Das Grundmodell der Entscheidungstheorie",
    free: false,
  },
  {
    id: "eu-02",
    topic: "Entscheiden unter Unsicherheit",
    type: "numeric",
    prompt:
      "Ein Getränkehändler kann sein Sortiment entweder unverändert lassen (Alternative A, sicherer Deckungsbeitrag: 200 €) oder eine limitierte Sommer-Aktion starten (Alternative B: bei gutem Wetter, Wahrscheinlichkeit 70 %, 500 € Deckungsbeitrag; bei schlechtem Wetter, Wahrscheinlichkeit 30 %, nur 40 €). Wie hoch ist der Erwartungswert von Alternative B?",
    correctValue: 362,
    tolerance: 1,
    unit: "€",
    explanation: "EW(B) = 0,7 · 500 € + 0,3 · 40 € = 350 € + 12 € = 362 €.",
    source: "Kapitel 3.2, Entscheidungen bei Risiko",
    free: false,
  },
  {
    id: "eu-03",
    topic: "Entscheiden unter Unsicherheit",
    type: "mc",
    prompt:
      "Ein Eisverkäufer prüft drei Kühlwagen-Modelle, deren Sommergewinn vom Wetter abhängt (schlecht/mittel/gut): Modell X liefert 5.000 € / 15.000 € / 25.000 €, Modell Y liefert 9.000 € / 13.000 € / 18.000 €, Modell Z liefert 2.000 € / 12.000 € / 30.000 €. Für welches Modell entscheidet sich eine Entscheiderin nach der Maximin-Regel?",
    options: ["Modell X", "Modell Y", "Modell Z", "Alle drei sind nach Maximin gleichwertig"],
    correctIndex: 1,
    explanation: "Maximin vergleicht die schlechtestmöglichen Ergebnisse: X = 5.000 €, Y = 9.000 €, Z = 2.000 €. Modell Y hat das höchste Minimum und wird gewählt.",
    source: "Kapitel 3.3, Entscheidungsregeln bei Ungewissheit",
    free: false,
  },
  {
    id: "eu-04",
    topic: "Entscheiden unter Unsicherheit",
    type: "numeric",
    prompt:
      "Für dieselben drei Kühlwagen-Modelle aus der vorherigen Aufgabe (X: 5.000/15.000/25.000 €, Y: 9.000/13.000/18.000 €, Z: 2.000/12.000/30.000 €) — wie hoch ist der Hurwicz-Wert für Modell Y bei einem Optimismusparameter von α = 0,3?",
    correctValue: 11700,
    tolerance: 50,
    unit: "€",
    explanation: "HV(Y) = 0,3 · 18.000 € + 0,7 · 9.000 € = 5.400 € + 6.300 € = 11.700 €.",
    source: "Kapitel 3.3, Entscheidungsregeln bei Ungewissheit",
    free: false,
  },
  {
    id: "eu-05",
    topic: "Entscheiden unter Unsicherheit",
    type: "mc",
    prompt: "Was beschreibt der 'Bandbreiteneffekt' bei der Nutzwertanalyse?",
    options: [
      "Kriterien mit größerer Wertespanne werden in der Praxis oft unbewusst stärker gewichtet als beabsichtigt",
      "Die Nutzwertanalyse funktioniert nur bei genau zwei Kriterien",
      "Je mehr Kriterien einbezogen werden, desto genauer wird das Ergebnis automatisch",
      "Die Gewichte müssen sich immer zu 100 addieren, niemals zu 1",
    ],
    correctIndex: 0,
    explanation: "Der Bandbreiteneffekt beschreibt die Verzerrung, dass Kriterien mit größerer Wertespanne implizit stärker in das Ergebnis eingehen, als ihr eigentliches Gewicht vorsieht.",
    source: "Kapitel 3.4, Entscheiden bei mehreren Zielen",
    free: false,
  },
  {
    id: "eu-06",
    topic: "Entscheiden unter Unsicherheit",
    type: "numeric",
    prompt:
      "Eine Kanzlei vergleicht zwei Buchhaltungs-Softwarelösungen nach den Kriterien Preis (Gewicht 0,3), Benutzerfreundlichkeit (Gewicht 0,5) und Support (Gewicht 0,2), jeweils auf einer Nutzenskala von 0 bis 1. Software A erzielt die Teilnutzen 0,5 / 0,8 / 0,6. Wie hoch ist ihr Gesamtnutzwert U(A)?",
    correctValue: 0.67,
    tolerance: 0.02,
    explanation: "U(A) = 0,3 · 0,5 + 0,5 · 0,8 + 0,2 · 0,6 = 0,15 + 0,40 + 0,12 = 0,67.",
    source: "Kapitel 3.4, Entscheiden bei mehreren Zielen",
    free: false,
  },
  {
    id: "eu-07",
    topic: "Entscheiden unter Unsicherheit",
    type: "mc",
    prompt: "Welcher Diagrammtyp eignet sich laut der Diagrammtyp-Matrix am besten für einen Korrelationsvergleich zwischen zwei Größen?",
    options: ["Kreisdiagramm", "Streudiagramm", "Balkendiagramm für Rangfolgen", "Gestapeltes Balkendiagramm für Anteile"],
    correctIndex: 1,
    explanation: "Zusammenhänge zwischen zwei Größen werden am klarsten in einem Streudiagramm (Scatterplot) sichtbar.",
    source: "Kapitel 3.5, Exkurs: Daten überzeugend in Schaubildern kommunizieren",
    free: false,
  },

  // ---------- Geschäftsmodelle ----------
  {
    id: "gm-01",
    topic: "Geschäftsmodelle",
    type: "mc",
    prompt: "Welches Feld steht im Zentrum des Business Model Canvas?",
    options: ["Kostenstruktur", "Value Proposition (Wertversprechen)", "Schlüsselpartner", "Erlösströme"],
    correctIndex: 1,
    explanation: "Die Value Proposition — das Wert- bzw. Leistungsversprechen — bildet das Zentrum des Canvas und wird auf die Kundensegmente bezogen.",
    source: "Kapitel 4.2, Der Business Model Canvas",
    free: false,
  },
  {
    id: "gm-02",
    topic: "Geschäftsmodelle",
    type: "mc",
    prompt: "Was unterscheidet ein Geschäftsmodell von einer Wettbewerbsstrategie?",
    options: [
      "Ein Geschäftsmodell beschreibt Komponenten und deren Zusammenspiel, ohne Aussagen zur Konkurrenz zu treffen; die Wettbewerbsstrategie beschreibt die Abgrenzung gegenüber Konkurrenten",
      "Beide Begriffe sind vollständig identisch",
      "Ein Geschäftsmodell ist nur für Startups relevant, eine Wettbewerbsstrategie nur für Konzerne",
      "Eine Wettbewerbsstrategie beschreibt ausschließlich die Kostenstruktur eines Unternehmens",
    ],
    correctIndex: 0,
    explanation: "Ein Geschäftsmodell zeigt, wie ein Unternehmen Wert erzeugt und Ertrag sichert — die Wettbewerbsstrategie ergänzt, wie es sich gegenüber Konkurrenz abgrenzt.",
    source: "Kapitel 4.1, Was ist ein Geschäftsmodell?",
    free: false,
  },
  {
    id: "gm-03",
    topic: "Geschäftsmodelle",
    type: "mc",
    prompt: "Nach Stachowiak (1973) muss ein Modell drei Eigenschaften erfüllen: Abbildung, Pragmatismus und …?",
    options: ["Idealisierung", "Perfektion", "Objektivität", "Unveränderlichkeit"],
    correctIndex: 0,
    explanation: "Ein Modell basiert auf begründeter Abstraktion und Vereinfachung (Idealisierung) — es bildet nicht alle Elemente der Realität ab.",
    source: "Kapitel 4.1, Was ist ein Geschäftsmodell?",
    free: false,
  },
  {
    id: "gm-04",
    topic: "Geschäftsmodelle",
    type: "mc",
    prompt: "Welche zwei Felder des Business Model Canvas verbinden die Value Proposition mit den Kundensegmenten?",
    options: [
      "Schlüsselressourcen und Schlüsselaktivitäten",
      "Kanäle und Kundenbeziehungen",
      "Kostenstruktur und Erlösströme",
      "Schlüsselpartner und Kostenstruktur",
    ],
    correctIndex: 1,
    explanation: "Kanäle beschreiben, wie Kundschaft das Angebot findet und erwirbt; Kundenbeziehungen reichen von der einmaligen Transaktion bis zur langfristigen Community.",
    source: "Kapitel 4.2, Der Business Model Canvas",
    free: false,
  },
  {
    id: "gm-05",
    topic: "Geschäftsmodelle",
    type: "mc",
    prompt: "Was versteht man unter dem 'Strategie-System-Fit'?",
    options: [
      "Die Übereinstimmung von Strategie, Geschäftsmodell und tatsächlicher Organisation",
      "Die Anzahl der Erlösströme eines Geschäftsmodells",
      "Ein Synonym für den Business Model Canvas",
      "Die Anpassung der Strategie an gesetzliche Vorgaben",
    ],
    correctIndex: 0,
    explanation: "Stimmen Strategie, Geschäftsmodell und Organisation nicht überein, bleibt selbst die beste Strategie wirkungslos.",
    source: "Kapitel 4.3, Geschäftsmodell als Instrument der Strategieumsetzung",
    free: false,
  },
  {
    id: "gm-06",
    topic: "Geschäftsmodelle",
    type: "mc",
    prompt: "Auf der linken Seite des Business Model Canvas ('hinter den Kulissen') stehen unter anderem …",
    options: [
      "Kundensegmente und Kanäle",
      "Schlüsselpartner, Schlüsselaktivitäten und Schlüsselressourcen",
      "Erlösströme und Kundenbeziehungen",
      "Nur die Kostenstruktur",
    ],
    correctIndex: 1,
    explanation: "Die linke Seite zeigt, was nötig ist, um das Wertversprechen zu erbringen: Partner, Aktivitäten und Ressourcen.",
    source: "Kapitel 4.2, Der Business Model Canvas",
    free: false,
  },

  // ---------- Planung und Effectuation ----------
  {
    id: "pe-01",
    topic: "Planung und Effectuation",
    type: "mc",
    prompt: "Wie lautet Steve Blanks bekannte Aussage über Geschäftspläne?",
    options: [
      "'Ein guter Geschäftsplan garantiert den Erfolg eines Startups'",
      "'Kein Geschäftsplan überlebt den ersten Kontakt mit einem Kunden'",
      "'Geschäftspläne sind für Startups überflüssig'",
      "'Ein Geschäftsplan sollte niemals überarbeitet werden'",
    ],
    correctIndex: 1,
    explanation: "Blank betont, dass Pläne in der Praxis ständig an reale Kundenreaktionen angepasst werden müssen.",
    source: "Kapitel 5.1, Funktion und Zielgruppen von Geschäftsplänen",
    free: false,
  },
  {
    id: "pe-02",
    topic: "Planung und Effectuation",
    type: "mc",
    prompt: "In der Hippodrom-Metapher (MacMillan et al., 1985) steht 'der Reiter' für was?",
    options: ["Das Produkt", "Das Team", "Den Markt", "Die Finanzen"],
    correctIndex: 1,
    explanation: "Pferd = Produkt, Reiter = Team, Parcours = Markt, Wetten = Finanzen.",
    source: "Kapitel 5.1, Funktion und Zielgruppen von Geschäftsplänen",
    free: false,
  },
  {
    id: "pe-03",
    topic: "Planung und Effectuation",
    type: "mc",
    prompt: "Was ist der zentrale Unterschied zwischen kausaler Logik und Effectuation?",
    options: [
      "Kausale Logik legt zuerst das Ziel fest, Effectuation beginnt bei den vorhandenen Mitteln",
      "Effectuation wird nur von Großunternehmen genutzt",
      "Kausale Logik verzichtet vollständig auf Planung",
      "Beide Ansätze sind inhaltlich identisch, nur die Begriffe unterscheiden sich",
    ],
    correctIndex: 0,
    explanation: "Effectuation fragt 'Was kann ich mit dem, was ich habe, sofort tun?', statt zuerst ein Ziel zu fixieren und dann Mittel dafür zu suchen.",
    source: "Kapitel 5.3, Effectuation: die Logik erfahrener Gründer",
    free: false,
  },
  {
    id: "pe-04",
    topic: "Planung und Effectuation",
    type: "mc",
    prompt: "Welches Effectuation-Prinzip orientiert sich am Einsatz, den man bereit ist zu verlieren, statt am erwarteten Ertrag?",
    options: ["Crazy Quilt Principle", "Affordable Loss Principle", "Lemonade Principle", "Pilot-in-the-Plane Principle"],
    correctIndex: 1,
    explanation: "Das Affordable-Loss-Prinzip ersetzt die Frage 'Was kann ich gewinnen?' durch 'Was kann ich mir zu verlieren leisten?'.",
    source: "Kapitel 5.4, Die fünf Prinzipien der Effectuation",
    free: false,
  },
  {
    id: "pe-05",
    topic: "Planung und Effectuation",
    type: "mc",
    prompt: "Percy Spencer entdeckte 1945 zufällig, dass ein Magnetron Schokolade in seiner Hosentasche schmelzen ließ, und entwickelte daraus die Mikrowelle. Welches Effectuation-Prinzip illustriert dieses Beispiel am besten?",
    options: ["Bird in Hand Principle", "Crazy Quilt Principle", "Lemonade Principle", "Affordable Loss Principle"],
    correctIndex: 2,
    explanation: "Das Lemonade-Prinzip lädt Zufälle und Überraschungen aktiv als Chance ein, statt sie zu vermeiden.",
    source: "Kapitel 5.4, Die fünf Prinzipien der Effectuation",
    free: false,
  },
  {
    id: "pe-06",
    topic: "Planung und Effectuation",
    type: "mc",
    prompt: "Wofür steht das 'Crazy Quilt Principle' der Effectuation?",
    options: [
      "Partnerschaften mit denen eingehen, die sich früh selbst an einem unsicheren Vorhaben beteiligen, statt strikt zwischen 'richtigen Partnern' und Konkurrenz zu trennen",
      "Ausschließlich mit bereits etablierten Großkonzernen zusammenzuarbeiten",
      "Alle Entscheidungen einem einzigen festen Businessplan unterzuordnen",
      "Wettbewerber grundsätzlich juristisch zu bekämpfen",
    ],
    correctIndex: 0,
    explanation: "So entsteht ein 'Flickenteppich' (crazy quilt) aus sich selbst selektierenden Partnerinnen und Partnern.",
    source: "Kapitel 5.4, Die fünf Prinzipien der Effectuation",
    free: false,
  },

  // ---------- Lean Startup und Design Thinking ----------
  {
    id: "ls-01",
    topic: "Lean Startup und Design Thinking",
    type: "mc",
    prompt: "Was ist ein Minimum Viable Product (MVP)?",
    options: [
      "Ein unfertiges, fehlerhaftes Produkt, das möglichst günstig produziert wird",
      "Eine Version eines neuen Produkts, die mit dem geringsten Aufwand ein Maximum an validiertem Wissen über Kundschaft liefert",
      "Das teuerste Produkt im Portfolio eines Startups",
      "Ein Produkt, das ausschließlich für interne Testzwecke gedacht ist und nie verkauft wird",
    ],
    correctIndex: 1,
    explanation: "Ein MVP ist funktionsfähig und stiftet echten Mehrwert — es ist bewusst minimal, aber kein fehlerhaftes Produkt (Ries, 2011).",
    source: "Kapitel 6.2, Minimum Viable Product und validiertes Lernen",
    free: false,
  },
  {
    id: "ls-02",
    topic: "Lean Startup und Design Thinking",
    type: "mc",
    prompt: "Was ist eine 'leap of faith assumption' im Lean-Startup-Ansatz?",
    options: [
      "Eine für den Erfolg entscheidende Annahme, zu der noch kaum belastbare Daten vorliegen",
      "Eine gesetzlich vorgeschriebene Aussage im Geschäftsplan",
      "Eine Annahme, die niemals getestet werden muss",
      "Ein anderes Wort für Umsatzprognose",
    ],
    correctIndex: 0,
    explanation: "Leap-of-faith-Annahmen sind erfolgskritisch, aber datenarm — sie sollten deshalb vorrangig getestet werden.",
    source: "Kapitel 6.1, Lean Startup: Hypothesen statt Gewissheiten",
    free: false,
  },
  {
    id: "ls-03",
    topic: "Lean Startup und Design Thinking",
    type: "mc",
    prompt: "Was unterscheidet einen Pivot von einer Iteration?",
    options: [
      "Ein Pivot ist eine kleine Anpassung, eine Iteration eine radikale Kurskorrektur",
      "Eine Iteration ist eine kleinere Anpassung, ein Pivot eine strukturierte, radikale Kurskorrektur einer grundlegenden Hypothese",
      "Beide Begriffe sind austauschbar",
      "Ein Pivot betrifft nur die Finanzierung, nicht das Produkt",
    ],
    correctIndex: 1,
    explanation: "Kleinere Anpassungen sind Iterationen; ein Pivot testet eine grundlegend neue Hypothese über Produkt, Strategie oder Wachstumsmotor (Ries, 2011).",
    source: "Kapitel 6.3, Der Pivot",
    free: false,
  },
  {
    id: "ls-04",
    topic: "Lean Startup und Design Thinking",
    type: "mc",
    prompt: "In welcher Reihenfolge läuft der Zyklus des validierten Lernens im Lean Startup ab?",
    options: [
      "Ideen → Bauen → Produkt → Messen → Daten → Lernen",
      "Bauen → Lernen → Ideen → Daten → Messen → Produkt",
      "Messen → Ideen → Lernen → Bauen → Produkt → Daten",
      "Produkt → Daten → Ideen → Messen → Bauen → Lernen",
    ],
    correctIndex: 0,
    explanation: "Der Zyklus folgt der Reihenfolge Ideen (Hypothesen) → Bauen (Funktionstyp) → Produkt (MVP) → Messen (Experiment) → Daten → Lernen.",
    source: "Kapitel 6.2, Minimum Viable Product und validiertes Lernen",
    free: false,
  },
  {
    id: "ls-05",
    topic: "Lean Startup und Design Thinking",
    type: "mc",
    prompt: "Welche drei Kernprinzipien tragen den Design-Thinking-Prozess?",
    options: [
      "Empathie, Kreativität, Experimentieren",
      "Planung, Kontrolle, Budgetierung",
      "Kostenführerschaft, Differenzierung, Fokus",
      "Effektivität, Effizienz, Legitimität",
    ],
    correctIndex: 0,
    explanation: "Design Thinking beruht auf Empathie für Nutzende, kreativer Ideengenerierung und schnellem Experimentieren.",
    source: "Kapitel 6.4, Design Thinking als nutzerorientierte Innovationsmethode",
    free: false,
  },
  {
    id: "ls-06",
    topic: "Lean Startup und Design Thinking",
    type: "mc",
    prompt: "Was beschreibt das 'Double Diamond'-Modell des Design Thinking?",
    options: [
      "Zwei aufeinanderfolgende Divergenz-Konvergenz-Phasen: erst den Problemraum, dann den Lösungsraum öffnen und wieder verdichten",
      "Eine einzige, streng lineare Abfolge ohne Wiederholungen",
      "Eine Methode, mit der ausschließlich Finanzkennzahlen visualisiert werden",
      "Ein Werkzeug zur Berechnung des optimalen Werbebudgets",
    ],
    correctIndex: 0,
    explanation: "Erst wird der Problemraum geöffnet und verdichtet (Verstehen, Beobachten, Sichtweise definieren), dann analog der Lösungsraum (Ideen finden, Prototypen, Testen).",
    source: "Kapitel 6.4, Design Thinking als nutzerorientierte Innovationsmethode",
    free: false,
  },

  // ---------- Organisation ----------
  {
    id: "org-01",
    topic: "Organisation",
    type: "mc",
    prompt: "Welcher Holding-Typ beschränkt sich auf die reine Kapitalbeteiligung und -steuerung der Töchter, ohne operativ einzugreifen?",
    options: ["Finanzholding", "Management-Holding", "Operative Holding", "Funktionalholding"],
    correctIndex: 0,
    explanation: "Die Finanzholding steuert nur das Kapital; die Management-Holding übernimmt zusätzlich strategische Führungsaufgaben, die operative Holding führt zusätzlich ein eigenes operatives Geschäft.",
    source: "Kapitel 7.2, Konzern- und Holdingstrukturen",
    free: false,
  },
  {
    id: "org-02",
    topic: "Organisation",
    type: "mc",
    prompt: "Ein Unternehmen bildet Abteilungen nach Einkauf, Produktion und Vertrieb. Um welche Gliederungsform handelt es sich?",
    options: ["Divisionale Gliederung", "Funktionale Gliederung", "Matrixorganisation", "Internes Netzwerk"],
    correctIndex: 1,
    explanation: "Die funktionale Gliederung bildet Abteilungen nach betrieblichen Funktionen — sie nutzt Spezialisierungsvorteile, erschwert aber die Koordination bei vielfältigen Produktlinien.",
    source: "Kapitel 7.3, Funktionale und divisionale Gliederung",
    free: false,
  },
  {
    id: "org-03",
    topic: "Organisation",
    type: "mc",
    prompt: "Was kennzeichnet ein Mehrliniensystem im Vergleich zum Einliniensystem?",
    options: [
      "Jede Stelle erhält Weisungen von genau einer übergeordneten Instanz",
      "Eine Stelle kann Weisungen von mehreren übergeordneten Instanzen gleichzeitig erhalten (z. B. Matrixorganisation)",
      "Es gibt überhaupt keine Weisungsbefugnisse mehr",
      "Es handelt sich um ein Synonym für die funktionale Gliederung",
    ],
    correctIndex: 1,
    explanation: "Das Mehrliniensystem erhöht die Flexibilität (z. B. fachliche und disziplinarische Linie), kann aber zu Kompetenzkonflikten führen.",
    source: "Kapitel 7.4, Liniensysteme und Koordinationsmechanismen",
    free: false,
  },
  {
    id: "org-04",
    topic: "Organisation",
    type: "mc",
    prompt: "Was besagt Gutenbergs Substitutionsgesetz der Organisation?",
    options: [
      "Je mehr Regeln, desto effizienter die Organisation",
      "Sowohl Unter- als auch Überorganisation senken die Effizienz — dazwischen liegt ein Organisationsoptimum",
      "Organisation ist für die Effizienz eines Unternehmens irrelevant",
      "Nur mechanistische Organisationen können effizient sein",
    ],
    correctIndex: 1,
    explanation: "Zu wenig Regelung erzeugt Reibungsverluste, zu viel Regelung erzeugt Starrheit — beides senkt die Effizienz.",
    source: "Kapitel 7.5, Gutenbergs Substitutionsgesetz und Organisationsstile",
    free: false,
  },
  {
    id: "org-05",
    topic: "Organisation",
    type: "mc",
    prompt: "Welchen Organisationsstil beschreiben Burns & Stalker als besonders geeignet für ein dynamisches, unsicheres Branchenumfeld?",
    options: ["Mechanistische Organisation", "Organische Organisation", "Funktionale Organisation", "Finanzholding"],
    correctIndex: 1,
    explanation: "Organische Organisationen mit flachen Hierarchien und hoher Selbstorganisation passen sich schneller an dynamische Umfelder an.",
    source: "Kapitel 7.5, Gutenbergs Substitutionsgesetz und Organisationsstile",
    free: false,
  },
  {
    id: "org-06",
    topic: "Organisation",
    type: "mc",
    prompt: "Welcher der folgenden Mechanismen gehört NICHT zu den vier klassischen Koordinationsmechanismen in Organisationen?",
    options: ["Persönliche Weisung", "Gegenseitige Anpassung", "Programmierung (feste Regeln)", "Aktienrückkauf"],
    correctIndex: 3,
    explanation: "Die vier Koordinationsmechanismen sind persönliche Weisung, gegenseitige Anpassung, Programmierung und Organisationskultur.",
    source: "Kapitel 7.4, Liniensysteme und Koordinationsmechanismen",
    free: false,
  },

  // ---------- Strategische Analyse ----------
  {
    id: "sa-01",
    topic: "Strategische Analyse",
    type: "mc",
    prompt: "Welches der fünf 'P's nach Mintzberg beschreibt Strategie als ein im Nachhinein erkennbares Handlungsmuster, auch ohne expliziten Plan?",
    options: ["Plan", "Muster (Pattern)", "Position", "Trick (Ploy)"],
    correctIndex: 1,
    explanation: "'Muster' beschreibt Strategie als konsistentes Handeln über die Zeit, das sich auch ohne vorab formulierten Plan erkennen lässt.",
    source: "Kapitel 8.1, Was ist Strategie? Die fünf P's nach Mintzberg",
    free: false,
  },
  {
    id: "sa-02",
    topic: "Strategische Analyse",
    type: "mc",
    prompt: "Was unterscheidet Unternehmensstrategie von Wettbewerbsstrategie?",
    options: [
      "Unternehmensstrategie klärt 'where to compete', Wettbewerbsstrategie 'how to compete'",
      "Beide Begriffe sind Synonyme",
      "Wettbewerbsstrategie betrifft nur die Kostenrechnung",
      "Unternehmensstrategie gilt nur für Konzerne, nie für Startups",
    ],
    correctIndex: 0,
    explanation: "Unternehmensstrategie legt fest, in welchen Geschäftsfeldern man tätig sein will; Wettbewerbsstrategie, wie man sich in einem Feld behauptet.",
    source: "Kapitel 8.1, Was ist Strategie? Die fünf P's nach Mintzberg",
    free: false,
  },
  {
    id: "sa-03",
    topic: "Strategische Analyse",
    type: "mc",
    prompt: "Welche zwei Dimensionen kombiniert die SWOT-Analyse?",
    options: [
      "Interne Stärken/Schwächen und externe Chancen/Risiken",
      "Preis und Menge",
      "Marktanteil und Marktwachstum",
      "Kosten und Erlöse",
    ],
    correctIndex: 0,
    explanation: "SWOT verbindet eine interne Analyse (Strengths/Weaknesses) mit einer externen Analyse (Opportunities/Threats).",
    source: "Kapitel 8.2, SWOT-Analyse und Branchenstrukturanalyse",
    free: false,
  },
  {
    id: "sa-04",
    topic: "Strategische Analyse",
    type: "mc",
    prompt: "Welche der folgenden Kräfte gehört NICHT zu Porters Five Forces?",
    options: ["Verhandlungsmacht von Lieferanten", "Bedrohung durch Ersatzprodukte", "Wechselkursschwankungen", "Rivalität unter bestehenden Wettbewerbern"],
    correctIndex: 2,
    explanation: "Die Five Forces sind Lieferantenmacht, Abnehmermacht, neue Konkurrenz, Ersatzprodukte und Rivalität — Wechselkursschwankungen gehören nicht dazu.",
    source: "Kapitel 8.2, SWOT-Analyse und Branchenstrukturanalyse",
    free: false,
  },
  {
    id: "sa-05",
    topic: "Strategische Analyse",
    type: "mc",
    prompt: "Marketing & Vertrieb sowie Kundendienst gehören in Porters Wertschöpfungskette zu welcher Kategorie?",
    options: ["Unterstützende Aktivitäten", "Primäre Aktivitäten", "Weder noch, sie gehören zur Unternehmensinfrastruktur", "Sie zählen zur Beschaffung"],
    correctIndex: 1,
    explanation: "Die fünf primären Aktivitäten sind Eingangslogistik, Produktion, Ausgangslogistik, Marketing & Vertrieb sowie Kundendienst.",
    source: "Kapitel 8.3, Die Wertschöpfungskette",
    free: false,
  },
  {
    id: "sa-06",
    topic: "Strategische Analyse",
    type: "mc",
    prompt: "Worauf führt der Resource-based View (Barney, 1991) nachhaltige Wettbewerbsvorteile primär zurück?",
    options: [
      "Eine attraktive Positionierung im Marktumfeld",
      "Wertvolle, seltene, schwer imitierbare und organisatorisch nutzbare interne Ressourcen und Fähigkeiten",
      "Ausschließlich den Zugang zu billigem Fremdkapital",
      "Die Anzahl der Wettbewerber in der Branche",
    ],
    correctIndex: 1,
    explanation: "Der Resource-based View blickt nach innen und sieht die Quelle von Wettbewerbsvorteilen in besonderen internen Ressourcen.",
    source: "Kapitel 8.4, Market-based View versus Resource-based View",
    free: false,
  },

  // ---------- Strategische Optionen ----------
  {
    id: "so-01",
    topic: "Strategische Optionen",
    type: "mc",
    prompt: "In der Ansoff-Matrix bezeichnet die Kombination 'neues Produkt, neuer Markt' welche Strategie?",
    options: ["Marktdurchdringung", "Marktentwicklung", "Produktentwicklung", "Diversifikation"],
    correctIndex: 3,
    explanation: "Diversifikation kombiniert ein neues Produkt mit einem neuen Markt — die risikoreichste der vier Ansoff-Strategien.",
    source: "Kapitel 9.1, Die Ansoff-Matrix",
    free: false,
  },
  {
    id: "so-02",
    topic: "Strategische Optionen",
    type: "mc",
    prompt: "Was bedeutet es, im Sinne Porters 'zwischen den Stühlen' zu landen ('stuck in the middle')?",
    options: [
      "Weder klar Kostenführer noch klar Differenzierer zu sein",
      "Erfolgreich beide generischen Strategien gleichzeitig zu verfolgen",
      "Ausschließlich in einem Nischenmarkt tätig zu sein",
      "Der höchste Marktanteil in der Branche zu sein",
    ],
    correctIndex: 0,
    explanation: "Wer sich weder klar über Kosten noch über Differenzierung positioniert, läuft Gefahr, gegenüber fokussierteren Wettbewerbern zu unterliegen.",
    source: "Kapitel 9.2, Generische Wettbewerbsstrategien",
    free: false,
  },
  {
    id: "so-03",
    topic: "Strategische Optionen",
    type: "numeric",
    prompt: "Ein Geschäftsfeld hält einen Marktanteil von 18 %; der größte Wettbewerber hält 30 %. Wie hoch ist der relative Marktanteil (für die BCG-Matrix)?",
    correctValue: 0.6,
    tolerance: 0.02,
    explanation: "Relativer Marktanteil = eigener Marktanteil / Marktanteil des größten Wettbewerbers = 18 % / 30 % = 0,6.",
    source: "Kapitel 9.3, Portfolioanalyse: BCG-Matrix und McKinsey-Matrix",
    free: false,
  },
  {
    id: "so-04",
    topic: "Strategische Optionen",
    type: "mc",
    prompt: "Ein Geschäftsfeld hat einen hohen relativen Marktanteil, aber nur geringes Marktwachstum. Wie wird es in der BCG-Matrix klassifiziert?",
    options: ["Star", "Cash Cow", "Question Mark", "Poor Dog"],
    correctIndex: 1,
    explanation: "Cash Cows liefern bei hohem Marktanteil und geringem Wachstum stabile finanzielle Überschüsse, die andere Geschäftsfelder querfinanzieren können.",
    source: "Kapitel 9.3, Portfolioanalyse: BCG-Matrix und McKinsey-Matrix",
    free: false,
  },
  {
    id: "so-05",
    topic: "Strategische Optionen",
    type: "mc",
    prompt: "Worin unterscheidet sich die McKinsey/GE-Matrix von der klassischen BCG-Matrix?",
    options: [
      "Sie verwendet zusammengesetzte Indizes für Marktattraktivität und Wettbewerbsstärke statt nur zweier einfacher Dimensionen",
      "Sie kennt nur zwei statt vier Felder",
      "Sie berücksichtigt ausschließlich den Umsatz, nicht den Gewinn",
      "Sie wird nur für Startups, nie für Konzerne verwendet",
    ],
    correctIndex: 0,
    explanation: "Die McKinsey/GE-Matrix ersetzt die beiden BCG-Dimensionen durch mehrdimensionale Indizes mit jeweils drei statt zwei Ausprägungen — das erlaubt eine feinere Einordnung.",
    source: "Kapitel 9.3, Portfolioanalyse: BCG-Matrix und McKinsey-Matrix",
    free: false,
  },
  {
    id: "so-06",
    topic: "Strategische Optionen",
    type: "mc",
    prompt: "Wie laufen strategische Planungsprozesse in der Unternehmenspraxis meist ab?",
    options: [
      "Rein top-down, ohne jede Rückkopplung",
      "Rein bottom-up, ohne jede Vorgabe der Führung",
      "Als iteratives Gegenstromverfahren zwischen top-down und bottom-up",
      "Vollständig zufallsgesteuert",
    ],
    correctIndex: 2,
    explanation: "In der Praxis wechseln sich Vorgaben der Führungsebene und Rückmeldungen aus operativen Einheiten iterativ ab.",
    source: "Kapitel 9.4, Strategieplanung und -umsetzung im Unternehmen",
    free: false,
  },

  // ---------- Corporate Governance ----------
  {
    id: "cg-01",
    topic: "Corporate Governance",
    type: "mc",
    prompt: "Welches theoretische Konzept erklärt Interessenkonflikte zwischen Eigentümern und Management?",
    options: ["Agency-Theorie", "Ansoff-Matrix", "Effectuation", "Luce-Modell"],
    correctIndex: 0,
    explanation: "Die Agency-Theorie analysiert Konflikte zwischen einem Prinzipal (Eigentümer) und einem Agenten (Management), deren Interessen nicht vollständig übereinstimmen.",
    source: "Kapitel 10.1, Was ist Corporate Governance?",
    free: false,
  },
  {
    id: "cg-02",
    topic: "Corporate Governance",
    type: "mc",
    prompt: "Welche Art von Entscheidungen trug maßgeblich zum Zusammenbruch von Arcandor (2009) bei?",
    options: [
      "Komplexe Sale-and-lease-back-Immobilienkonstruktionen, die kurzfristig Liquidität, aber langfristig hohe Mietkosten brachten",
      "Ein plötzlicher, unerwarteter Rohstoffpreisschock ohne jedes Managementverschulden",
      "Eine zu geringe Verschuldung des Konzerns",
      "Ein reines Marketingproblem ohne Bezug zur Unternehmensführung",
    ],
    correctIndex: 0,
    explanation: "Arcandor veräußerte Immobilien und mietete sie langfristig teuer zurück — kurzfristig lukrativ, langfristig eine erhebliche Kostenbelastung.",
    source: "Kapitel 10.2, Der Fall Arcandor",
    free: false,
  },
  {
    id: "cg-03",
    topic: "Corporate Governance",
    type: "mc",
    prompt: "In welchem Land ist das monistische System der Unternehmensverfassung (Board of Directors) üblich?",
    options: ["Deutschland", "Österreich", "USA", "Dänemark"],
    correctIndex: 2,
    explanation: "USA und Großbritannien nutzen das monistische System mit einem einzigen Organ (Board of Directors); Deutschland, Österreich und Dänemark das dualistische System.",
    source: "Kapitel 10.3, Dualistisches und monistisches System der Unternehmensverfassung",
    free: false,
  },
  {
    id: "cg-04",
    topic: "Corporate Governance",
    type: "mc",
    prompt: "Welche Aufgaben hat der Aufsichtsrat im dualistischen System typischerweise?",
    options: [
      "Ausschließlich operative Tagesgeschäfte",
      "Kontroll- und Entscheidungsaufgaben sowie Beratung des Vorstands",
      "Nur die Erstellung der Werbekampagnen",
      "Die alleinige Festlegung der Produktpreise",
    ],
    correctIndex: 1,
    explanation: "Der Aufsichtsrat überwacht den Vorstand, entscheidet u. a. über dessen Bestellung/Abberufung und berät ihn.",
    source: "Kapitel 10.3, Dualistisches und monistisches System der Unternehmensverfassung",
    free: false,
  },
  {
    id: "cg-05",
    topic: "Corporate Governance",
    type: "mc",
    prompt: "Welches der folgenden Verhaltensweisen zählt NICHT zu den klassischen Agency-Konflikten zwischen Management und Eigentümern?",
    options: ["Zu geringer Arbeitseinsatz des Managements", "Suboptimale Investitionsentscheidungen", "Eigenhandel zulasten der Eigentümer", "Eine zu hohe Dividendenausschüttung an alle Aktionäre gleichermaßen"],
    correctIndex: 3,
    explanation: "Eine gleichmäßige, satzungsgemäße Dividendenausschüttung ist kein typischer Agency-Konflikt — anders als Trägheit, Fehlinvestitionen oder Selbstbereicherung des Managements.",
    source: "Kapitel 10.1, Was ist Corporate Governance?",
    free: false,
  },

  // ---------- Personalführung ----------
  {
    id: "pf-01",
    topic: "Personalführung",
    type: "mc",
    prompt: "Welche drei Quellen tragen laut Vorlesung zum Kontrollproblem in Arbeitsverhältnissen bei?",
    options: [
      "Exogene Faktoren, Risiko-Anreiz-Trade-off, Selektionsmechanismus",
      "Preiselastizität, Werbebudget, Kundenbindung",
      "SWOT, Five Forces, Wertschöpfungskette",
      "Marktanteil, Marktwachstum, Portfolio",
    ],
    correctIndex: 0,
    explanation: "Das Kontrollproblem entsteht aus exogenen Einflussfaktoren, dem Risiko-Anreiz-Trade-off und einem Selektionsmechanismus unterschiedlicher Vergütungsmodelle.",
    source: "Kapitel 11.1, Das Kontrollproblem in Arbeitsverhältnissen",
    free: false,
  },
  {
    id: "pf-02",
    topic: "Personalführung",
    type: "mc",
    prompt: "Eine Autoglas-Reparaturfirma vergütet Mitarbeitende rein nach Stückzahl reparierter Scheiben — die Sorgfalt bei der Montage sinkt daraufhin. Welches Problem beschreibt dieses Beispiel?",
    options: ["Interdependenzproblem", "Multitasking-Problem", "Bandbreiteneffekt", "Aggregationsbias"],
    correctIndex: 1,
    explanation: "Beim Multitasking-Problem werden nicht gemessene Aufgaben (hier: Sorgfalt) zugunsten der gemessenen Kennzahl (Stückzahl) vernachlässigt.",
    source: "Kapitel 11.2, Multitasking- und Interdependenzprobleme",
    free: false,
  },
  {
    id: "pf-03",
    topic: "Personalführung",
    type: "mc",
    prompt: "Was beschreibt das Interdependenzproblem in Teams?",
    options: [
      "Mitarbeitende vernachlässigen ungemessene Aufgaben zugunsten gemessener Kennzahlen",
      "Einzelne Teammitglieder haben einen Anreiz zum Trittbrettfahren, wenn nur die Teamleistung gemessen wird",
      "Zwei unabhängige Variablen korrelieren zufällig miteinander",
      "Die Löhne zwischen zwei Abteilungen unterscheiden sich zu stark",
    ],
    correctIndex: 1,
    explanation: "Wird nur auf Teamebene gemessen, können sich Einzelne auf die Anstrengung der übrigen Gruppe verlassen.",
    source: "Kapitel 11.2, Multitasking- und Interdependenzprobleme",
    free: false,
  },
  {
    id: "pf-04",
    topic: "Personalführung",
    type: "mc",
    prompt: "Womit erklären Bradler et al. (2016) die Leistungssteigerung durch persönliche Dankeskarten?",
    options: ["Ausschließlich durch höhere Bezahlung", "Konformitätsstreben und Reziprozitätsnormen", "Zufall, es gab keinen signifikanten Effekt", "Eine gesetzliche Verpflichtung zur Anerkennung"],
    correctIndex: 1,
    explanation: "Anerkennung erzeugt bei Beschäftigten das Bedürfnis, sich zu revanchieren (Reziprozität) und sich sozial erwünscht zu verhalten (Konformität).",
    source: "Kapitel 11.3, Anerkennung als Anreiz: die Dankeskarten-Studie",
    free: false,
  },
  {
    id: "pf-05",
    topic: "Personalführung",
    type: "mc",
    prompt: "Wie lässt sich eine Investition in Humankapital (z. B. eine Weiterbildung) ökonomisch bewerten?",
    options: [
      "Sie lohnt sich immer, unabhängig von Kosten und Ertrag",
      "Sie lohnt sich, solange der abgezinste erwartete Mehrertrag die Kosten der Investition übersteigt",
      "Sie ist grundsätzlich nie rentabel",
      "Nur der Staat kann über die Rentabilität von Bildungsinvestitionen entscheiden",
    ],
    correctIndex: 1,
    explanation: "Wie jede Investition wird eine Bildungsinvestition anhand der abgezinsten erwarteten Mehrerträge im Vergleich zu den Kosten bewertet.",
    source: "Kapitel 11.4, Investitionen in Humankapital und der Gender Pay Gap",
    free: false,
  },
  {
    id: "pf-06",
    topic: "Personalführung",
    type: "mc",
    prompt: "Was zählt nach Northouse eher zu 'Management' statt zu 'Leadership'?",
    options: ["Eine Richtung vorgeben und inspirieren", "Planung, Budgetierung und Kontrolle", "Menschen hinter einer Vision vereinen", "Wandel anstoßen"],
    correctIndex: 1,
    explanation: "Management sichert Ordnung und Verlässlichkeit (Planung, Budgetierung, Organisation, Kontrolle, Problemlösung); Leadership befähigt zu Wandel.",
    source: "Kapitel 11.5, Manager oder Leader?",
    free: false,
  },

  // ---------- Kundenverhalten und Daten ----------
  {
    id: "kd-01",
    topic: "Kundenverhalten und Daten",
    type: "numeric",
    prompt: "Sechs Kundinnen eines Blumenladens geben an einem Tag folgende Beträge aus: 12 €, 45 €, 8 €, 60 €, 25 €, 33 €. Wie hoch ist der Median?",
    correctValue: 29,
    tolerance: 0.5,
    unit: "€",
    explanation: "Sortiert: 8, 12, 25, 33, 45, 60. Bei 6 (gerade) Werten ist der Median der Mittelwert der beiden mittleren Werte: (25 + 33) / 2 = 29 €.",
    source: "Kapitel 12.1, Deskriptive Statistik im Marketing",
    free: false,
  },
  {
    id: "kd-02",
    topic: "Kundenverhalten und Daten",
    type: "numeric",
    prompt: "Fünf Kundinnen und Kunden eines Möbelhauses kaufen für 320 €, 150 €, 890 €, 210 € und 430 €. Wie hoch ist das arithmetische Mittel?",
    correctValue: 400,
    tolerance: 1,
    unit: "€",
    explanation: "Summe = 2.000 €, geteilt durch n = 5 ergibt 400 €.",
    source: "Kapitel 12.1, Deskriptive Statistik im Marketing",
    free: false,
  },
  {
    id: "kd-03",
    topic: "Kundenverhalten und Daten",
    type: "mc",
    prompt: "In welchem Wertebereich liegt der Korrelationskoeffizient r?",
    options: ["0 bis 1", "−1 bis +1", "−100 bis +100", "0 bis unendlich"],
    correctIndex: 1,
    explanation: "Der Korrelationskoeffizient liegt stets zwischen −1 (perfekt negativ) und +1 (perfekt positiv linear).",
    source: "Kapitel 12.2, Zusammenhänge messen: Korrelation und Regression",
    free: false,
  },
  {
    id: "kd-04",
    topic: "Kundenverhalten und Daten",
    type: "numeric",
    prompt:
      "Ein Unternehmen erfasst Werbeausgaben x (in Tsd. €) und Absatz y (in Tsd. Stück) über vier Monate: x = 1, 2, 3, 4 und y = 5, 7, 8, 10. Wie hoch ist der Steigungsparameter b der linearen Regressionsgeraden (OLS)?",
    correctValue: 1.6,
    tolerance: 0.05,
    explanation: "b = [n·Σxy − Σx·Σy] / [n·Σx² − (Σx)²] = [4·83 − 10·30] / [4·30 − 100] = 32/20 = 1,6.",
    source: "Kapitel 12.2, Zusammenhänge messen: Korrelation und Regression",
    free: false,
  },
  {
    id: "kd-05",
    topic: "Kundenverhalten und Daten",
    type: "mc",
    prompt: "Was bedeutet ein Bestimmtheitsmaß von r² = 0,10 für eine Regressionsschätzung?",
    options: [
      "90 % der Streuung der abhängigen Variable werden durch die Regressionsgerade erklärt",
      "Nur 10 % der Streuung der abhängigen Variable werden durch die Regressionsgerade erklärt — der lineare Erklärungsgehalt ist gering",
      "Die Regression ist perfekt und fehlerfrei",
      "Es besteht überhaupt kein Zusammenhang zwischen x und y",
    ],
    correctIndex: 1,
    explanation: "r² = 0,10 bedeutet, dass nur ein kleiner Teil der Streuung von y durch das lineare Modell erklärt wird.",
    source: "Kapitel 12.2, Zusammenhänge messen: Korrelation und Regression",
    free: false,
  },
  {
    id: "kd-06",
    topic: "Kundenverhalten und Daten",
    type: "mc",
    prompt: "Ein Getränkehersteller schätzt die Preis-Absatz-Beziehung anhand aggregierter Daten aus Filialen mit sehr unterschiedlichem Preisniveau. Welches Problem droht dabei?",
    options: ["Bandbreiteneffekt", "Aggregationsbias", "Multitasking-Problem", "Kreuzpreiselastizität"],
    correctIndex: 1,
    explanation: "Werden Beobachtungen aus unterschiedlichen Preiskontexten zusammengefasst, kann die geschätzte Beziehung den wahren Zusammenhang innerhalb eines Kontexts verzerren (Aggregationsbias).",
    source: "Kapitel 12.2, Zusammenhänge messen: Korrelation und Regression",
    free: false,
  },
  {
    id: "kd-07",
    topic: "Kundenverhalten und Daten",
    type: "numeric",
    prompt:
      "Drei Produkte haben (bei β = 1) die Nutzenwerte U1 = 4, U2 = 6, U3 = 10. Mit welcher Wahrscheinlichkeit wählt eine Person nach dem Luce-Modell Produkt 2?",
    correctValue: 0.3,
    tolerance: 0.02,
    explanation: "P2 = U2 / (U1+U2+U3) = 6 / 20 = 0,3.",
    source: "Kapitel 12.3, Das Luce-Modell der Produktwahl",
    free: false,
  },

  // ---------- Produktgestaltung und Preispolitik ----------
  {
    id: "pp-01",
    topic: "Produktgestaltung und Preispolitik",
    type: "mc",
    prompt: "Was ermittelt eine Conjoint-Analyse?",
    options: [
      "Den Gesamtnutzen eines Produktprofils aus den Teilnutzen seiner Merkmalsausprägungen",
      "Ausschließlich die Herstellungskosten eines Produkts",
      "Die Kreuzpreiselastizität zweier Produkte",
      "Den Customer Lifetime Value eines Kunden",
    ],
    correctIndex: 0,
    explanation: "Up = ΣΣ TNij · xij — der Gesamtnutzen ergibt sich als Summe der Teilnutzen aller im Profil enthaltenen Merkmalsausprägungen.",
    source: "Kapitel 13.1, Conjoint-Analyse",
    free: false,
  },
  {
    id: "pp-02",
    topic: "Produktgestaltung und Preispolitik",
    type: "numeric",
    prompt: "Für ein Produkt gilt die lineare Preis-Absatz-Funktion x = 500 − 20·p. Wie hoch ist der Absatz x bei einem Preis von 15 €?",
    correctValue: 200,
    tolerance: 1,
    unit: "Stück",
    explanation: "x = 500 − 20 · 15 = 500 − 300 = 200 Stück.",
    source: "Kapitel 13.2, Preis-Absatz-Funktionen",
    free: false,
  },
  {
    id: "pp-03",
    topic: "Produktgestaltung und Preispolitik",
    type: "mc",
    prompt: "Welchen Nachteil hat die lineare Preis-Absatz-Funktion gegenüber der multiplikativen?",
    options: [
      "Sie kann für sehr hohe Preise rechnerisch negative Absatzmengen vorhersagen",
      "Sie lässt sich niemals statistisch schätzen",
      "Sie unterstellt eine unendlich hohe Preiselastizität",
      "Sie kann nur für Dienstleistungen verwendet werden",
    ],
    correctIndex: 0,
    explanation: "Die lineare PAF sinkt gleichmäßig und wird ab einem bestimmten Preis rechnerisch negativ — realitätsfern im Vergleich zur asymptotisch gegen null laufenden multiplikativen PAF.",
    source: "Kapitel 13.2, Preis-Absatz-Funktionen",
    free: false,
  },
  {
    id: "pp-04",
    topic: "Produktgestaltung und Preispolitik",
    type: "numeric",
    prompt: "Bei einem Preis von 15 € beträgt der Absatz eines Produkts 200 Stück; dx/dp beträgt an dieser Stelle −20. Wie hoch ist die Punktelastizität ε an dieser Stelle?",
    correctValue: -1.5,
    tolerance: 0.05,
    explanation: "ε = (dx/dp) · (p/x) = −20 · (15/200) = −1,5.",
    source: "Kapitel 13.3, Preiselastizität und Kreuzpreiselastizität",
    free: false,
  },
  {
    id: "pp-05",
    topic: "Produktgestaltung und Preispolitik",
    type: "mc",
    prompt: "Steigt der Preis von Produkt B, und steigt daraufhin auch der Absatz von Produkt A — welches Vorzeichen hat dann die Kreuzpreiselastizität εAB, und was bedeutet das?",
    options: [
      "Positiv — A und B sind Substitutionsgüter",
      "Negativ — A und B sind Substitutionsgüter",
      "Positiv — A und B sind Komplementärgüter",
      "Negativ — A und B sind Komplementärgüter",
    ],
    correctIndex: 0,
    explanation: "Ein positiver Wert der Kreuzpreiselastizität deutet auf Substitutionsgüter hin: Wird B teurer, weichen Kundinnen und Kunden auf A aus.",
    source: "Kapitel 13.3, Preiselastizität und Kreuzpreiselastizität",
    free: false,
  },
  {
    id: "pp-06",
    topic: "Produktgestaltung und Preispolitik",
    type: "numeric",
    prompt:
      "Ein Hersteller von Trinkflaschen hat die lineare PAF x = 6.000 − 30·p ermittelt; die variablen Stückkosten betragen 8 €. Wie hoch ist der gewinnoptimale Cournot-Preis?",
    correctValue: 104,
    tolerance: 1,
    unit: "€",
    explanation: "p* = ½ · (a/b + k) = ½ · (6.000/30 + 8) = ½ · (200 + 8) = 104 €.",
    source: "Kapitel 13.4, Gewinnoptimale Preise: Amoroso-Robinson und Cournot",
    free: false,
  },
  {
    id: "pp-07",
    topic: "Produktgestaltung und Preispolitik",
    type: "mc",
    prompt: "Was besagt die Amoroso-Robinson-Relation?",
    options: [
      "Je unelastischer die Nachfrage, desto größer der optimale Preisaufschlag über die Grenzkosten",
      "Je elastischer die Nachfrage, desto größer der optimale Preisaufschlag über die Grenzkosten",
      "Preis und Grenzkosten müssen immer identisch sein",
      "Die Preiselastizität hat keinen Einfluss auf den optimalen Preis",
    ],
    correctIndex: 0,
    explanation: "p* = ε(p*)/(1+ε(p*)) · K′ — bei geringer Preissensibilität (kleinem |ε|) lohnt sich ein größerer Aufschlag über die Grenzkosten.",
    source: "Kapitel 13.4, Gewinnoptimale Preise: Amoroso-Robinson und Cournot",
    free: false,
  },

  // ---------- Kommunikationspolitik ----------
  {
    id: "kp-01",
    topic: "Kommunikationspolitik",
    type: "mc",
    prompt: "Welche Werbe-Response-Funktion hat im Unterschied zur Wurzel- oder Logarithmusfunktion eine feste Sättigungsmenge?",
    options: ["Die lineare PAF", "Die S-förmige Werbe-Response-Funktion", "Die multiplikative PAF", "Der Cournot-Preis"],
    correctIndex: 1,
    explanation: "Die S-förmige Funktion x(W) = xs/(1+e^(a−bW)) nähert sich einer festen Sättigungsmenge xs an; degressive Verläufe (Wurzel, Logarithmus) kennen keine feste Obergrenze.",
    source: "Kapitel 14.1, Werbe-Response-Funktionen",
    free: false,
  },
  {
    id: "kp-02",
    topic: "Kommunikationspolitik",
    type: "numeric",
    prompt:
      "Bei einem Werbebudget von 10.000 € verkauft ein Unternehmen 2.000 Einheiten; die geschätzte marginale Absatzänderung dx/dW beträgt 0,15 Einheiten je Euro. Wie hoch ist die Werbeelastizität α an dieser Stelle?",
    correctValue: 0.75,
    tolerance: 0.02,
    explanation: "α = (dx/dW) · (W/x) = 0,15 · (10.000/2.000) = 0,15 · 5 = 0,75.",
    source: "Kapitel 14.2, Werbeelastizität und das optimale Werbebudget",
    free: false,
  },
  {
    id: "kp-03",
    topic: "Kommunikationspolitik",
    type: "numeric",
    prompt:
      "Ein Sportartikelhersteller verkauft 8.000 Einheiten eines Produkts zu 45 € bei variablen Stückkosten von 25 €; die geschätzte Werbeelastizität beträgt 0,06. Wie hoch ist das optimale Werbebudget W*?",
    correctValue: 9600,
    tolerance: 100,
    unit: "€",
    explanation: "W* = α · (p − kvar) · x = 0,06 · (45 − 25) · 8.000 = 0,06 · 20 · 8.000 = 9.600 €.",
    source: "Kapitel 14.2, Werbeelastizität und das optimale Werbebudget",
    free: false,
  },
  {
    id: "kp-04",
    topic: "Kommunikationspolitik",
    type: "numeric",
    prompt: "Eine Werbebelegung kostet 1.200 € und erreicht 150.000 Nutzerinnen und Nutzer. Wie hoch ist der Tausenderkontaktpreis (TKP)?",
    correctValue: 8,
    tolerance: 0.2,
    unit: "€",
    explanation: "TKP = (c/K) · 1.000 = (1.200 / 150.000) · 1.000 = 8 €.",
    source: "Kapitel 14.3, Der Tausenderkontaktpreis",
    free: false,
  },
  {
    id: "kp-05",
    topic: "Kommunikationspolitik",
    type: "mc",
    prompt: "Wofür wird der Tausenderkontaktpreis (TKP) typischerweise verwendet?",
    options: [
      "Zum Vergleich der Kosteneffizienz verschiedener Werbeträger",
      "Zur Berechnung des Customer Lifetime Value",
      "Zur Schätzung der Preiselastizität eines Produkts",
      "Zur Bestimmung des relativen Marktanteils in der BCG-Matrix",
    ],
    correctIndex: 0,
    explanation: "Der TKP gibt an, wie teuer es ist, 1.000 Personen über ein bestimmtes Medium zu erreichen, und erlaubt so den Vergleich verschiedener Werbeträger.",
    source: "Kapitel 14.3, Der Tausenderkontaktpreis",
    free: false,
  },

  // ---------- Erfolgsmessung: CLV ----------
  {
    id: "cl-01",
    topic: "Erfolgsmessung: CLV",
    type: "numeric",
    prompt:
      "Eine Kundenbeziehung erzielt folgende Nettobeiträge (Umsatz minus Investition): 100 € in t=0, 150 € in t=1, 180 € in t=2. Bei einem Diskontsatz von 10 % — wie hoch ist der CLV (gerundet auf zwei Nachkommastellen)?",
    correctValue: 385.12,
    tolerance: 1,
    unit: "€",
    explanation: "CLV = 100 + 150/1,1 + 180/1,1² = 100 + 136,36 + 148,76 ≈ 385,12 €.",
    source: "Kapitel 15.1, Der Customer Lifetime Value",
    free: false,
  },
  {
    id: "cl-02",
    topic: "Erfolgsmessung: CLV",
    type: "numeric",
    prompt:
      "Ein Yogastudio gewinnt eine Kundin über eine Empfehlungskarte für 10 € Akquisitionskosten. Sie bringt einen jährlichen Nettobeitrag von 60 €, die Bindungsrate liegt bei 80 %, der Diskontsatz bei 8 %. Wie hoch ist der CLV für n → ∞ (gerundet auf zwei Nachkommastellen)?",
    correctValue: 221.43,
    tolerance: 2,
    unit: "€",
    explanation: "CLV = (e−a) · (1+i)/(1+i−r) − AC = 60 · 1,08/0,28 − 10 = 60 · 3,857 − 10 ≈ 231,43 − 10 = 221,43 €.",
    source: "Kapitel 15.2, CLV anhand der Wiederkaufrate",
    free: false,
  },
  {
    id: "cl-03",
    topic: "Erfolgsmessung: CLV",
    type: "mc",
    prompt: "Was ist die Customer Equity eines Unternehmens?",
    options: [
      "Die Summe der Customer Lifetime Values aller (aktuellen und potenziellen) Kunden",
      "Der Marktwert des Anlagevermögens eines Unternehmens",
      "Die Summe aller Werbeausgaben eines Jahres",
      "Der Tausenderkontaktpreis über alle Medien hinweg",
    ],
    correctIndex: 0,
    explanation: "CE = Σj CLVj — die Customer Equity aggregiert den CLV über den gesamten (aktuellen und potenziellen) Kundenstamm.",
    source: "Kapitel 15.3, Customer Equity",
    free: false,
  },
  {
    id: "cl-04",
    topic: "Erfolgsmessung: CLV",
    type: "numeric",
    prompt:
      "Für dasselbe Yogastudio (jährlicher Nettobeitrag 60 €, Bindungsrate 80 %, Diskontsatz 8 %) — wie hoch dürften die Akquisitionskosten maximal sein, damit der CLV gerade noch positiv (also 0 €) bleibt?",
    correctValue: 231.43,
    tolerance: 2,
    unit: "€",
    explanation: "Der Perpetuitätswert ohne Akquisitionskosten beträgt 60 · 1,08/0,28 ≈ 231,43 € — bis zu diesem Betrag darf AC maximal steigen, ohne dass der CLV negativ wird.",
    source: "Kapitel 15.2, CLV anhand der Wiederkaufrate",
    free: false,
  },
  {
    id: "cl-05",
    topic: "Erfolgsmessung: CLV",
    type: "mc",
    prompt: "Welche Handlungsimplikation folgt unmittelbar aus dem CLV-Konzept für das Marketingbudget?",
    options: [
      "Kundenakquise sollte grundsätzlich vermieden werden",
      "In Kundengewinnung und -bindung lohnt es sich zu investieren, solange die Investition den CLV stärker erhöht, als sie kostet",
      "Der CLV ist für operative Entscheidungen irrelevant",
      "Nur einmalige Käufe zählen für den Unternehmenswert, keine wiederkehrenden",
    ],
    correctIndex: 1,
    explanation: "Der CLV liefert die ökonomische Obergrenze dafür, wie viel eine zusätzliche Investition in Akquise oder Bindung maximal kosten darf.",
    source: "Kapitel 15.3, Customer Equity",
    free: false,
  },
];
