import type { Question } from "@/lib/questions";

// Themen entsprechen (in Kurzform) den Kapiteltiteln aus lib/content/ing-1.ts.
// Alle Übungsaufgaben, die inhaltlich auf reale Übungsblätter zurückgehen,
// wurden gemäß den Projektregeln (CLAUDE.md) sowohl in den Zahlen als auch
// im Szenario verändert — es taucht nie derselbe Zahlensatz UND dasselbe
// Szenario wie im Original gleichzeitig auf. Mehrere Original-Aufgaben
// (insbesondere zu Spannungs-Dehnungs- und Phasendiagrammen) hingen stark
// von Zeichnungen ab, die sich nicht direkt in eine textbasierte Fragenbank
// übertragen lassen; dafür wurden eigenständige, aber thematisch
// gleichwertige Rechenaufgaben mit rein textuell gegebenen Werten entworfen.
export const TOPICS = [
  "Werkstoffgruppen und Bindungsarten",
  "Atomarer Aufbau und Periodensystem",
  "Elastisches Verhalten",
  "Kristallgitter und Packungsdichte",
  "Röntgenographische Strukturanalyse",
  "Legierungsstrukturen und Mischkristalle",
  "Ionen-, kovalente und Polymerstrukturen",
  "Kristallbaufehler",
  "Plastische Verformung und Bruch",
  "Elektrische und thermische Eigenschaften",
  "Thermodynamik von Phasenübergängen",
  "Zustandsdiagramme",
  "Das Eisen-Kohlenstoff-System",
] as const;

export const questions: Question[] = [
  // ---------- Werkstoffgruppen und Bindungsarten (frei zugänglich) ----------
  {
    id: "wb-01",
    topic: "Werkstoffgruppen und Bindungsarten",
    type: "mc",
    prompt: "Welche Werkstoffgruppe ist typischerweise ein elektrischer Isolator mit geringer Dichte und guter Verformbarkeit, aber vergleichsweise geringer Festigkeit?",
    options: ["Metalle", "Polymere", "Keramik/Glas", "Halbleiter"],
    correctIndex: 1,
    explanation: "Polymere sind meist elektrische Isolatoren mit geringer Dichte und guter Verformbarkeit, aber geringerer Festigkeit und Steifigkeit als Metalle oder Keramiken.",
    source: "Kapitel 1.1, Die vier Werkstoffgruppen",
    free: true,
  },
  {
    id: "wb-02",
    topic: "Werkstoffgruppen und Bindungsarten",
    type: "mc",
    prompt: "Warum lassen sich Metalle plastisch verformen, ohne dass die Bindung dabei zerstört wird?",
    options: [
      "Weil die Ionenbindung besonders elastisch ist",
      "Weil die frei bewegliche Elektronenwolke Verschiebungen der Atomrümpfe 'mitmacht'",
      "Weil Metalle keine Kristallstruktur besitzen",
      "Weil Metalle keine Valenzelektronen abgeben",
    ],
    correctIndex: 1,
    explanation: "Bei der Metallbindung bleibt die Bindung bei Verschiebung der Atomebenen erhalten, weil die delokalisierte Elektronenwolke die Verschiebung mitmacht — anders als bei der Ionenbindung, bei der Verschiebung zur Abstoßung gleichnamiger Ladungen führt.",
    source: "Kapitel 1.3, Kovalente Bindung und Metallbindung",
    free: true,
  },
  {
    id: "wb-03",
    topic: "Werkstoffgruppen und Bindungsarten",
    type: "numeric",
    prompt: "In Kaliumbromid (KBr) beträgt der Ionenradius rK+ = 0,138 nm und rBr− = 0,196 nm. Wie groß ist die Coulombsche Anziehungskraft zwischen einem K+- und einem Br−-Ion? (e = 1,602·10⁻¹⁹ C, 1/(4πε0) = 8,99·10⁹ N·m²/C²)",
    correctValue: 2.07,
    tolerance: 0.15,
    unit: "nN",
    explanation: "r = 0,138+0,196 = 0,334 nm. FC = 8,99·10⁹ · (1,602·10⁻¹⁹)² / (0,334·10⁻⁹)² ≈ 8,99·10⁹ · 2,566·10⁻³⁸ / 1,116·10⁻¹⁹ ≈ 2,07·10⁻⁹ N = 2,07 nN.",
    source: "Kapitel 1.2, Ionenbindung und Coulombkraft",
    free: true,
  },

  // ---------- Atomarer Aufbau und Periodensystem ----------
  {
    id: "aa-01",
    topic: "Atomarer Aufbau und Periodensystem",
    type: "numeric",
    prompt: "Ein Uran-Atom besitzt die Ordnungszahl Z=92 und die Massenzahl M=238. Wie viele Neutronen enthält der Atomkern?",
    correctValue: 146,
    tolerance: 0,
    unit: "",
    explanation: "N = M − Z = 238 − 92 = 146.",
    source: "Kapitel 2.1, Atomkern, Massenzahl und Isotope",
    free: false,
  },
  {
    id: "aa-02",
    topic: "Atomarer Aufbau und Periodensystem",
    type: "mc",
    prompt: "Was besagt das Pauli-Prinzip?",
    options: [
      "Alle Elektronen eines Atoms besitzen dieselbe Energie",
      "Zwei Elektronen eines Atoms dürfen niemals in allen vier Quantenzahlen übereinstimmen",
      "Ein Atom kann maximal 8 Elektronen besitzen",
      "Elektronen bewegen sich auf festen Kreisbahnen um den Kern",
    ],
    correctIndex: 1,
    explanation: "Das Pauli-Prinzip besagt, dass niemals zwei Elektronen eines Atoms in allen vier Quantenzahlen (n, l, ml, ms) übereinstimmen dürfen — jedes Elektron besetzt ein eindeutiges Energieniveau.",
    source: "Kapitel 2.2, Quantenzahlen und Elektronenkonfiguration",
    free: false,
  },
  {
    id: "aa-03",
    topic: "Atomarer Aufbau und Periodensystem",
    type: "numeric",
    prompt: "Wie viele Elektronen kann eine Schale mit Hauptquantenzahl n=4 nach dem Pauli-Prinzip maximal aufnehmen?",
    correctValue: 32,
    tolerance: 0,
    unit: "",
    explanation: "Nmax(n) = 2n² = 2·4² = 2·16 = 32.",
    source: "Kapitel 2.2, Quantenzahlen und Elektronenkonfiguration",
    free: false,
  },
  {
    id: "aa-04",
    topic: "Atomarer Aufbau und Periodensystem",
    type: "mc",
    prompt: "Warum folgen bei den Übergangsmetallen (Nebengruppenelementen) auf das Element Calcium nicht direkt die Elemente der 5. Periode, sondern zunächst 10 weitere Elemente?",
    options: [
      "Weil bei diesen Elementen zunächst das energetisch tiefer liegende 3d-Niveau aufgefüllt wird, nachdem das 4s-Niveau bereits besetzt ist",
      "Weil diese Elemente radioaktiv sind",
      "Weil das Periodensystem an dieser Stelle eine Lücke besitzt",
      "Weil diese Elemente keine Elektronenhülle besitzen",
    ],
    correctIndex: 0,
    explanation: "Nach Calcium wird zunächst das energetisch etwas tiefer liegende 3d-Niveau mit maximal 10 Elektronen aufgefüllt, bevor mit der 5. Periode fortgefahren wird — das ergibt die Nebengruppenelemente Scandium bis Zink.",
    source: "Kapitel 2.3, Aufbau des Periodensystems",
    free: false,
  },

  // ---------- Elastisches Verhalten ----------
  {
    id: "el-01",
    topic: "Elastisches Verhalten",
    type: "numeric",
    prompt: "Ein Bauteil mit Querschnittsfläche A = 40 mm² wird mit einer Kraft F = 8000 N belastet. Wie groß ist die Normalspannung σ?",
    correctValue: 200,
    tolerance: 2,
    unit: "N/mm²",
    explanation: "σ = F/A = 8000 N / 40 mm² = 200 N/mm².",
    source: "Kapitel 3.1, Normalspannung und Dehnung",
    free: false,
  },
  {
    id: "el-02",
    topic: "Elastisches Verhalten",
    type: "numeric",
    prompt: "Ein Titanstab (E = 110 000 N/mm²) mit Querschnittsfläche A = 30 mm² und Ausgangslänge l0 = 600 mm wird mit F = 6000 N belastet. Um wie viel mm verlängert er sich?",
    correctValue: 1.09,
    tolerance: 0.05,
    unit: "mm",
    explanation: "σ = F/A = 6000/30 = 200 N/mm². ε = σ/E = 200/110 000 ≈ 0,001818. Δl = ε·l0 ≈ 0,001818·600 ≈ 1,09 mm.",
    source: "Kapitel 3.3, Hookesches Gesetz und Elastizitätsmodul",
    free: false,
  },
  {
    id: "el-03",
    topic: "Elastisches Verhalten",
    type: "mc",
    prompt: "Wie hängen Elastizitätsmodul E, Schubmodul G und Querkontraktionszahl ν bei isotropen Werkstoffen zusammen?",
    options: ["ν = E·G − 1", "ν = E/(2G) − 1", "ν = 2G/E", "ν = E + G"],
    correctIndex: 1,
    explanation: "Bei isotropen Werkstoffen gilt die feste Beziehung ν = E/(2G) − 1 zwischen den drei elastischen Konstanten.",
    source: "Kapitel 3.3, Hookesches Gesetz und Elastizitätsmodul",
    free: false,
  },
  {
    id: "el-04",
    topic: "Elastisches Verhalten",
    type: "numeric",
    prompt: "Ein Bauteil mit Querkontraktionszahl ν = 0,30 wird auf eine Längsdehnung von ε = 0,5% gedehnt. Wie groß ist die Querkontraktion εq (mit Vorzeichen, in %)?",
    correctValue: -0.15,
    tolerance: 0.02,
    unit: "%",
    explanation: "εq = −ν·ε = −0,30·0,5% = −0,15%.",
    source: "Kapitel 3.2, Schubspannung und Querkontraktion",
    free: false,
  },

  // ---------- Kristallgitter und Packungsdichte ----------
  {
    id: "kg-01",
    topic: "Kristallgitter und Packungsdichte",
    type: "numeric",
    prompt: "Wie viele Atome pro Elementarzelle besitzt das kubisch flächenzentrierte Gitter (kfz)?",
    correctValue: 4,
    tolerance: 0,
    unit: "",
    explanation: "8 Eckatome zu je 1/8 (= 1 Atom) plus 6 Flächenatome zu je 1/2 (= 3 Atome) ergeben 4 Atome pro Elementarzelle.",
    source: "Kapitel 4.2, Kubisch primitives, raumzentriertes und flächenzentriertes Gitter",
    free: false,
  },
  {
    id: "kg-02",
    topic: "Kristallgitter und Packungsdichte",
    type: "numeric",
    prompt: "Wie hoch ist die Packungsdichte des kubisch raumzentrierten Gitters (krz), gerundet in Prozent?",
    correctValue: 68,
    tolerance: 1,
    unit: "%",
    explanation: "Beim krz-Gitter (2 Atome/EZ, a=4r/√3) ergibt sich eine Packungsdichte von rund 68%.",
    source: "Kapitel 4.2, Kubisch primitives, raumzentriertes und flächenzentriertes Gitter",
    free: false,
  },
  {
    id: "kg-03",
    topic: "Kristallgitter und Packungsdichte",
    type: "numeric",
    prompt: "Chrom kristallisiert kubisch raumzentriert mit einem Atomradius von r = 0,125 nm. Wie groß ist die Gitterkonstante a0?",
    correctValue: 0.289,
    tolerance: 0.003,
    unit: "nm",
    explanation: "Beim krz-Gitter gilt a0 = 4r/√3 = 4·0,125/1,732 ≈ 0,289 nm.",
    source: "Kapitel 4.2, Kubisch primitives, raumzentriertes und flächenzentriertes Gitter",
    free: false,
  },
  {
    id: "kg-04",
    topic: "Kristallgitter und Packungsdichte",
    type: "numeric",
    prompt: "Wie groß ist die Koordinationszahl (KOZ) im kubisch flächenzentrierten Gitter?",
    correctValue: 12,
    tolerance: 0,
    unit: "",
    explanation: "Sowohl das kfz- als auch das hdP-Gitter besitzen als dichteste Packungen die maximale Koordinationszahl KOZ=12.",
    source: "Kapitel 4.3, Hexagonal dichteste Packung und Koordinationszahl",
    free: false,
  },

  // ---------- Röntgenographische Strukturanalyse ----------
  {
    id: "rg-01",
    topic: "Röntgenographische Strukturanalyse",
    type: "numeric",
    prompt: "Ein Kristall zeigt bei Bestrahlung mit Röntgenstrahlung der Wellenlänge λ = 1,54 Å einen Reflex 1. Ordnung (n=1) bei einem Einfallswinkel θ = 15°. Wie groß ist der zugehörige Netzebenenabstand d?",
    correctValue: 2.98,
    tolerance: 0.05,
    unit: "Å",
    explanation: "Aus der Bragg'schen Gleichung 2d·sinθ=nλ folgt d = λ/(2·sinθ) = 1,54/(2·sin15°) = 1,54/0,5176 ≈ 2,98 Å.",
    source: "Kapitel 5.2, Bragg'sche Gleichung und Netzebenenabstand",
    free: false,
  },
  {
    id: "rg-02",
    topic: "Röntgenographische Strukturanalyse",
    type: "mc",
    prompt: "Eine Netzebene verläuft parallel zur c-Achse. Welchen Wert hat der zugehörige dritte Millersche Index l?",
    options: ["l = 0", "l = 1", "l = ∞", "l ist nicht definiert"],
    correctIndex: 0,
    explanation: "Verläuft eine Ebene parallel zu einer Achse, liegt der Schnittpunkt im Unendlichen; der Kehrwert 1/∞ ergibt den Miller-Index 0.",
    source: "Kapitel 5.1, Gitterrichtungen und Millersche Indizes",
    free: false,
  },
  {
    id: "rg-03",
    topic: "Röntgenographische Strukturanalyse",
    type: "numeric",
    prompt: "Ein kubischer Kristall besitzt einen Netzebenenabstand von d=2,0 Å für die (110)-Ebene. Wie groß ist die Gitterkonstante a0?",
    correctValue: 2.83,
    tolerance: 0.03,
    unit: "Å",
    explanation: "Für kubische Systeme gilt a0 = d·√(h²+k²+l²). Für (110) ist h²+k²+l²=1+1+0=2, also a0 = 2,0·√2 ≈ 2,83 Å.",
    source: "Kapitel 5.2, Bragg'sche Gleichung und Netzebenenabstand",
    free: false,
  },

  // ---------- Legierungsstrukturen und Mischkristalle ----------
  {
    id: "lg-01",
    topic: "Legierungsstrukturen und Mischkristalle",
    type: "mc",
    prompt: "Welche Bedingung ist KEINE Voraussetzung für eine lückenlose Substitutionsmischkristallreihe zweier Elemente?",
    options: [
      "Beide Elemente kristallisieren im gleichen Strukturtyp",
      "Die Atomradien unterscheiden sich um weniger als etwa 15%",
      "Die Elemente besitzen eine geringe chemische Affinität zueinander",
      "Beide Elemente besitzen dieselbe Massenzahl",
    ],
    correctIndex: 3,
    explanation: "Die Massenzahl der Elemente spielt für die Mischkristallbildung keine Rolle — entscheidend sind gleicher Strukturtyp, ähnliche Atomradien (<~15% Unterschied) und geringe chemische Affinität.",
    source: "Kapitel 6.1, Substitutions- und Einlagerungsmischkristalle",
    free: false,
  },
  {
    id: "lg-02",
    topic: "Legierungsstrukturen und Mischkristalle",
    type: "numeric",
    prompt: "Silizium (a0=5,431 Å) und Germanium (a0=5,658 Å) bilden eine Mischkristallreihe. Wie groß ist die Gitterkonstante eines Mischkristalls mit 30 Atomprozent Germanium nach der Vegard'schen Regel?",
    correctValue: 5.5,
    tolerance: 0.02,
    unit: "Å",
    explanation: "a0,MK = a0,Si·(1−0,3) + a0,Ge·0,3 = 5,431·0,7 + 5,658·0,3 ≈ 3,802 + 1,697 ≈ 5,50 Å.",
    source: "Kapitel 6.2, Die Vegard'sche Regel",
    free: false,
  },
  {
    id: "lg-03",
    topic: "Legierungsstrukturen und Mischkristalle",
    type: "mc",
    prompt: "Welche Bedingung begünstigt die Bildung eines Einlagerungsmischkristalls?",
    options: [
      "Das Radienverhältnis von Fremd- zu Wirtsatom ist deutlich größer als 1",
      "Das Radienverhältnis von Fremd- zu Wirtsatom liegt unter etwa 0,59",
      "Beide Atomsorten besitzen exakt denselben Radius",
      "Das Wirtsgitter besitzt keine Gitterlücken",
    ],
    correctIndex: 1,
    explanation: "Nur wenn das Fremdatom hinreichend klein im Vergleich zum Wirtsatom ist (Radienverhältnis unter etwa 0,59), passt es überhaupt in die Gitterlücken des Wirtsgitters.",
    source: "Kapitel 6.1, Substitutions- und Einlagerungsmischkristalle",
    free: false,
  },

  // ---------- Ionen-, kovalente und Polymerstrukturen ----------
  {
    id: "ik-01",
    topic: "Ionen-, kovalente und Polymerstrukturen",
    type: "mc",
    prompt: "Was unterscheidet die CsCl-Struktur von der NaCl-Struktur?",
    options: [
      "Die CsCl-Struktur besitzt KOZ=8, die NaCl-Struktur KOZ=6",
      "Die CsCl-Struktur ist kovalent, die NaCl-Struktur ionisch gebunden",
      "Die NaCl-Struktur kommt nur bei Polymeren vor",
      "Es gibt keinen Unterschied, beide Bezeichnungen meinen dieselbe Struktur",
    ],
    correctIndex: 0,
    explanation: "Die CsCl-Struktur besteht aus zwei verschobenen kubisch primitiven Gittern mit KOZ=8, während bei der NaCl-Struktur die Kationen die Oktaederlücken eines kfz-Anionengitters besetzen (KOZ=6).",
    source: "Kapitel 7.1, Ionenstrukturen: CsCl, NaCl, Fluorit und Perowskit",
    free: false,
  },
  {
    id: "ik-02",
    topic: "Ionen-, kovalente und Polymerstrukturen",
    type: "mc",
    prompt: "Warum ist Graphit im Gegensatz zu Diamant elektrisch leitfähig (innerhalb der Basalebenen)?",
    options: [
      "Weil Graphit ionisch gebunden ist",
      "Weil bei der sp²-Hybridisierung ein Elektron pro Kohlenstoffatom frei beweglich bleibt",
      "Weil Graphit kein Kristallgitter besitzt",
      "Weil Diamant metallisch gebunden ist",
    ],
    correctIndex: 1,
    explanation: "Bei der sp²-Hybridisierung des Graphits bildet jedes C-Atom nur 3 Bindungen aus; das vierte Elektron bleibt frei beweglich und ermöglicht elektrische Leitfähigkeit innerhalb der Ebenen.",
    source: "Kapitel 7.2, Kovalente Strukturen: Diamant und Graphit",
    free: false,
  },
  {
    id: "ik-03",
    topic: "Ionen-, kovalente und Polymerstrukturen",
    type: "mc",
    prompt: "Welche Polymerklasse ist stark vernetzt, dadurch hart und spröde, und nicht mehr schmelzbar?",
    options: ["Thermoplast", "Elastomer", "Duromer", "Halbleiterpolymer"],
    correctIndex: 2,
    explanation: "Duromere sind stark vernetzt, hart, spröde und nicht schmelzbar — im Gegensatz zu Thermoplasten (unvernetzt, schmelzbar) und Elastomeren (schwach vernetzt, dehnbar).",
    source: "Kapitel 7.3, Aufbau und Klassifikation von Hochpolymeren",
    free: false,
  },

  // ---------- Kristallbaufehler ----------
  {
    id: "kb-01",
    topic: "Kristallbaufehler",
    type: "mc",
    prompt: "Was unterscheidet einen Schottky-Defekt von einem Frenkel-Defekt in einem Ionenkristall?",
    options: [
      "Beim Schottky-Defekt entstehen eine Kationen- und eine Anionenleerstelle, beim Frenkel-Defekt wandert ein Ion auf einen Zwischengitterplatz",
      "Der Schottky-Defekt tritt nur bei Metallen auf",
      "Beide Defekte sind identisch",
      "Der Frenkel-Defekt betrifft ausschließlich Anionen",
    ],
    correctIndex: 0,
    explanation: "Beim Schottky-Defekt entstehen gepaart eine Kationen- und eine Anionenleerstelle; beim Frenkel-Defekt wandert ein Ion (meist das Kation) auf einen Zwischengitterplatz und hinterlässt dort eine Leerstelle.",
    source: "Kapitel 8.1, Punktdefekte",
    free: false,
  },
  {
    id: "kb-02",
    topic: "Kristallbaufehler",
    type: "mc",
    prompt: "Wie stehen Burgersvektor und Versetzungslinie bei einer reinen Stufenversetzung zueinander?",
    options: ["Parallel", "Senkrecht", "Im 45°-Winkel", "Sie sind identisch"],
    correctIndex: 1,
    explanation: "Bei der Stufenversetzung stehen Burgersvektor und Versetzungslinie senkrecht aufeinander; bei der Schraubenversetzung liegen sie parallel.",
    source: "Kapitel 8.2, Versetzungen und der Burgersvektor",
    free: false,
  },
  {
    id: "kb-03",
    topic: "Kristallbaufehler",
    type: "mc",
    prompt: "Welches Gleitsystem besitzt ein kubisch flächenzentriertes Metall?",
    options: ["{100}<100>", "{111}<110>", "{110}<111>", "{100}<010>"],
    correctIndex: 1,
    explanation: "Beim kfz-Gitter ist die (111)-Ebene die dichtest gepackte Ebene und [110] die dichtest gepackte Richtung — zusammen ergibt sich das Gleitsystem {111}<110>.",
    source: "Kapitel 8.2, Versetzungen und der Burgersvektor",
    free: false,
  },

  // ---------- Plastische Verformung und Bruch ----------
  {
    id: "pv-01",
    topic: "Plastische Verformung und Bruch",
    type: "mc",
    prompt: "Wie ist die Ersatzstreckgrenze R0,2 definiert?",
    options: [
      "Als die Spannung beim Bruch der Probe",
      "Als die Spannung, bei der eine bleibende Dehnung von 0,2% auftritt",
      "Als 20% der Zugfestigkeit Rm",
      "Als die Spannung im Ursprung des Diagramms",
    ],
    correctIndex: 1,
    explanation: "R0,2 ist die Spannung, bei der eine bleibende (plastische) Dehnung von genau 0,2% zurückbleibt — verwendet bei Werkstoffen ohne scharf erkennbare Streckgrenze.",
    source: "Kapitel 9.1, Streckgrenze, Zugfestigkeit und Bruchdehnung",
    free: false,
  },
  {
    id: "pv-02",
    topic: "Plastische Verformung und Bruch",
    type: "numeric",
    prompt: "Ein Stahl besitzt eine Streckgrenze von Re=420 MPa. Bei welcher Kraft beginnt ein Zugstab mit Durchmesser d=12 mm plastisch zu verformen?",
    correctValue: 47.5,
    tolerance: 1,
    unit: "kN",
    explanation: "A = π·(d/2)² = π·6² ≈ 113,1 mm². F = Re·A = 420·113,1 ≈ 47 502 N ≈ 47,5 kN.",
    source: "Kapitel 9.1, Streckgrenze, Zugfestigkeit und Bruchdehnung",
    free: false,
  },
  {
    id: "pv-03",
    topic: "Plastische Verformung und Bruch",
    type: "mc",
    prompt: "Was passiert beim Orowan-Mechanismus, wenn eine Versetzung auf ein inkohärentes Teilchen trifft?",
    options: [
      "Die Versetzung schneidet das Teilchen glatt durch",
      "Die Versetzung umgeht das Teilchen und hinterlässt einen Versetzungsring um es herum",
      "Das Teilchen löst sich vollständig auf",
      "Die Versetzung bleibt dauerhaft am Teilchen hängen",
    ],
    correctIndex: 1,
    explanation: "Beim Orowan-Mechanismus umgeht die Versetzung ein inkohärentes Teilchen und hinterlässt dabei einen Versetzungsring um das Teilchen, während sie selbst weiterläuft.",
    source: "Kapitel 9.2, Verfestigungsmechanismen",
    free: false,
  },
  {
    id: "pv-04",
    topic: "Plastische Verformung und Bruch",
    type: "mc",
    prompt: "Welcher Bruchtyp verläuft entlang der Korngrenzen statt durch die Körner hindurch?",
    options: ["Transkristalliner Bruch", "Interkristalliner Bruch", "Zähbruch", "Ermüdungsbruch"],
    correctIndex: 1,
    explanation: "Beim interkristallinen Bruch folgt der Riss den (energetisch günstigeren) Korngrenzen; beim transkristallinen Bruch läuft er dagegen nahezu geradlinig durch die Körner.",
    source: "Kapitel 9.3, Sprödbruch und Zähbruch",
    free: false,
  },

  // ---------- Elektrische und thermische Eigenschaften ----------
  {
    id: "et-01",
    topic: "Elektrische und thermische Eigenschaften",
    type: "numeric",
    prompt: "Ein Draht mit Querschnittsfläche A=1 mm² und Länge l=1 m besitzt einen elektrischen Widerstand von R=0,02 Ω. Wie groß ist der spezifische Widerstand ρ?",
    correctValue: 0.02,
    tolerance: 0.002,
    unit: "Ω·mm²/m",
    explanation: "ρ = R·A/l = 0,02·1/1 = 0,02 Ω·mm²/m.",
    source: "Kapitel 10.1, Elektrische Leitfähigkeit",
    free: false,
  },
  {
    id: "et-02",
    topic: "Elektrische und thermische Eigenschaften",
    type: "mc",
    prompt: "Warum sinkt die elektrische Leitfähigkeit von Metallen mit steigender Temperatur, während sie bei Halbleitern steigt?",
    options: [
      "Bei Metallen behindern stärkere Gitterschwingungen die Elektronenbeweglichkeit; bei Halbleitern werden durch Wärme mehr Elektronen ins Leitungsband gehoben",
      "Bei Metallen verschwinden die freien Elektronen bei Erwärmung vollständig",
      "Halbleiter besitzen bei hoher Temperatur keine Bandlücke mehr",
      "Es gibt keinen Unterschied im Temperaturverhalten",
    ],
    correctIndex: 0,
    explanation: "Bei Metallen sinkt die Leitfähigkeit, weil stärkere thermische Gitterschwingungen die Elektronenbeweglichkeit behindern; bei Halbleitern steigt sie, weil mehr Elektronen die (relativ kleine) Bandlücke thermisch überwinden können.",
    source: "Kapitel 10.2, Bändermodell: Metalle, Halbleiter und Isolatoren",
    free: false,
  },
  {
    id: "et-03",
    topic: "Elektrische und thermische Eigenschaften",
    type: "numeric",
    prompt: "Ein Aluminiumbauteil mit l0=25 m und α=23·10⁻⁶ K⁻¹ wird um ΔT=50 K erwärmt. Um wie viel mm verlängert es sich?",
    correctValue: 28.75,
    tolerance: 1,
    unit: "mm",
    explanation: "Δl = α·l0·ΔT = 23·10⁻⁶·25·50 = 0,02875 m = 28,75 mm.",
    source: "Kapitel 10.4, Thermische Ausdehnung",
    free: false,
  },
  {
    id: "et-04",
    topic: "Elektrische und thermische Eigenschaften",
    type: "mc",
    prompt: "Was besagt das Wiedemann-Franz-Gesetz?",
    options: [
      "Die Wärmeleitfähigkeit eines Metalls ist proportional zum Produkt aus Temperatur und elektrischer Leitfähigkeit",
      "Alle Metalle besitzen dieselbe Wärmeleitfähigkeit",
      "Die elektrische Leitfähigkeit ist unabhängig von der Temperatur",
      "Wärmeleitfähigkeit und elektrische Leitfähigkeit sind bei Metallen umgekehrt proportional",
    ],
    correctIndex: 0,
    explanation: "Das Wiedemann-Franz-Gesetz beschreibt λ=L·T·σ — bei Metallen ist die Wärmeleitfähigkeit proportional zum Produkt aus absoluter Temperatur und elektrischer Leitfähigkeit.",
    source: "Kapitel 10.3, Wärmeleitfähigkeit",
    free: false,
  },

  // ---------- Thermodynamik von Phasenübergängen ----------
  {
    id: "tp-01",
    topic: "Thermodynamik von Phasenübergängen",
    type: "mc",
    prompt: "Unter welcher Bedingung läuft ein Vorgang thermodynamisch freiwillig ab?",
    options: ["ΔG > 0", "ΔG = 0", "ΔG < 0", "ΔG ist irrelevant"],
    correctIndex: 2,
    explanation: "Ein Vorgang läuft freiwillig ab, wenn dabei die freie Enthalpie sinkt, also ΔG<0 gilt. Bei ΔG=0 herrscht Gleichgewicht, bei ΔG>0 läuft der Vorgang nicht freiwillig ab.",
    source: "Kapitel 11.1, Innere Energie, Enthalpie und freie Enthalpie",
    free: false,
  },
  {
    id: "tp-02",
    topic: "Thermodynamik von Phasenübergängen",
    type: "mc",
    prompt: "Wie verändert sich der kritische Keimradius r*, wenn die Unterkühlung ΔT einer Schmelze zunimmt?",
    options: ["r* wird größer", "r* wird kleiner", "r* bleibt konstant", "r* wird negativ"],
    correctIndex: 1,
    explanation: "Mit zunehmender Unterkühlung steigt die freiwerdende Volumenenergie gV an, wodurch der kritische Keimradius r* kleiner wird — bei starker Unterkühlung bilden sich deshalb leichter stabile Keime.",
    source: "Kapitel 11.2, Keimbildung und kritischer Keimradius",
    free: false,
  },
  {
    id: "tp-03",
    topic: "Thermodynamik von Phasenübergängen",
    type: "mc",
    prompt: "Wie ist die Enthalpie H definiert?",
    options: ["H = U − pV", "H = U + pV", "H = TS − U", "H = U · pV"],
    correctIndex: 1,
    explanation: "Die Enthalpie ist definiert als H = U + pV, wobei U die innere Energie und pV die Volumenarbeit ist.",
    source: "Kapitel 11.1, Innere Energie, Enthalpie und freie Enthalpie",
    free: false,
  },

  // ---------- Zustandsdiagramme ----------
  {
    id: "zd-01",
    topic: "Zustandsdiagramme",
    type: "numeric",
    prompt: "In einem Zweistoffsystem (K=2) bei konstantem Druck stehen 2 Phasen im Gleichgewicht. Wie viele Freiheitsgrade F besitzt das System nach der Gibbschen Phasenregel?",
    correctValue: 1,
    tolerance: 0,
    unit: "",
    explanation: "Bei p=konstant gilt F = K+1−P = 2+1−2 = 1.",
    source: "Kapitel 12.1, Konzentrationsangaben und die Gibbsche Phasenregel",
    free: false,
  },
  {
    id: "zd-02",
    topic: "Zustandsdiagramme",
    type: "numeric",
    prompt: "Eine Legierung mit Gesamtzusammensetzung c=35% wird bei einer Temperatur abgekühlt, bei der eine Konode das Zweiphasengebiet bei c′=20% (Mischkristall) und c″=55% (Schmelze) schneidet. Wie hoch ist der Mengenanteil mK des Mischkristalls?",
    correctValue: 57.1,
    tolerance: 1,
    unit: "%",
    explanation: "mK = (c−c″)/(c′−c″) = (35−55)/(20−55) = (−20)/(−35) ≈ 0,571 = 57,1%.",
    source: "Kapitel 12.2, Vollständige Mischbarkeit und die Hebelregel",
    free: false,
  },
  {
    id: "zd-03",
    topic: "Zustandsdiagramme",
    type: "mc",
    prompt: "Wie lautet die allgemeine Reaktionsgleichung für die eutektische Reaktion?",
    options: ["S → A + B", "S + α → β", "A + B → S", "α → β + γ"],
    correctIndex: 0,
    explanation: "Bei der eutektischen Reaktion erstarrt die gesamte Restschmelze S bei konstanter Temperatur gleichzeitig in zwei feste Phasen A und B: S → A + B.",
    source: "Kapitel 12.3, Eutektische und peritektische Systeme",
    free: false,
  },
  {
    id: "zd-04",
    topic: "Zustandsdiagramme",
    type: "mc",
    prompt: "Was passiert bei der peritektischen Reaktion?",
    options: [
      "Die Restschmelze reagiert mit einer bereits ausgeschiedenen festen Phase zu einer neuen festen Phase",
      "Zwei Schmelzen vermischen sich zu einer homogenen Schmelze",
      "Eine feste Phase schmilzt vollständig auf",
      "Zwei feste Phasen bilden gemeinsam eine neue Schmelze",
    ],
    correctIndex: 0,
    explanation: "Bei der peritektischen Reaktion S+α→β reagiert die Restschmelze mit einer bereits zuvor ausgeschiedenen festen Phase α zu einer neuen festen Phase β.",
    source: "Kapitel 12.3, Eutektische und peritektische Systeme",
    free: false,
  },

  // ---------- Das Eisen-Kohlenstoff-System ----------
  {
    id: "fe-01",
    topic: "Das Eisen-Kohlenstoff-System",
    type: "mc",
    prompt: "Was ist Zementit?",
    options: [
      "Reines α-Eisen",
      "Die intermetallische Phase Fe3C mit 6,67 Masseprozent Kohlenstoff",
      "Eine Bezeichnung für Perlit",
      "Ein anderer Name für Austenit",
    ],
    correctIndex: 1,
    explanation: "Zementit ist die intermetallische Phase Fe3C mit 6,67 Masseprozent Kohlenstoff — hart und spröde, sie entsteht, wenn mehr Kohlenstoff vorliegt, als im jeweiligen Eisen-Mischkristall gelöst werden kann.",
    source: "Kapitel 13.1, Das Fe-C-Diagramm: Phasen und Gefüge",
    free: false,
  },
  {
    id: "fe-02",
    topic: "Das Eisen-Kohlenstoff-System",
    type: "numeric",
    prompt: "Wie hoch ist die maximale Kohlenstofflöslichkeit von Austenit (γ-Eisen), in Masseprozent?",
    correctValue: 2.06,
    tolerance: 0.05,
    unit: "%",
    explanation: "Austenit (γ-Eisen, kfz) kann bei 1147°C bis zu 2,06 Masseprozent Kohlenstoff lösen — deutlich mehr als Ferrit mit maximal 0,8%.",
    source: "Kapitel 13.1, Das Fe-C-Diagramm: Phasen und Gefüge",
    free: false,
  },
  {
    id: "fe-03",
    topic: "Das Eisen-Kohlenstoff-System",
    type: "mc",
    prompt: "Aus welchen Gefügebestandteilen besteht Perlit?",
    options: [
      "Ferrit und Zementit (lamellar)",
      "Austenit und Zementit (lamellar)",
      "Nur aus reinem Ferrit",
      "Martensit und Restaustenit",
    ],
    correctIndex: 0,
    explanation: "Perlit ist das eutektoide Gefüge aus fein verteilten, lamellaren Schichten von Ferrit (α-Mischkristall) und Zementit (Fe3C), entstanden aus dem eutektoiden Zerfall von Austenit bei 723°C.",
    source: "Kapitel 13.1, Das Fe-C-Diagramm: Phasen und Gefüge",
    free: false,
  },
  {
    id: "fe-04",
    topic: "Das Eisen-Kohlenstoff-System",
    type: "numeric",
    prompt: "Bei welcher Temperatur (in °C) liegt die eutektoide Reaktion des Fe-C-Systems?",
    correctValue: 723,
    tolerance: 5,
    unit: "°C",
    explanation: "Die eutektoide Reaktion (Austenit zerfällt zu Ferrit + Zementit = Perlit) findet bei 723°C und einem Kohlenstoffgehalt von 0,8% statt.",
    source: "Kapitel 13.1, Das Fe-C-Diagramm: Phasen und Gefüge",
    free: false,
  },
  {
    id: "fe-05",
    topic: "Das Eisen-Kohlenstoff-System",
    type: "mc",
    prompt: "Wie entsteht Martensit beim Härten von Stahl?",
    options: [
      "Durch sehr langsames Abkühlen aus dem Austenitgebiet",
      "Durch so schnelles Abschrecken aus dem Austenitgebiet, dass Kohlenstoff im Gitter zwangsgelöst bleibt",
      "Durch Erhitzen von Ferrit über den Schmelzpunkt",
      "Durch Zugabe von reinem Kohlenstoff zu geschmolzenem Eisen",
    ],
    correctIndex: 1,
    explanation: "Beim martensitischen Härten wird der Stahl so schnell abgeschreckt, dass keine Diffusion mehr stattfinden kann; der Kohlenstoff bleibt zwangsgelöst im Kristallgitter, das sich dadurch tetragonal verzerrt.",
    source: "Kapitel 13.2, Wärmebehandlung: Härten, Anlassen, Vergüten",
    free: false,
  },
];
